### ISSUE TITLE
Credit card sync (when logged in) pulls in incorrect formatting

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14687] opened 2023-06-01 21:19 UTC
## Steps to reproduce
1. Add a credit card on desktop (logged in)
2. Sync on mobile (logged in with same account)
3. Open Credit Card Autofills

### Expected behavior
Card logo, expiration date come in in the proper formatting as if you were adding on mobile.

### Actual behavior
When logged in and credit cards are synced from desktop to mobile, mobile is pulling in a different format that triggers the error message. It also seems to pull in just a default card icon even though it’s a Visa.

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments: 
<img width="512" alt="Screenshot 2023-06-01 at 4 18 21 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/76cf3215-bcf4-47c3-8ddd-a7047af5589b">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6560)

**Comment by data-sync-user** [comment] 2023-07-14 18:02
➤ Nishant Bhasin commented:

Should be fixed on main / v116 and dupe of https://mozilla-hub.atlassian.net/browse/FXIOS-6903 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6903|smart-link )

**Comment by DianaBarladeanu** [comment] 2023-07-24 10:23
The expiration date has the proper formatting, but it still pulls in a default card icon instead of the proper logo.
Verified on v116 (32873) with iPhone SE (16.5).

**Closed** 2023-08-30 13:02 UTC
Labels: Bug 🐞, credit-card-autofill
