### ISSUE TITLE
iOS opens on random old tab instead of new tab

### ISSUE THREAD

**Issue by kawaiigeorgiapeach** [mozilla-mobile/firefox-ios#14182] opened 2023-04-29 20:59 UTC
### Device & build information
* Device: iPhone SE 2020, iOS 16.4.1
* Build version: Firefox iOS 112.2
* First seen version: I have been experiencing this issue for almost a year.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6304)

**Comment by DianaBarladeanu** [comment] 2023-08-10 10:25
I wasn't able to reproduce this issue, verified on v117 (33331) on iPhone SE (16.5).

**Comment by kawaiigeorgiapeach** [comment] 2023-08-10 17:21
This issue is still happening to me. It’s hard to use Firefox. I have a
million tabs open, and am trying to bookmark as many as I can to start
fresh.

**Comment by data-sync-user** [comment] 2023-08-11 12:50
➤ Alina Moldovan commented:

Validated this issue using iPhone 14+ (16.0.3) and iPhone SE (16.4) using FF v117 (33432)

Here is the STR and current behavior: 

  1. have more than 50 tabs opens 
  2. go to settings → Homepage → and set the Opening screen to: Homepage 
  3. Force close the FF app 
  4. Open the FF app

Actual behavior:  The latest opened tab is displayed 

Orla Mitchell it looks like this issue still reproduces.

**Comment by data-sync-user** [comment] 2024-04-01 09:20
➤ Andrei Bodea commented:

Verified as fixed on v125 (40250) with iPhone 15 Pro (17.3).

**Closed by data-sync-user** 2024-04-01 09:20 UTC
Labels: Bug 🐞
