### ISSUE TITLE
[Favicons refactor] - "Facebook" favicon is different

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22019] opened 2024-09-17 08:58 UTC
**Steps to reproduce**
1. Fresh install FF.
2. Observe Facebook's favicon in top sites.

**Expected behavior**
Facebook favicon is the same as before.

**Actual behavior**
Facebook favicon is different.

**Device & build information**
* Device: iPhone 15 (17.5)
* Build version: v131 (45309)
* First seen version: ? 
Notes

Attachments: 

![collage](https://github.com/user-attachments/assets/e52742ea-e74f-4bc5-96be-61a336d1e7a1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10042)

**Comment by nbhasin2** [comment] 2024-09-25 03:11
The one on the right (After) is the correct icon. Closing as this is working as intended. 
This is same as the one below. Feel free to open if you consider it otherwise cc @afurlan-firefox @DianaABarladeanu 

https://github.com/mozilla-mobile/firefox-ios/issues/22021 - [Favicons refactor] - "YT" favicon is different

**Closed by nbhasin2** 2024-09-25 03:11 UTC
Labels: Bug 🐞, S3
