### ISSUE TITLE
Subheadings in Library Panel disappear after switching themes

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#12259] opened 2022-10-28 20:55 UTC
## Steps to reproduce
1. In Firefox Settings, change from either light theme to dark theme or vice versa
2. Open Library Panel > History
3. Initially, the "Today," "Yesterday," etc. subheadings are not visible
4. Some of them appear after some time has passed or they can be manually triggered to appear by scrolling the page until the subheadings touch the top of the screen

### Expected behavior
The subheadings should be visible by default

### Actual behavior
Subheadings are not visible immediately after switching themes

### Device & build information
* Device: iPhone 12, iOS 16
* Build version: 106.0 (20303)
### Notes
Attachments: 
![IMG_8318](https://user-images.githubusercontent.com/87655586/198730760-f7a0f209-f4b1-45de-b597-d452444c2ff4.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5170)

**Comment by SimonBasca** [comment] 2022-10-31 08:45
This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/12121 and should be fixed in the next release.

**Closed by SimonBasca** 2022-10-31 08:45 UTC
Labels: Bug 🐞
