### ISSUE TITLE
`NSInternalInconsistencyException` `BrowserViewController.viewDidLayoutSubviews` Permanent crash on iPad Air when closing the split screen or when changing the device orientation

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#18650] opened 2024-02-09 11:48 UTC
## Steps to reproduce
1. Launch FF.
2. Change the device orientation while being on the home page.
### Expected behavior
The split screen should be correctly displayed.
### Actual behavior
Permanent crash on iPad Air when going to split screen or when changing the orientation of the device
### Device & build information
* Device: iPad Air (15.7), iPad mini 5 (16.2), iPad Pro (16.3.1) 
* Build version:  v123 (38665)
* First seen version:  v123 (38120)
### Notes
**Please note that this issue cannot be reproduced on iPads with iOS 17.x.**
[Sentry](https://mozilla.sentry.io/issues/4918748723/?project=6176941&query=release%3Aorg.mozilla.ios.FirefoxBeta%40123.0%2B%2838665%29&referrer=release-issue-stream) 
Please note that I was able to reproduce this also on the latest v9000 build.
Please note that this issue only occurs if you don't have any webpage open while on the home screen when rotating from landscape to portrait. 
If a webpage is open there are no crashes.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/981a4f76-2453-4987-8e77-04d7a2bcd890

[Crashlog](https://github.com/mozilla-mobile/firefox-ios/files/14221175/Client-2024-02-09-134046.ips.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8415)

**Comment by abodea** [comment] 2024-02-09 11:57
Please note that I tested all the previous versions and this issue only started to occur with v123 (38120) but it is very specific because if you rotate the device (while being on the Home screen) in landscape-> open a page and then rotate it to Portrait, it won't crash. But doing the same thing without having any web page open will always crash.

**Comment by data-sync-user** [comment] 2024-02-13 10:55
➤ Andrei Bodea commented:

Verified as fixed on v123 (38749) with iPad Air (15.7), iPad mini 5 (16.2), and iPad Air (16.7) please note that I was not able to reproduce the crash anymore.

**Closed** 2024-02-13 10:55 UTC
Labels: Bug 🐞, Crash, S1, iOS16, iOS 15
