### ISSUE TITLE
[Toolbar Redesign] `URL copied to Clipboard` displayed behind the keyboard

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22536] opened 2024-10-14 13:58 UTC
## Steps to reproduce
1. Launch FF and access any website.
2. Tap on the URL (the URL is fully selected).
3. Long tap > copy the URL.
4. Observe the screen.
### Expected behavior
The `URL copied to Clipboard` toast should be correctly displayed on the screen.
### Actual behavior
`URL copied to Clipboard` displayed behind the keyboard
### Device & build information
* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46355) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/5d74d42f-05d2-4e64-93e8-ebddf1fafbc5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10287)

**Comment by data-sync-user** [comment] 2024-10-14 20:24
➤ Matt Lichtenstein commented:

Norberto Andres Furlan Aarjav Pandya the precedent set by the old toolbar was that long pressing the url bar while the text field was focused was not allowed, so this couldn’t happen. How should we handle this for the new toolbar?

**Comment by data-sync-user** [comment] 2024-10-15 15:54
➤ Aarjav Pandya commented:

I think I can do it as intended right now. i.e. When the user long presses on the selected url, it should hide the keyboard and show the action sheet with copy address as an option.

**Comment by data-sync-user** [comment] 2024-10-15 16:02
➤ Matt Lichtenstein commented:

Aarjav Pandya to confirm, this is expected behavior and I should close the ticket?

**Comment by data-sync-user** [comment] 2024-10-15 16:03
➤ Aarjav Pandya commented:

Yes, we can close it.

**Comment by data-sync-user** [comment] 2024-10-15 16:06
➤ Matt Lichtenstein commented:

Closing as this is expected behavior.

**Closed** 2024-10-15 16:06 UTC
Labels: Bug 🐞, S2, Toolbar redesign📲
