### ISSUE TITLE
Review ReaderModeStyleViewController delegate to be weak

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13691] opened 2023-03-22 19:47 UTC
Noticed we have some delegates that aren't marked as weak in the code. Delegates should normally be weak to avoid reference cycles. This task is to review ReaderModeStyleViewController delegate to mark it as weak, and add tests for it.

To add tests for leaks in our code, you can use `trackForMemoryLeaks`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6041)

**Comment by mirscode** [comment] 2023-05-01 21:51
I believe we can close this issue since this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13612 and it's already been fixed by a contributor in https://github.com/mozilla-mobile/firefox-ios/pull/13634.

**Closed** 2023-05-02 13:06 UTC
Labels: Contributor OK
