### ISSUE TITLE
Firefox on iPhone makes a flood of requests for icons

### ISSUE THREAD

**Issue by nguyenmp** [mozilla-mobile/firefox-ios#12660] opened 2022-12-09 22:40 UTC
## Steps to reproduce
This only reproduces on my iPhone for Firefox.  Not any other browser and not firefox for mac.

Sign into a Firefox account with tab sync enabled.  I don't think any other devices are needed, it just needs to be able to sync tabs to the cloud.

Visit any low-traffic website that you own and can see the access logs.

### Expected behavior
When I visit my website or trigger a sync, I expect a normal level of requests to my website from my device.  Honestly, I don't expect any requests to my website since all my pages are already loaded.

### Actual behavior
I consistently get a ridiculous number of requests from my iPhone, at the moment it's between 3-5 sets of:
* Request to the page in question `/`
* `/favicon.ico`
* `/apple-touch-icon-precomposed.png`
* `/apple-touch-icon.png`
* `/wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png` <- I get multiple of these, one for each `<link rel="icon" href="..." />` I have on my website.

This means every time I create a new tab, sync tabs, close a tab, or navigate my website while one of my tabs is on my website, I get flooded with about 30-90 requests for the above resources.  This has actually led me to take down my own website by just clicking around a bunch since many of these requests used to lead to 404 and were uncached.

### Device & build information
* Device: iPhone 12 mini (iOS 16.1.2)
* Build version: Firefox 107.2 (22549)

#### Analysis

It seems to me what's happening is something with the user-agent `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"` is requesting the page 3-5 times whenever tabs sync to Firefox's servers.  Whatever that user-agent represents is unconditionally requesting every icon on the resulting page which leads to about 30-60 requests from the user-agent `com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0`.  It requests some default icons like `favicon.ico`, `/apple-touch-icon-precomposed.png`, and `/apple-touch-icon.png`.  It also requests every `<link rel="icon" .../>` defined on the page.  There doesn't seem to be any caching or request deduplication used.

If those icons are unavailable, they trigger lots of 404 and can run up the server CPU which is how I noticed this in the first place.

#### Example Access Logs for when I open a new tab and visit /photography/

```
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /photography/ HTTP/1.1" 200 10221 "https://aggressivelyparaphrasing.me/" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/107.2  Mobile/15E148 Safari/605.1.15"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /favicon.ico HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /apple-touch-icon.png HTTP/2" 404 9453 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /apple-touch-icon-precomposed.png HTTP/2" 404 9468 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /photography/ HTTP/1.1" 200 10220 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /photography/ HTTP/1.1" 200 10220 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
174.70.101.114 - - [08/Dec/2022:21:54:21 -0600] "GET /photography/ HTTP/2" 200 10221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /favicon.ico HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /photography/ HTTP/2" 200 10221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /apple-touch-icon-precomposed.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /apple-touch-icon.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:22 -0600] "GET /photography/ HTTP/1.1" 200 10220 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /favicon.ico HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /favicon.ico HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /photography/ HTTP/2" 200 10221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /apple-touch-icon-precomposed.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /apple-touch-icon.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /apple-touch-icon-precomposed.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /apple-touch-icon.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:23 -0600] "GET /photography/ HTTP/2" 200 10221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"

174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /favicon.ico HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /photography/ HTTP/2" 200 10220 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /wp-content/uploads/2022/12/face-with-open-mouth_1f62e.png HTTP/2" 200 4515 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /apple-touch-icon-precomposed.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
174.70.101.114 - - [08/Dec/2022:21:54:27 -0600] "GET /apple-touch-icon.png HTTP/2" 200 0 "-" "com.apple.WebKit.Networking/8614.2.9.0.11 CFNetwork/1399 Darwin/22.1.0"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5413)

**Comment by OrlaM** [comment] 2022-12-10 02:30
Duplicate of #12617

**Closed by OrlaM** 2022-12-10 02:30 UTC
Labels: Bug 🐞
