### ISSUE TITLE
firefox crashes on autofill

### ISSUE THREAD

**Issue by kraxel** [mozilla-mobile/firefox-ios#8367] opened 2021-04-21 15:33 UTC
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

reproducer: go to http://jenkins.kraxel.org

the site is configured for basic authentication, so possibly firefox fails to handle the 401 auth response

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2848)

**Comment by dnarcese** [comment] 2021-04-22 16:38
@kraxel is the crash happening before or after logging in? I have tried reproducing and I see the authentication popup with no crashing.

**Comment by kraxel** [comment] 2021-04-22 17:33
Instant crash, I don't see the popup window.  Latest iPadOS (14.4.2).

**Comment by kraxel** [comment] 2021-04-22 18:19
Tried the same thing on the iPhone (iOS 14.4.2 too), works fine there, so maybe happens on ipads only.

**Comment by data-sync-user** [comment] 2021-07-08 18:51
➤ Daniela Arcese commented:

Simion Basca Can you investigate whether there is a difference in behaviour here bw iPhone and iPad?

**Comment by SimonBasca** [comment] 2021-07-12 12:38
@dnarcese I was able to reproduce the crash on iPhone and iPad after:
1. On desktop, go to saved logins
2. Create a login for http://jenkins.kraxel.org with a random username and password.
3. Sync the login on iPad or iPhone
4. Go to http://jenkins.kraxel.org

Firefox will crash instantly and I assume it's crashing due to autofill. Without the saved login going to http://jenkins.kraxel.org does not crash the app.

[Client-2021-07-12-152616.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6801406/Client-2021-07-12-152616.ips.beta.zip)

**Comment by data-sync-user** [comment] 2021-07-13 15:32
➤ Daniela Arcese commented:

Simion Basca would you be able to investigate if there are others sites this is happening on?

**Comment by SimonBasca** [comment] 2021-07-14 14:46
@dnarcese I've manage to reproduce the issue also on "www.weberg.de/intern" after I previously created a login on desktop with a random username and password and synced it to iOS. After the login is save on iOS going to "www.weberg.de/intern" crashes the app.

Also note that after some digging I've found out that this issue is actually a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/5757 where we had more reports.

**Comment by dnarcese** [comment] 2021-07-14 15:07
Duplicate of #5757

**Closed by dnarcese** 2021-07-14 15:07 UTC
Labels: Crash
