### ISSUE TITLE
FXIOS-1208 ⁃ Updated app now it won’t open or work don’t know how to fix I tried it all

### ISSUE THREAD

**Issue by bassnado** [mozilla-mobile/firefox-ios#7648] opened 2020-11-14 00:55 UTC
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1208)

**Comment by SimonBasca** [comment] 2020-11-16 13:41
Hello, thanks for the feedback. Could you please let me know from what version did you update?

**Comment by bassnado** [comment] 2020-11-16 17:24
iPhone XR and the version from 3 weeks ago I think just the newest iOS update

**Comment by bassnado** [comment] 2020-11-16 17:25
Firefox 29.1 iOS 14

**Comment by bassnado** [comment] 2020-11-16 17:39
Firefox 29.1 iOS 14

**Comment by bassnado** [comment] 2020-11-16 17:45
Oh sorry I meant 29 to 29.1

**Comment by bassnado** [comment] 2020-11-18 16:01
I had Firefox 29 then updated to 29.1
iOS 14.2

**Comment by SimonBasca** [comment] 2020-11-18 16:40
Thanks for the feedback. Unfortunately I am currently unable to reproduce this issue on Firefox 29.1 (3022) and on latest beta 29.2 (3120). 

Do you have a Firefox Account set up on your device?

**Comment by bassnado** [comment] 2020-11-18 16:45
No
Don’t have account set up

**Comment by bassnado** [comment] 2020-11-18 16:47
Do not have account tied to browser when does next update come out

**Comment by dnarcese** [comment] 2021-02-03 19:27
@bassnado Hello, is it working for you now?

**Comment by dnarcese** [comment] 2021-02-25 18:26
Closing for now, will re-open if it is still an issue.

**Closed by dnarcese** 2021-02-25 18:26 UTC
Labels: Bug 🐞
