### ISSUE TITLE
Fakespot - spinner remains in an infinite loop for some products after the user taps 'Check now'

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17102] opened 2023-11-01 15:37 UTC
This issue is intermittent

## Steps to reproduce
1. Open a product having "New info to check" card displayed 
1. Tap "Check now"
1. The Analyze stats and the spinner is visible 
1. Check the https://trustwerty.com/api/v1/fx/analysis_status call using the correct product id in order to see if the analyze is finished on the server side 
1. Wait for the Analyze to be finished on the server side 
1. Check the iOS client

### Expected behavior
The updated status must be displayed 

### Actual behavior
Spinner remains in an infinite loop. Refreshing the page will updated the review details

### Device & build information
* Device: iPhone 14+ (16.0.1) 
* Build version: 120 (35673) 
* First seen version: 120 (35673) 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7669)

**Comment by data-sync-user** [comment] 2023-11-07 14:30
➤ Razvan Litianu commented:

According to the internal discussion here ( https://mozilla.slack.com/archives/C05GB828L2K/p1699355157007679 ) it seems the issue appears probably caused by the lack of workers in staging. Keeping an eye if it’s a serious issue.

**Comment by data-sync-user** [comment] 2023-11-07 15:40
➤ Chris Peterson commented:

Razvan will check how Android handles this state.

**Comment by data-sync-user** [comment] 2023-11-15 13:44
➤ Alina Moldovan commented:

QA -additional comments

  * The bug reproduces very rarely, but it seems that if it has reproduced once it continues to reproduce quite easily for some time. 
  * the last time it was reproduced was during the Fakespot responsiveness testing session using the staging env while the server was under load.

**Comment by data-sync-user** [comment] 2023-11-21 08:06
➤ Razvan Litianu commented:

Synced with Android, they fallback to previous state in case of failure so I implemented something similar.

**Comment by data-sync-user** [comment] 2023-11-21 15:37
➤ Chris Peterson commented:

We will want to uplift this fix to Fx 121.

**Comment by data-sync-user** [comment] 2023-11-29 14:01
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36484), with iPhone SE(16.6.1).

**Closed by data-sync-user** 2023-11-29 14:01 UTC
Labels: Bug 🐞, S3
