### ISSUE TITLE
[Address autofill phase]  - "Remove" button not visible - unable to delete addresses

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21081] opened 2024-07-18 14:53 UTC
**Prerequisites**
Have "Address autofill phase 2 beta rollout" experiment enabled in secret settings.

**Steps to reproduce**

1. Fresh install Firefox.
1. Make sure you have at least one saved address.
1. Go to one of the addresses and tap on "edit" in order to remove it.
1. Observe.

**Expected behavior**
The "remove address" button is visible at the bottom of the sheet.

**Actual behavior**
The "remove address" button is NOT visible, it is covered by the keyboard.

**Device & build information**

* Device: iPad Air 3rd gen (17.5)
* Build version: v129 (43631)
* First seen version: ? 

Notes
This issue is not reproducible on iPhone since you can close the keyboard by tapping on "done".
Attachments: 

https://github.com/user-attachments/assets/dcfc7981-6d1e-49a7-8c39-2fc95451ef1c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9525)

**Comment by data-sync-user** [comment] 2024-07-18 20:54
➤ Matt Lichtenstein commented:

Diana Andreea Barladeanu It seems like the keyboard covers the “remove address” button on both iPhone and iPad. iPad also has a “close keyboard” button as part of it’s software keyboard (see picture). Does this resolve the issue?

Regardless, I would argue that automatically displaying the keyboard upon entering “edit” mode could result in a bad UX since it is not apparent that the “remove address” button becomes unhidden.

!Simulator Screenshot - iPad Air 13-inch (M2) - 2024-07-18 at 16.45.38.png|width=2048,height=2732,alt="Simulator Screenshot - iPad Air 13-inch (M2) - 2024-07-18 at 16.45.38.png"!

**Comment by data-sync-user** [comment] 2024-07-18 21:02
➤ Matt Lichtenstein commented:

Norberto Andres Furlan see part about UX ^

**Comment by data-sync-user** [comment] 2024-08-27 17:09
➤ Roux Buciu commented:

Norberto Andres Furlan to check this out.

**Comment by data-sync-user** [comment] 2024-10-07 14:04
➤ Norberto Andres Furlan commented:

Nishant Bhasin Issam Mani can you take a look to this one?

**Comment by data-sync-user** [comment] 2024-10-07 14:13
➤ Matt Lichtenstein commented:

Norberto Andres Furlan this is a UX issue. The “Remove address button is there, it is just behind the keyboard. We either need to

a) move the button higher so that it is not hidden behind the keyboard

b) not bring up the keyboard (caused by automatically focusing the “name” text field) when the modal is initially displayed

c) do nothing - and allow the users to discover the button by closing the keyboard via on-screen close keyboard button

**Comment by data-sync-user** [comment] 2024-10-07 14:49
➤ Norberto Andres Furlan commented:

Jeffrey Guerrero can you let me know what you think on this one? In my opinion we should go with option a) and move the button higher. Matt Lichtenstein can we do just for iPad? How is this with passwords? (I don’t have my iPad right now to test it)

**Comment by data-sync-user** [comment] 2024-10-07 15:02
➤ Matt Lichtenstein commented:

iPad UX is slightly different in that no modals are used, but ultimately it solves a similar problem by pushing the button up higher

!Simulator Screen Recording - iPad Pro 13-inch (M4) - 2024-10-07 at 11.01.49.mp4|width=2064,height=2752,alt="Simulator Screen Recording - iPad Pro 13-inch (M4) - 2024-10-07 at 11.01.49.mp4"!

**Comment by data-sync-user** [comment] 2024-10-07 16:11
➤ Jeffrey Guerrero commented:

Hi all, 

I was trying to review this, but on both iphone and ipad, my edit functionality is broken. I also noticed the + sign for adding an address manually is missing.

!Screenshot 2024-10-07 at 11.07.52 AM.jpeg|width=820,height=1180,alt="Screenshot 2024-10-07 at 11.07.52 AM.jpeg"!

Norberto Andres Furlan

**Comment by data-sync-user** [comment] 2024-10-07 16:16
➤ Norberto Andres Furlan commented:

I think you might not be enrolled in the experiment for Phase 2. Is this on Beta? Because it is not live yet on release (I just asked for it).

Nishant Bhasin Issam Mani

**Comment by data-sync-user** [comment] 2024-10-07 16:37
➤ Matt Lichtenstein commented:

Jeffrey Guerrero to enable address adding/editing on the latest beta or release, you should be able go to settings > click the firefox version 5 times to unhide the debug options > experiments > address autofill phase 2 rollout > enable “control”

**Comment by data-sync-user** [comment] 2024-10-08 00:49
➤ Issam Mani commented:

We can just move the button up when the keyboard shows for both iphone/ipad. Would something like this be acceptable ? Jeffrey Guerrero 

!Screen Recording 2024-10-08 at 02.47.22.mov|width=858,height=1824,alt="Screen Recording 2024-10-08 at 02.47.22.mov"!

!Screen Recording 2024-10-08 at 02.41.36.mov|width=1430,height=1876,alt="Screen Recording 2024-10-08 at 02.41.36.mov"!

**Comment by data-sync-user** [comment] 2024-10-10 16:39
➤ Jeffrey Guerrero commented:

Issam Mani - we can proceed with this fix. Thank you!

**Comment by data-sync-user** [comment] 2024-10-14 13:22
➤ Adina Petridean commented:

Verified as fixed on Firefox 132.0 (46361) with iPhone 14 Pro Max (iOS 16.2).

!remove.jpeg|width=430,height=932,alt="remove.jpeg"!

**Closed** 2024-10-14 13:22 UTC
Labels: Bug 🐞, S2
