### ISSUE TITLE
Can't remove homepage shortcut

### ISSUE THREAD

**Issue by ponchpert** [mozilla-mobile/firefox-ios#12099] opened 2022-10-08 19:00 UTC
## Steps to reproduce
1. Open new tab, homepage shortcuts appear
2. Long press on shortcut (Obakki Myshopify) and click Remove 

![5ABD3CE6-39AE-46B5-BBF4-7E64A12800AD](https://user-images.githubusercontent.com/63983732/194723308-fe126b9e-95da-41b8-9f35-e79663c27c53.png)

![Uploading 533ED591-C127-431C-B961-7BF3612847AB.png…]()

### Expected behavior
Shortcut should disappear

### Actual behavior
Shortcut does not disappear

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments: 
![90BD9AA4-5CE4-42CE-8167-BEA7F27A8E72](https://user-images.githubusercontent.com/63983732/194723315-30b72dc1-a317-4ee0-ae2b-375e47c5feb0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5059)

**Comment by dnarcese** [comment] 2022-10-13 19:37
@ponchpert were you able to tell if that tile was removed on another visit to the homepage? Is this problem consistent for you or only intermittent?

**Comment by ponchpert** [comment] 2022-10-13 20:18
Hi! It's always there, no matter what I do. I've revisited, pinned and
unpinned, removed all website data from settings and it still won't go
away!!

**Comment by dnarcese** [comment] 2022-11-14 21:22
@SimonBasca we are having trouble reproducing this. Are you able to find more stable STR?

**Comment by SimonBasca** [comment] 2022-11-15 12:24
@dnarcese we are unable to reproduce the issue on latest v9000 (21907) and 106.2 (app store version) on iPhone mini 13  (16.0). 

@ponchpert are you able to remove other sites from the shortcuts list or is the problem specific to that website? Also what iOS / Firefox version are you using?

**Comment by lmarceau** [comment] 2022-11-15 14:40
Hope this helps, I've seen this issue but it's an intermittent one. Last week I had it on my prod application but I can't reproduce this week. I'll try again later this week on v106.2 in case I can see it again. Not sure what triggers the problem.

**Comment by rfpludwick** [comment] 2023-01-08 20:44
I have the same problem. iOS version 16.1.1, Firefox 108.1 (24234)

**Comment by yoanarios** [comment] 2023-01-10 14:50
@rfpludwick is the issue related to a specific website, are you able to remove other shortcuts? If you could provide a video it will be helpful to have better steps to reproduce. Thanks in advanced

I couldn't reproduce the issue on main and there was a refactoring work that touch Top sites see [PR](https://github.com/mozilla-mobile/firefox-ios/pull/12420) so the issue could be fix now, I will like to have more info on the steps to reproduce to confirm.

**Comment by rfpludwick** [comment] 2023-01-10 15:51
It's happening for at least two. I haven't tried others, because I don't want to actually delete any others right now.

**Comment by ctbfourone** [comment] 2023-01-13 16:28
Also adding that I experience this same issue both on iPhone (iOS 16.2, iPhone 11 Pro) and iPad (iOS 16.2, iPad mini 6th Gen), both using Firefox 108.1, both hooked up to FxA sync (fwiw). I've noticed this for a few months now, probably as long as this issue has been open. I can pin/unpin, but can't remove. Acts/looks just like rfpludwick's recording.

**Comment by SimonBasca** [comment] 2023-01-16 07:38
Thanks for the information @ctbfourone. This seems like the same issue as https://github.com/mozilla-mobile/firefox-ios/issues/12809. Note it will probably be fixed in v110.

**Comment by data-sync-user** [comment] 2023-01-20 13:43
➤ Simion Basca commented:

Marking as verified fix on v110 (26107)

**Closed by data-sync-user** 2023-01-20 13:43 UTC
Labels: Bug 🐞
