### ISSUE TITLE
Reload icon is not displayed in landscape mode.

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9092] opened 2021-09-09 13:01 UTC
v37.0 (5971)
iPhone 12 Pro (14.7.1)

1. Clean install the app.
2. Open the app and switch to landscape mode.
3. Visit a page.

 Actual 1:  The reload icon is not displayed.

4. Tap on the place where the icon should be.

Actual 2:  The page is reloaded but the icon is still not displayed.

5. Switch to portrait and tap on the place where the icon should be.

Actual 3:  The page is reloaded and the reload icon is now displayed correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3145)

**Comment by lmarceau** [comment] 2022-01-18 23:48
I just experienced the issue that the reload icon doesn't appear, but we can still click it on iPad. 
![IMG_0004](https://user-images.githubusercontent.com/11338480/150036720-7e54a06a-67f7-4676-bc41-e5c337512222.jpg)

Discussed with @dnarcese: If we're on iPad and there's a reload button to the left of the url bar, we shouldn't have a second reload button. Reader mode icon should be in place of that reload button (so constraints adjusted).

**Comment by junbio** [comment] 2022-01-19 17:16
Is there any circumstance where the reload button would show in the URL bar on iPad? In compact mode (i.e. Slide Over and Split View), the reload button appears on the bottom toolbar, and in regular mode, the reload button appears on the top toolbar. Would it be better not to return the reload button when the current idiom is iPad?

**Comment by lmarceau** [comment] 2022-01-19 18:06
@junbio reload button appearing on the bottom bar in multitasking was another bug: https://github.com/mozilla-mobile/firefox-ios/issues/9282 When in multitasking mode, the bottom bar needs to have the home button. This will be fixed with my latest opened PR. 

Knowing that, this means on iPad in multitasking mode we need the reload button in the url bar (as iPhone in portrait and landscape mode).

**Comment by SimonBasca** [comment] 2022-01-21 14:43
This issue is no longer reproducible on latest main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5. Closing for now and will re-open if the issue is reproducible again.

**Closed by SimonBasca** 2022-01-21 14:43 UTC
Labels: Contributor OK, Bug 🐞
