### ISSUE TITLE
App Links Don't Recognize Installed Apps

### ISSUE THREAD

**Issue by rmehyde** [mozilla-mobile/firefox-ios#20857] opened 2024-06-29 17:25 UTC
## Steps to reproduce
1. Go to a website with an app link you have installed, e.g. Instagram or Reddit
1. Follow the "Open in app" link

### Expected behavior
Link opens in the app

### Actual behavior
Firefox asks if you want to open in the App Store, taking you to the installation page for the already-installed app in the App Store.

Occasionally an app link works for me, I can't recall which do work but Instagram and Reddit consistently do not.

### Device & build information
* Device: iPhone 12 Pro, iOS 17.5.1
* Build version: 127.1 (42781)
* First seen version: I've had this bug as long as I've been using Firefox in iOS, >1 year
    1. Notes
Screen Recording:
https://github.com/mozilla-mobile/firefox-ios/assets/34076153/32da5562-4c7b-4e16-9bb0-db97e979ea23

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9419)

**Comment by data-sync-user** [comment] 2024-07-17 10:07
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan 

I investigated this and we can’t handle this behaviour. It is happening also on Chrome and Safari. (for some websites like Reddit or Instagram)

Why?

So, few sites like Reddit, Instagram or Youtube have that top banner with a button to open the native app.

The problem is, that button have a different URL structure, few examples:

Instagram: https://apps.apple.com/app/instagram/id389801252?ct=igweb.unknown&mt=8&pt=428156&vt=lo ( https://apps.apple.com/app/instagram/id389801252?ct=igweb.unknown&mt=8&pt=428156&vt=lo ) 

Reddit: https://apps.apple.com/app/id1064216828 ( https://apps.apple.com/app/id1064216828 ) 

Youtube: vnd.youtube://m.youtube.com/watch?v=whge6XLIQB0&feature=mwebtonativeapp11268432&itccampaign=mwebtonativeapp11268432&redirectappstoreios=1&app=desktop

After this words, that redirection to the AppStore is expected in the Instagram and Reddit cases because of that URLs structures and we can’t change the URLs.

**Comment by data-sync-user** [comment] 2024-07-24 00:19
➤ Nishant Bhasin commented:

This is on the website to send the user to the proper page and is not something we can fix. 
If its a universal link / deeplink we can offer to open the app automatically however if its not then we don’t have a provision currently built in iOS to check all the supported apps for the link.
Suggestion to close this. cc Norberto Andres Furlan Alexandru Farcasanu

**Comment by rmehyde** [comment] 2024-09-14 14:42
Thank you for the help. On exploring a little more, it looks like there are often two links:
1. An "Open this link in the App Store" banner at the bottom (circled)
1. Other "Open in app" links embedded in the site (arrows)

<img src="https://github.com/user-attachments/assets/172cfb3c-ebfe-4055-8e94-c30e1d9cbf78" width="250">



You are correct that using the "Open this link in the App Store" takes you to the app store in both Safari and Firefox, you have to use the other "open in app" links natively embedded in the site.

I will note that while Reddit "Use app" links work, I found that Instagram simply refreshes the page in Firefox without actually opening the app. Instagram app links do work in Safari.

**Closed** 2024-10-13 08:39 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2024-11-24 21:03
➤ Chris Peterson commented:

Some people on Reddit are reporting that they still experience this bug. They have the Reddit app installed, but tapping Reddit.com ( http://Reddit.com )’s “View in Reddit App” button in Firefox opens the App Store’s Reddit app entry, not the Reddit app itself.

Reddit thread: https://www.reddit.com/r/firefox/comments/1f1punc/firefox_doesnt_open_reddit_in_app_ios/ ( https://www.reddit.com/r/firefox/comments/1f1punc/firefox_doesnt_open_reddit_in_app_ios/ )

Screen recording: https://vimeo.com/1032734807?share=copy ( https://vimeo.com/1032734807?share=copy|smart-link )

**Comment by data-sync-user** [comment] 2025-04-10 11:03
➤ Filippo Zazzeroni commented:

Andres Furlan should we close this issue ?
