### ISSUE TITLE
"Firefox crashed. Restore your tabs?" prompt missing

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19830] opened 2024-04-17 08:36 UTC
**Steps to reproduce**

1. Install FF, open some tabs.
1. From iOS settings, go to secret settings--->force crash.

**Expected behavior**
Firefox(...) crashed prompt is displayed, followed by "Firefox crashed. Restore your tabs?" prompt.

**Actual behavior**
"Firefox crashed. Restore your tabs?" prompt is missing.
Tabs are restored automatically.

**Device & build information**

* Device: iPhone 15 (17.4)
* Build version: 126 (40846)
* First seen version: 126 (40774)

Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/e852ba1c-e02b-4d8b-9e47-57131728f2c6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8982)

**Comment by data-sync-user** [comment] 2024-04-25 21:58
➤ Nishant Bhasin commented:

Did mini investigation around some time I had and will continue tomorrow morninghttps://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/Client/Fronten[… ( https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/Client/Fronten[… )Browser/BrowserViewController/Views/BrowserViewController.swift|https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift#L751-L763]This is the piece of code that deals with showing the popup

  1. ❌ Initially thought something is blocking the popup - This is ruled out and is not the case unless you are running dev builds then you can expect the crash crashedLastLaunch() method to not give you anything. This comes from sentry
  2. ❌ Next I checked previous instances where someone made any changes - Nothing here as well so ruling out this piece as well
  3. 🤔  We did however bumped sentry 3 weeks ago - https://github.com/mozilla-mobile/firefox-ios/pull/19665 ( https://github.com/mozilla-mobile/firefox-ios/pull/19665|smart-link )  - 8.23.0 so there is a hypothesis that this could be the culprit (see no.1) as we use sentry

One last thing, as annoying this might be its not a blocker because the path it takes should go back to restoring tabs. In short the user should not even feel as if the app crashed.The only drawback we have is if there is a tab which is causing issues i.e. memory hogger or slowness we wouldn't be able to recover from it. So this should be fixed. Will write it all in the ticket itself as well.

**Comment by data-sync-user** [comment] 2024-05-01 01:24
➤ Ryan VanderMeulen commented:

Nishant Bhasin Have you been able to confirm that the revert worked?

**Comment by nbhasin2** [comment] 2024-05-01 02:02
@rvandermeulen yes, I confirmed with Andy that it works

**Comment by AdinaPetridean** [comment] 2024-11-28 11:58
This issue is reproducible again on v9000 (48229) with an iPhone 14 Pro Max (iOS 16.2).

**Comment by lmarceau** [comment] 2024-11-28 14:51
@AdinaPetridean The prompt was removed on purpose in this issue: https://github.com/mozilla-mobile/firefox-ios/issues/23299. So not seeing the prompt is considered normal

**Comment by AdinaPetridean** [comment] 2024-11-28 16:36
Thank you, @lmarceau! I'll close this issue based on the above comment.

**Closed by AdinaPetridean** 2024-11-28 16:36 UTC
Labels: Bug 🐞
