### ISSUE TITLE
Firefox crashes when trying to add a customised search engine.

### ISSUE THREAD

**Issue by RaulNMS** [mozilla-mobile/firefox-ios#11651] opened 2022-08-19 12:57 UTC
## Steps to reproduce
Under settings/search/add new search engine
Type the desired search engine: e.g: 
https://youtube.com/search?q=%s
Tap SAVE

### Expected behavior
Save the search engine.
### Actual behavior
Browser crashes
### Device & build information
* Device: iphone 12 pro (ios 15.6.1)
* Build version: Firefox Daylight 103.1 (15076)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4794)

**Comment by SimonBasca** [comment] 2022-08-19 13:33
Thanks for the feedback. The fix for this problem was merged for v105. Marking as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11187

**Closed by SimonBasca** 2022-08-19 13:33 UTC
Labels: Bug 🐞
