### ISSUE TITLE
Sync process shows white screen when scanning QR code to get signed in

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#16438] opened 2023-09-18 13:51 UTC
## Steps to reproduce
Try to sync to your existing account using QR

### Expected behavior
User can complete the sync process using a QR code

### Actual behavior
After scanning the QR code use lands in a white screen
![rpapa-after-qr-code-sync-i-land-here(blankscreen)](https://github.com/mozilla-mobile/firefox-ios/assets/1897507/2dd47a90-a497-4e2b-9a57-1493c8746b29)

The only option is to go back and then you don't know if they sync was successfull or not. Usually not and you have to start again

### Device & build information
* Device: iPhone 12 Pro Max, 16.6.1
* Build version: 117.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7411)

**Comment by isabelrios** [comment] 2023-09-18 13:52
Please see similar issue with wrong QR code https://github.com/mozilla-mobile/firefox-ios/issues/16023

**Comment by jona-es** [comment] 2023-10-02 07:56
I hve the exact same behaviour on iPhone 13 mini, firefox 118.0. This problem occurs for months now. 
Btw, same behaviour when I want to use my e-mail instead of QR code.

**Comment by isabelrios** [comment] 2023-10-03 09:35
Similar issue reported here too #16681

**Comment by isabelrios** [comment] 2023-10-03 09:35
@clarmso could you please raise this bug in the next triage? it has been open for some time now and more users are seeing this. Thanks!

**Comment by isabelrios** [comment] 2023-10-06 07:26
Hi @dnarcese I would like to bring htis to your attention... it has been triaged yet and there are several complains about this behaviour. 
It is not possible to start syncing using QR code, looks like an issue to addressed sooner rather than later... what do you think?
Thanks

**Comment by data-sync-user** [comment] 2023-10-16 09:39
➤ Razvan Litianu commented:

I reviewed this issue and was unable to reproduce it on both iPhone and iPad, whether using QR or email login. Our current approach involves loading a webview that sends a callback to the view controller to trigger dismissal. It appears that either the callback is not being received, or the data it contains is invalid. To address this, I've implemented a solution where I explicitly call the onDismiss function in cases like this, which should enhance the user experience.

Additionally, we can further improve the user experience by implementing an alert or a similar notification mechanism to inform the user when such failures occur.

**Comment by data-sync-user** [comment] 2023-10-16 15:56
➤ Daniela Arcese commented:

Andrei Bodea are you able to reproduce this?

Razvan Litianu I would like to figure out what the root cause here is before we close the issue.

**Comment by data-sync-user** [comment] 2023-10-17 13:48
➤ Andrei Bodea commented:

Hello, Daniela Arceseplease note that I was not able to reproduce this issue on the latest Nightly v9000 (35230) and the Latest  v119 (35222) with iPhone 13 Pro (15.7.1), iPhone SE (16.4.1), iPhone 14 (17).

**Comment by data-sync-user** [comment] 2023-11-06 08:01
➤ Razvan Litianu commented:

Moving this back to todo until we see it’s not fixed.

**Comment by data-sync-user** [comment] 2023-11-07 14:41
➤ Norberto Andres Furlan commented:

I was able to reproduce it using Beta 35801. iPhone 14 pro. (16.1.1)

**Comment by data-sync-user** [comment] 2023-11-08 13:24
➤ Razvan Litianu commented:

Norberto Andres Furlan ohhh that’s interesting, you’re scanning the wrong QR (that is for tha appstore download). You have to tap sync your device button and a 2nd QR will show. I also found it out to be confusing in the begging and still do.

**Comment by data-sync-user** [comment] 2023-11-08 13:24
➤ Razvan Litianu commented:

Daniela Arcese can we brig this up to Desktop and UX?

**Closed** 2023-11-08 13:52 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2023-11-08 13:59
➤ Norberto Andres Furlan commented:

I tried it with the right QR, and couldn’t reproduce the issue. I think the reporter had the same problem as me. 😅  I am closing the ticket and follow up to see if we can improve design. Thanks!

**Comment by isabelrios** [comment] 2023-11-13 09:01
> Norberto Andres Furlan ohhh that’s interesting, you’re scanning the wrong QR (that is for tha appstore download). You have to tap sync your device button and a 2nd QR will show. I also found it out to be confusing in the begging and still do.

Should not we show an error or something letting user know that the QR code is wrong? if only a white screen is shown it is difficult to know that you are not using the correct one and will stop trying to sync :(
