### ISSUE TITLE
[Enhanced FF suggest settings] - Missing toggles 

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18998] opened 2024-03-05 08:01 UTC
**Prerequisites**
Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment.

**Steps to reproduce**
Go to FF settings --> Search and observe the menu.

**Expected behavior**
All the toggles are correctly displayed.

**Actual behavior**
"Show Search Suggestions" and  "Show in Private Sessions" toggles are missing from the settings menu.

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v124 (39359)
* First seen version: ?
**Notes**

**Attachments:** 
![Skype_Picture_2024_03_05T07_58_56_157Z](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/eaf2d956-1519-441a-9c74-ab5bdd3d8cc7)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8572)

**Comment by data-sync-user** [comment] 2024-03-06 14:33
➤ Norberto Andres Furlan commented:

Alina Moldovan Diana Andreea Barladeanu I am closing this ticket as it is a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-8560 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8560|smart-link )  

I added the new specs on the other ticket. Thanks!

**Closed** 2024-03-06 14:32 UTC
Labels: Bug 🐞
