### ISSUE TITLE
Missing text in the account management page

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5596] opened 2019-10-11 12:47 UTC
v20.0(16347)
iPad Pro (13.1)

1. Sign into sync.
2. Open the FxA management page.

Expected: 
1. "Firefox Accounts" should be displayed next to the Firefox logo.
OR
2. The Firefox logo is centered.

Actual: 
The Firefox logo is displayed on the left side of the header with no text next to it.

![Screen Shot 2019-10-11 at 15 34 01](https://user-images.githubusercontent.com/1866605/66652418-5df55f00-ec3e-11e9-9679-7318aaa8098f.png)

**Comment by garvankeeley** [comment] 2019-10-11 15:05
Very odd! We need to file this to FxA as it is their webpage.

**Comment by garvankeeley** [comment] 2019-10-11 18:16
https://github.com/mozilla/fxa/issues/2864

**Comment by athomasmoz** [comment] 2019-10-22 19:35
This was closed as intended behaviour on the FxA side because adding the heading would conflict with another button.

**Closed by athomasmoz** 2019-10-22 19:35 UTC

**Comment by garvankeeley** [comment] 2019-10-22 19:39
If that header was hidden for FxiOS user agent it would look much better.
