### ISSUE TITLE
The Tabs Tray icon is highlighted when opening a webpage or launching FF

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#17863] opened 2023-12-21 14:27 UTC
## Steps to reproduce
1. Launch FF open a few tabs and then close FF.
1. Re-launch FF and observe the Tabs Tray Icon.
### Expected behavior
The tabs tray should not be highlighted when re-launching FF.
### Actual behavior
The Tabs Tray icon is highlighted when opening a webpage or launching FF.
### Device & build information

* Device: iPhone 15 Pro Max (17.1.2) 
* Build version: v9000 (37132) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/a980d077-c708-4494-aef5-fa6ed649e43d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8004)

**Comment by tisumi99** [comment] 2024-01-18 23:18
I have a fix for this and will submit a PR shortly.

https://github.com/mozilla-mobile/firefox-ios/assets/98071325/5ad73c76-0085-4621-90f4-ddc77b319851

**Comment by tisumi99** [comment] 2024-01-19 20:18
I can no longer reproduce the issue with the latest code from the main branch.  I believe that pull request [Refactor FXIOS-8169 [v122.1] Theming manager not saving theme (backport #18211)](https://github.com/mozilla-mobile/firefox-ios/pull/18242) fixes the actual root cause of this issue.  I will close my pull request.

**Comment by csuciu** [comment] 2024-02-26 11:13
Closing per last comment.

**Closed by csuciu** 2024-02-26 11:13 UTC
Labels: Contributor OK, Bug 🐞, S3
