### ISSUE TITLE
FXIOS-1823 ⁃ "Request Desktop Site" erroneously mangles URL

### ISSUE THREAD

**Issue by PandorasFox** [mozilla-mobile/firefox-ios#8491] opened 2021-05-12 21:18 UTC
## Steps to reproduce

* Navigate to a webpage that contains `m.` anywhere in the url (e.g. `https://www.instagram.com/accounts/login/`)
* Request desktop site
* Be redirected to `https://www.instagracom/accounts/login`

### Expected behavior

Request desktop site should not mangle the url of the current page

### Actual behavior

The `m.` in the middle of the URL is stripped out (presumably to make `m.foo.bar` redirect to `foo.bar`).

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox Daylight 33.1 (4629)

### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/3235827/118045472-cb8ed300-b32c-11eb-95ee-d612a0bc5ca3.png)
![image](https://user-images.githubusercontent.com/3235827/118045480-ce89c380-b32c-11eb-9c05-dd98f723f483.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1823)

**Comment by gutley** [comment] 2021-05-13 16:13
This is the same as [#8227 ](url)

**Comment by dnarcese** [comment] 2021-05-13 18:39
Duplicate of #8227

**Closed by dnarcese** 2021-05-13 18:39 UTC
Labels: Bug 🐞
