### ISSUE TITLE
Links from external apps open Firefox but don't load the link (intermittent)

### ISSUE THREAD

**Issue by davismtl** [mozilla-mobile/firefox-ios#18033] opened 2024-01-08 18:30 UTC
## Steps to reproduce
- Click on a link in another app (e.g. email)
- Firefox opens

### Expected behavior
- Link opens a new tab and loads

### Actual behavior
- Nothing. Loads the last viewed tab.
- I need to click on the link a second time

### Device & build information
* Device: iPhone 15 Pro Max, 17.2.1
* Build version: 122.0 (37367)
* First seen version: I don't know. 

### Notes
- It's hard to reproduce because it happens every so often but not enough to easily reproduce but then again often enough that it annoyed me over the holidays (and I could easily see how it could lead to browser churn).
- It's not a new problem but it didn't happen often enough in the past for me to actually file a bug. It took 2 weeks of intense mobile usage to make the problem apparent.
- A small observation (though anecdotal) is that I think it tends to happen more often when Firefox hasn't been used for some amount of time. I don't know if the OS put the app to sleep and it leads to this. But again there, it's not always doing this.
- I've had this happen across multiple iPhones. (I had the iPhone 13 Pro prior to this one and it happened there too)
- The tab doesn't seem to be opening in the background behind the last seen tab.

I'll try to start logging more detailed accounts of the situation. Are there any logs I can somehow get to that could help diagnose this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8103)

**Comment by brendanjones** [comment] 2024-01-09 14:23
When trying to get a screen recording of https://github.com/mozilla-mobile/firefox-ios/issues/17927 I actually reproduced this one instead, so here’s a recording! I suspect they’re linked. 

I don’t know the conditions that separate these two bugs, so I don’t know why sometimes the new page does/ doesn’t load. 

Vid is too big to attach so here’s an iCloud link: https://share.icloud.com/photos/0d8AvYecQIrWxz4QIah-6JXNQ

What you’re seeing is:
- video starts with me in Slack
- I open the link in slack
- Slack opens the link in its in-app browser
- I tell it to open the link in my browser
- Firefox opens, and the last tab I had open loads (the Kafka band event)
- I go back to slack and open the link in browser again
- Firefox loads, and correctly loads the link in a new tab.

**Comment by bholley** [comment] 2024-01-09 22:57
This recently started happening to me as well. I suspect it depends on whether Firefox is still running. Retrying generally works, which makes me suspect it's a similar type of failure to #17395.

**Comment by davismtl** [comment] 2024-01-10 23:59
It occurred first thing this morning again which somewhat aligns with my observation that it happens when Firefox has been idle for some time. It's been fine for the rest of the day. 

I do see an updated release version so the app also updated overnight while charging so perhaps the app gets into a weird state after an update (which happens regularly with pre-release builds). This new hypothesis should be easier for me to test. I can try to do a manual update of the app at the next opportunity and see if I can replicate.

**Comment by davismtl** [comment] 2024-01-12 17:49
Circling back, I replicated it yesterday. I updated Firefox and the first link I clicked on didn't work. I had to click on it a second time to work. I'll try to replicate again on the next update.

**Comment by data-sync-user** [comment] 2024-01-13 00:36
➤ Matthew Reagan commented:

I’m investigating this though I’ve not been able to replicate yet, and the requisite conditions causing the problem aren’t 100% clear. I did find a bug in the App Event Queue which could be related, so I am preparing a PR to address that; there is a chance that will fix the bug described in this ticket (8103) however I haven’t been able to confirm directly yet since I can’t replicate.

So far I’ve tested different scenarios including deeplinking while the app is backgrounded or after being jetsammed, forcing low-memory conditions, and also forcing the Start at Home feature to always trigger (to see if that was possibly causing a conflict with the tab loading). I’ve also got a device I’m letting sit idle to see if I can replicate after a long period of inactivity.

Sidenote: a few comments sound slightly similar to #17395 (FXIOS-7799) which should now be fixed but was a different issue that was 100% reproducible, and I don’t believe it’s related (that bug was occurring because the client simply wasn’t handling Sent Tab URLs which are routed differently when the app is killed vs. when the app is running or backgrounded).

Any additional screen recordings, logs, or repro steps would be helpful (cc Andrei Bodea Norberto Andres Furlan ).

**Comment by data-sync-user** [comment] 2024-01-16 07:38
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (37686), on iPhone 15 (17.0).

No external link loading issue encountered.

**Closed by data-sync-user** 2024-01-16 07:38 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2024-02-02 20:40
➤ Norberto Andres Furlan commented:

Andrei Bodea Diana Andreea Barladeanu I have reports from people inside Firefox that says that it is still happening on 122.1. However, I am not able to reproduce it. Can you do more testing to see if still happening?

**Comment by data-sync-user** [comment] 2024-02-07 15:44
➤ Matthew Reagan commented:

This is likely a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-7799 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7799|smart-link ) , even though that ticket specifically mentions Send to Device, I believe the underlying culprit is likely the same. 

The issue is being actively investigated; I’ve been able to reproduce it a few times now and am gathering additional diagnostic information and will update on 7799 as soon as I’m able.

**Comment by Sobakel** [comment] 2024-04-07 21:32
This is still happening for me.
iPhone 15pro
Ios17.4 
Firefox 124.2 (40108) set as default browser

in any app, I press hyperlink. Firefox opens but no link appears and no activity

**Comment by AkaZecik** [comment] 2024-04-08 07:25
Happening for me as well. Same symptoms as @Sobakel's and others'.

iPhone 8
iOS 16.7.7
Firefox 124.3 (40336) set as default browser

**Comment by florianjehn** [comment] 2024-06-23 09:21
I also experience this issue. The bug always occurs when I try to open a link with Firefox while Firefox is not open. As Firefox is my default browser, it opens, but does not load. Also when other tabs from previous sessions were open, I cannot view them, as Firefox tells me they have crashed. To use Firefox again I have to restart it. This happens on both my Laptop and my Desktop computer.  Both use:
- Linux (Zorin 17)
- Firefox 127.0.1
