### ISSUE TITLE
Pop-up window crashes app

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#21658] opened 2024-08-27 23:55 UTC
## Steps to reproduce
1. Open a (test) website that contains a pop-up window. (Example: https://www.webroot.com/services/popuptester1.htm)
1. Tap hamburger menu and open Settings.
1. Turn off "Block Pop-up Windows".
1. Tap "Done" to close the Settings.
1. Open a (test) website that contains a pop-up window. (Example: https://www.webroot.com/services/popuptester1.htm)

Automated test: XCUITests/NavigationTest/testWriteToChildPopupTab
The test fixture used in the automated test: https://github.com/mozilla-mobile/firefox-ios/blob/main/test-fixtures/test-window-opener.html

### Expected behavior
The pop-up window is shown in the last step

### Actual behavior
The app crashes in the last step.

### Device & build information
* Device: iPhone 15 iOS 17.5 simulator
* Build version: Aug 27, 2024
* First seen version: ~Aug 27, 2024
### Notes
Attachments: 

https://github.com/user-attachments/assets/b1c10d56-1227-4814-8253-1353a8066315

* Also seen in iOS 16.4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9871)

**Comment by abodea** [comment] 2024-08-28 12:35
Hello, @clarmso please note that we are not able to reproduce this issue:
On the website example you posted, I don't think anything is happening as it looks broken for example when you attempt to "test" any pop-up it only redirects you to a blank page (I tried this on a desktop website to see how the website is).
We tried on the following devices:
- iPhone 15 (17.5)
- iPhone 13 Pro (15.7.1)
- iPhone 15 Pro max (17.5.1)
Can you please re-upload the video? Looks like it's not working

**Comment by data-sync-user** [comment] 2024-08-28 13:33
➤ Clare So commented:

Andrei Bodea I have attached the recording to the Jira ticket.

**Comment by clarmso** [comment] 2024-08-28 15:02
I have confirmed that the PR https://github.com/mozilla-mobile/firefox-ios/commit/1a53ed9dd0cc3a41cc63786bbc6ee6f3667dfa48 is the cause of the regression.

v130 is not affected.

**Comment by clarmso** [comment] 2024-08-28 15:07
I confirmed that the PR https://github.com/mozilla-mobile/firefox-ios/commit/1a53ed9dd0cc3a41cc63786bbc6ee6f3667dfa48 from Aug 26 started the regression.

v130 is not affected.

**Comment by data-sync-user** [comment] 2024-08-28 15:11
➤ Andrei Bodea commented:

Thank you I was able to reproduce it on v9000 (44662) with iPhone 13 Pro (15.7.1).
Also, thx I can see now the video on Jira, I was checking GitHub.

**Comment by nbhasin2** [comment] 2024-09-03 22:01
Alex is already assigned to this, should be fixed soon 🤞🏼

**Comment by data-sync-user** [comment] 2024-09-04 11:27
➤ Alexandru Farcasanu commented:

Nishant Bhasin Yesterday I was able to reproduce the issue but now is no more reproducible on main. After did some checks, Matt Reagan fixed this https://mozilla-hub.atlassian.net/browse/FXIOS-9921 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9921|smart-link )  and merged it. Also, Matt’s fix fixed also this issue. (after investigations). Moving it to the QA.

**Comment by data-sync-user** [comment] 2024-09-23 09:44
➤ Andrei Bodea commented:

Verified as fixed on v131 (45514) with iPhone 15 Pro (17.5). 
Please note that the issue cannot be reproduced anymore, FF does not crash but there is a regression as an About:blank tab/page is opened instead of crashing now. 
https://github.com/mozilla-mobile/firefox-ios/issues/22139 ( https://github.com/mozilla-mobile/firefox-ios/issues/22139|smart-link )  added this as a regression.

**Closed** 2024-10-13 07:59 UTC
Labels: Bug 🐞, Crash, eng:bug-auto-found
