### ISSUE TITLE
URL bar focus hides bottom bar

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-mobile/firefox-ios#9037] opened 2021-08-30 23:40 UTC
## Steps to reproduce
1. Open Firefox for iOS with a new session

### Expected behavior
1. Open Firefox for iOS with a new session
2. URL bar is or is not focused (On Safari the URL bar is not focused, on Focus it is)
3. Keyboard is or is not visible (On Safari the keyboard is not shown, on Focus it is, but bottom bar is still visible)
4. The bottom bar is visible

### Actual behavior
1. Open Firefox for iOS with a new session
2. A new tab appears, URL bar is focused, keyboard is visible
3. There is no bottom bar (list of tabs, hamburger menu)
4. Dismiss keyboard
5. There is no bottom bar
6. Press the < arrow on the left of the URL bar
7. Now there is a bottom bar

### Device & build information
* Device: iPhone 12
* Build version: Firefox Daylight 36.0 (5732)

### Notes
Attachments: 

# Fresh Start, URL is focused
![2021-08-30 19 33 00](https://user-images.githubusercontent.com/119884/131419363-0fd4d9d7-7011-411d-9a32-8605dc4166ed.png)

# Keyboard is dismissed
![2021-08-30 19 33 08](https://user-images.githubusercontent.com/119884/131419361-d9d87970-d1ec-4d71-946f-45c0cdc4d25e.png)

# Left arrow on URL bar is pressed
![2021-08-30 19 33 14](https://user-images.githubusercontent.com/119884/131419357-3e3795d2-556a-4158-ae48-417f62e9e839.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3109)

**Comment by dnarcese** [comment] 2021-09-16 18:49
duplicate of #7608

**Closed by dnarcese** 2021-09-16 18:50 UTC
Labels: Bug 🐞
