### ISSUE TITLE
Update position of Show All to be aligned in all sections on Homepage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11488] opened 2022-08-02 18:26 UTC
The position Show All in JumpBackIn section is the correct one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4687)

**Comment by dnarcese** [comment] 2022-08-04 19:43
duplicate of #11501

**Closed by dnarcese** 2022-08-04 19:43 UTC
