### ISSUE TITLE
FXIOS-1633 ⁃ Opening a map link from facebook with apple maps removed causes FF to open hundreds of tabs within seconds causing the screen to flash rapidly.

### ISSUE THREAD

**Issue by Spax123** [mozilla-mobile/firefox-ios#8205] opened 2021-03-24 23:21 UTC
## Steps to reproduce
Remove Apple maps from IOS device, open a map link from a facebook business page with FF set as default browser.
### Expected behavior
Dialog box should appear telling the user they need to "restore maps"
### Actual behavior
Firefox opens hundred of tabs within seconds causing the screen to flash extremely quickly, only way to stop is to force close FF.
### Device & build information
* Device: ? iPhone 8 (iOS 14.4.1)
* Build version: ? Firefox Daylight 32.1 (3961)
### Notes
Heres a link to a post I made on Reddit where I uploaded a video of what happens.
https://www.reddit.com/r/firefox/comments/mcj1a8/epilepsy_warning_horrible_bug_in_ff_for_ios_when/
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1633)

**Comment by SimonBasca** [comment] 2021-03-25 09:53
Duplicate of #7363

**Closed by SimonBasca** 2021-03-25 09:53 UTC
Labels: Bug 🐞
