### ISSUE TITLE
Téléphone is always linked

### ISSUE THREAD

**Issue by DorianCoding** [mozilla-mobile/firefox-ios#14007] opened 2023-04-19 05:44 UTC
## Steps to reproduce
Create a html page with a 10-digit number.
### Expected behavior
On iOS, the number will be linked unless `<meta name="format-detection" content="telephone=no">` is given.
### Actual behavior
On Firefox this option is ignored and phone is always linked.
### Device & build information
* Device: iOS 16.4 IPhone XR
* Build version: Firefox 112.0 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6212)

**Comment by dnarcese** [comment] 2023-04-20 18:43
Duplicate of #9553

**Closed by dnarcese** 2023-04-20 18:43 UTC
Labels: Bug 🐞
