### ISSUE TITLE
Update shavar prod list to latest version

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12166] opened 2022-10-18 20:52 UTC
Shavar prod list wasn’t updated for a while, let’s point to latest version and fix issues that comes up.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5102)

**Comment by lmarceau** [comment] 2022-10-19 18:32
Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11218

**Closed by lmarceau** 2022-10-19 18:32 UTC
