### ISSUE TITLE
Toast messages are incorrectly displayed when user closes multiple tabs by sweeping them in tab tray 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14289] opened 2023-05-08 13:32 UTC
## Steps to reproduce
1. Have multiple tabs in tabs tray 
2. Close multiple tabs by sweeping them in a quick session 
3. Check the toast messages 

### Expected behavior
The toast massages are displayed in row, when the new message appear the old one is removed 

### Actual behavior
The toast messages overlap 

### Device & build information
* Device: iPhone 14 Plus (16.0.3) 
* Build version: V9000 (30588) 
* First seen version: ? 
### Notes
Attachments: 

https://user-images.githubusercontent.com/124251579/236837303-b69b43ae-65a2-478f-b493-d5d535b8f209.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6362)

**Comment by data-sync-user** [comment] 2023-05-08 13:49
➤ Yoana Rios Diaz commented:

Alina Moldovan this will be fixed by the work done by Sorin Paraipan for https://github.com/mozilla-mobile/firefox-ios/pull/14181 ( https://github.com/mozilla-mobile/firefox-ios/pull/14181|smart-link ) https://mozilla-hub.atlassian.net/browse/FXIOS-6328 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6328|smart-link )

**Comment by DianaBarladeanu** [comment] 2023-05-25 10:18
Verified the fix using FF v9000 (31186) and iphone SE (15.4). The issue is no longer reproducible. 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/330ab109-9401-4111-8ab2-d816e835746f

**Closed** 2023-05-25 10:20 UTC
Labels: Bug 🐞, S3
