### ISSUE TITLE
117.0, 117.1 and 117.2 crash on launch on iOS 14 iPhone X (jailbroken)

### ISSUE THREAD

**Issue by Amzd** [mozilla-mobile/firefox-ios#16281] opened 2023-09-07 13:31 UTC
## Logs

[Client-crash-logs.zip](https://github.com/mozilla-mobile/firefox-ios/files/12549585/Client-crash-logs.zip)

Cannot get Firefox log as the app does not launch and after downgrading to 116.4 the log it exports does not include the crashes.

## Steps to reproduce

- Launch app

### Expected behavior

- Not crash

### Actual behavior

- Crash

### Device & build information
* Device: iPhone X (jailbroken)
* Build version: 117.0, 117.1 and 117.2

### Notes

Not sure if jailbroken state matters as I don't have a different device.

I am also able to provide further crash logs from eg Cr4shed if deemed necessary.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7353)

**Comment by lmarceau** [comment] 2023-09-07 14:50
Hello @Amzd, thank you for opening this ticket and sharing the logs with us. This is very helpful, we'll have a look on our end to figure out why it's crashing at launch.

**Comment by lmarceau** [comment] 2023-09-07 14:51
This relates to ticket https://github.com/mozilla-mobile/firefox-ios/issues/16209 as well (same cause)

**Comment by lmarceau** [comment] 2023-09-07 15:24
Hello! Thank you for reporting this issue. We're investigating it, and it seems to be related to the OS version (between 14.0 and 14.4), if you upgrade your OS to a more recent version it should fix the problem. In the meantime, we'll continue to figure out a solution. Thank you!

**Comment by Amzd** [comment] 2023-09-07 15:37
> if you upgrade your OS to a more recent version it should fix the problem.

As my device is jailbroken that is not an option because there is no newer iOS versions that have real jailbreaks. I appreciate you trying to this iOS version!

**Comment by dnarcese** [comment] 2023-09-07 18:33
Duplicate of #16209

**Closed by dnarcese** 2023-09-07 18:33 UTC
Labels: Crash
