### ISSUE TITLE
Navigation and ulrbar overlap

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#17680] opened 2023-12-07 20:59 UTC
## Steps to reproduce
I have the URL bar set to appear at the top of the screen. Intermittently, when rotating the device to portrait orientation or switching back to Firefox from other apps, the URL bar and navigation bar are superimposed at the top of the screen. Rotating the device fixes this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7924)

**Comment by dnarcese** [comment] 2023-12-07 20:59
split from #16167

**Comment by dicarobinho** [comment] 2024-05-28 12:50
Hello @dnarcese,

May you confirm please, still have this issue? I am not able to reproduce it. :)

Thank you.

**Comment by data-sync-user** [comment] 2024-05-31 08:23
➤ Alexandru Farcasanu commented:

Moved it to the QA team. I am not able to reproduce it.
Andrei Bodea

**Comment by data-sync-user** [comment] 2024-05-31 13:21
➤ Andrei Bodea commented:

Verified as fixed on v127 (42366) with iPad Pro (16.4.1).

**Closed** 2024-10-20 03:34 UTC
Labels: Bug 🐞
