### ISSUE TITLE
The home icon overlaps the + icon in landscape

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9245] opened 2021-10-04 14:28 UTC
## Steps to reproduce
1. Set Firefox as default browser
2. Open a link from notes e.g "google.com"
3. Change device orientation to landscape
### Expected behavior
- No overlap should be displayed.
### Actual behavior
- The home icon overlaps the + icon
### Device & build information
* Device: iPhone 12 Pro 14.7
* Build version: 38.1 (6216)
### Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7278726/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3246)

**Comment by dnarcese** [comment] 2021-10-07 16:48
Caused by https://github.com/mozilla-mobile/firefox-ios/commit/444c4bedd5def27b6fabbb22cc85d6c73485cac2. Let's revert that commit for now and find a better solution.

**Comment by csuciu** [comment] 2022-01-26 12:03
Verifying as fixed on v97.0 (7635)

**Closed by csuciu** 2022-01-26 12:03 UTC
Labels: Contributor OK, Bug 🐞, Contributor Fix
