### ISSUE TITLE
Inconsistency in opening tabs from external links in normal vs private browsing [Intermittent]

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21773] opened 2024-09-04 09:07 UTC
**Steps to reproduce**

1. Fresh install FF.
1. In normal browsing, open https://www.huffpost.com/entry/laundry-detergent-amount-clean-clothes-2_n_66cf6a04e4b054d208573425?utm_source=pocket-newtab-en-us and tap on the first link, the one with (...)"Am I doing it wrong(...).
1. Observe
4 Repeat steps 2 and 3 in private browsing.

**Expected behavior**
The external links opening behavior is the same both in normal and private browsing, either opening in a new tab or in the same tab.

**Actual behavior**
In the example presented above, the external link opens in a new tab in normal browsing mode and in the same tab in private browsing mode.

**Device & build information**

* Device: 
* Build version: v131 (44858)
* First seen version: ? 

Notes
An example of website where the external link opening has the same behavior both in normal and private browsing, it opens in a new tab:
Access: https://arhiblog.ro/cu-voia-voastra-ultimul-de-pe-lista-ion-iliescu/ and tap on "Aurel Manea".

Attachments: 

https://github.com/user-attachments/assets/e1f2ebcd-dd21-4a8a-b58a-a83c1f9b0fe8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9924)

**Comment by data-sync-user** [comment] 2024-09-06 16:15
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu whenever you have time can you take a look to this one? In normal mode, the link should also open on the same tab.

**Comment by data-sync-user** [comment] 2024-09-09 14:57
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan 

Few things here: it seems this issue appeared after a fix for this https://mozilla-hub.atlassian.net/browse/FXIOS-7586 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7586|smart-link ). 

From the 7586 ticket description:  “If the user is in private browsing the app should never deeplink to an external application.“ 

Well, after a while I have added an option in settings (available also for private mode) to “Block Opening External Apps”.

Current implementation:

            if navigationAction.navigationType == .linkActivated { 
                if tab.isPrivate || (profile.prefs.boolForKey(PrefsKeys.BlockOpeningExternalApps) ?? false) {
                    decisionHandler(.cancel)
                    webView.load(navigationAction.request)
                    return
                }
            }line 2: if a link was detected

line 3: if is private mode or we have that option from settings enabled “Block Opening External Apps”.

we continue to load the page in the current tab (without opening a new tab or opening an external app)

The problem is (from my perspective):

We are not able to identify exactly if the link is going to redirect us to the external app or is just a normal website link. (hope to be wrong here 🤞 )

Also, it can be confusing for users with the current implementation (for example they don’t have enabled the “Block Opening External Apps” option but because they are in private mode, external apps will not be opened).

My suggestions here are: 

1. Still block any links in private mode by going to the external apps but hide that option (“Block Opening External Apps” ) in private mode, from settings.

or

  1. Let the links to open the external apps in private mode if the “Block Opening External Apps” is disabled.

Suggestion number 2, for sure will fix also this issue (9924). In case we are going for suggestion 1 (or other fixes), we still need to find an option to separate the external apps links by the normal websites links.

cc: Nishant Bhasin

**Comment by data-sync-user** [comment] 2024-09-19 14:38
➤ Nishant Bhasin commented:

Alexandru Farcasanu please go with suggestion 2. to respect the toggle for both private and regular tabs.

Reason: Its a single toggle for both and should behave as such unless a new copy change or another toggle of sorts is added for private / regular tabs

cc Norberto Andres Furlan

**Comment by data-sync-user** [comment] 2024-10-03 13:32
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v132 (45901), with iPhone 15 (17.5).

**Closed** 2024-10-20 04:49 UTC
Labels: Bug 🐞, S3
