### ISSUE TITLE
Night mode missing in 124

### ISSUE THREAD

**Issue by jryans** [mozilla-mobile/firefox-ios#19365] opened 2024-03-25 00:58 UTC
## Steps to reproduce

1. Look for night mode in the menu

### Expected behavior

It should be there so I can control content night mode as I have for years…

### Actual behavior

No night mode option 😭

### Device & build information
* Device: iPhone 15 Plus, iOS 17.4
* Build version: 124.0
* First seen version: Seems new to 124
### Notes

I am very concerned by issues I am seeing that suggest you are experimenting with removing the separate night mode switch. I have used it every day, and it is currently missing… If you remove it for real I will have to find a new browser so I can use my phone at night… 😭

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8735)

**Comment by kelimuttu** [comment] 2024-03-25 03:12
Someone brought this up on [SUMO](https://support.mozilla.org/questions/1443158#answer-1644006) just recently.

**Comment by machinshin** [comment] 2024-03-25 13:53
I also noticed this last night 

Firefox 124.0 (39709)
On iPhone 14 Plus

iOS version: 17.3.1

**Comment by MarkTheUnruly** [comment] 2024-03-25 16:45
This is a serious issue for me, I have cataracts and photophobia caused by my diabetes.  I only every use night mode to avoid eyestrain.  

Is there a way to go back to ver 123 on my iPad until the issue is resolved? Running iPadOS 17.3.1

**Comment by Zumbas** [comment] 2024-03-25 19:13
+1 
Unbelievable how such a thing can happen.

**Comment by kelimuttu** [comment] 2024-03-26 01:45
Another accessibility concern. This one is from [SUMO](https://support.mozilla.org/questions/1443105#answer-1644128): 

> I, too depend on night mode to do my job as a videographer. Lack of this feature renders your browser inaccessible and unusable for my sensory disability, as well. Last night it disappeared from the menus in my iPad and Android phone. Setting the theme to dark mode in iOS does not darken webpages.

**Comment by crawford** [comment] 2024-03-27 13:13
> We're using this experiment to monitor and evaluate the impact of removing, so it'll be hugely valuable to hear your feedback around this feature.

I’m not sure how the team is monitoring the impact of removing, so I guess I’ll just pile on here. Without Night Mode, the browser is unusable in the early morning and night, since most websites I visit do not respect the system theme. This is compounded by the fact that Firefox on iOS does not support extensions (i.e. Dark Reader cannot be installed). I have a strong preference towards using websites instead of apps, so this regression is particularly jarring. I’ll add to the sentiment expressed above, I do not appreciate being a part of this experiment and this only further encourages me to stop updating the apps on my phone.

**Comment by brixtonn** [comment] 2024-03-28 05:11
this feature is the only reason i used firefox. since it no longer works i've uninstalled the app.

**Comment by MarkTheUnruly** [comment] 2024-03-28 13:57
Interesting that there is no one assigned to this.  Do I assume from that that the Firefox team doesn't care?

**Comment by crawford** [comment] 2024-03-28 14:08
@MarkTheUnruly they are currently running an experiment via Nimbus (here’s the pull request which introduced it: https://github.com/mozilla-mobile/firefox-ios/pull/18803) and are waiting to hear users’ responses (I’m not sure how that feedback is gathered or monitored). In the meantime, I can’t imagine they would consider this a bug.

**Comment by crawford** [comment] 2024-03-28 14:41
Here's the workaround for anyone who's interested.

Navigate to Menu > Settings > About and tap on "Firefox \<version number\>" five times. That will open up a hidden Debug section. From there go to Debug > Experiments > iOS - Night Mode and select "control" instead of "treatment-a". That will bring back the "Turn on Night Night" menu item.

I pulled this from https://support.mozilla.org/en-US/questions/1443105#answer-1644537. Thanks TimmyTango.

**Comment by MarkTheUnruly** [comment] 2024-03-28 15:12
So, they removed an accessability feature WITHOUT WARNING.  What an utter lack of porfessionalism.  I have been a coder since 1985 and I would never do what they have done.

I am a diabetic with vision issues.  A dark background is a requirement for me to use a device without strain and most websites don't support a dark mode, (including support.mozilla.org). This will affect everyone with cataracts, photophobia and various other conditions.  Having diabetes makes you 2 to 5 times more likely to develop cataracts. It also makes you more likely to get them at a younger age.  This means that the number of people is growing along with the rise in Type 2 diabetes.

One of Firefox's missions is supposed to be to make the web more accessible to people.  I dont have night mode, so for me, Firefox for IOS is currently failing that misssion.  

Removing this feature would force me to switch browsers on my iPad, probably to Safari, which I hate, since I can use the Dark Reader add-in.  I have been using Firefox since 2004 when the committee advising the US government said IE6 was a security concern and I love the features and ease of use.

**Comment by MarkTheUnruly** [comment] 2024-03-28 15:14
> Here's the workaround for anyone who's interested.
> 
> Navigate to Menu > Settings > About and tap on "Firefox <version number>" five times. That will open up a hidden Debug section. From there go to Debug > Experiments > iOS - Night Mode and select "control" instead of "treatment-a". That will bring back the "Turn on Night Mode" menu item.
> 
> I pulled this from https://support.mozilla.org/en-US/questions/1443105#answer-1644537. Thanks TimmyTango.

Thank you!

**Comment by crawford** [comment] 2024-03-28 15:44
> So, they removed an accessability feature WITHOUT WARNING. What an utter lack of porfessionalism.

@MarkTheUnruly let me take this one step further, if you'll allow me. As evidenced in https://github.com/mozilla-mobile/firefox-ios/pull/18803, it was @nbhasin2 who signed off on this change. According to both GitHub and LinkedIn, this individual holds the title "Engineer" and is based in Canada. Canada has a strict definition of who may hold that title and how they must conduct business, defined in the Engineers and Geoscience Professions Act (detailed here: https://engineerscanada.ca/become-an-engineer/use-of-professional-title-and-designations). I'm going to give them the benefit of the doubt and assume that they are in fact a registered member of APEGA and are not illegally using that title. In that case, they have simply, in my opinion, violated the third tenet of the "practice of engineering" and should be re-evaluated for continued membership in the professional organization.

**Comment by MarkTheUnruly** [comment] 2024-03-28 16:23
> @MarkTheUnruly let me take this one step further, if you'll allow me. As evidenced in #18803, it was @nbhasin2 who signed off on this change. According to both GitHub and LinkedIn, this individual holds the title "Engineer" and is based in Canada. Canada has a strict definition of who may hold that title and how they must conduct business, defined in the Engineers and Geoscience Professions Act (detailed here: https://engineerscanada.ca/become-an-engineer/use-of-professional-title-and-designations). I'm going to give them the benefit of the doubt and assume that they are in fact a registered member of APEGA and are not illegally using that title. In that case, they have simply, in my opinion, violated the third tenet of the "practice of engineering" and should be re-evaluated for continued membership in the professional organization.

Crawford, I thoroughly agree!

**Comment by jevans-mozilla** [comment] 2024-03-28 16:53
Please do not let conversations devolve into personal attacks.  Feeling strongly about a topic is acceptable.  Feedback on topics is acceptable.  Personal attacks on individuals is not.

**Comment by MarkTheUnruly** [comment] 2024-03-28 17:39
> Please do not let conversations devolve into personal attacks. Feeling strongly about a topic is acceptable. Feedback on topics is acceptable. Personal attacks on individuals is not.

Jeremy, fair comment, but if a person has broken professional rules in their country of residence, should they not be held accountable for their actions?

**Comment by data-sync-user** [comment] 2024-03-28 17:44
➤ Norberto Andres Furlan commented:

Thank you for taking the time to share your concerns and feedback. We truly understand the importance of accessibility features and your feedback is really valuable for us. We apologize for any inconvenience caused by the experiment. 

In response to the feedback collected, I have requested the termination of the experiment. The nightmode option will be reinstated soon. Please feel free to reach out to us if you have any further questions or concerns.

**Closed by data-sync-user** 2024-03-28 17:44 UTC
Labels: Bug 🐞

**Comment by cdaylward** [comment] 2024-03-28 18:33
> ➤ Norberto Andres Furlan commented:
> 
> Thank you for taking the time to share your concerns and feedback. We truly understand the importance of accessibility features and your feedback is really valuable for us. We apologize for any inconvenience caused by the experiment.
> 
> In response to the feedback collected, I have requested the termination of the experiment. The nightmode option will be reinstated soon. Please feel free to reach out to us if you have any further questions or concerns.

Friendly note: Perhaps check in a code comment or other documentation that this is an important accessibility and usability feature so that future devs do not venture down this route?

Needless to say that browsers are now an important part of modern life. It might be good to have a reminder that it's not all just a matter of aesthetics (or even developer burden).

**Comment by ironlion37** [comment] 2024-03-28 18:52
Yes, this is the main reason I use the app on my phone. There's room for major improvements here though:

1. Tie the dark mode to system settings on the phones. In other words, if my iPhone is set to use dark mode, give me the option in Firefox settings to "use system setting." 
2. Dark mode should work as the "Dark Reader" browser extension does. (If there was a way to get than on my phone browser, I would do it.) Firefox dark mode doesn't work really well - some sites I want to turn it on, some site I need to turn it off. The Dark Reader extension is very good about handling all that gracefully and automatically. I suggest studying how that piece of software does its thing.

**Comment by MarkTheUnruly** [comment] 2024-03-28 19:28
Ok, apparently the experiment is being terminated and night mode re-instated, good news.

**Comment by jevans-mozilla** [comment] 2024-03-28 19:54
> > Please do not let conversations devolve into personal attacks. Feeling strongly about a topic is acceptable. Feedback on topics is acceptable. Personal attacks on individuals is not.
> 
> Jeremy, fair comment, but if a person has broken professional rules in their country of residence, should they not be held accountable for their actions?

Mozilla complies with professional titles for job positions in Canada as it varies between province of residence.  In this case no professional rules were broken.

We do enforce our [Code of Conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/) here and posting personal information about an employee is not only in breach of our code of conduct, but also in bad taste.

If you feel anyone (especially Mozilla employees) are acting unprofessionally, there is a means to submit a concern at the bottom of the above link.

**Comment by ironlion37** [comment] 2024-03-29 04:50
An update: I just found out that the Dark Reader browser extension can be downloaded and used with Safari on iOS. So I've now switched to Safari as my default browser on my phone as well. Dark mode is a main requirement for me in a browser.

As I mentioned above Dark Reader handles sites much more gracefully than Firefox dark mode.

If Firefox could load the dark reader extension as Safari does, then I would switch back to Safari.
