### ISSUE TITLE
[Intermittent] If the last tab opens another app (amazon) when opening a new deep link it will redirect straight to the last opened app instead of Firefox

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19864] opened 2024-04-18 11:51 UTC
## Prerequisites
Have any product on Amazon link saved in Notes - long tap on it and open it in the Amazon App. (make sure the Amazon app is installed).
Set Firefox as the default browser.
Have a www.google.com link saved in Notes.

## Steps to reproduce
1. Install and Launch FF.
1. Go to FF open any Amazon product, share it via the share menu, and choose `Find product on Amazon`.
1. The Amazon App is opened with the shared product.
1. Close the Amazon app and close Firefox.
1. Go to notes and tap on the www.google.com.
### Expected behavior
Firefox should correctly open and www.google.com should be loaded.
### Actual behavior
If the last tab opens another app (amazon) when opening a new deep link it will redirect straight to the last opened app instead of Firefox.
### Device & build information

* Device: iPhone 15 Pro (17.4.1) 
* Build version: v126 (40846) 
* First seen version: v126 (40846) 
### Notes
Please note that this issue is intermittent and sometimes might not be reproducible.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/cf13c1cb-a28c-4a72-acac-305f8195b011

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9000)

**Comment by data-sync-user** [comment] 2024-04-18 19:18
➤ Norberto Andres Furlan commented:

Andrei Bodea I think linkedin has the same problem. This is an OS bug, not Firefox, so we don’t have any control here.

**Comment by data-sync-user** [comment] 2024-06-04 09:17
➤ Diana Andreea Barladeanu commented:

The issue is still reproducible. Checked on v127 (42448), with iPhone 15 (17.4.1) and FF as default browser.

Norberto Andres Furlan, if you consider that this is an iOS bug, we can close this ticket. Thanks!

!RPReplay_Final1717492437.mp4|width=590,height=1280,alt="RPReplay_Final1717492437.mp4"!

**Comment by data-sync-user** [comment] 2024-06-07 06:53
➤ Alexandru Farcasanu commented:

After my investigations and Orla’s comment, I am going to close it at least for the moment.

!Screenshot 2024-06-07 at 09.49.26.png|width=405,height=131,alt="Screenshot 2024-06-07 at 09.49.26.png"!

cc: Norberto Andres Furlan

**Closed** 2024-10-27 23:28 UTC
Labels: Bug 🐞, S2
