### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by M4tul** [mozilla-mobile/firefox-ios#17936] opened 2023-12-28 10:12 UTC
## Steps to reproduce
Find pdf to scroll, eg.: https://arxiv.org/pdf/1002.0200.pdf. Start to scroll. 

### Expected behavior
Smooth scrolling 

### Actual behavior
When scrolling down it jumps back to the beginning of the pdf after while.

### Device & build information
* Device: iPad Air 5th gen, iPadOS 17.1.2
* Build version: 121.0 (36782)
* First seen version: ? It is a few months.
    1. Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/111222289/87b817eb-bfef-4479-9607-decab6f1d530

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8047)

**Comment by Prurite** [comment] 2023-12-29 01:10
duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/17146 ?

**Comment by M4tul** [comment] 2023-12-29 13:23
I am blind, duplicate.

**Closed** 2023-12-29 13:24 UTC
Labels: Bug 🐞
