### ISSUE TITLE
Dark Mode - Check box to select logins is not visible

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5738] opened 2019-11-08 10:15 UTC
**Steps**
Have some logins stored and select Dark Mode
Go to Settings -> Passwords and Logins -> Edit

**Expected** 
The view is correct

**Actual**
The checkbox to select each login is not visible when login is not selected.
Please see screenshot.
![Untitled2](https://user-images.githubusercontent.com/1897507/68468789-01736880-0219-11ea-8c08-fbcb8659a1eb.png)

Note: This is failing only on iOS13

**Comment by isabelrios** [comment] 2019-11-08 10:20
Note also how the magnifier, next to Filter text, is shown, very difficult to see it too.

**Comment by nick130586** [comment] 2019-11-11 01:00
On 13.2 simulator, the issue is reproduced. However, on a real device running iOS 13.2.2, the issue isn't reproduced.

![IMG_0146](https://user-images.githubusercontent.com/168651/68554166-525caa00-042f-11ea-97f2-e0e5f4ed9adb.png)

![IMG_0146](https://user-images.githubusercontent.com/168651/68554170-5f799900-042f-11ea-9177-00e26abd6bfd.png)

**Comment by dnarcese** [comment] 2019-11-14 19:31
The circle selection icon is a system icon that changes with the system theme rather than with our app theme. Because of this, it makes it more difficult to control the appearance. I investigated if it would be possible but it turned out that it is much more difficult and time-consuming than initially thought. Since this screen is not one of the main screens that users see, I don't think it is worth the effort to fix. Additionally, this doesn't affect functionality, users can still select a login by clicking on the row and the checkmark will still show.

@athomasmoz what do you think about closing this as won't fix?

**Comment by athomasmoz** [comment] 2019-11-14 20:16
Yes, that sounds like a good idea. Since our default is to match the system theme, sounds like the likelihood that users will run into this is very low. Closing as won't fix

**Closed by athomasmoz** 2019-11-14 20:16 UTC
Labels: 1, Bug 🐞, iOS13
