### ISSUE TITLE
FXIOS-372 ⁃ partnersonlinebanking.partnersfcu.org - Web page fails to load and contains errors

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#6471] opened 2020-04-27 23:39 UTC
## Steps to reproduce

**URL**: https://partnersonlinebanking.partnersfcu.org/OnlineBanking/AOP/Password.aspx

1) Go to Partners FCU website: https://www.partnersfcu.org/
2) Type anything in the Username field (ex: "test")
3) Click the "LOGIN" button
4) Page fails to load with the following error:
"error on line 79 at column 271: xmlParseEntityRef: no name"
<details><summary>View the screenshot</summary><img alt='Screenshot' src='https://webcompat.com/uploads/2020/3/de613821-9f9d-4d92-8cfe-4e502c64f795.jpeg'></details>

### Expected behavior
form for password
### Actual behavior
Web page fails to load and contains errors

### Device & build information
* Device: iphone xs iOS 13.4
* Build version: Firefox iOS 23.0
### Notes
initially reported and tested on https://github.com/webcompat/web-bugs/issues/50808

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2367)

**Comment by lmarceau** [comment] 2022-06-13 16:37
Closing this as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/6327

**Closed by lmarceau** 2022-06-13 16:37 UTC
Labels: Bug 🐞
