### ISSUE TITLE
[Toolbar redesign] - Last visited URL is displayed in the address bar when returning on homepage and when switching tabs

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21516] opened 2024-08-13 06:36 UTC
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

**Scenario 1**

1. Install FF and open a website.
1. Tap on "+" button from toolbar.
1. Observe the URL bar.

**Scenario 2**

1. Repeat steps 1-3, but this time, open several websites in different tabs and switch from a tab to another.

**Expected behavior**
Scenario 1:
Once returned to homepage, the address bar is cleared. 
Scenario 2:
When switching to another tab, the URL is correctly displayed/updated.

**Actual behavior**
Scenario 1:
The URL from the last visited website is displayed on homepage. Also, the site is displayed as unsecure.
The share and refresh buttons are non functional.
Scenario 2:
When switching from a tab to another, the last visited URL is displayed.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v9000 (44362)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/ed555e2e-7db3-4c1a-8015-0dcd8275ce44

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9797)

**Comment by data-sync-user** [comment] 2024-08-13 09:37
➤ Winnie Teichmann commented:

This sounds like a duplicate of this task. ( https://mozilla-hub.atlassian.net/browse/FXIOS-9764 ) There is already a PR for this one that should fix the issue.

**Comment by data-sync-user** [comment] 2024-08-22 12:24
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(44528), with iPhone 15 (17.5).

**Closed** 2024-11-04 13:41 UTC
Labels: Bug 🐞, S3, Toolbar redesign📲
