### ISSUE TITLE
Toolbar Actions Menu won't scroll in Landscape on iPhone when Toolbar is at the top

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10196] opened 2022-03-10 11:50 UTC
## Steps to reproduce

- Open Settings and set the Toolbar to be at the Top.
- Close the settings
- Rotate the phone to landscape
- Click the Actions menu button
- Try to scroll the action menu to get to the items at the bottom

### Expected behavior
The menu scrolls and you can access the items at the bottom
### Actual behavior
The menu will not scroll. See screen recording
### Device & build information
* Device: iPhone 13
* Build version: 98.1
### Notes
This isn't a problem when the Toolbar is at the bottom, you can scroll up to the top in that case.
Attachments: 

https://user-images.githubusercontent.com/2040690/157656099-c4c718cc-455d-425c-b4be-40f4d27d3922.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3890)

**Comment by lmarceau** [comment] 2022-03-10 16:20
@gutley your video isn't showing for me, seems there was an issue. 

Also I can't reproduce. Video of what I get in landscape with top toolbar, just so you can confirm if this is what you described.

https://user-images.githubusercontent.com/11338480/157705933-6b4980d9-37dc-4030-8132-90e9aa7b47d6.MP4

**Comment by gutley** [comment] 2022-03-10 16:45
@lmarceau Try it on the iPhone 13 simulator - It may be related to the safe area handling (and unlike my issue with the gaps on the setting menu this also happens when built with Xcode 3.2.1.

I'll try and get a video that works for you...

**Comment by gutley** [comment] 2022-03-10 16:48
@lmarceau Here's the video again. Note this also happens with Released Firefox v98 on my iPhone 12 Pro Max

https://user-images.githubusercontent.com/2040690/157713100-98a54357-c3ad-4f32-9e2d-fef0d0468ebd.mp4

.

**Comment by lmarceau** [comment] 2022-03-10 21:39
@dnarcese I can reproduce on iPhone 13.0. This seems like a huge blocker for v98.0 and was missed, I think we should look into this asap. Thanks a lot @gutley !

**Comment by lmarceau** [comment] 2022-03-11 17:27
@gutley Hello! A fix was just merged on v98.1 branch. It's all good for me on simulator, but I didn't have a real device to reproduce. Would you mind having a look this is working on your side too? 🙏

**Comment by gutley** [comment] 2022-03-14 09:48
@lmarceau Yes - All good on my real iPhone

**Comment by gutley** [comment] 2022-03-14 09:54
BTW - One thing that menu doesn't do while scrolling is the normal 'over bounce' effect that other scrollable areas have when hitting the top or bottom. Certainly not a showstopper, but it makes it feel a bit 'wrong'. Not worth delaying anything for unless its a simple fix.

**Comment by lmarceau** [comment] 2022-03-14 14:10
@gutley Scrolling in this menu isn't new (ex: with dynamic type is had to scroll), hence that would be a change todo and investigate. Would you mind opening a feature request ticket so this can be discussed in triage? Thanks!

**Comment by csuciu** [comment] 2022-03-15 09:04
Tested on multiple screen sizes on v98.1 and couldn't reproduce the initial issue.

**Closed by csuciu** 2022-03-15 09:04 UTC
Labels: Bug 🐞
