### ISSUE TITLE
Crashes in 105.0 (16923)

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#11776] opened 2022-09-01 11:51 UTC
## Steps to reproduce

I don't really have any good steps to reproduce the crashes.
The best I can say is that it seems to happen often when putting the app into background after normal usage.
Sometimes it seems that certain interactions in the browser don't work (e.g. pressing the menu button doesn't show the menu), and then when putting the app to background it crashes.

This seems to have started with build 16923.

### Expected behavior

No crashes.

### Actual behavior

Crashes.

### Device & build information
* Device: iPhone 11, iOS 15.6.1
* Build version: 105.0 (16923) (beta from TestFlight)

### Notes
Attachments: crash logs from my iphone from 3 different crashes (yesterday and today)

[Client-2022-08-31-213546.ips.txt](https://github.com/mozilla-mobile/firefox-ios/files/9469441/Client-2022-08-31-213546.ips.txt)

```
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
```

[Client-2022-09-01-092915.ips.txt](https://github.com/mozilla-mobile/firefox-ios/files/9469442/Client-2022-09-01-092915.ips.txt)

```
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},
  "termination" : {"code":2343432205,"flags":6,"namespace":"FRONTBOARD","reasons":["<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<org.mozilla.ios.FirefoxBeta>:88219 exhausted real (wall clock) time allowance of 10.00 seconds","ProcessVisibility: Background","ProcessState: Running","WatchdogEvent: scene-update","WatchdogVisibility: Background","WatchdogCPUStatistics: (","\"Elapsed total CPU time (seconds): 21.860 (user 21.860, system 0.000), 36% CPU\",","\"Elapsed application CPU time (seconds): 10.217, 17% CPU\"",") reportType:CrashLog maxTerminationResistance:Interactive>"]},
  "ktriageinfo" : "VM - Compressor failed a blocking pager_get\n",
```

[Client-2022-09-01-123254.ips.txt](https://github.com/mozilla-mobile/firefox-ios/files/9469444/Client-2022-09-01-123254.ips.txt)

```
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},
  "termination" : {"code":2343432205,"flags":6,"namespace":"FRONTBOARD","reasons":["<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<org.mozilla.ios.FirefoxBeta>:91364 exhausted real (wall clock) time allowance of 10.00 seconds","ProcessVisibility: Background","ProcessState: Running","WatchdogEvent: scene-update","WatchdogVisibility: Background","WatchdogCPUStatistics: (","\"Elapsed total CPU time (seconds): 18.240 (user 18.240, system 0.000), 29% CPU\",","\"Elapsed application CPU time (seconds): 10.900, 17% CPU\"",") reportType:CrashLog maxTerminationResistance:Interactive>"]},
```

I have similar crashes from the past days as well, always one of these 2 exceptions.
~~A friend of mine actually saw similar crashes on v104.0 (release) just today, though in slightly different context (opening and trying to share a PDF in a private tab)~~ (that's another unrelated bug: #11777)

Homepage settings:

<details>

![IMG_3254](https://user-images.githubusercontent.com/2129/187906776-10978565-03a3-482c-ac12-042c0e04e0e7.PNG)

</details>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4855)

**Comment by badboy** [comment] 2022-09-16 10:33
After deinstalling Firefox iOS completely yesterday, then reinstalling v103 and later upgrading to v105.0, build 17614 I'm not experiencing any crashes anymore so far.

**Comment by data-sync-user** [comment] 2022-10-13 13:23
➤ Catalin Suciu commented:

We were not able to reproduce this issue while testing the latest v106.0 builds. We’ll leave the issue open for now maybe we can reproduce while testing the next builds.

**Comment by data-sync-user** [comment] 2022-10-19 13:43
➤ Orla Mitchell commented:

This is still occurring in v106. I have reopened the bugzilla ticket the glean team are using to track this. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1791789 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1791789|smart-link )

**Comment by data-sync-user** [comment] 2022-10-27 16:30
➤ Catalin Suciu commented:

No crashes encountered while testing v106.1. We’ll leave the issue open until after the build is released.

**Comment by data-sync-user** [comment] 2022-11-03 19:21
➤ Laurie Marceau commented:

Stack traces that could relate to this bug

thumbnail ( https://user-images.githubusercontent.com/11338480/199814620-cc4f0713-484d-4f2a-bad0-66eb0d88a2a9.png )

thumbnail ( https://user-images.githubusercontent.com/11338480/199814623-ce02016d-3e94-4a3e-b1ee-c4b883412fa9.png )

thumbnail ( https://user-images.githubusercontent.com/11338480/199814626-f06b00e4-e571-42a8-b243-c48ae3777431.png )

thumbnail ( https://user-images.githubusercontent.com/11338480/199814627-4e29a800-0bfd-4cd1-9112-6ff22abc3023.png )

**Comment by data-sync-user** [comment] 2022-11-18 16:15
➤ Andrei Bodea commented:

No crashes were encountered while testing v107.1. We’ll leave the issue open until after the build is released.

**Comment by data-sync-user** [comment] 2022-12-12 18:53
➤ Laurie Marceau commented:

I’ll close this issue for now, please let me know if it should be reopened (better to have a new ticket if this still occurs).

**Closed by data-sync-user** 2022-12-12 18:53 UTC
Labels: Bug 🐞
