### ISSUE TITLE
FXIOS-1509 ⁃ Reading list icon is misplaced after rotating screen

### ISSUE THREAD

**Issue by eeeple** [mozilla-mobile/firefox-ios#8020] opened 2021-02-22 21:31 UTC
## Steps to reproduce
1- Disable portrait orientation lock
2- Rotate from portrait to landscape and back

### Expected behavior
Reading list icon should remain at the same place in the address bar

### Actual behavior
Icon is offset to the left on portrait mode

### Device & build information
* Device: iPhone 11
* Build version: Firefox Daylight 31.0 (3537)
### Notes
Attachments: 
![899F53B9-EF84-4DDB-840D-35F6537E9C8A](https://user-images.githubusercontent.com/2037523/108772754-b55b4d00-755d-11eb-8b84-fc049e45ccce.jpeg)
![B3BF60F7-1A7F-4C8A-89C1-775FF361DD79](https://user-images.githubusercontent.com/2037523/108772763-b7251080-755d-11eb-9ba2-47269f746f07.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1509)

**Comment by SimonBasca** [comment] 2021-02-23 10:26
Duplicate of #7566

**Closed by SimonBasca** 2021-02-23 10:26 UTC
Labels: Bug 🐞
