### ISSUE TITLE
iOS blocking after hiding/pausing

### ISSUE THREAD

**Issue by thotha** [mozilla-mobile/firefox-ios#16116] opened 2023-08-18 10:30 UTC
## Steps to reproduce
Put iOS app to sleep by put iOS to sleep mode by hitting once the power button. Wake up to Firefox and Firefox doesn't accept any user interaction. 

### Expected behavior
Accept user interaction like scroll, touch, ...

### Actual behavior
Does not recognize any user interaction. Only way is to kill Firefox and reload/restart

### Device & build information
* Device: ? 
iPhone SE 2022
iOS 16.6 (20G75)
* Build version: ? 
Firefox 116.2 (33536)
* First seen version: ? 
In earlier 115/116 version. Most iftne with 116.0-116.2

### Notes
Attachments: 

There is no way to screen record user interactions like touch/scroll as it won't be recorded.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7266)

**Comment by OrlaM** [comment] 2023-08-18 14:48
Thanks for logging, if you could upload your logs it would help us out a lot with debugging. You can find out how to get them here https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-Firefox-logs
A note on what time you experienced the issue would also be very helpful.

**Comment by LeoniePhiline** [comment] 2023-08-21 16:41
Is have the same issue. 
I regularly force closed and reopened Firefox iOS recently.

However, I found the following workaround:

For me, rotating the phone to landscape mode makes Firefox unfreeze.

**Comment by LeoniePhiline** [comment] 2023-08-23 10:04
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/16018 ?

**Comment by lmarceau** [comment] 2023-08-24 02:55
@LeoniePhiline out of curiosity, have you tried the new v116.3 build? It hopefully help with this issue.

**Comment by thotha** [comment] 2023-08-24 03:55
Hello LenoieThank you for your suggestion about the new version, but I have switched to Brave on iOS as well as on macOS. I can say it‘s much faster in startup even with lots of open tabs as well as with opening new web sites. Feels line a turbo. SorryKind regardsThomas ThalerAm 24.08.2023 um 04:56 schrieb lmarceau ***@***.***>:﻿
@LeoniePhiline out of curiosity, have you tried the new v116.3 build? It hopefully help with this issue.

**Comment by LeoniePhiline** [comment] 2023-08-24 12:08
> @LeoniePhiline out of curiosity, have you tried the new v116.3 build? It hopefully help with this issue. 

I updated, but since I have no defined reproduction steps, I can only wait and see if it happens again.

**Closed** 2023-12-14 19:50 UTC
