### ISSUE TITLE
A synced CC from the desktop is not displaying the correct card icon

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14748] opened 2023-06-06 13:50 UTC
## Preconditions
Save a few credit cards on the desktop Firefox.

## Steps to reproduce
1. Launch FF and perform a sync.
1. Access the Autofill CC section.
1. Check the synced cards.

### Expected behavior
The icon for the cards should be correctly displayed.

### Actual behavior
A synced CC from the desktop is not displaying the correct card icon.

### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31461). 
* First seen version: N/A 
    1. Notes
Please note that if I save the same CC on iOS straight the icon is correctly displayed, so the problem is only if it was saved on the desktop first and after sync.
Attachments: 

![image0](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/156b97ec-4cc3-4fb6-8c34-8f73345f18b2)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6589)

**Comment by data-sync-user** [comment] 2023-06-29 13:44
➤ Stefan Vladut commented:

duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-6560 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6560|smart-link )

**Closed** 2023-07-07 15:15 UTC
Labels: Bug 🐞, S2, credit-card-autofill
