### ISSUE TITLE
FXIOS-275 ⁃ New Tab "Custom URL" placeholder text is barely visible

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6153] opened 2020-02-24 12:06 UTC
Build: 23.0(17297)
Device: iPhone X
iOS: 13.3

Preconditions:
- Set theme to Manual Light.
- Set iOS theme to Dark.

Steps to reproduce:
1. Go to Settings -> New Tab
2. Check the "Custom URL" placeholder text

Actual results:
- The placeholder text is barley visible

Expected results:
- The placeholder text should be visible

![Screen Shot 2020-02-24 at 2 00 19 PM](https://user-images.githubusercontent.com/32130829/75150964-419a2080-570e-11ea-9cba-9e45a4e0ccfb.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-275)

**Comment by LamourBt** [comment] 2020-03-02 20:26
I will try tackling this issue

**Comment by tomislaveric** [comment] 2020-05-26 10:05
Hi, i my last PR https://github.com/mozilla-mobile/firefox-ios/pull/6678 i fixed all of those issues. The PR was merged and should now be ok in develop. Could you please take a look? If all is ok, this issue can be deleted

**Comment by electricRGB** [comment] 2021-02-18 20:11
Closing as a dupe of #6512

**Closed** 2021-02-18 20:11 UTC
Labels: Bug 🐞, Contributor OK
