### ISSUE TITLE
[Crash] FF crashes when closing the tabs in PB/switching to normal browsing on iPad `NSInternalInconsistencyException TabDisplayManager.performChain`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13711] opened 2023-03-23 15:29 UTC
## Sentry logs
https://mozilla.sentry.io/releases/org.mozilla.ios.Firefox%40111.1%2B(29556)/?project=6176941
https://mozilla.sentry.io/issues/4025804608/?project=6176941&referrer=release-issue-stream
## Steps to reproduce
1. Launch FF.
2. Open a few tabs in Normal Browsing or let it only with the homepage only.
3. Switch to PB and open a few tabs.
4. Tap on the tabs tray and close all the tabs.
5. Right after that fast tap on the `Done` button.
### Expected behavior
Firefox should switch to normal browsing without crashing.
### Actual behavior
FF crashes when closing the tabs in PB/switching to normal browsing on iPad `NSInternalInconsistencyException TabDisplayManager.performChain`
### Device & build information
* Device: **iPad mini 5 (14.7).**
* Build version: **v9000 (29660).**
* First seen version: **111.1+(29556).**

### Notes
It has a weird behavior sometimes it crashed when I manually closed all the private browsing tabs.

Attachments: 

https://user-images.githubusercontent.com/42831109/227252094-a050b5c1-a429-4089-8603-7277441400e3.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6054)

**Comment by abodea** [comment] 2023-03-23 15:31
Might be related to https://github.com/mozilla-mobile/firefox-ios/issues/10302. But this one looks new in Sentry (like 2 days old)

**Comment by lmarceau** [comment] 2023-03-23 18:44
I think this could relate to https://github.com/mozilla-mobile/firefox-ios/issues/12871 possible due to performChainedOperations crash

**Comment by data-sync-user** [comment] 2023-05-10 11:06
➤ Andrei Bodea commented:

Verified as fixed on v114 (30639) with iPad mini 5 (14.7) and iPad Pro (16.4.1).

I was not able to reproduce the crash anymore.

**Closed by data-sync-user** 2023-05-10 11:06 UTC
Labels: Bug 🐞, Crash, iPad, S1
