### ISSUE TITLE
[Tab tray refactor] Weird behavior when rearranging tabs

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18739] opened 2024-02-16 09:53 UTC
**Prerequisites**
Go to FF secret settings ---> Experiments ---> enable “Rollout of tab tray refactor - iOS" feature.

**Steps to reproduce**

1. Open three tabs in tabs tray, e.g. Amazon.com, olx.ro and ebay.com.
1. Move ebay.com to the second position, where olx.ro is and observe.

**Expected behavior**
Ebay.com correctly switched positions with olx.ro, the thumbnails are displayed accordingly, only one tab is focused.

**Actual behavior**
The ebay.com tab transforms into olx.ro and both tabs are focused.
The thumbnails return to normal when tapping on one of them.

**Device & build information**

* Device: iPhone SE (16.3)
* Build version: V123 (38801)
* First seen version: 

**Notes**
! Please note that this issue doesn't reproduce immediately after fresh install. You need to play with tabs tray a bit, first (open tabs, close, switch positions etc.)
The same weird behavior happens in private browsing.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/947b14fc-1ecc-47ac-884a-a89f2531782e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8449)

**Comment by data-sync-user** [comment] 2024-02-26 22:30
➤ Sophie Amin commented:

As part of https://mozilla-hub.atlassian.net/browse/FXIOS-8418 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8418|smart-link )  after I implemented swiping left to delete you can still see there’s some timing issues when initiating gestures. Attached in a video below you can see that when you have multiple tabs open it’s possible to swipe left quickly to delete a bunch of them and the last tab gets “stuck” in it’s animation and does not close the tab completely (hard to see but when the last tab closes in the video you can see the black corner of the last tab stuck on the side). If swipes are performed slowly it’s harder to get into this state, and if they’re done quicker it’s easier.

[^RPReplay_Final1708733944.MP4]

**Comment by data-sync-user** [comment] 2024-03-07 16:54
➤ Norberto Andres Furlan commented:

Sophie Amin to check this one. It is not easy to reproduce but they seem related to this ticket, except that is happening in private mode.

We see an issue of the current tab not being selected (purple border). Since there is no current tab selected that’s in private mode after doing the Undo action, that could be the reason we also don’t see the private mode theme (so, it might be the cause of this bug -> https://mozilla-hub.atlassian.net/browse/FXIOS-8571 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8571|smart-link ) )

CC: Diana Andreea Barladeanu Alina Moldovan Diana Andreea Barladeanu Cyndi Chin 

!Simulator Screen Recording - iPhone 15 - 2024-03-06 at 17.00.19.mp4|width=1178,height=2556!

!Simulator Screenshot - iPhone 15 - 2024-03-06 at 17.02.33.png|width=1179,height=2556!

**Comment by data-sync-user** [comment] 2024-04-05 07:50
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40470), with iPhone 15 (17.0).

**Closed by data-sync-user** 2024-04-05 07:50 UTC
Labels: Bug 🐞
