### ISSUE TITLE
FXIOS-1495 ⁃ Sharing the file from downloads

### ISSUE THREAD

**Issue by capiet** [mozilla-mobile/firefox-ios#7986] opened 2021-02-14 17:20 UTC
## Steps to reproduce
1. Download any file
2. Go to Downloads
3. Share this file to Telegram
4. Check the result in Telegram
### Expected behavior
The file has been uploaded to Telegram
### Actual behavior
Only the path to the file has been uploaded to Telegram
### Device & build information
* Device: iPhone XR, iOS 14.4
* Build version: 31
### Notes
Attachments: 
<details> <summary>Images: </summary>
<a href="https://user-images.githubusercontent.com/79054211/107883404-dab5de80-6eff-11eb-92b5-477600bfd6ca.PNG"> Image 1</a>
<a href="https://user-images.githubusercontent.com/79054211/107883398-d5f12a80-6eff-11eb-89d1-f10228018a9e.PNG"> Image 2 </a>
<a href="https://user-images.githubusercontent.com/79054211/107883407-dee1fc00-6eff-11eb-9676-2ed1fbbc6b67.PNG"> Image 3 </a>
</details>

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1495)

**Comment by dnarcese** [comment] 2021-02-18 17:08
Dupe of #7933

**Closed by dnarcese** 2021-02-18 17:08 UTC
Labels: Bug 🐞
