### ISSUE TITLE
Unable to close tab by clicking X on iOS

### ISSUE THREAD

**Issue by dethier1958** [mozilla-mobile/firefox-ios#8949] opened 2021-08-03 17:14 UTC
Using Firefox on iPhone or iPad. Tapping the close button on the tab (the X on the right end of the tab) does not close the tab. This started with the recent update to the new style of tabs on iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3029)

**Comment by dnarcese** [comment] 2021-08-03 21:24
Duplicate of #8613

**Closed by dnarcese** 2021-08-03 21:24 UTC
Labels: Bug 🐞
