### ISSUE TITLE
FXIOS-1026 ⁃ Infinite loop when opening an address link from another app

### ISSUE THREAD

**Issue by moon8orange** [mozilla-mobile/firefox-ios#7466] opened 2020-10-07 10:39 UTC
## Steps to reproduce
1. Set iOS Firefox as the default web browser
1. Remove the iOS Apple Maps app
1. Paste an address into the iOS Apple Notes app.
1. Accidentally tap the address to automatically open it in the default web browser
1. Watch as Firefox opens infinite tabs.

### Expected behavior
Would be cool if Firefox automatically deleted the proprietary notes app, thus fixing multiple problems.
Otherwise Firefox should display a message asking if you want to "restore the Maps App from the App store"
### Actual behavior
Infinite tabs
### Device & build information
* Device: ios 14.01 iPhone SE (2)
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1026)

**Comment by jakewilkins** [comment] 2020-10-08 01:56
I came to report this issue as well, but it seems to happen with any address recognized by iOS.

I noticed it tapping an address from an email I received via Apple Mail.

**Comment by dnarcese** [comment] 2021-03-04 19:45
Investigate: Is there a way to close the app when this is happening? Does this happen if a different maps app is installed (like Google Maps)?

**Comment by SimonBasca** [comment] 2021-03-05 11:31
This issue is reproducible on v32.0 (3841). After step 5), Fireofx can be closed via app switcher and after re-opening the app the tabs stop loading. This is also reproducible if other map apps like Google maps are installed. 

Note:
- Not reproducible in Safari, Edge, Chrome, Focus when any of these browsers are set as default browser. See screenshot.
![Picture_2021_03_05T11_30_39_903Z](https://user-images.githubusercontent.com/32130829/110110177-1fbe8980-7db7-11eb-9624-f2976001c9a0.jpeg)

**Comment by data-sync-user** [comment] 2021-05-13 16:55
➤ Ashley Thomas commented:

[~bpitoyo@mozilla.com] Can you help us determine strings for the message that pops up?

**Comment by SimonBasca** [comment] 2021-05-17 09:56
More reports of this issue at https://bugzilla.mozilla.org/show_bug.cgi?id=1684308

**Closed** 2021-05-20 19:35 UTC
Labels: Bug 🐞, Needs-UX, P1

**Comment by data-sync-user** [comment] 2021-05-28 12:09
➤ Simion Basca commented:

We are unable to test this on the latest main branch due to https://github.com/mozilla-mobile/firefox-ios/issues/8595. ( https://github.com/mozilla-mobile/firefox-ios/issues/8595. )

We will verify this issue on the beta channel when it is uplifted.

**Comment by SimonBasca** [comment] 2021-06-14 10:15
Verified fix on v34.1 (5167).
