### ISSUE TITLE
[regression] Scroll position is reset to the top of previous page when navigating back

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16643] opened 2023-09-28 16:59 UTC
## Steps to reproduce
1. Open a long page, such as a Wikipedia article.
1. Scroll half way down the page.
1. Tap a link to open a new page.
1. Navigate back using the back button or the left-swipe gesture.

### Expected behavior
The scroll position on the first page should be restored half way down the page where the tapped link was.

### Actual behavior
The scroll position is reset to the top of the first page.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.0.2
* Build version: TestFlight 9000 (34498)
* First seen version: This bug is a regression in 9000 (34498). Back navigation works as expected in the previous build, 9000 (34412).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7497)

**Comment by abodea** [comment] 2023-09-29 13:52
Thank you for adding this issue, @cpeterso I was also able to reproduce it on the latest Nightly (9000 (34679)) with iPhone 13 Pro (15.7.1).

**Comment by darren12345** [comment] 2023-11-24 08:32
Disappointing that this hasn’t been fixed in the latest release. Every other browser seems to many this OK, so why is it a problem on FF (and a relatively new one, at that)?

**Comment by lmarceau** [comment] 2024-01-04 20:02
We are investigating the problem

**Comment by data-sync-user** [comment] 2024-01-04 21:31
➤ Laurie Marceau commented:

The issue was introduced end of September (Regression in build 34498 September 23, 2023 and was fine in build 34412 September 21, 2023 as the description mentions). One related commit was made in that area in this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/16538/files ), although at this point reverting this change has no effect. This possibly point to having a timing/async related problem? I can’t confirm this at this point. Other previous changes in that area included the following PRs 17429 ( https://github.com/mozilla-mobile/firefox-ios/pull/17429/files ), 14736 ( https://github.com/mozilla-mobile/firefox-ios/pull/14736/files ), 13824 ( https://github.com/mozilla-mobile/firefox-ios/pull/13824/files?diff=split&w=0 ).

Current investigation is pointing to an issue in the tab scroll controller, and strangely if commenting out the following section of code in the tab scroll controller then the issue isn’t happening anymore. See branch here ( https://github.com/lmarceau/firefox-ios/tree/lm/FXIOS-7497-%2316643-scroll-position ) for more details. 

!Screenshot 2024-01-04 at 4.27.34 PM.png|width=1052,height=338!

!Screenshot 2024-01-04 at 4.27.55 PM.png|width=770,height=116!

I say strangely, since 1- those lines of code are effectively not called when we press the back button, and 2- one of those lines relates to content offset which make sense it would have an effect, the other line relates to top constraint which makes less sense to me as to why it would have an effect on the scroll position. If I put back one or the other of those two section of code, then the issue happens again. Maybe the previous content offset/constraint on pages have side effects on the scroll position (i.e. when I press the back button, the current page constraint and offset overrides the previous page offset?)

**Comment by darren12345** [comment] 2024-01-04 21:38
This issue has been fixed as of the last update. At least for me!

**Comment by lmarceau** [comment] 2024-01-04 21:53
Tested and it's not fixed for me at least 😬

**Comment by captn3m0** [comment] 2024-01-05 05:45
Resolved for me on 121.1. I was also facing some other bug with the back button, where the page wouldn't render at all - that seems to be resolved as well.

**Comment by mlissner** [comment] 2024-01-09 14:34
I have a variation of this issue on 121.1. When I load a page, click a link, scroll down the page, and go back, the original page has scrolled instead of being where I left it. 

It's as if when I scroll the second page, the first one scrolls too, even though it's only in my history.

**Comment by data-sync-user** [comment] 2024-01-10 11:04
➤ Alina Moldovan commented:

Orla Mitchell Able to reproduce this issue intermittently: 

iPhones (14+ (16.0.3), 15+(17.0.2), SE (16.6)) steps:  

  1. Open wiki page and search for Italy
  2. Scroll down to ‘Kingdom of Italy’ link and tap on it 
  3. Scroll down to ‘League of Nations’ link and tap on it
  4. Scroll down to external links and expend the section 
  5. Tap on “history of league of nation” link 
  6. Scroll down to the end of the page 
  7. Tap Back arrow and check the views → The scroll position is not restored for the “Kingdom of Italy“ and “Italy“ pages 

please note that 

  * the using the above steps the issue is not reproducing if user swipes-left or the step 6 is skipped. 
  * Able to reproduce intermittently using the iPad Pro 4th gen (16.6) by navigation thought the wiki pages (not needed to go to the external links) 

!Skype_Video37.mp4|width=886,height=1920!

!Skype_Video38.mp4|width=1342,height=1920!

**Comment by data-sync-user** [comment] 2024-01-10 11:04
➤ Alina Moldovan commented:

Orla Mitchell Able to reproduce this issue intermittently: 

iPhones (14+ (16.0.3), 15+(17.0.2), SE (16.6)) steps:  

  1. Open wiki page and search for Italy
  2. Scroll down to ‘Kingdom of Italy’ link and tap on it 
  3. Scroll down to ‘League of Nations’ link and tap on it
  4. Scroll down to external links and expend the section 
  5. Tap on “history of league of nation” link 
  6. Scroll down to the end of the page 
  7. Tap Back arrow and check the views → The scroll position is not restored for the “Kingdom of Italy“ and “Italy“ pages 

please note that 

  * the using the above steps the issue is not reproducing if user swipes-left or the step 6 is skipped. 
  * Able to reproduce intermittently using the iPad Pro 4th gen (16.6) by navigation thought the wiki pages (not needed to go to the external links) 

!Skype_Video37 (a3e841c5-f0ed-436d-a4ef-f6da68cb9cfe).mp4|width=886,height=1920!

!Skype_Video38 (115dc5a6-0925-436b-ae3b-6c70f2d3fe95).mp4|width=1342,height=1920!

**Closed** 2024-01-10 14:38 UTC
Labels: Bug 🐞, S3
