### ISSUE TITLE
The "Autofill Credit Cards" option opens the "Passwords" screen if the device doesn't have a Face ID or Passcode

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/firefox-ios#15782] opened 2023-07-27 13:45 UTC
**[Notes]**

* This behavior can be confusing for the users since they tap on the "Autofill Credit Cards" option and the "Passwords" screen is opened. Also, on the "Password" screen there is no mention of the "Autofill Credit Cards" feature and the fact that you need to enable a Face ID or Passcode to use it. 

**[Affected versions]:**

* Firefox Beta 9000 (33001) 
* Firefox Release 116.0 (32958)

**[Affected Platforms]:**

* iOS 16.5 - iPhone 13 mini

**[Prerequisites]:**

* Have an iPhone device with NO Face ID and Passcode set.
* Have the latest Firefox Beta 9000 (33001) installed.

**[Steps to reproduce]:**

1. Open Firefox Beta 9000 (33001).
1. Open the Settings menu.
1. Scroll down to the "Privacy" section.
1. Tap on the "Autofill Credit Cards" option.
1. Observe the behavior. 

**[Expected results]:**

* The "Autofill Credit Cards" screen is open and a message is displayed to inform the user to enable the Face ID or passcode in order to use this feature.
OR
* The "Passwords" screen is open and the message also mentions that in order to use the "Autofill Credit Cards" feature a  Face ID or passcode needs to be set.

**[Actual results]:**

* The "Passwords" screen is opened and there is no mention of the "Autofill Credit Cards". 

**[Additional Notes]**:

* Attached is a screen recording of the issue:

https://github.com/mozilla-mobile/firefox-ios/assets/19226534/999842a7-1a4d-4711-ab4a-38fedfee0c59

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7103)

**Comment by dnarcese** [comment] 2023-07-27 18:41
This will not block the experiment, but we will look into improving the copy here.

**Comment by data-sync-user** [comment] 2023-07-27 19:13
➤ Daniela Arcese commented:

Emily Wachowiak Can we get suggestions on how to improve this copy so it is relevant for both screens. Or, whether we need 2 different strings for each use case.

**Comment by data-sync-user** [comment] 2023-07-27 19:23
➤ Emily Wachowiak commented:

Daniela Arcese I had to come up with a generic string for a similar use case with Nishant Bhasin recently. I believe that the string will need to work for both use cases and it has to be specific (e.g. saying passwords and cards) vs. general (e.g. saying “private information”).

So based on that, for this use case I suggest: To save and autofill logins and encrypted cards, enable Face ID, Touch ID, or a device passcode.

**Comment by data-sync-user** [comment] 2023-07-28 16:09
➤ Emily Wachowiak commented:

Laurie Marceau That’s great! Thanks for the info. Then I recommend that we update the string to: To save and autofill credit cards cards, enable Face ID, Touch ID, or a device passcode.

We likely don’t have design resources to re-style this screen right now so it’s ok to use the existing style.

**Comment by data-sync-user** [comment] 2023-10-03 14:51
➤ Nishant Bhasin commented:

Andrei Bodea To investigate this bug

**Comment by data-sync-user** [comment] 2023-10-17 14:37
➤ Andrei Bodea commented:

Hello, I was not able to reproduce this issue, I’m not sure if we need an experiment, on v119 (35222) with iPhone 13 Pro (15.7.1).

**Comment by abodea** [comment] 2023-12-14 16:35
I can reproduce this on v121 (36782)

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/07392cfe-0f57-4f1c-9667-0e2f02b8388c

**Comment by data-sync-user** [comment] 2024-03-18 10:04
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39865), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment] 2024-03-20 09:20
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone SE (16.6).

**Closed** 2024-03-20 09:20 UTC
Labels: Bug 🐞, S2
