### ISSUE TITLE
Clearing Browsing History through Data Management does not appear to work

### ISSUE THREAD

**Issue by leamingrad** [mozilla-mobile/firefox-ios#16234] opened 2023-09-04 11:23 UTC
## Steps to reproduce

1. Go to Settings > Data Management
2. Click the toggle to include Browsing History
3. Click "Clear Private Data"

Context: I'm currently trying to reduce the size of "Documents & Data" as reported by iOS (since Firefox has the largest size and I am running out of storage).

### Expected behavior

Browsing history is deleted (and thus space is freed up).

### Actual behavior

Browsing history still appears in the menu.

### Device & build information
* Device: iPhone SE (first generation), iOS 15.7.8
* Build version: 116.4 (33723)
* First seen version: Unknown (this has always been the case for me)

### Notes

To attempt to reduce storage, I have disabled History sync to my Firefox account. I would expect this to mean that I can delete the local history, but that it does not affect my other synced devices.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7310)

**Comment by OrlaM** [comment] 2023-11-02 19:05
Duplicate of #16956

**Closed by OrlaM** 2023-11-02 19:05 UTC
Labels: Bug 🐞
