### ISSUE TITLE
[regression] google.com search field closes the keyboard before you can finish typing

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16035] opened 2023-08-12 21:34 UTC
## Steps to reproduce

1. Using build 9000 (33293), open https://www.google.com/
2. Tap input focus to the page's search field.

Alternative steps to reproduce:

1. Using build 9000 (33293), open https://www.google.com/ or https://support.mozilla.org/
2. Tap input focus to the page's search field.
3. Enter *one* character and wait.

### Expected behavior

The keyboard should stay open so you can enter the rest of your search query.

### Actual behavior

The keyboard closes before you can enter the rest of your search query.

This bug is a regression in build 9000 (33293). The bug is not reproducible in build 9000 (32972), Safari 16.6, or Chrome iOS 115.0.5790.160.

### Device & build information

* Device: iPhone 12 running iOS 16.6
* Build version: 9000 (33293)
* First seen version: 9000 (33293)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7230)

**Comment by RaiseDennis** [comment] 2023-08-12 21:49
Yes thanks! For sending this link to my mail! This is a great community and together we can make Firefox for ios better. I just want to question why GitHub only allows for 10 mb upload cause I reproduced the bug 10 times in a row. I would like to sent the clip but I can’t since it exceeds file limit

**Comment by Fidelity88** [comment] 2023-08-13 21:42
I’m having the same problem on iOS 17 on my iPhone 14 Pro. Some weird behavior with the input field for Google.

also @RaiseDennis, try an online video compress service. That including .MP4 format compression usually works

**Comment by data-sync-user** [comment] 2023-08-21 13:29
➤ Andrei Bodea commented:

Verified as fixed on v116.3 (33647) with iPhone 13 Pro (15.7.1), iPhone 14 (16.0.1).

The keyboard was still displayed after inserting any letter on the search bar.

**Closed** 2023-08-21 13:29 UTC
Labels: Bug 🐞
