### ISSUE TITLE
The app crashes when the last tab is closed and the button undo is clicked.

### ISSUE THREAD

**Issue by FilippoZazzeroni** [mozilla-mobile/firefox-ios#14838] opened 2023-06-09 08:37 UTC
## Steps to reproduce
Close the last open tab and click the undo button.

### Expected behavior
The app crashes.

### Actual behavior
The app shouldn't crash.

### Device & build information
* Device: Iphone 14 pro iOS 16.4
* Build version: 116 (1)
* First seen version: ? 
### Notes

# Crash report
`Collection view: <UICollectionView: 0x7fbb8e09e400; frame = (0 0; 393 683); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000001c32a0>; backgroundColor = UIExtendedSRGBColorSpace 0.109804 0.105882 0.133333 1; layer = <CALayer: 0x600000eda440>; contentOffset: {0, 0}; contentSize: {393, 222}; adjustedContentInset: {0, 0, 83, 0}; layout: <UICollectionViewFlowLayout: 0x7fbb8f023090>; dataSource: <Client.TabDisplayManager: 0x7fbb8f027630>>'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011442d78b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010f040b73 objc_exception_throw + 48
	2   Foundation                          0x00000001163d9f64 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000012e9c282f -[UICollectionView _Bug_Detected_In_Client_Of_UICollectionView_Invalid_Batch_Updates:] + 115
	4   UIKitCore                           0x000000012e9c1c20 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:] + 13321
	5   UIKitCore                           0x000000012e9cfd1c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:animationHandler:] + 443
	6   UIKitCore                           0x000000012e9cfad3 -[UICollectionView performBatchUpdates:completion:] + 34
	7   Client                              0x0000000102e8d58b $s6Client17TabDisplayManagerC24performChainedOperations33_1A65387E8136A8968C6559640AD3A593LLyyF + 1355
	8   Client                              0x0000000102e898ca $s6Client17TabDisplayManagerC10updateWith33_1A65387E8136A8968C6559640AD3A593LL13animationType9operationyAA0b9AnimationN0O_yycSgtF + 458
	9   Client                              0x0000000102e8023d $s6Client17TabDisplayManagerC13updateCellFor33_1A65387E8136A8968C6559640AD3A593LL3tab08selectedB7ChangedyAA0B0C_SbtF + 365
	10  Client                              0x0000000102e8be70 $s6Client17TabDisplayManagerC03tabD0_011didSelectedB6Change8previous11isRestoringyAA0bD0_p_AA0B0CSgAKSbtF + 656
	11  Client                              0x0000000102e8dbe0 $s6Client17TabDisplayManagerCAA0bD8DelegateA2aDP03tabD0_011didSelectedB6Change8previous11isRestoringyAA0bD0_p_AA0B0CSgAMSbtFTW + 16
	12  Client                              0x0000000102f8def5 $s6Client16LegacyTabManagerC06selectC0_8previous11sessionDatayAA0C0CSg_AI10Foundation0H0VSgtFyAA04WeakcD8DelegateCXEfU_ + 517
	13  Client                              0x0000000102f9e0e8 $s6Client16LegacyTabManagerC06selectC0_8previous11sessionDatayAA0C0CSg_AI10Foundation0H0VSgtFyAA04WeakcD8DelegateCXEfU_TA + 24
	14  libswiftCore.dylib                  0x000000011af22674 $sSTsE7forEachyyy7ElementQzKXEKF + 420
	15  Client                              0x0000000102f8d95b $s6Client16LegacyTabManagerC06selectC0_8previous11sessionDatayAA0C0CSg_AI10Foundation0H0VSgtF + 3403
	16  Client                              0x00000001033d8ebf $s6Client24TabManagerImplementationC06selectB11WithSession33_944164A9464AD1503DC23C6533506C64LL3tab8previous11sessionDatayAA0B0C_AJSg10Foundation0P0VSgtF + 143
	17  Client                              0x00000001033d8ae5 $s6Client24TabManagerImplementationC06selectB0_8previousyAA0B0CSg_AHtFyyYaYbcfU_TY1_ + 85
	18  Client                              0x00000001033d91e1 $s6Client24TabManagerImplementationC06selectB0_8previousyAA0B0CSg_AHtFyyYaYbcfU_TATQ0_ + 1
	19  Client                              0x0000000102c97841 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTQ0_ + 1
	20  Client                              0x0000000102c97971 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTATQ0_ + 1
	21  libswift_Concurrency.dylib          0x0000000115caba31 _ZL23completeTaskWithClosurePN5swift12AsyncContextEPNS_10SwiftErrorE + 1
)`

https://github.com/mozilla-mobile/firefox-ios/assets/55580351/b0a9c7d0-7e7e-4106-8564-0b678819778a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6630)

**Comment by dicarobinho** [comment] 2024-03-26 08:34
I am working on this.

**Comment by data-sync-user** [comment] 2024-03-26 13:02
➤ Alexandru Farcasanu commented:

I tried for many times to get the same behaviour but no success.

!Screen Recording 2024-03-26 at 14.58.19 (eb382816-4f45-49a8-ad8a-e76842591777).mov|width=854,height=1872!

**Comment by data-sync-user** [comment] 2024-03-28 07:30
➤ Alexandru Farcasanu commented:

Moved back in ToDo, since is not reproducible.

**Comment by data-sync-user** [comment] 2024-04-03 21:10
➤ Norberto Andres Furlan commented:

I was not able to reproduce either. Andrei Bodea Diana Andreea Barladeanu can you take a look to this one? If you can’t reproduce, lets close it for not. Thanks!

**Comment by data-sync-user** [comment] 2024-04-04 04:52
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40398), with iPhone 15 (17.0).

We weren’t able to reproduce this issue anymore.

**Closed by data-sync-user** 2024-04-04 04:52 UTC
Labels: Bug 🐞
