### ISSUE TITLE
Quick-search engine icons no longer appear in 38.0

### ISSUE THREAD

**Issue by MikeStucke** [mozilla-mobile/firefox-ios#9223] opened 2021-09-30 03:57 UTC
## Steps to reproduce
Type a search query into the address bar while one or more quick-search engines is active in Search settings.

### Expected behavior
A row of icons appears above the user’s keyboard, allowing the user to submit the search query to one of their enabled Quick-search engines instead of the Default search engine.

### Actual behavior
The quick-search engine icons no longer appear in version 38.0, and do not appear to be accessible by other means.

### Device & build information
* Device: iPhone XS Max (iOS 15.0)
* Build version: 38.0 (6157)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3235)

**Comment by SimonBasca** [comment] 2021-09-30 08:58
Thanks for the feedback. This is a duplicate of #9084.

**Closed by SimonBasca** 2021-09-30 08:58 UTC
Labels: Bug 🐞
