### ISSUE TITLE
Logins list no longer searchable

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#9477] opened 2021-11-07 17:50 UTC
## Steps to reproduce

* Install current TestFlight (6528)
* Open Passwords
* Enter a search string that matches a username or URL

### Expected behavior
* Matches are shown when searching 

### Actual behavior
* They are not

### Device & build information
* Device: iPhone 13
* Build version: 6528

### Notes

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3410)

**Comment by SimonBasca** [comment] 2021-11-08 09:16
This seems like a duplicate of #9468. Closing this one in favor of #9468

**Comment by rnewman** [comment] 2021-11-08 14:42
Not a duplicate, @SimonBasca — that ticket is about usernames not displaying, this ticket is that text search no longer works in the Passwords UI. They might have the same root cause, but they're different bugs.

**Comment by dnarcese** [comment] 2021-11-10 20:37
This is not always reproducible. @SimonBasca are you able to provide reliable STR?

**Comment by SimonBasca** [comment] 2021-11-15 11:54
I was unable to reproduce the issue on v95 (6631) or latest main 4f7d4851. Let's keep the issue opened and I will keep trying to find reliable STR.

**Comment by akamfoad** [comment] 2021-12-14 14:13
Browser: `Firefox Daylight 40.1 (7037)`
OS: iOS 15.1
Phone: iPhone 6s

I have the same issue, seems like if you type slowly, obv until the browser finishes the request and the request handling, it shows a list, but, if you type another character while it's processing prev search, it cancels current search and wont start a new one. If you hit `Search` button the keyboard it'll search again.

@SimonBasca  @dnarcese

**Comment by rbclark** [comment] 2022-01-01 14:49
It seems my phone is very slow so it is able to reproduce this reliably. I am only able to search if I type very slowly, as soon as I type another character before the last one is finished loading it will cancel the search and show "No logins found"

https://user-images.githubusercontent.com/2308869/147853184-1583b833-a884-4146-9698-6850b3ec3735.mov

## Device & build information

iPhone 11 XR
IOS 15.2
Firefox Daylight 40.2 (7167)

**Comment by rbclark** [comment] 2022-01-01 16:38
Small update to my previous comment, I've discovered that the results do in fact show up, it seems the issue here is that it doesn't show a loading page and also takes forever to show up, leading users to believe that it is not loading when it is in fact just taking a very long time to load.

**Comment by lmarceau** [comment] 2022-01-13 16:29
Just as a note, to be able to get this issue I think you need a lot of logins. Just a couple won't trigger the spinner and the issue we see here. With around a 100 I started to get the spinner.

**Comment by lmarceau** [comment] 2022-01-13 16:32
Reopen since needs QA

**Comment by data-sync-user** [comment] 2022-01-21 16:26
➤ Simion Basca commented:

Tested on iPad Pro (15.2), iPad mini (15.2) and simulator iPad Air 4th gen (14.2). I was unable to reproduce the issue after the fix on main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5. I my case the login list can be correctly filtered by username.

**Closed** 2022-01-21 16:57 UTC
Labels: Bug 🐞, Needs-QA, P3, Contributor Fix
