### ISSUE TITLE
SSL Lock Badge Toggles to Invalid

### ISSUE THREAD

**Issue by bkochendorfer** [mozilla-mobile/firefox-ios#12616] opened 2022-12-07 15:33 UTC
## Steps to reproduce
1. Navigate to a website with SSL. My example in the screenshots below is https://bookshop.org/.
1. Lock your phone and wait :clock1: 
1. Open the application again. If the tab does not auto-refresh (I've noticed sometimes it auto-refreshes) the SSL badge will show a line through it.
![IMG](https://user-images.githubusercontent.com/1072933/206220889-368de3ec-f1be-4ea7-af28-192aad45617c.png)UNITO-UNDERSCORE!3147!
1. Clicking on the badge I would expect some information about why the cert is invalid but it is listed as valid.
![IMG](https://user-images.githubusercontent.com/1072933/206221062-9d2f6539-aaf8-4278-9aa4-18d2405c14f1.png)UNITO-UNDERSCORE!3148!
1. Manually refreshing the tab will remove the red `\` through the SSL Lock.
![IMG](https://user-images.githubusercontent.com/1072933/206221227-63728e55-25fa-43ec-b709-53d89be94658.png)UNITO-UNDERSCORE!3147!

### Expected behavior
I would expect the SSL Lock Badge to reflect the state of the SSL certificate. Either valid or invalid. 

### Actual behavior
The SSL Lock Badge is showing as invalid when the cert is actually valid. There seems to be some state it is falling into.

### Device & build information
* Device:  iPhone 11 iOS 16.1.2
* Build version: 107.2 (22549)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5390)

**Comment by data-sync-user** [comment] 2023-05-17 17:22
➤ Nishant Patel commented:

I’m having trouble reproducing this with the given STR. Andrei Bodea Could you verify if this is still an issue in `main` when you get the chance?

**Comment by abodea** [comment] 2023-05-18 11:05
Hello, @nishiths23 I was not able to reproduce this issue on the latest 9000 with iPhone 13 Pro (15.7.1).
@bkochendorfer any chance you can check and see if you still reproduce this? 
@nishant2718 based on the response I think we can close this one and maybe re-open it in case it will be reproducible in the future.

**Comment by bkochendorfer** [comment] 2023-05-18 14:22
Morning, I am now on Firefox 113.0 (30633) and have not seen this issue for a while. I'll keep an eye out.

**Comment by DianaBarladeanu** [comment] 2023-05-25 11:35
I investigated this issue on multiple SSL websites with FF v9000 (31186) and iPhone SE (15.4) and wasn't able to reproduce it.

**Comment by DianaBarladeanu** [comment] 2023-06-30 09:14
I investigated this issue on multiple websites with FF v9000 (332297) and iPhone SE (15.4) and wasn't able to reproduce it.

**Closed** 2023-07-03 08:41 UTC
Labels: Bug 🐞
