### ISSUE TITLE
jQuery e.preventDefault(); not working

### ISSUE THREAD

**Issue by vdecree** [mozilla-mobile/firefox-ios#1377] opened 2015-12-21 11:49 UTC
Hi there,

I've been finding that the following doesn't work for Firefox iOS. The links appear still touchable however in other mobile browsers this is working:

```
group_link.on("click touchstart", function(e){
	e.preventDefault();
	console.log("clicked");
});
```

**Comment by vladikoff** [comment] 2016-10-06 16:54
Cannot reproduce this bug, can probably close this...

**Closed** 2016-10-07 07:25 UTC
Labels: needs bug
