### ISSUE TITLE
Tabs on iPad have wrong highlight when new tab page is set to blank page

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#13830] opened 2023-04-02 02:11 UTC
## Steps to reproduce
1. Set new tab page to blank page
2. Open a new tab
3. Switch between other tabs and the blank new tab

### Expected behavior
1. Only the selected tab should be highlighted
 
### Actual behavior
1. After opening a new tab, both the previous tab and the new tab are highlighted
2. After switching back to another tab and the new tab, the new tab are not highlighted even when it is the selected tab

### Device & build information
* Device: iPad Pro 10.5-inch iOS 16.4
* Build version: 111.2 (29672)
* First seen version: 111.0
### Notes
* Version 110.2 did not have this issue.
Attachments: 

https://user-images.githubusercontent.com/2097707/229327236-2a143ffc-799f-49a4-b762-a007e4071916.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6115)

**Comment by abodea** [comment] 2023-04-03 08:07
Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13462.

**Closed by abodea** 2023-04-03 08:07 UTC
Labels: Bug 🐞

**Comment by struq** [comment] 2023-05-28 04:01
Still not fixed in 113.2 (31081). Please re-open. @abodea

**Comment by lmarceau** [comment] 2023-05-29 15:10
@struq As mentioned in the other linked issue https://github.com/mozilla-mobile/firefox-ios/issues/13462, this will be normally fixed in v114. Let us know if it's not fixed in that release. Thank you!

**Comment by struq** [comment] 2023-06-09 04:57
@lmarceau unfortunately it's not fixed in 114.0 (31388)
