### ISSUE TITLE
invisible button that overlays the address bar read in VoiceOver

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/firefox-ios#5017] opened 2019-05-23 16:47 UTC
On Firefox's start page, the first thing that gets read by VoiceOver is simply "button" and it appears to be an invisible button overlaying the address bar that does nothing when double-tapped. Tested with iOS 12.0.1 on the latest release version of Firefox.

**Comment by SimonBasca** [comment] 2019-05-24 10:29
Still reproducible on iPhone Xr running with iOS 12.2

![IMG_D1F551196365-1](https://user-images.githubusercontent.com/32130829/58321801-d68e8700-7e27-11e9-9101-b44e4dd73f7c.jpeg)

**Comment by SimonBasca** [comment] 2019-05-24 12:38
I think this is a duplicate of #4992

**Closed by SimonBasca** 2019-05-24 12:38 UTC
Labels: Accessibility
