### ISSUE TITLE
Tabs disappeared in the tabs tray after creating the second one

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13942] opened 2023-04-12 14:39 UTC
## Steps to reproduce
1. Launch FF and open 2 or more tabs.
2. The tabs disappear from the tabs tray.
### Expected behavior
The tabs should always be displayed.
### Actual behavior
Tabs disappeared in the tabs tray after creating the second one
### Device & build information
* Device: **iPhone 13 Pro (15.7.1).** 
* Build version: **113 (30010).** 
* First seen version: **113 (30010).** 
### Notes
This issue occurred once and I was not able to generate any attachments.
I will keep an eye on it in case I can find some better steps to repro.
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6179)

**Comment by yoanarios** [comment] 2023-04-20 20:02
I found a similar issue when testing #7574 changes, in my case is easier to reproduce long pressing on a tab to reorder 1 of the tabs disappears temporarily also the UI freeze in some cases

**Comment by data-sync-user** [comment] 2023-04-24 11:41
➤ Andrei Bodea commented:

Verified as fixed on v113 (30257) with iPhone 13 Pro (15.7.1).

Please note that I was not able to reproduce it but even before it was very hard to reproduce this issue.

Yoana Rios DiazI also tried what you mentioned in the comment but had no chance to reproduce.

**Closed by data-sync-user** 2023-04-24 11:41 UTC
Labels: Bug 🐞, S2
