### ISSUE TITLE
Firefox 121.0 (36782) "send tab to device" does not show connected devices

### ISSUE THREAD

**Issue by ronaldho** [mozilla-mobile/firefox-ios#17789] opened 2023-12-18 01:07 UTC
## Steps to reproduce

- Tap Shareow (share extension icon) on Safari
- Select Firefox
- Choose "send to device"
- See message "You don't have any other devices connected to this account available to sync"
- Try to "refresh" the list by pulling to refresh, but the operation never completes or the list never updates
- Go to Firefox App
- Choose Hamburger Icon (Three Lines)
- Choose Send link to device
- See that there are connected devices

### Expected behavior
- See the same connected devices in Share Extension as shown in Firefox 

### Actual behavior
- No actual devices shown "You don't have any other devices connected to this account available to sync"

### Device & build information
* Device: ? iPhone 14 Pro, iOS 17.1.2
* Build version: ?  121.0 (36782)
* First seen version: ?  121.0 (36782)
### Notes
- I have an iPad with build 120.4 (36613) which does not exhibit this behaviour
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7984)

**Comment by ronaldho** [comment] 2023-12-18 01:13
I have tried signing out and back in, deleting the app (and signing in again) and also restarting the device but the issue is still present

**Comment by stromfeldt** [comment] 2023-12-18 02:56
I have this issue as well, which seems to have started with version 121.0. That is, I can't send a link to Firefox on my Mac from any app other than Firefox iOS itself.

![IMG_5691](https://github.com/mozilla-mobile/firefox-ios/assets/27488257/96d93413-c87b-46fe-8969-cca6c5b35899)

I've tried signing in and out as well, but to no avail. Since you say that deleting the app didn't work for you I won't bother trying that.

**Comment by pashynskykh** [comment] 2023-12-18 17:51
I am having the same problem. I have tried logging out, reinstalling the application, and restarting the iPhone. I have three devices connected to the account and I can't share a link from the _iOS share menu_.

I'd like to note that if I have the tab already open in Firefox, the "Send Link to Device" option in the menu works perfectly fine.

**Comment by slrgt** [comment] 2023-12-19 16:06
I have the same issue. Works perfectly if im in firefox but it says i hve not other devices if im sending a link from any other app. Refreshing the send screen never finishes and I tried deleting everything and enabling notifications for sent tabs

**Comment by ronjouch** [comment] 2023-12-20 03:00
Same, and also tried signing out & in, and disconnecting the phone from Desktop fxsync, then re-logging in, to no avail. 

Also started with version 121.0.36782, looks like a regression. iOS 17.2.

**Comment by abodea** [comment] 2023-12-20 15:43
Thank you for adding this issue, I will try and check to see if I can reproduce it. 
I will keep you updated and in case I can find a good way to reproduce it, but so far it's on our radar and we will try to solve it.

**Comment by afurlan-firefox** [comment] 2023-12-20 15:45
See attached. 

https://github.com/mozilla-mobile/firefox-ios/assets/148247564/c65b01a3-d3a8-4d12-b1fc-d705937954a6

**Comment by abodea** [comment] 2023-12-21 12:54
> See attached.
> 
>  RPReplay_Final1703087008.MP4

I was able to repro it too.

**Comment by ClintOxx** [comment] 2023-12-29 18:29
Having the same problem, the share send to device function works inside the firefox app but not in safari share tab

**Comment by cottmann** [comment] 2023-12-29 21:18
Can confirm this problem. 
Send to device from "Share [icon with up arrow]" does not work -- both for Safari and Firefox.
Firefox "Send Link to Device [icon with right arrow]" works (and Firefox sync works too).

iOS 17.2.1
Firefox 121.0 (36782)

**Comment by rvandermeulen** [comment] 2023-12-29 21:21
We expect this to be fixed in v121.1 shipping early next week. Please don't hesitate to let us know if you still see the problem after receiving that update.

**Comment by data-sync-user** [comment] 2024-01-01 16:12
➤ Ryan VanderMeulen commented:

Uplifted for 121.1 via https://github.com/mozilla-mobile/firefox-ios/pull/17854 ( https://github.com/mozilla-mobile/firefox-ios/pull/17854|smart-link )

**Comment by ronjouch** [comment] 2024-01-03 19:39
Fix confirmed too! 121.1 on iOS 17.2.1. Thanks!

**Comment by data-sync-user** [comment] 2024-01-03 19:40
➤ Norberto Andres Furlan commented:

Thanks for the confirmation and collaboration!

**Comment by pashynskykh** [comment] 2024-01-03 19:41
121.1. It’s working again!

**Comment by cxt666** [comment] 2024-01-03 20:47
Fix confirmed  
121.1 on iOS 17.2.1.

**Comment by data-sync-user** [comment] 2024-01-04 12:47
➤ Andrei Bodea commented:

Verified as fixed on v121.1 (37312) with iPhone 15 Pro (17.1.2).
I was able to see the devices in the list and send tabs without issues.

**Closed** 2024-01-04 12:47 UTC
Labels: Bug 🐞, S2

**Comment by d-oderbolz** [comment] 2024-01-04 16:59
Thanks a lot! For me, the update to 121.1 indeed fixes this issue!

**Comment by kop3** [comment] 2024-01-08 15:47
Hi,
 Since 121.1 the feature works again, but with a glitch in my personal case.

I use firefox iOS from iPad (iPadOS 17.2 - last) and iPhone (iOS 17.2.1), and both suffers identical glitch. Sometimes, when I click in "Send to device" firefox context menu, does nothing. I can only cancel and retry the sharing action, and then works (and shows the devices submenu).

The first time it happened to me was after updating to 121.1, and I thought it was a problem of lack of recent synchronization of my firefox account. But this continues to happen randomly without any associable cause or correlation in my opinion.

**Comment by ronjouch** [comment] 2024-01-08 15:55
> Since 121.1 the feature works again, but with a glitch in my personal case.
> 
> I use firefox iOS from iPad (iPadOS 17.2 - last) and iPhone (iOS 17.2.1), and both suffers identical glitch. Sometimes, when I click in "Send to device" firefox context menu, does nothing. I can only cancel and retry the sharing action, and then works (and shows the devices submenu).
> 
> The first time it happened to me was after updating to 121.1, and I thought it was a problem of lack of recent synchronization of my firefox account. But this continues to happen randomly without any associable cause or correlation in my opinion.

@kop3 I was also about to file this regression! I confirm it, and I confirm it started happening in 121.1.

@rvandermeulen @abodea is this regression known to you already? Should @kop3 file it as a new issue?

**Comment by pashynskykh** [comment] 2024-01-08 15:57
> Sometimes, when I click in "Send to device" firefox context menu, does nothing.

I confirm this. Had the same problem a couple of times. Clicking on "Send to Device" from the context menu sometimes does nothing - the context menu for selecting the device does not open.

**Comment by rvandermeulen** [comment] 2024-01-08 16:00
A new issue for that would definitely be preferred. Thanks.

**Comment by ronjouch** [comment] 2024-01-08 20:29
> A new issue for that would definitely be preferred. Thanks.

@rvandermeulen @abodea done: [#18037 [121.1 regression] "Send to Device" sometimes fails to list devices](https://github.com/mozilla-mobile/firefox-ios/issues/18037)

**Comment by kop3** [comment] 2024-01-09 00:04
> > A new issue for that would definitely be preferred. Thanks.
> 
> @rvandermeulen @abodea done: [#18037 [121.1 regression] "Send to Device" sometimes fails to list devices](https://github.com/mozilla-mobile/firefox-ios/issues/18037)

Thanks, it was my first report in github, and I don't know the protocol

**Comment by slrgt** [comment] 2024-01-10 20:57
Firefox 121.2 broke it again. Now sometimes randomly Firefox doesn't even appear in the share sheet at all

**Comment by afurlan-firefox** [comment] 2024-01-10 21:48
Hi! I am not able to reproduce it on 121.2. @slrgt can you attach a video and more information about your device? Thanks!

**Comment by ronjouch** [comment] 2024-01-10 22:16
> Firefox 121.2 broke it again. Now sometimes randomly Firefox doesn't even appear in the share sheet at all

Can't repro, so far 121.2 works for me, and I cannot guarantee the race is 100% fixed, but in a dozen usages I haven't seen it yet. I just shared 4 tabs from 2 apps, the Firefox button does appear in the share sheet, devices display, and the tab is received in the receiving device.

**Comment by slrgt** [comment] 2024-01-10 22:21
Restarted my device and its working again. Its an iphone 10S on ios 17.2.1
