### ISSUE TITLE
[Felt privacy] - Incorrect theming of context menu

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20896] opened 2024-07-03 08:08 UTC
**Steps to reproduce**

1. Install FF, go to private browsing mode and open a page with hyperlinks.
1. Long tap on a hyperlink and observe.

**Expected behavior**
Context menu is displayed in purple.

**Actual behavior**
Context menu is displayed in grey.

**Device & build information**

* Device: iPhone SE (17.5)
* Build version: v9000 (43238)
* First seen version: ?

Notes
Attachments: 
![image0-2](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/c07b7eed-e45b-4660-8ff8-c810ad54b9dc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9442)

**Comment by data-sync-user** [comment] 2024-07-17 14:04
➤ Alexandru Farcasanu commented:

I have tried to change the Context Menu colour but Apple does not provide a way to change that just in order to keep the consistency of iOS applications.

It may be possible to change that but it will require more documentation and may be necessary to create a new custom UIMenu and not using the “native“ one.

Norberto Andres Furlan do you think we still want to change the theme/colour of the context menu? Is there any Figma available for that? 

Thank you.

**Comment by data-sync-user** [comment] 2024-07-24 00:17
➤ Nishant Bhasin commented:

Alexandru Farcasanu - This isn’t possible without performing workarounds. You can tint the icons but changing the color of the whole menu would be a tedious task. This is Apple’s implementation afaik.

Would recommend closing this ticket as its not a bug. cc Norberto Andres Furlan any objections?

**Comment by data-sync-user** [comment] 2024-07-30 14:09
➤ Nishant Bhasin commented:

Closed after syncing with Andy

**Closed** 2024-10-13 08:40 UTC
Labels: Bug 🐞
