### ISSUE TITLE
[Favicons refactor] - "YT" favicon is different

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22021] opened 2024-09-17 09:05 UTC
**Steps to reproduce**
1. Fresh install FF.
2. Observe YT favicon in top sites.

**Expected behavior**
YT favicon is the same as before.

**Actual behavior**
YT favicon is different.

 **Device & build information**
*Device: iPhone 15 (17.5)
*Build version: v131 (45309)
* First seen version: ? 

Notes
Attachments: 

![collage](https://github.com/user-attachments/assets/0e295205-78f1-4426-9097-08b2a86d5f51)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10044)

**Comment by nbhasin2** [comment] 2024-09-25 03:06
The second one seems to be the correct icon, before it wasn't the correct one

@DianaABarladeanu this seems to be working as intended so we can potentially close this

**Comment by nbhasin2** [comment] 2024-09-25 03:08
Closing with the above comment, feel free to open if you believe it otherwise

**Closed by nbhasin2** 2024-09-25 03:08 UTC
Labels: Bug 🐞, S3
