### ISSUE TITLE
Clearing all browsing history does not appear to work

### ISSUE THREAD

**Issue by leamingrad** [mozilla-mobile/firefox-ios#16235] opened 2023-09-04 11:25 UTC
## Steps to reproduce
1. Go to History
1. Click the bin icon
1. Click "Everything"

Context: I'm currently trying to reduce the size of "Documents & Data" as reported by iOS (since Firefox has the largest size and I am running out of storage).

### Expected behavior
Browsing history is deleted (and thus space is freed up).

### Actual behavior
Browsing history still appears, and there is no confirmation the deletion has occurred.

### Device & build information
* Device: iPhone SE (first generation), iOS 15.7.8
* Build version: 116.4 (33723)
* First seen version: Unknown (this has always been the case for me)

### Notes
To attempt to reduce storage, I have disabled History sync to my Firefox account. I would expect this to mean that I can delete the local history, but that it does not affect my other synced devices.

I am raising this separately to #16234 in case the deletion mechanism is different between the two screens.

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/FXIOS-7311)

**Comment by loganmarchione** [comment] 2023-09-20 03:18
I'm running an iPhone 12 Mini with iOS 17. Deleting history does delete my browsing history, but doesn't free space. See below where Firefox is using 6GB.

![image](https://github.com/mozilla-mobile/firefox-ios/assets/4955337/7c5e0307-2d06-471d-9633-ea73ba90c4ae)

**Comment by abodea** [comment] 2023-10-19 14:47
Hello, I was not able to reproduce this issue on build v9000 (35319) with iPhone 13 Pro (15.7.1).
@leamingrad @loganmarchione are you still reproducing this issue?

**Comment by loganmarchione** [comment] 2023-10-19 15:37
Yes, you can see my Firefox is growing even larger. 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/4955337/63ac291c-5f9b-46d7-b4c1-fc726f1d2589)

**Comment by leamingrad** [comment] 2023-10-25 17:15
@abodea I'v just tried on version 34971 and the issue does not replicate.

However, I think I might have a slightly different setup to before: after reinstalling I did not sign into my firefox account on iOS, and that seems to have resulted in generally lower storage consumption than before I reinstalled (127MB vs 500MB).

@loganmarchione Are you signed into a firefox account?

**Comment by loganmarchione** [comment] 2023-10-25 18:10
Yes I am, but I'm only syncing bookmarks. 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/4955337/80688722-f754-493e-b2e2-d2f8ec0a2778)

**Comment by leamingrad** [comment] 2023-10-27 08:36
When I was logged into my account I also wasn't syncing history, so I wonder if the syncing settings aren't respected in some way?

**Comment by OrlaM** [comment] 2023-11-02 19:06
Duplicate of #16956

**Closed by OrlaM** 2023-11-02 19:06 UTC
Labels: Bug 🐞, S2

**Comment by data-sync-user** [comment] 2023-11-22 16:57
➤ Orla Mitchell commented:

Good catch. The screenshot logic was updated along with the tab refactor work so it’s likely the clean up code isn’t working correctly. I recently moved some of that code around and I think I recall moving the code that clean ups screenshots for dead tabs, it’s possible this is fixed on main, but I’m not certain.
