### ISSUE TITLE
"Privacy Settings" from the privacy protection panel is not clickable

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#23706] opened 2024-12-11 23:23 UTC
## Steps to reproduce
1. Open https://www.example.com (note *https*).
2. Tap the lock 🔒 icon from the URL bar.
3. Toggle "Enhanced Tracking Protection".
4. Tap "Privacy settings" link near the bottom of the popover.

### Expected behavior
"Tracking Protection" from the settings is opened.

### Actual behavior
Nothing. 🤷🏼‍♀️ 

### Device & build information
* Device: iPhone 16 iOS 18.2 simulator
* Build version: `main`
* First seen version: (TBA)
### Notes
Attachments: 

The "Privacy settings" link from this screen does nothing.
![Simulator Screenshot - iPhone 16 - 2024-12-11 at 17 59 13](https://github.com/user-attachments/assets/08e8fd4f-9f9c-4b70-9d3a-a6ef6b7ace96)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10867)

**Comment by abodea** [comment] 2024-12-12 13:59
Closing as duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-10844, please note that the steps, actual and expected are the same as the Privacy Settings is not working.

**Closed by abodea** 2024-12-12 13:59 UTC
Labels: Bug 🐞, eng:bug-auto-found
