### ISSUE TITLE
FXIOS-1735 ⁃ As a user I want to use my Firefox managed password in other applications

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8371] opened 2021-04-21 17:36 UTC
This story is about implementing a _Credential Provider Extension_ in Firefox so that it becomes a system-wide provider for password filling in other applications.

References:

 * [Credential Provider Extension](https://developer.apple.com/documentation/authenticationservices/ascredentialproviderviewcontroller?language=objc)
 * [Lockwise CredentialProvider](https://github.com/mozilla-lockwise/lockwise-ios/tree/master/CredentialProvider)

The goal is to have feature parity with Lockwise iOS.

> Part of the P16107 work. Stefan will provide more detail in this ticket.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2850)

**Comment by lolrepeatlol** [comment] 2021-04-21 19:38
Hey @st3fan ! I'm very excited about this but I remember seeing an issue about it a while ago. Wouldn't this be a duplicate of #6202 ?

**Comment by SimonBasca** [comment] 2021-07-22 14:53
Not sure why this ticket was not closed. The PR was checked, tests where executed at [TestRail](https://testrail.stage.mozaws.net/index.php?/runs/view/44534&group_by=cases:section_id&group_order=asc) and all tests passed. 
We need this merged into main in order to verify [FXIOS-2953](https://mozilla-hub.atlassian.net/browse/FXIOS-2953)

@st3fan is this safe to close and merge into main?

**Closed** 2021-08-01 20:59 UTC
Labels: P1, P16107

**Comment by SimonBasca** [comment] 2021-08-02 15:30
Verified fix on main b17e7f53
