### ISSUE TITLE
FXIOS-924 ⁃ [Regression] There is no Reader View option

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7345] opened 2020-09-18 14:12 UTC
Issue found by automated test running as part as the Smoketest: [testAddToReadingList](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/ReaderViewUITest.swift#L37)
## Steps to reproduce
Go to: mozilla.org
### Expected behavior
There is an option to select reader view
### Actual behavior
The reader view buttom is not shown
### Device & build information
* Device: iPhone 8
* Build version: main
### Notes
Attachments: 
![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 12 21 15](https://user-images.githubusercontent.com/1897507/93607352-7e3ea980-f9c9-11ea-8f3a-364de4c560f7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-924)

**Comment by data-sync-user** [comment] 2020-09-22 19:47
➤ Ashley Thomas commented:

This is also affecting the refresh icon that shows in that location. NOTE: This was working a few weeks ago

**Comment by dnarcese** [comment] 2020-09-23 19:44
Caused by https://github.com/mozilla-mobile/firefox-ios/issues/7385

**Comment by dnarcese** [comment] 2020-09-24 17:29
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/7387

**Closed by dnarcese** 2020-09-24 17:29 UTC
Labels: Bug 🐞, P1, Regression, iOS14

**Comment by SimonBasca** [comment] 2020-09-25 11:56
Verified fix on main 8f59ee4
