### ISSUE TITLE
Can't download, share or markup dynamic PDF files on iPad OS 14.8

### ISSUE THREAD

**Issue by hazington** [mozilla-mobile/firefox-ios#9119] opened 2021-09-14 19:04 UTC
## Steps to reproduce
1.) Request a dynamic PDF file that is generated and doesn't have a file extension in the URL. Something like "https://example.com/download?fileid=1".
2.) Open the share menu and try to markup or download the previewed PDF file.
3.) Markup for example will then show "Unsupported file format".

These files can be previewed and downloaded as PDF:
https://example.com/*file.pdf*

These PDF files can be previewed, but download and markup doesn't work:
https://example.com/*download?fileid=1*

### Expected behavior
That the downloaded PDF file contains the actual and previewed PDF content.

### Actual behavior
The PDF file contains the URL and can't be opened.

### Device & build information
* Device: iPad Pro 2018 (iPad OS 14.8)
* Build version: 37.0 (5971)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3167)

**Comment by data-sync-user** [comment] 2021-09-16 18:18
➤ Daniela Arcese commented:

This is working for me. Are you able to provide some screenshots of the steps you are taking or a screen recording?

**Comment by cimnine** [comment] 2021-09-22 16:38
I have this as well sometimes. It usually happens with generated PDFs.

I suspect that Firefox tries to re-download the PDFs when sharing, rather than sharing its local copy. Then the URL might already be expired, eg because the XRCF token was already invalidated.

I also experienced this behavior for data URLs. FF previews the PDF, but I was not able to store or share it.

**Comment by Lekensteyn** [comment] 2022-09-21 16:05
I suspect that this is a duplicate of #9010, the download actions does not save the local copy, but tries to fetch the file again without appropriate cookies and credentials.

**Comment by data-sync-user** [comment] 2023-07-25 02:23
➤ Nishant Bhasin commented:

Seems like the comment related to temp document also applies here. 

Ref: https://mozilla-hub.atlassian.net/browse/FXIOS-4579?focusedCommentId=710833 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4579?focusedCommentId=710833|smart-link )

**Closed** 2024-01-01 21:19 UTC
Labels: Bug 🐞, P2
