### ISSUE TITLE
FXIOS-1346 ⁃ iPadOS top bar freeze

### ISSUE THREAD

**Issue by TimurEke** [mozilla-mobile/firefox-ios#7788] opened 2020-12-22 23:00 UTC
## Steps to reproduce
normal use: interact with the URL bar or the tabs
### Expected behavior
reaction
### Actual behavior
freeze for several seconds, the actions get executed after the top bar unfreezes
### Device & build information
* Device: iPad Air 4 iPadOS 14
* Build version: Firefox Daylight 30.0 (3279)
### Notes
Attachments: 
A video of the bug; a mouse is used only for the pointer, the bug occurs with regular touches too.

https://user-images.githubusercontent.com/8298517/102940945-c03c2780-44b1-11eb-9cee-4771848efe19.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2682)

**Comment by dnarcese** [comment] 2021-01-14 16:54
@SimonBasca are you able to reproduce this?

**Comment by SimonBasca** [comment] 2021-01-18 15:18
I am unable to reproduce this issue. I tried opening over 100 tabs but for me, scrolling on a page using swipe gesture works fine. Tested on iPad Pro (14.0) on Firefox 30.0 (3279) and main cdef0615d

**Comment by TimurEke** [comment] 2021-01-24 11:11
I still experience the issue. Is there a way to share logs? I do not have access to a mac, sadly.

**Comment by SimonBasca** [comment] 2021-03-04 09:30
Is this issue still reproducible with the latest version 32.0 (3841)?

**Comment by TimurEke** [comment] 2021-03-04 09:54
Yes, I still experience it daily. I also determined that the whole application freezes, not only the top bar.

I am able to reproduce it every time by loading a website and immediately scrolling down a bit.

**Comment by SimonBasca** [comment] 2021-03-04 14:51
I am experience some slow performance after opening ~350 tabs but still not able to reproduce the iPadOS top bar issue. 
@TimurEke Could you try closing some tabs and deactivating Night mode from the hamburger menu? Let me know if that changes anything.

**Comment by TimurEke** [comment] 2021-03-04 15:38
I only have about 50 tabs open; night mode is not enabled.

**Closed** 2021-11-16 21:48 UTC
Labels: Bug 🐞, Needs-QA, P2, qa-triaged

**Comment by lmarceau** [comment] 2022-04-29 13:46
@tirw I updated so username doesn't appear :)

**Comment by lmarceau** [comment] 2022-04-29 14:03
I can't delete the history. I'll delete the comment and repost it with the modified version.

Comment by @SimonBasca 
> I am experience some slow performance after opening ~350 tabs but still not able to reproduce the iPadOS top bar issue.
@tirw Could you try closing some tabs and deactivating Night mode from the hamburger menu? Let me know if that changes anything.
