### ISSUE TITLE
FXIOS-942 ⁃ App crashes whenever the option “save image” is selected from drop-down menu

### ISSUE THREAD

**Issue by Pr1m36** [mozilla-mobile/firefox-ios#7366] opened 2020-09-22 17:40 UTC
For images that aren’t embedded into the website, but direct to an address, the long-press menu option “save image” makes the app to crash and not download the selected image.

Doesn’t happen when the image is embedded into the website, where the option shown has a different name: “add to photos”.

* Device: iPhone 11
* Build version: 28.2

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-942)

**Comment by athomasmoz** [comment] 2020-09-24 15:47
Thanks for logging. Looks like this is also an iPad issue for certai ways of saving. @SimonBasca will test some different scenarios and add more steps to reproduce

**Comment by SimonBasca** [comment] 2020-09-24 16:22
Steps to reproduce:

1. Go to "pixiv.net" or "cnn.com"
2. Long press on an image
3. Tap "Save image"

Note:
- This is working in Safari.
- In Safari on "pixiv.net", long pressing on a image will show option "Add to photos" rather than "Save image" in Firefox.

**Comment by athomasmoz** [comment] 2020-09-29 18:34
Closing as duplicate of #7350

**Closed** 2020-09-30 15:48 UTC
Labels: Bug 🐞, P1
