### ISSUE TITLE
FXIOS-235 ⁃ Feature Request: Support hard refresh (like ctrl+F5 on desktop)

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla-mobile/firefox-ios#6009] opened 2020-01-14 07:19 UTC
On&nbsp;desktop, you&nbsp;can do&nbsp;<kbd>ctrl+F5</kbd> or&nbsp;<kbd>ctrl+shift+R</kbd> to&nbsp;clear the&nbsp;cache and&nbsp;force&nbsp;refresh a&nbsp;page.

**Firefox&nbsp;for&nbsp;Android** also&nbsp;supports&nbsp;this by&nbsp;long‑pressing the&nbsp;reload&nbsp;button, but&nbsp;**Firefox&nbsp;for&nbsp;iOS** currently&nbsp;only&nbsp;offers to&nbsp;reload with&nbsp;trackers&nbsp;disabled or&nbsp;in&nbsp;desktop&nbsp;mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2252)

**Comment by dnarcese** [comment] 2021-11-01 20:37
duplicate of #7024

**Closed by dnarcese** 2021-11-01 20:37 UTC
Labels: Feature-Request
