### ISSUE TITLE
Theming System - URL Bar - Private mode - The color used to highlight the link is wrong

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14857] opened 2023-06-09 12:01 UTC
## Steps to reproduce
1. Fresh install the FF app while device is in Dark mode 
2. Open a web page in private mode
3. Tap on the link to select it 
4. Check the highlight color 

### Expected behavior
The color should be light purple

### Actual behavior
The color is light blue (the same color used for normal browsing)

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 115 (31602) 
* First seen version: 115 (31602)
### Notes

1. Same issue reproduces for Light mode 

Attachments: 

![Skype_Picture_1](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/b9d3b4a1-176d-4f57-8327-50b5c24ce17a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6648)

**Comment by data-sync-user** [comment] 2023-06-14 12:10
➤ Alina Moldovan commented:

Validated this issue using v115 (31736) and iPhone 14+ (16.0.3) and iPad 3rd Gen (16.3.1). The issue is fixed now.

**Closed by data-sync-user** 2023-06-14 12:10 UTC
Labels: Bug 🐞, S3, Theming System
