### ISSUE TITLE
Splash screen briefly shows white screen while Firefox theme is set to night mode 

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#5921] opened 2019-12-16 21:50 UTC
**Bug:** White splash screen is seen when iOS System mode wasn't set to Night Mode but the theme for Firefox was set to Night Mode manually. Once in this mode all you need to do is open Firefox iOS and you should see white splash screen.

**More Info:** If both Firefox and System settings are set to Night Mode then all works perfectly and no white splash is seen.

**Comment by nishant2718** [comment] 2020-01-13 00:24
Hey! I'm looking to participate in this issue. I see a v22 milestone - what's the deadline for this?

Here's a small clip showing the issue on a simulator. Two things to note:
- From 0 to 3 seconds (w/ the iPhone on light mode), the splash screen shows up and a black screen is shown very briefly. Is this expected behavior?
- The issue of light mode showing despite enabling light theme (b/w 15 and 18 sec) is not an issue in the production app. I'm running the fennec scheme in the simulator. 
- Also see this in the production app, and reproducibility is at 100%.

**Comment by nbhasin2** [comment] 2020-01-14 18:14
> Hey! I'm looking to participate in this issue. I see a v22 milestone - what's the deadline for this?
> 
> Here's a small clip showing the issue on a simulator. Few things to note:
> 
>     * From 0 to 3 seconds (w/ the iPhone on light mode), the splash screen shows up and a black screen is shown very briefly. Is this expected behavior?
> 
>     * The issue of light mode showing (despite enabling night theme) in cold start (b/w 15 and 18 sec) is not an issue in the production app. I'm running the fennec scheme in the simulator.
> 
>     * Also see this in the production app, and reproducibility is at 100%.
> 
> 
> Video link
> https://drive.google.com/open?id=1AIWgOrN62sB55iQ5jZESpSwlJj7VNu4O

Hi @nishant2718, thanks for showing interest in this issue. I'd say if you have a pull request ready by end of this week or early next week (Eg. Monday, 20th Jan) then that would be ideal. 

And as for your 1st question. Are you on the Dark Theme mode on the app? Likely that;s whats causing the black screen as even though your iPhone is set to light mode but if the Firefox app is set to Dark Theme then that can make the screen black.

**Comment by nishant2718** [comment] 2020-01-15 01:04
Hey @nbhasin2, thanks for the reply! Regarding your question - my iPhone is set to light mode and "Enable Night Mode" is set to off. That's when I see a black screen on my phone in prod (iPhone 7 V.13.3) and also in the simulator's Fennec scheme. 

Regarding the timeline, it's a bit tight but I'll give it a shot. In the case that it doesn't make the end of the week, will the bug be reassigned or does it become part of a v23?

**Comment by nbhasin2** [comment] 2020-01-16 15:41
Hi @nishant2718, if timelines are tight for you I'd suggest you give it a shot or feel free to take some other issue if you would like to just contribute to Mozilla Firefox codebase :) 

I'll try to answer more questions as they come and ones I missed soon. 

Good luck!

**Comment by dnarcese** [comment] 2020-01-20 21:13
I don't think there is a way we can fix this. Since the app hasn't fully loaded yet at the point of the launchscreen, we do not have access to the theme settings. The only thing we can check is the system theme. I checked on Chrome and they do have a launchscreen that correctly matches, but that is only because they do not have any settings to manually change the app theme (they always follow the system theme).

**Comment by dnarcese** [comment] 2020-01-21 19:56
Closing as can't fix

**Closed by dnarcese** 2020-01-21 19:56 UTC
Labels: 2, Bug 🐞, P2
