### ISSUE TITLE
 Night Mode: Link previw shows image with inverted colors 

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5799] opened 2019-11-22 08:16 UTC
Steps to reproduce:
1. Open the CNN home page.
2. Long press on an image that is a link.

Expected:
Image is shown with correct colors in link preview mode.

Actual Behavior:

• Colors or image are inverted while user long-taps on the image.
• When user lets go of the tap, the image stays.

(notice also that the colors of the CNN logo on that page are also inverted. don't have to tap though.)

Originally filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1598311

**Comment by athomasmoz** [comment] 2020-01-16 17:45
Closing as a duplicate of #5951

**Closed by athomasmoz** 2020-01-16 17:45 UTC
