### ISSUE TITLE
Had 1 private tab but 0 normal tab

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#16080] opened 2023-08-16 15:45 UTC
## Steps to reproduce
Not sure how I got into this state, but I had 1 private tab but 0 normal tab

### Expected behavior
We should always have at least 1 normal tab

### Actual behavior
I had 0 normal tab and couldn't switch to normal mode because of that

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: [Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/12361134/Firefox.log)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7252)

**Comment by data-sync-user** [comment] 2023-09-20 13:38
➤ Orla Mitchell commented:

For QA since there are no repo steps for the original issue I think just verifying there are no regressions around tab restore should be good enough.

**Comment by data-sync-user** [comment] 2023-10-10 10:47
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (34959), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.

**Closed** 2023-10-10 10:47 UTC
Labels: Bug 🐞
