### ISSUE TITLE
Navigating a PDF in reverse results in (randomly triggered) jump to top of page 1

### ISSUE THREAD

**Issue by CipEna** [mozilla-mobile/firefox-ios#18249] opened 2024-01-19 04:51 UTC
## Steps to reproduce
1. Open a PDF file
1. Go to page 20 the navigate the PDF via touch to page 10, then 9, then 8 etc.
1. The PDF will unexpectedly jump to top of page 1.

### Expected behavior
The browser will navigate smoothly to page 9, 8 etc.

### Actual behavior
The browser jumps to page 1 in the PDF file.

### Device & build information
* Device: iPad Air 4th generation, iOS 17.2
* Build version: 121.1 (37312)
* First seen version: not earlier than Dec 2023

### Note
Easily triggered on the following PDF: https://api.printnode.com/static/test/pdf/multipage.pdf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8214)

**Comment by dicarobinho** [comment] 2024-04-29 11:09
Hello, @CipEna,

May you do a quick re-check here, please, because after some investigations, I am not able to reproduce this issue.

Thank you.

https://github.com/mozilla-mobile/firefox-ios/assets/61138287/5a909f38-8428-42bb-a368-d4afa39f02d6

**Comment by CipEna** [comment] 2024-04-29 13:27
Hello @dicarobinho,

I confirm this is fixed in Firefox 125.2 (41035). Checked both the PDF
posted as a test case and a 600 page PDF with the Apollo flight plans.

Thank you guys for doing a great job 👏.

Best wishes,
CipEna

**Comment by dicarobinho** [comment] 2024-04-29 13:39
Thank you @CipEna!

Going to close this as fixed!

**Closed by dicarobinho** 2024-04-29 13:39 UTC
Labels: Bug 🐞
