### ISSUE TITLE
Private tabs are lost after force close - "close private tabs" button missing from settings

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20073] opened 2024-04-30 11:15 UTC
Steps to reproduce

1. Fresh install FF.
1. Go to private browsing and open some tabs.
1. Force close the app.
1. Reopen the app and observe tabs tray.

Expected behavior
Alll tabs (normal and private) are restored. 

Actual behavior
Private tabs are closed.
"Close private tabs" button is missing from settings.

### Device & build information
* Device: iPhone 15 (17.4)
* Build version:v9000 (41381)
* First seen version: ? 

Notes 
This issue only reproduces on the v9000 build.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/0e2e2ec7-9c16-4f2a-8458-2439803a5e3b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9062)

**Comment by data-sync-user** [comment] 2024-05-02 19:17
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu this is expected behavior.

**Comment by zach-flaglerhealth** [comment] 2024-06-13 18:56
Since when is this expected behavior? I only ever use Private Tabs and Firefox iOS has persisted those (for 3+ years). Issue #15989 seems to be where the discussion of this bug is otherwise taking place, but was there a behavior change that was intended and not communicated?

**Comment by SomewhatOrangish** [comment] 2024-06-14 19:21
> Since when is this expected behavior? I only ever use Private Tabs and Firefox iOS has persisted those (for 3+ years). Issue #15989 seems to be where the discussion of this bug is otherwise taking place, but was there a behavior change that was intended and not communicated?

Like Zach, this took me completely by surprise and I"m quite frustrated by it.

**Comment by rschristian** [comment] 2024-06-15 10:00
Indeed, as a heavy user over the past few years, private tab persistence has been a (largely) reliable feature and it matches other browsers on the platform. Safari doesn't drop private tabs, why should FireFox?

In fact, if you take a look through Reddit, you'll find instances of Mozilla employees _apologizing_ over particularly buggy updates that broke private tab persistence and dropped tabs.

If this is intended to be a new change, it should've been announced well ahead of time and needs justification for divergence from a) existing expectations/behavior and b) from other apps on the platform.

**Comment by Woozlebats** [comment] 2024-06-17 07:07
I’m in the same boat, I lost so much shit that was really important to me. I won’t pretend it was the greatest system for maintaining all the things I wanted to come back to but I never had any issues until for some reason they decided we don’t get that feature anymore. Really sucks

**Comment by venezia** [comment] 2024-06-17 22:57
I would consider this a feature change - and one I'm not in favor of. I don't see it being mentioned in the release notes and if it had been mentioned, I wouldn't have upgraded. 

It's a real bummer and now I'm unsure if I should continue with this app - it was a feature I relied on.

**Comment by likeasummerain** [comment] 2024-06-18 03:23
This is absolutely not expected behavior. I have been saving pages to look at later this way for years. I just lost 30 + items on my to do list and I don’t have any idea what they are. I use private browsing for security and because I don’t want to be tracked between sites, and now I’ll have to find a new browser. The lack of tab functionality is exactly why I don’t use the focus browser and now this one is ruined too.  If I don’t close the tab I want it to be there when I go back, that’s why it’s open, that’s the whole point.

**Comment by aodgizmo** [comment] 2024-06-18 19:12
Not even having the option which is as simple as a check box in the settings, to keep tabs open if the user wanted to is a huge kick in the nuts to the people that did. Really hate it when "feature" changes are done just to change things that have been like that for years, I am all for bug fixes and the like,  but stuff like this is just annoying.

**Comment by garnetred** [comment] 2024-06-21 00:03
I've also noticed this same behavior even if you don't force-close the app - sometimes when you open the app after it's been out of focus for a while, it'll close all the private windows and open a default new tab in the regular section, and other times it won't. The varied behavior makes it hard to keep track of any work in private tabs at all.

**Comment by scribblemaniac** [comment] 2024-06-21 23:58
Like many, I am not happy with this change to say the least. Even if I did agree that private tabs should be deleted when the application is closed (which I don't, on mobile at least), the way this change has been handled is completely unacceptable. Please put someone on the firefox-ios development team that understands that ***open tabs are valuable personal data*** to some people. Deleting tabs which have been persistent for years without any warning or any means of exporting/transferring/backing them after upgrading up is not okay. Not even listing changes that would cause them to be deleted in the change log is not okay.

When the testimonials of users started coming it saying they're losing things important to them, a new update reverting this change should have been pushed right away before further damage could be done. Instead a week after the release went live and over a month after this issue was first reported we get absolutely no official response here or on any of the aforementioned threads except to say that this is "expected", and a minor update that makes absolutely no attempt to correct this issue or prevent further tab loss as more users upgrade. All of the shortcomings in the handling of this issue (not to mention the questionable decisions that lead to this change in the first place and previous tab loss issues) have destroyed any confidence I have in Firefox for iOS and have made me reevaluate my support for Mozilla as a whole.

<hr>

Since Mozilla isn't rushing to rectify this issue, I have taken it upon myself to write a tool that can recovery a list of all tabs (including private ones) under some circumstances. It requires some comfort with the command line+Docker and a full local backup of your device that was taken before running Firefox 127.0 for the first time. Simply restoring the backup does not help because iOS backups don't downgrade apps, so even if you restore your private tab data Firefox will just delete it again the instant you open the app :facepalm:. This tool extracts the tab URLs directly from the backup data to avoid this problem. I was fortunate enough to have made a backup recently, and hopefully some other people can benefit from this as well. It can be found here: https://github.com/scribblemaniac/firefox-ios-tab-recovery.

**Comment by robpneu** [comment] 2024-06-22 00:20
Yep, lost about a dozen tabs here. Unfortunately this has pushed me back to using Safari as my default on iOS (which does keep my private tabs open!). I’ll keep Firefox installed purely to for the share sheet to send links to Firefox on my desktop or laptop.

> Like many, I am not happy with this change to say the least. Even if I did agree that private tabs should be deleted when the application is closed (which I don't, on mobile at least), the way this change has been handled is completely unacceptable. Please put someone on the firefox-ios development team that understands that open tabs are valuable personal data to some people. Deleting tabs which have been persistent for years without any warning or any means of exporting/transferring/backing them after upgrading up is not okay. Not even listing changes that would cause them to be deleted in the change log is not okay.

I mostly agree. They really messed up here. Unfortunately just adding it to the changes would not have helped me as I allow iOS to keep all my apps up to date and I very rarely actually check the change notes as most developers don’t even put an actual list. At a glance I’d say at least half of Firefox’s “Bug Fixes”. This change was definitely not listed on the 127.0 update.


> Since Mozilla isn't rushing to rectify this issue, I have taken it upon myself to write a tool that can recovery a list of all tabs (including private ones) under some circumstances. It requires some comfort with the command line+Docker and a full local backup of your device that was taken before running Firefox 127.0 for the first time. Simply restoring the backup does not help because iOS backups don't downgrade apps, so even if you restore your private tab data Firefox will just delete it again the instant you open the app 🤦. This tool extracts the tab URLs directly from the backup data to avoid this problem. I was fortunate enough to have made a backup recently, and hopefully some other people can benefit from this as well. It can be found here: https://github.com/scribblemaniac/firefox-ios-tab-recovery.

You’re awesome! I haven’t done a local backup in years so this does nothing for me (I’ve just accepted my tabs are lost) but props to you for coming up with at least some sort of solution that I hope will help someone out there.

**Comment by mathmodave** [comment] 2024-06-22 11:57
It looks like this was discussed in [FXIOS-8672](https://mozilla-hub.atlassian.net/browse/FXIOS-8672), although I don't have access to that JIRA to take a look at the discussion.

Of the three PRs that I see that reference FXIOS-8672, [one of them](https://github.com/mozilla-mobile/firefox-ios/pull/19936) mentions:
> I've intentionally kept this PR as simple as possible so we can release it and then be sure there is no major blow back from users. If we need to roll back it should be very simple in the current state.

I'm not sure what would count as "major blow back" but there is at least some hope that this functionality can be restored.

I agree with @garnetred that this behaviour isn't limited to force closing the app.

**Comment by mapster127** [comment] 2024-06-25 18:28
There are many of us wrestling with this unannounced and unwelcome change - see the Mozilla community posts here https://connect.mozilla.org/t5/discussions/private-tabs-ios-no-longer-automatically-stay-open-since-new/m-p/59620#M20963
For example.  Yet no clear response from Mozilla anywhere and I doubt many of us suffering even thought about looking here on GitHub. It seems like FIXIOS-8672 may be intended to correct this but what is the timing? Firefox is essentially unusable for me in the interim but both the declaration above that this unannounced change is intentional and the lack of any obvious comment from Mozilla has me wondering whether I should even bother continuing with Firefox. Like others I’m defaulting back to Safari for now. How difficult is it for some public comment, or even acknowledgment of the issue to be made?

**Comment by ThinkChaos** [comment] 2024-06-25 18:57
Please at least add an option to turn this off.
IMO this should've at least had a prompt on first post-update launch because, even if I understand the intention, data loss is not cool.

**Comment by mapster127** [comment] 2024-06-25 19:16
And just to reinforce this is not just on crash or force quit. Firefox on iOS for iPad 17.5.1 has done this overnight every night for the last week or more (with the browser open but out of focus). Now today and yesterday it is randomly throwing all private tabs away every couple of hours. Again browser not closed or crashed and iPad not shut down. So just what the heck is going on? Surely this behaviour cannot be intentional?

**Comment by robpneu** [comment] 2024-06-25 20:10
> And just to reinforce this is not just on crash or force quit.

correct, it’s whenever the app is unloaded from RAM. Crashing and force quit both do that. iOS itself also does it automatically when it’s in the background (probably the same as “not in focus” as you put it) and iOS decides it should be unloaded from RAM. That’s what’s happening to you every couple of hours. This happens to all apps on iOS, most other apps actually try to save the state you left them in and then restore it when it’s opened again so you don’t notice, instead of just  throwing away what you left open.

**Comment by mapster127** [comment] 2024-06-26 04:23
Thanks @robpneu good point. I wasn’t thinking about how iOS was behaving here. But the fact that this is normal behaviour from the OS leaves me baffled that anyone would think not restoring tabs is in any way helpful. There are bound to be times in the day when one’s focus or priorities change, other apps are used, before returning to a prior topic being researched or other use of a Firefox tab. I fail to comprehend a use case/user story that would take precedence and expect those open tabs to be dropped. But I guess whoever decided to push this change also decided those users impacted did not have equally important needs.

**Comment by likeasummerain** [comment] 2024-06-26 13:46
Exactly! And it's even worse because links open in private if that was the last place you were using the app. I keep finding myself having to copy and paste links from private to regular so that they are actually available when I want them.

**Comment by ru-mi-al** [comment] 2024-06-29 12:41
I am currently using Firefox 127.1 (42781).
Since 2 days I lost all my tabs. I simply closed Firefox in the evening and the next day when I opened it, all tabs and private tabs were lost.
I understand this issue was fixed in version 116.2.

116.1 update deleted all open tabs #15989

The bug was reintroduced in version 127.1?
Anyway please let me know if there is a way to restore all my tabs.
Thanks

**Comment by ogra01** [comment] 2024-07-01 09:59
Adding my support for this ticket. Private tabs absolutely did not close in the past so this is a feature change or a bug. There is no good reason for private tabs to disappear. Please fix this issue and make them behave like normals tabs again. Thank you

**Comment by mkismy** [comment] 2024-07-04 03:42
I guess Mozilla cares no more privacy anymore 🤷‍♂️

**Comment by FloMiau** [comment] 2024-07-12 20:27
I think this is really annoying es

**Comment by Semimmortal** [comment] 2024-07-16 20:11
It's already been said in so many words, but this is easily the most egregious change I've ever experienced with M/FF. It's one thing to mistakenly do away with opened tabs over an update, but to remove entire functions/features and doing little-to-nothing in the way of restoring them? FF has been my go-to for longer than I can remember now; I've loved the functionality and ease of use. Who's bright idea was it to suddenly decide for us how we get to browse? Mozilla, it is in your best interest to allow us to use this browser not only as it was presented to us, but also as we've grown accustomed to doing. You wanna make changes? Sure, it's your creation, have at it. _But to remove our ability to CHOOSE in its entirety is deplorable._ Introduce as many features as you want. Provide toggles and recommendations if you believe certain things should be changed and leave it up to us! Risk is inherent in just about everything these days, especially on the digital front, but beyond some critical security implementation or stability fixes, it is not for you to determine what's best for us while simultaneously removing any option to maintain what we enjoyed about it to begin with. I want to choose how I use _this_ browser; please don't make me choose another browser altogether.

**Comment by tsangwpx** [comment] 2024-07-16 21:39
the last update (v128?) introduced the split window feature to Firefox iOS, which make the app more powerful. However, the private mode is now unstable. The private tabs are lost out of my control. The private mode now is just another Firefox Focus with tabs.

The app sometimes crash under special loads, and this bug / feature change makes it worse because all private tabs are also lost. 

Private tabs prevent sync between devices but do not imply the tabs are discardable. 

For the moment, I use private mode from other browsers.

**Comment by daryasary** [comment] 2024-07-30 16:18
It's ridiculous to see this issue reported 3 months ago by several users in several ways and it's not addressed by Mozilla yet, we don't even know whether it was a new feature or a release bug. What exactly are you guys doing? Could someone please point us in the direction of the plan regarding this?

**Comment by mapster127** [comment] 2024-07-30 19:45
Re: semiimmortal
> It's already been said in so many words, but this is easily the most egregious change I've ever experienced with M/FF. It's one thing to mistakenly do away with opened tabs over an update, but to remove entire functions/features and doing little-to-nothing in the way of restoring them? FF has been my go-to for longer than I can remember now; I've loved the functionality and ease of use. Whose bright idea was it to suddenly decide for us how we get to browse? Mozilla, it is in your best interest to allow us to use this browser not only as it was presented to us, but also as we've grown accustomed to doing. You wanna make changes? Sure, it's your creation, have at it. _But to remove our ability to CHOOSE in its entirety is deplorable.<
Kudos and I could not agree more. Sadly with radio silence from Mozilla on this it seems clear they don’t care about the impact or indeed consider the change to need fixing. I’ve given up hoping and switched to Safari in most places where I need a reliable browser. Sad times.

**Comment by data-sync-user** [comment] 2024-08-05 15:49
➤ Norberto Andres Furlan commented:

Hi! In response to your feedback, we have reintroduced the option to persist tabs in Firefox iOS. It is already available in our last version (FX 129). In order to persist private tabs, download the new update (FX 129), navigate to settings and disable the default setting "Close Private Tabs when Leaving Private Browsing". We appreciate your patience and your continue support to Firefox. Please let me know if you have any additional questions or concerns. Thanks!

**Comment by Semimmortal** [comment] 2024-08-05 15:55
> ➤ Norberto Andres Furlan commented:
> 
> Hi! In response to your feedback, we have reintroduced the option to persist tabs in Firefox iOS. It is already available in our last version (FX 129). In order to persist private tabs, download the new update (FX 129), navigate to settings and disable the default setting "Close Private Tabs when Leaving Private Browsing". We appreciate your patience and your continue support to Firefox. Please let me know if you have any additional questions or concerns. Thanks!

This is great news! Rarely have I seen pointed response to disagreeable changes, so this gives me some amount of hope. Your guys' response in both recognition and action is appreciated.

**Comment by pushcx** [comment] 2024-08-05 16:20
I'm really glad to hear the previous behavior is being restored.

You asked for questions: is there any information available on how the decision was made, how it was reversed, or anything else to help users set expectations around similar changes? Thanks.

**Comment by scribblemaniac** [comment] 2024-08-05 21:36
While this is a step in the right direction, it's not enough for me. Several questions remain:
- Why did this take over 3 months from the first report for the team to acknowledge any problem with this change?
- Why did it take nearly 2 months since the first production release with this change (when many users immediately started reporting loosing their tabs) before there was an official fix of any kind? A revert of the relevant changes could have been performed in a matter of days and saved the tabs of many users.
- Will there be any official acknowledgement of and apology for the damage caused by this change?
- What is being done to prevent yet another tab wipe issue in the future? Why should we trust Firefox for iOS after this?

I also second all the good questions by @pushcx above. Some transparency here could help us to understand what went wrong, both with the initial decision and subsequent inaction.

**Comment by mapster127** [comment] 2024-08-05 21:57
I’ll add my thanks here too, but likewise have many questions and discomfort with how this was handled and how non-existent communication was. Glad it’s fixed, hoping to see something more from the team about lessons learned. I’ll also note that there appears no change to this git issue status despite a fix and a new release being released.

**Closed** 2024-10-27 23:34 UTC
Labels: Bug 🐞

**Comment by cpeterso** [comment] 2024-10-28 05:09
Can you still reproduce this bug? Unchecking the "Close Private Tabs" setting keeps private tabs open for me.

https://support.mozilla.org/kb/automatically-close-private-tabs-when-leaving-priv

**Comment by pushcx** [comment] 2024-10-28 13:49
The misdesign is fixed, but the maintainers asked for questions and then didn't respond to any of them.
