### ISSUE TITLE
[Intermittent] Incorrect redirect when opening the app after a link was opened using the native app from FF 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19865] opened 2024-04-18 12:01 UTC
## Steps to reproduce
1. Make sure you have native YouTube app installed on the device 
1. Open FF and search for a YouTube video 
1. Tap on the link 
1. The video starts using the native app 
1. Force close FF and/or YouTube app
1. Start FF

### Expected behavior
The latest opened webpage is loaded (google search in my case)

### Actual behavior
The old redirect is lunched and FF app is skipped 

### Device & build information
* Device: 15+ (17.4.1) 
* Build version: 125.1(40778) 
* First seen version:  

*# 
*## Notes

* Issue is intermittent (5/10)
* I was not able to reproduce it using the latest V9000 (40882) nor v126 (40846). I'm not sure this issue is less intermittent on there builds or it was fix by other changes.

Attachments: 

<

!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!

-->

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/8e498765-ec94-4444-bdd5-c4178d631d02](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/8e498765-ec94-4444-bdd5-c4178d631d02)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9001)

**Comment by data-sync-user** [comment] 2024-04-18 19:14
➤ Norberto Andres Furlan commented:

Sorin Paraipan Alexandru Farcasanu can you take a look this?

**Comment by data-sync-user** [comment] 2024-04-19 10:46
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan 

I have started to investigate this. Yes, on 125 is reproducible because this fix 19514 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8803 ) is included only in 126. (also already verified by the QA team).

What I did to test this?
First, I build the app from main branch (126) and was impossible to reproduce the issue. After that, I added back the code that was removed in 19514 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8803 ) and the problem appeared. 

cc: Sorin Paraipan 

!yt.mp4|width=592,height=1280,alt="yt.mp4"!

**Comment by data-sync-user** [comment] 2024-04-19 11:08
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu is it easy to backport the changes on 126 to the next weekly release? If so, can you create the backport?

**Comment by data-sync-user** [comment] 2024-04-19 13:33
➤ Alexandru Farcasanu commented:

As a discussion with Norberto Andres Furlan , this should be verified only in v126.

fyi Andrei Bodea

**Comment by data-sync-user** [comment] 2024-04-22 14:54
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (41006), with iPhone 15 (17.4).

**Closed by data-sync-user** 2024-04-22 14:54 UTC
Labels: Bug 🐞, S3
