### ISSUE TITLE
YouTube warns that Firefox for iOS will soon not be supported

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#6097] opened 2020-02-08 23:19 UTC
When opening a page on YouTube, the following warning appears at the top of the screen:

> We'll stop supporting your browser soon. For the best experience, please [update your browser](https://www.youtube.com/supported_browsers).

![1571A048-4E2E-493A-925C-AFA1421E880D](https://user-images.githubusercontent.com/23159282/74093397-571d1280-4a9f-11ea-93f2-4ac67b162d48.jpeg)

---

Firefox for iOS 22.0 (17157)
iPadOS 13.3.1

**Comment by softvision-sergiulogigan** [comment] 2020-02-11 11:25
I have opened https://bugzilla.mozilla.org/show_bug.cgi?id=1614597 and added this one to the See also list.
@csuciu, you can close this as a Duplicate of the BZ one.

**Comment by csuciu** [comment] 2020-02-11 11:31
Thanks @softvision-sergiulogigan

**Closed by csuciu** 2020-02-11 11:31 UTC
