### ISSUE TITLE
URL bar autocomplete got into a weird state

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#15373] opened 2023-07-06 15:27 UTC
Current TestFlight. I started typing “Wikipedia”, and it got wedged into autocompleting (or at least rendering) something else. Clearing all the text left it in a bad state. See screenshots.

First screenshot after typing “wikiped”.

![IMG_4488](https://github.com/mozilla-mobile/firefox-ios/assets/91722/2ec6500c-adb7-427a-877c-99f5cc0a9fe9)
![IMG_4489](https://github.com/mozilla-mobile/firefox-ios/assets/91722/13f014b0-2ab4-460c-961b-e2007b7cc20d)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6908)

**Comment by lmarceau** [comment] 2023-07-06 15:47
Hello! You mean TestFlight 32373 right? (this is our first Beta for v116)

**Comment by dnarcese** [comment] 2023-07-06 19:08
@rnewman do you remember what happens if you start typing again? Does the autofill part then go away?

**Comment by rnewman** [comment] 2023-07-06 19:28
The remaining autocomplete fragment remained rendered over the top of whatever I typed.

**Comment by lmarceau** [comment] 2023-07-07 18:53
I could reproduce this, I'll have a look.

**Comment by lmarceau** [comment] 2023-07-10 16:40
The fix will be available in the next Beta. I had some issues reproducing reliably even before making changes, so could not confirm 100% this was reliably fixed. Let me know if it wasn't.

**Comment by data-sync-user** [comment] 2023-07-13 12:07
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).

**Comment by lolrepeatlol** [comment] 2023-07-17 19:39
> The fix will be available in the next Beta. I had some issues reproducing reliably even before making changes, so could not confirm 100% this was reliably fixed. Let me know if it wasn't.

@lmarceau

Unfortunately still noticing this issue on my iPhone X, beta build 32765

![image](https://github.com/mozilla-mobile/firefox-ios/assets/17863082/c5083f27-b84b-43d2-a7a5-024d250e8543)

**Comment by lmarceau** [comment] 2023-07-17 20:10
@lolrepeatlol the initial issue was that the suggestion autofill was still showing in the URL bar from a previous search. In the screenshot you're showing, the autocomplete suggestion is a valid one. I had a look and it seems our current behavior is, if the query has no match with the user's search history, then we try to show a suggestion based on the [topDomains list](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Assets/topdomains.txt). The auto complete suggestion in the URL bar isn't based on the third-party search engine result (in your case, Kagi).

**Comment by lolrepeatlol** [comment] 2023-07-18 02:43
> @lolrepeatlol the initial issue was that the suggestion autofill was still showing in the URL bar from a previous search. In the screenshot you're showing, the autocomplete suggestion is a valid one. I had a look and it seems our current behavior is, if the query has no match with the user's search history, then we try to show a suggestion based on the [topDomains list](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Assets/topdomains.txt). The auto complete suggestion in the URL bar isn't based on the third-party search engine result (in your case, Kagi).

Hi @lmarceau apologies for the confusion on my part.

The above screenshot had "redux" typed in the URL bar, which was shown in the search suggestion field, while the URL bar continued to show a reddit.com autocomplete.

I took some screen recordings of the issue in action on build 32745. It's a little difficult to reliably reproduce this issue, but it does continue to appear pretty often in my experience.

https://github.com/mozilla-mobile/firefox-ios/assets/17863082/9dce0824-cc81-4a1e-bbfd-be67fba00a19

https://github.com/mozilla-mobile/firefox-ios/assets/17863082/63e5b09e-97e2-4f0a-b7e7-a42e8f9f5824

**Comment by lmarceau** [comment] 2023-07-18 14:45
Ohh ok! Thank you, then I'll have another look at this 🙏

**Comment by data-sync-user** [comment] 2023-07-18 17:08
➤ Laurie Marceau commented:

Found something that could be causing the issue, although I couldn’t reproduce the problem (with with simulator or real device, tried as the video was doing multiple times, tried going faster, etc.). The fix will be available in the next beta build for 116.

**Comment by lmarceau** [comment] 2023-07-19 18:43
@lolrepeatlol so turns out it's apparently reproducible after the last fix still (in build 32820) 🤔 I was wondering, on which OS are you?

**Comment by lolrepeatlol** [comment] 2023-07-19 19:19
> @lolrepeatlol so turns out it's apparently reproducible after the last fix still (in build 32820) 🤔 I was wondering, on which OS are you? 

@lmarceau, I'm on 16.5.1 (c) :)

**Comment by lmarceau** [comment] 2023-07-20 15:13
I could reproduce this time, and after the last fix tried for a long time to reproduce and couldn't. So hopefully got it right this time around, and fix will be in the next Beta 🙏 Thank you!

**Comment by data-sync-user** [comment] 2023-07-21 11:35
➤ Andrei Bodea commented:

Verified as fixed on v116 (32873) with iPhone 13 Pro (15.7.1).

**Closed by data-sync-user** 2023-07-21 11:35 UTC
Labels: Bug 🐞
