### ISSUE TITLE
"Send user data" option does not work (when disabled FF still constantly phoning incoming.telemetry.mozilla.org)

### ISSUE THREAD

**Issue by pashynskykh** [mozilla-mobile/firefox-ios#11525] opened 2022-08-05 06:15 UTC
## Steps to reproduce
1. Disable "Send user data".
2. Check DNS logs / use mitmproxy, etc.

### Expected behavior
If Firefox stands for privacy, there should be an option to disable all telemetry. Furthermore, it should be opt-in, not opt-out.

### Actual behavior
Firefox constantly phoning incoming.telemetry.mozilla.org regardless of settings / No option to disable telemetry.

### Device & build information
* Device: iPhone 11.
* Build version: 103.0 (13910).

### Notes
Attachments: 
![bilde](https://user-images.githubusercontent.com/14852335/183013269-819f7cbc-d822-45ed-abad-5ef7d9d080e3.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4712)

**Comment by pashynskykh** [comment] 2022-08-07 09:11
Also, looks like FF still connecting to Adjust, ignoring disabled «Send user data» setting. 
![17DF9BBD-0C0D-4DD5-BCAF-39B009AB5BE8](https://user-images.githubusercontent.com/14852335/183283775-4ff1f26b-8fbb-494d-8029-6065bd86ff33.jpeg)

**Comment by pashynskykh** [comment] 2022-08-09 09:31
Just checked desktop version of FF, and there it works as expected.

Also, looks like opting-out from telemetry on iOS does not assume removing all previously collected data, as it implemented on desktop.

I suggest not only fixing this issue ASAP, but also implementing automatic removal of all previously collected data after opting out from telemetry, as it implemented on desktop FF. 

![image](https://user-images.githubusercontent.com/14852335/183615400-043c42c7-90ff-4576-af12-531349c60644.png)

**Comment by dnarcese** [comment] 2022-09-13 18:27
Duplicate of #11142

**Closed by dnarcese** 2022-09-13 18:27 UTC
Labels: Bug 🐞

**Comment by pashynskykh** [comment] 2022-09-13 19:03
@dnarcese after disabling DNS blocking for few minutes, connecting attempts to incoming.telemetry.mozilla.org really stopped. But I still see connection attempts to Adjust. Should I create a separate bug for this issue?

**Comment by pashynskykh** [comment] 2022-09-14 05:28
Thanks for update @dnarcese! After disabling DNS blocking, connection attempts to "incoming.telemetry.mozilla.org" really stopped. It was a deletion request. But the problem with Adjust still persist. It wasn't disabled, and I again have connection attempts to "app.adjust.com", "app.adjust.net.in" and "app.adjust.world".
Should I create a separate bug for this?

**Comment by pashynskykh** [comment] 2022-09-14 06:06
Thanks for update @dnarcese! After disabling DNS blocking, connection attempts to "incoming.telemetry.mozilla.org" really stopped. It was a deletion request. But I still see connection attempts to "app.adjust.com", "app.adjust.net.in" and "app.adjust.world".
I found, that FF is using Adjust Telemetry, so looks like it still active after turning off "Send user data".
