### ISSUE TITLE
Firefox offers to visit deleted bookmarks from iOS home screen

### ISSUE THREAD

**Issue by timstr** [mozilla-mobile/firefox-ios#8234] opened 2021-03-27 15:56 UTC
## Steps to reproduce
In FireFox, visit a website. From the three-dots menu at the top right beside the address bar, select "Bookmark this page." Then select "Remove Bookmark." Now go to the iOS homescreen and 3D-touch (touch and hold) the Firefox app to bring up its context menu.

### Expected behavior
Firefox should not offer to visit a deleted bookmark.

### Actual behavior
The 3D-touch context has an item labeled "Open Last Bookmark" which displays the title or URL of the website I just deleted from my bookmarks. Tapping on this item takes me to that site. This works whether or not the site is in my history or was visited in private mode.

### Device & build information
* Device: iPhone 6s, running iOS 14.4
* Build version: Firefox Daylight 32.1 (3961)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2806)

**Comment by lmarceau** [comment] 2022-01-15 00:02
Video of issue for reference:

https://user-images.githubusercontent.com/11338480/149599887-e8a2a2af-3e67-4669-b19c-b59494b8e9a8.mp4

**Comment by SimonBasca** [comment] 2022-04-04 11:51
Closing this issue as verified fix as the issue is no longer reproducible by following the STR on v9000. (8716)

Note that I've found a different entry point for this issue and logged is as a regression [here](https://github.com/mozilla-mobile/firefox-ios/issues/10386)

**Closed by SimonBasca** 2022-04-04 11:51 UTC
Labels: Bug 🐞, P3, Contributor Fix
