### ISSUE TITLE
Debug: Force Crash doesn't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#6038] opened 2020-01-22 08:43 UTC
## Steps to reproduce
1. Open the Settings
2. From the "About" section tap repeatedly a couple of times on the version
3. From the debugging menu, tap on "**Debug: Force Crash**"

### Expected behavior
Firefox should crash.

### Actual behavior
Nothing happens.

### Device information

* iOS device:
• iPad Pro 11" (13.2.3)
• iPhone 8 (12.3)

* Firefox version:  22.0 (17123)

**Comment by nishant2718** [comment] 2020-02-05 11:40
Oddly enough, I'm able to see the debug menu in the production app. Is this expected? @AndiAJ @athomasmoz

**Comment by garvankeeley** [comment] 2020-02-05 22:01
The  debug menu in the production app is expected yes

**Comment by nishant2718** [comment] 2020-02-06 12:13
> The debug menu in the production app is expected yes

Okay, gotcha - thanks for confirming @garvankeeley . I'll update as I make progress on this issue.

**Comment by nishant2718** [comment] 2020-02-15 16:24
It seems like Sentry is not being enabled in SentryIntegration --> setup(...). The following doesn't allow it to fall through at launch:

`guard let dsn = Bundle.main.object(forInfoDictionaryKey: SentryDSNKey) as? String, !dsn.isEmpty else {
            Logger.browserLogger.debug("Not enabling Sentry; Not configured in Info.plist")
            return
        }`

This results in `Client.shared?` to return as a nil in:
`public func crash() {
        Client.shared?.crash()
    }`

Maybe a Maintainer has the necessary privileges to dive deeper into this issue? If I seem to be missing something here, please feel free to let me know as well!

**Comment by dnarcese** [comment] 2020-02-24 21:45
I believe that this is only broken on v22.0 because there was an error in the Sentry setup. I have confirmed that it is fixed in v23.0 beta.

**Closed by dnarcese** 2020-02-24 21:45 UTC
Labels: Bug 🐞
