### ISSUE TITLE
The "Synchronised Tab" label is truncated on English (UK) localization.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5889] opened 2019-12-10 14:21 UTC
Build: 21.0 (16814)
Device: iPad Air 3
iOS: 13.1

Steps to reproduce:
1. Open Library

Actual results:
- The "Sync Tab" label is truncated.

Reproducible on:
- iPhone 7, iPhone X, iPhone Xr, iPad mini 4, iPad Air 3, iPad Pro 3rd gen 10.5 inch

![Skype_Picture_2019_12_10T14_20_00_828Z](https://user-images.githubusercontent.com/32130829/70537371-ff2e6200-1b68-11ea-9719-78da84392531.jpeg)

**Comment by garvankeeley** [comment] 2019-12-10 20:53
What locale is this? We should guide english translators to use the word 'Sync' instead of 'Synchronised'.

**Comment by SimonBasca** [comment] 2019-12-11 08:22
@garvankeeley I just realized that my phone language was set to English (UK). On English (US) the label is "Synced Tabs"

**Comment by dfperry5** [comment] 2019-12-18 01:54
@SimonBasca  - It's me again :P. This would be an interesting one. I'm not too familiar with how localization and translations work on iOS :) So this would be a cool learning opportunity for me. 

If you or @garvankeeley  could point me to a starting point, I'd love to give this one a shot too!

**Comment by isabelrios** [comment] 2019-12-18 08:36
@SimonBasca I think this is a dupe of Issue #5853 could you please confirm and close this one? Just because the other has info about Localization and so ... :) Thanks!

**Comment by SimonBasca** [comment] 2019-12-18 09:15
This seems to be the same issue as #5853 . Duplicate of #5853#.

**Closed** 2019-12-18 09:15 UTC
Labels: Bug 🐞
