### ISSUE TITLE
FXIOS-1977 ⁃ iPadOS daylight 34.1（5186），用magic keyboard触摸板浏览网页的时候，地址栏不会自动隐藏

### ISSUE THREAD

**Issue by brandyblacktea** [mozilla-mobile/firefox-ios#8729] opened 2021-06-17 03:00 UTC
iPadOS daylight 34.1（5186），用magic keyboard触摸板浏览网页的时候，地址栏不会自动隐藏。

https://user-images.githubusercontent.com/43712342/122324285-1e2a6300-cf5b-11eb-92a2-20579061a6ed.mp4

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1977)

**Comment by SimonBasca** [comment] 2021-06-17 10:33
Translating title : When browsing the web with magic keyboard touch pad, the address bar will not be hidden automatically.

Seems like a duplicate of #7788

**Closed by SimonBasca** 2021-06-17 10:33 UTC
