### ISSUE TITLE
FXIOS-1787 ⁃ [Bug] Keyboard should be dismissed when tapping on any empty space on the home screen on iOS < 14.x

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8448] opened 2021-05-06 11:21 UTC
## Prerequisites
Have a fresh install of Firefox or a clean profile

## Steps to reproduce
1. Tap the Search bar or close the Home tab from the tabs Tray
2. Tap on an empty space on the home screen

### Expected behavior
Keyboard should be dismissed

### Actual behavior
The keyboard isn't dismissed

### Device & build information
* Device: iPhone X (13.3.1)
* Build version: 34.0 (4722)

❗ Related #7608

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1787)

**Comment by dnarcese** [comment] 2021-05-13 18:50
Duplicate of #7608

**Closed by dnarcese** 2021-05-13 18:50 UTC
Labels: Bug 🐞
