### ISSUE TITLE
After the closing the current tab, the browser switches to the tab after the immediate next one

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#10190] opened 2022-03-10 00:11 UTC
## Steps to reproduce
- Open more than 3 tabs in Firefox
- Switch to the first tab (or any tab that's not the last two)
- Close the current tab by clicking the cross button in the tab

### Expected behavior
Either one of the following:
- Switch to the tab right next to the closed one
- Switch to the tab that was previously viewed before the closed tab

### Actual behavior
Firefox always switches to the tab after the immediate next one (the third tab counting from the closed one). (screen recording attached)

### Device & build information
* Device: iPad Pro 10.5"
* Build version: Firefox Daylight 98.0 (8233)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2097707/157560936-155f0863-11bf-4967-b9ea-be135cab5832.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3885)

**Comment by SimonBasca** [comment] 2022-03-17 14:52
[This looks like a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/10191 but slightly different steps to reproduce.](https://github.com/mozilla-mobile/firefox-ios/issues/10191)

**Comment by lmarceau** [comment] 2022-07-29 19:31
I'll bring this ticket to be tested in the sprint @SimonBasca, as it's possibly now fixed

**Comment by data-sync-user** [comment] 2022-08-04 09:36
➤ Simion Basca commented:

Verifying as fix on main b66207372d2c8ed00bf937e3cc3d31caf99e8ef8

**Closed** 2022-08-04 09:36 UTC
Labels: Bug 🐞, QA Verified, Contributor Fix
