### ISSUE TITLE
[Experiment][iOS] Set Firefox as default push notification is not triggered initially after 72+ hours

### ISSUE THREAD

**Issue by Softvision-AlexandruBejenaru** [mozilla-mobile/firefox-ios#17729] opened 2023-12-12 13:34 UTC
**[Notes]:**

* The notification can be triggered only if the browser is closed for 72h+ after enrolling in the experiment then the browser is sent to the background for another 72h+. However, if the app was closed instead the notification is still not received. We did not find any other way to trigger the notification.

**[Affected versions]:**

* Firefox Release 120.4 (36613).
* Firefox 121.0 (36782).
* Firefox Beta 900 (36796).

**[Affected Platforms]:**

* iOS 16.2 - iPhone 12 Pro.
* iOS 16.5 - iPhone 13 mini.

**[Prerequisites]:**

* User is enrolled in the “Set to Default reminder notification for iOS” [experiment](https://experimenter.services.mozilla.com/nimbus/set-to-default-reminder-notification-for-ios/summary). Steps to enroll in the experiment can be found in the following [Gdoc](https://docs.google.com/document/d/17p5yX4NXCdHMDFqXu3J__mLVTfiRu9SWyurjRD95gzk/edit#heading=h.tqbo2i5wzp4w).
* Firefox notifications are allowed.

**[Steps to reproduce]:**

1. Open the Firefox app;
1. Close the app / place the app in background;
1. Change the device date to 72+ hours into the future;
1. Open the app again;
1. Observe the behavior.

**[Expected result]:**

* Set Firefox as default notification is received.

**[Actual result]:**

* Nothing happens. Set Firefox as default notification is not received.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7951)

**Comment by Softvision-AlexandruBejenaru** [comment] 2023-12-12 14:24
https://github.com/mozilla-mobile/firefox-ios/assets/141239909/eb4328a7-e736-42f4-8f91-a4b364dcfd21

**Comment by data-sync-user** [comment] 2024-01-09 15:22
➤ James Hugman commented:

We have seen issues like this on iOS, and suspicion always comes back to `days_since_install`.

Lines of enquiry to confirm this: 

  1. In testing, can we remove the DAY_3_AFTER_INSTALL trigger, and see what happens? (if it’s days_since_install then the notification would display after a few hours).

If it is days_since_install then there are a couple of options:

  1. Workaround: in the experiment, rewrite DAY_3_AFTER_INSTALL in terms of last seen and event sum. e.g ( http://e.gf ). 'app_cycle.foreground'|eventLastSeen('Days', 0) <= 3 && 'app_cycle.foreground'|eventSum('Days', 49, 3) == 1
    1. This is “seen in the last 3 days, but only seen once in the 49 days prior to that”
    2. This is not ideal, because it is conceptually more complex.

  2. Fix the bug, in the Nimbus SDK. I’ve opened https://mozilla-hub.atlassian.net/browse/EXP-4181 ( https://mozilla-hub.atlassian.net/browse/EXP-4181|smart-link ) which moves the calculation of days_since_install closer to where it is used, rather than startup. I suspect that this is a problem, but I don’t know if it’s this problem or not.

Alexandru Bejenaru : could you confirm that this message is triggered if we remove the DAY_3_AFTER_INSTALL trigger?

**Comment by data-sync-user** [comment] 2024-01-10 15:40
➤ Alexandru Bejenaru commented:

Hi James Hugman 

We’ve started looking into this but ran into several issues. We’ve eventually updated the production recipe and added a new Treatment B without any triggers in order to try out your scenario. We might come back up with an answer only tomorrow, after the recipe update is properly reflected on all clients..

**Comment by data-sync-user** [comment] 2024-01-11 12:45
➤ Razvan Litianu commented:

hi, just to give an update. I managed to make it work while doing the steps to reproduce. 

!image-20240111-124431.png|width=472,height=1024!

**Comment by data-sync-user** [comment] 2024-01-11 16:20
➤ Alexandru Bejenaru commented:

Hello James Hugman 

We’ve removed the triggers and replaced them with ALWAYS as you suggested (see treatment B[ |https://experimenter.services.mozilla.com/nimbus/set-to-default-reminder-notification-for-ios/summary]+here+ ( https://experimenter.services.mozilla.com/nimbus/set-to-default-reminder-notification-for-ios/summary )). After enrolling in the branch we have changed the time to a few hours into the future when performing the steps to reproduce. 
However, even with these steps, triggering the notification has been inconsistent and we’ve managed to see it only once on an iPhone 12 Pro (iOS 16.2). So it would appear that the answer is no, removing DAY_3_AFTER_INSTALL does not make the notification trigger more consistently than before.

Razvan Litianu  Could you please let us know what app version you used and what branch were you enrolled in? Can you trigger the notification consistently? 
The problem is that we cannot trigger it constantly with the same steps. It would probably also help to know your device type + OS version. Thank you!

**Comment by data-sync-user** [comment] 2024-01-11 19:46
➤ James Hugman commented:

Alexandru Bejenaru I’m hoping you’re working on a current beta of 122.

Razvan Litianu It looks like you’re working on a nightly, taken from testflight.

https://mozilla-hub.atlassian.net/browse/EXP-4181 ( https://mozilla-hub.atlassian.net/browse/EXP-4181|smart-link )  is landed in main and is being uplifted to the final beta of 122 (I think 122.0.3), available from tomorrow.

Could one of you re-test this issue when that beta comes out, to see if it makes the problem better or go away?

**Comment by data-sync-user** [comment] 2024-01-12 07:46
➤ Razvan Litianu commented:

James Hugman correct. Alexandru Bejenaru iPhone 14 Pro iOS 17.0.3 on the latest 9000 build on test flight, branch treatment-a.

**Comment by data-sync-user** [comment] 2024-01-15 14:31
➤ Alexandru Bejenaru commented:

Hi James Hugman , fyi Razvan Litianu 

After further investigations using the latest Firefox Beta 9000 (37649), I’ve managed to trigger the notification consistently now on both Treatment A (with triggers, which requires 72h+ passed since running the app) and Treatment B (no triggers, only requires a couple of hours to pass). This confirms that it wasn’t an issue with the experiment triggers.

However, I’ve noticed that the app must be running in background for this to work. If the app is force closed instead the notification is not triggered with either of the branches so this might indicate a problem with push notifications.

**Comment by data-sync-user** [comment] 2024-01-15 17:16
➤ James Hugman commented:

{quote}If the app is force closed instead the notification is not triggered with either of the branches so this might indicate a problem with push notifications.{quote}

Could you loop in Winnie Teichmann for this part.

Winnie: please could you look at this, and let us know what you think.

**Comment by data-sync-user** [comment] 2024-01-16 14:03
➤ Winnie Teichmann commented:

James Hugman this is a limitation that I voiced during the development of the notification feature: The app has to be running in background for the background refresh to be able to be triggered. Another problem could arise if the user turns off background app refresh on a system level for Firefox or in general. In this case notifications would also not arrive as the background refresh can’t be triggered.

As for the notifications not arriving after 72+ hours: We are using background refresh to evaluate if a notification should be displayed to the user. We have however no control over when background refresh is triggered. This is Apple’s decision and it depends on a few parameters like device usage and app usage and likely others. I have been told by Apple that iOS attempts to monitor when apps are commonly launched and will attempt to adjust background fetch to match real world usage. We can only tell Apple how often the background refresh should run (every 4 hours in our case) but Apple could decide to launch the task only every 12 or 24 hours or not at all.

**Closed** 2024-03-17 06:44 UTC
Labels: Bug 🐞, S2
