### ISSUE TITLE
MacOS-iOS Handoff functionality is broken

### ISSUE THREAD

**Issue by broken-browser** [mozilla-mobile/firefox-ios#10444] opened 2022-04-10 04:11 UTC
##Reproduction
1. Open Firefox on a MacOS (MacBook, Mac, iMac) running device, running as the default browser, using the desktop icon.
2. Open any tab other than the home screen with a URL.
3. Set Firefox to the Default browser on your iOS (iPhone) device. 
4. Open app switcher on your iOS device to see application handoff tab.

##Expected Behavior
App switcher would reveal handoff **to Firefox** from the matching tab on the MacOS device.

##Actual Behavior
App switcher defaults to using Safari over Firefox in every instance. This is regardless to whether Firefox is set to default browser on MacOS and/or iOS.

##Device & build information
* Devices:
iPhone 12 mini
MacBook Pro 2021 using M1 Apple Silicone
* Build versions:
On iPhone 12 mini: Firefox Daylight 99.0 (8654)
On MacBook Pro: Firefox 99.0 (20220328190900)
### Notes
This issue has appeared to be an ongoing issue for several versions now, since Firefox on iOS has gotten the new home screen and search bar placement.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4078)

**Comment by SimonBasca** [comment] 2022-04-11 08:00
This seems like a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9513. The issue described here is that Firefox iOS is not receiving hand-off from MacOS. Instead of Firefox iOS, Safari is opened every time when tapping on the hand-off icon. Is this correct @broken-browser ?

**Closed** 2022-04-11 20:32 UTC
Labels: Bug 🐞

**Comment by broken-browser** [comment] 2022-04-12 04:14
@SimonBasca I would like to say it is VERY similar but this is a separate occasion, and has reappeared. I'm not 100% certain if that answers your question, but it is an issue regardless and has not necessarily been solved in this instance, I cannot say it is necessary to close this issue at the moment, I am not sure.

**Comment by SimonBasca** [comment] 2022-04-12 09:55
@broken-browser I've moved the steps to reproduce to https://github.com/mozilla-mobile/firefox-ios/issues/9513#issuecomment-1096473158. When #9513 will be fixed we will also check this scenario.
