### ISSUE TITLE
Update the cyan in dark mode

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#12572] opened 2022-12-02 20:23 UTC
Design Systems recently conducted some user testing and we found the cyan blue currently used in dark mode to be too bright. In order to improve the user experience, we'd like to change this blue to something more appropriate and suitable for dark mode viewing. We are essentially changing most instances of Blue 20 to Blue 30.

These are the following changes:
| **Color Token**                                                                             | **Current**                                          | **New**                                            |
|---------------------------------------------------------------------------------------|------------------------------------------------------|----------------------------------------------------|
| Action Primary<br> Text Accent<br> Icon Action<br> Icon Accent Blue<br> Border Accent | #00DDFF<br> rgba(0, 221, 255, 1)<br> fxColorBlue20   | #00B3F4<br> rgba(0, 179, 244, 1)<br> fxColorBlue30 |
| Action Primary Hover                                                                  | #80EBFF<br> rgba(128, 235, 255, 1)<br> fxColorBlue10 | #00DDFF<br>rgba(0, 221, 255, 1)<br>fxColorBlue20     |

These changes have been updated in [Mobile Styles](https://www.figma.com/file/pEyGeE4KV5ytYHeXMfLcEr/Mobile-Styles?node-id=889%3A46413&t=lLUM1tFOJ8iBzuSk-1).

Going forward, I will also be tracking these changes in a changelog [here](https://docs.google.com/spreadsheets/d/1T_f73XoWN7ZZlhoDz6dzHsjSdte4s3NKdVXvI7jh1AI/edit#gid=0).

Please let me know if you have any questions, thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5371)

**Comment by cwzilla** [comment] 2022-12-02 21:02
Sorry putting this on hold! Requires further solutioning on the design side.

**Comment by cwzilla** [comment] 2022-12-05 21:34
@OrlaM @lmarceau I updated the ticket and it's ready now! The new changes are now colors within the Fx color scale :)

Thank you!

**Comment by data-sync-user** [comment] 2022-12-06 18:47
➤ Laurie Marceau commented:

For QA, we can test the dark mode blue color is the expected one where the theme was already updated to the new theming system (homepage, settings, tabs tray, library panel, reader mode)

**Comment by data-sync-user** [comment] 2022-12-20 14:27
➤ Simion Basca commented:

Moving this to QA verified as we can see the updated color. Please note that the library panels still have the old color. The issue is tracked at : Library buttons color is not cyan in dark mode #12719 ( https://github.com/mozilla-mobile/firefox-ios/issues/12719 )

**Closed by data-sync-user** 2022-12-20 14:27 UTC
