### ISSUE TITLE
Slow tab close performance on Firefox iOS (v98, 99)

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#10285] opened 2022-03-22 18:20 UTC
## Steps to reproduce
Open 10 or tabs with some groups and regular items and tap on close all tabs

### Expected behavior
Closing of tabs should be instant regardless of regular or grouped tabs

### Actual behavior
but specifically, when there are groups the tabs take forever to close

### Device & build information
* Device: iPhone 11 pro

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3953)

**Comment by data-sync-user** [comment] 2022-03-29 16:10
➤ Nishant Bhasin commented:

We are investigating this on high priority.

Its seems to be causing slowness when closing more tabs. 

Most likely a computation related to tab groupings is happening on main thread.

On a side note. We have another bug related to jump back in which should not be related to slowness. https://mozilla-hub.atlassian.net/browse/FXIOS-3970 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3970|smart-link )

**Comment by data-sync-user** [comment] 2022-03-29 21:29
➤ Nishant Bhasin commented:

Found the culprit but it's not an easy fix. Basically, we never had a way to simply close all tabs gracefully. 

What we currently do is iterate through all tabs and try to close them one by one. This works but wait till you see the next pic where everything is done on main thread which is not the best for performance when we have more tabs (20>) 

Lastly, we do a lot some computation when we remove tab in general (2nd pic). The part where we select (1st pic) and add tab also does work as we now have inactive tabs and grouped tabs. Even if they are disabled some computation still happens.

!Screen Shot 2022-03-29 at 5.20.24 PM.png|width=695,height=235!

Everything is done on main thread 

!image-20220329-212113.png|width=1009,height=676!

The best way to fix it is to move all the computation related to the closing of tab on the background thread and only do UI updates on the main thread. This is a classic UI thread blocker problem to solve however the complexity of Firefox will take some time to do a proper implementation of the solution.

**Comment by data-sync-user** [comment] 2022-03-29 21:37
➤ Nishant Bhasin commented:

Going to be doing some performance improvements locally and hope I can have a 2 part fix
a) *Minor Fix* with partial background solution
b) *Major Fix* which should be a full background solution

**Comment by data-sync-user** [comment] 2022-04-13 12:36
➤ Simion Basca commented:

Verifying as fix on Fennec main bdc1e009354679b7b811748a0d55383452b44ef4. The issue was no longer reproducible and closing tabs performance has been increased. Also tested on low end devices and the performance is increased.

**Closed** 2022-04-13 12:36 UTC
Labels: Bug 🐞
