### ISSUE TITLE
Part 1 - Replace SDWebImage with Kingfisher to stop Firefox from crashing when opening some PDF which causes memory pressure

### ISSUE THREAD

**Issue by jamieoo** [mozilla-mobile/firefox-ios#10837] opened 2022-05-21 21:55 UTC
## Steps to reproduce
Opening the link to this PDF crashes Firefox:
https://www.makochicago.com/s/20220421-Mako-Menu.pdf

### Expected behavior
PDF loads.
### Actual behavior
Firefox crashes to home screen after 1-2 seconds.
### Device & build information
* Device: iPhone 11 max pro /iOS 15.4.1
* Build version: FF Daylight 101.1 (9384)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4285)

**Comment by koobs** [comment] 2022-05-24 05:06
Confirmed and reproducible on

Firefox Daylight 100.1 (9384)
Firefox Daylight 101.0 (9619)

with:

https://pure.bond.edu.au/ws/files/137915149/AM_Risk_management_processes_used_in_determining_project_feasibility.pdf

Via 

https://www.lens.org/lens/scholar/article/063-184-609-884-972/main

**Comment by koobs** [comment] 2022-05-25 05:20
> @koobs @jamieoo could you please post a video of the issue?

Added reproduction video (Firefox Daylight 101.0 (9619)) in my confirmation comment.

Firefox Daylight 100.1 (9384) is identical.

App Settings 

![image](https://user-images.githubusercontent.com/1011612/170185580-40ef3cfb-fca7-4165-ae32-db3eaff2718e.png)
![image](https://user-images.githubusercontent.com/1011612/170185605-8604441f-5ab6-4899-87fe-78da8a5b1955.png)
![image](https://user-images.githubusercontent.com/1011612/170185622-1f06671a-80e3-4c6b-8629-f31f8b705bbb.png)
![image](https://user-images.githubusercontent.com/1011612/170185637-ec2b0421-e557-40a3-a7e7-b5b6ed0f167a.png)

**Comment by koobs** [comment] 2022-05-25 22:27
Reproducible with latest beta:

Firefox Daylight 101.0 (9723)

https://user-images.githubusercontent.com/1011612/170379594-886402b8-0191-4961-bbf3-3b8fc23e33b3.MOV

**Comment by jamieoo** [comment] 2022-05-26 12:09
> We were unable to reproduce the issue on v101.0 (9619) or 9000 (9738). 
> 
> 
> 
> @koobs @jamieoo could you please post a video of the issue?

https://user-images.githubusercontent.com/19867593/170485143-779053c0-f1c5-4f34-a32b-2b19512a2c35.MOV

**Comment by data-sync-user** [comment] 2022-05-27 22:45
➤ Nishant Bhasin commented:

!Screen Shot 2022-05-27 at 6.43.42 PM.png|width=58.33333333333333%!

**Comment by data-sync-user** [comment] 2022-05-27 22:48
➤ Nishant Bhasin commented:

It seems like this crash is happening due to memory pressure and is not directly related to pdf. Since the system cannot handle pressure we get memory warnings and app crashes. 

It’ll require more investigation to know exactly where the crash is happening but one such place is SDWebImage which is allocating close to 2GB of memory on a fresh install when a user visits a pdf page. This is concerning and calls for further digging in that area.

!Screen Shot 2022-05-27 at 6.43.42 PM.png|width=58.33%!

**Comment by koobs** [comment] 2022-05-29 00:51
@nbhasin2 Can we add some logging that might prove useful for isolation? I've perused logs copied to the application container and could not see anything interesting, but would he happy to provide them

**Comment by nbhasin2** [comment] 2022-05-30 14:30
@koobs will look into adding logging although a first step would be to try and isolate SDWebImage cache and run the app. Ideally, the app shouldn't allocate 2+GB of memory on startup. I also saw another instance of memory leak with WKWebview but will chase that after SDWebImage lead. 

Unfortunately device logs might not have everything we need here.

**Comment by nbhasin2** [comment] 2022-05-30 19:38
Spent some more time in this area and I see the issue here. It's not a straightforward fix but I'll try to keep it brief in my explanation below: 

Due to heavy download of favicons / images etc. it creates memory pressure in general which iOS can handle on App Startup. However, we use SDWebImage which creates cache directory and manages downloads of images. This all seems normal until we visit website(s) and start loading PDFs or any heavy document(s). This on top SDWebImage's caching mechanism causes an overall mem pressure and crashes the app.

NOTE: Not all PDFs are made the same. PDFs can get complicated when they are joined. Some small PDFs can be heavy to load whereas other big ones can be easy to load. Hence not every PDF loading will cause a crash.

For example below is app startup on iPhone 11 pro which has a max 4GB ram. 
When a user loads a pdf on startup then with all the image loading it causes a mem spike and hence the crash. The amount of mem allocated is close to 4GB (see below)

![image](https://user-images.githubusercontent.com/8919439/171046676-c646bf42-a701-478f-b488-034d374b8cfd.png)

I did some temporary cleanup and disabled parts of SDWebImage options and running the app with the same PDFs mentioned above I get around 40MB which is very acceptable.  

![image](https://user-images.githubusercontent.com/8919439/171047270-c7f197df-5108-476e-8868-1e0983d24ed4.png)

more investigation to be continued...

**Comment by nbhasin2** [comment] 2022-06-02 03:57
I have been performing some more tests on my end and it seems SDWebImage's cache mechanism is causing this issue. 
Performing same operation with [Kingfisher](https://github.com/onevcat/Kingfisher) gives much better results where we barely go over 77MB with opening the same PDF. Again the issue is not related to PDF but how SDWebImage triggers its cache. 

I have also increased points for this ticket as there are some extra steps involved in making sure we have smooth transition to a new library

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/8919439/171549974-6dff21c6-3f37-477a-97f2-7e975d8eb425.png">

There aren't many places where this change is required so moving to Kingfisher is fairly straightforward. However,  SDWebImage builds its own disk cache and it is important to perform a slow transition and clear its cache while we move to Kingfisher. This is to ensure our users do not have a stale cache where Firefox iOS is taking up unnecessary space on the device.

Steps: 

1. Add Kingfisher library using SPM (https://github.com/onevcat/Kingfisher.git -> 7.2.2) 
2. Modify places in the app where we used SDWebImage and replace them with Kingfisher operations
3. Add a mechanism to clear both disk and memory cache for Kingfisher (Clear Data settings in Firefox iOS) 
4. Add operation to clear SD WebImage cache and add Glean report so we are able to track its progress and eventually remove the library in the next few releases 
5. Add mechanism to limit kingfisher cache to certain percentage of the device memory otherwise the disk cache can easily become bloated 
6. Add add some tests to measure memory pressure using the new Kingfisher library

**Comment by csuciu** [comment] 2022-06-30 16:55
Tested this issue on v103.0 (12108) and didn't noticed any issues in the areas mentioned above. Also didn't experienced any crashes while visiting different pdf files. Closing as fixed.

**Closed by csuciu** 2022-06-30 16:55 UTC
Labels: Bug 🐞

**Comment by koobs** [comment] 2022-06-30 23:22
> Tested this issue on v103.0 (12108) and didn't noticed any issues in the areas mentioned above. Also didn't experienced any crashes while visiting different pdf files. Closing as fixed.

Confirming both original repro PDF's no longer cause Firefox (Daylight 103.0 (12108)) to close

**Comment by koobs** [comment] 2022-06-30 23:22
Thank you for resolving @nbhasin2
