### ISSUE TITLE
Tab Images Pixelated

### ISSUE THREAD

**Issue by bkochendorfer** [mozilla-mobile/firefox-ios#14698] opened 2023-06-02 14:24 UTC
## Steps to reproduce

No particular steps here. Noticed this happening recently when I open a new I click the Tab Number button.

### Expected behavior

Existing tab images are crisp

### Actual behavior

Existing tab images are pixelated and distorted

### Device & build information
* Device: ? 
* Build version:  113.2 (31081)
* First seen version: Not sure but this just started happening in the last week or so.
Attachments: 
![img_3652](https://github.com/mozilla-mobile/firefox-ios/assets/1072933/46f2b063-0efc-4d48-8c79-f5f0c6b669cf)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6569)

**Comment by OrlaM** [comment] 2023-06-02 14:38
Duplicate of #13855, the fix will be release in v114.

**Closed by OrlaM** 2023-06-02 14:38 UTC
Labels: Bug 🐞
