### ISSUE TITLE
Crash on startup on iPhone and iPad (iOS 16.2)

### ISSUE THREAD

**Issue by StephanDziem** [mozilla-mobile/firefox-ios#12916] opened 2023-01-10 12:36 UTC
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).

## Steps to reproduce
Install Firefox on iPhone. Start up Firefox and sign in with Firefox account. Close Firefox. Start up Firefox.

### Expected behavior
Firefox should not crash after startup

### Actual behavior
Every time Firefox is started up, it crashes. Suspected cause: siging in with Firefox account and/or syncing.

### Device & build information
* Device: iPhone 13 Pro Max
* Build version: MLLE3ZD/A
* iOS 16.2

### Notes
Attachments: 
[CrashReports.zip](https://github.com/mozilla-mobile/firefox-ios/files/10382288/CrashReports.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5577)

**Comment by OrlaM** [comment] 2023-01-10 21:46
The fix will be released in version 110.

**Comment by data-sync-user** [comment] 2023-02-13 11:05
➤ Simion Basca commented:

We were unable to reproduce any crash on latest v110 (27761). Orla Mitchell should we move this to “Done”?

**Comment by StephanDziem** [comment] 2023-02-13 11:22
I noticed that the issue somehow already was fixed in v109. So with v109 I was able to sync again, without Firefox crashing.

**Comment by SimonBasca** [comment] 2023-02-13 11:24
Thanks for confirming @StephanDziem . I'll close this issue. Feel free to re-open if the issue is reproducible again.

**Closed** 2023-02-13 11:23 UTC
Labels: Crash
