### ISSUE TITLE
GleanPlumbMessaging: Unit Tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10601] opened 2022-04-27 19:36 UTC
Just do it!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4157)

**Comment by nishant2718** [comment] 2022-05-02 12:53
Closing b/c a duplicate of another Unit test on Messaging ticket.

**Closed** 2022-08-11 19:58 UTC
