### ISSUE TITLE
Multiple new tabs open when pressing [cmd + T]

### ISSUE THREAD

**Issue by wmorrel** [mozilla-mobile/firefox-ios#8869] opened 2021-07-17 17:18 UTC
## Steps to reproduce
* Press cmd + T on a Magic Keyboard using Firefox for iPad
* Two new tabs will open rather than one

### Expected behavior
* One new tab opens

### Actual behavior
* Two new tabs open

### Device & build information
* Device: iPad Pro 12.9-inch 5th generation
* Build version: Firefox Daylight 35.0 (5448)

### Notes
None

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2972)

**Comment by data-sync-user** [comment] 2021-07-19 21:27
➤ Daniela Arcese commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-2583 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2583|smart-link )

**Closed** 2021-07-20 07:05 UTC
Labels: Bug 🐞
