### ISSUE TITLE
FXIOS-842 ⁃ Night mode makes background to be white, making difficult to read text

### ISSUE THREAD

**Issue by SathyaseelanRamachandran** [mozilla-mobile/firefox-ios#7256] opened 2020-09-02 14:48 UTC
### Device & build information
* Device: iOS version 13.6
* Build version: 13.6.1
### Notes
Attachments: 
![firefox](https://user-images.githubusercontent.com/50044265/91998905-64b52500-ed6e-11ea-80cf-4d367c3615d5.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-842)

**Comment by dnarcese** [comment] 2021-03-25 16:51
Duplicate of #5772

**Closed by dnarcese** 2021-03-25 16:51 UTC
Labels: Bug 🐞
