### ISSUE TITLE
Layout breaks in tabs tray after changing device orientation 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12699] opened 2022-12-15 11:10 UTC
## Steps to reproduce
1. Clean install the app
2. Open tabs tray 
3. Tap on Sybced tabs
4. Change orientation to landscape 
5. Tap on Private Browsing mask
### Actual behavior
- layout breaks 
### Device & build information
* Build version: 109 24441
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/207844439-961e2513-03fe-4023-838d-3bd9f97550fd.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5444)

**Comment by yoanarios** [comment] 2022-12-15 22:06
I briefly investigated this issue because I thought it was related to #12190 but is not I could trace it back to v107. Inspecting XCode Debug View Hierarchy I could see the issue is the view from the child ViewController either `RemoteTabsPanel` or `GridTabViewController` is not updating the frame on rotation.

**Comment by data-sync-user** [comment] 2022-12-20 18:20
➤ Yoana Rios Diaz commented:

Another issue related to iOS < 15 the top and bottom cell are not visible

**Comment by data-sync-user** [comment] 2023-01-30 15:06
➤ Catalin Suciu commented:

This issue is verified as fixed on latest v9000.

**Closed by data-sync-user** 2023-01-30 15:06 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2023-02-15 12:00
➤ Simion Basca commented:

Verifying as fix on v111 (28148)
