### ISSUE TITLE
bug with IOS Firefox APP with Voice Over

### ISSUE THREAD

**Issue by lockwoodnd** [mozilla-mobile/firefox-ios#9944] opened 2022-02-03 20:25 UTC
I am blind and thus use the built-in screen reader for IOS. THis happens on iPhone 11 Pro Max and iPhone 12Pro Max. it happens on all versions of IOS 15 and most up-to-date version of Firefox App. it has happened ever since i downloaded the firefox app which was many versions ago. so it is not unique to latest App version.  

Behavior: use iPhone or other IOS device, turn on voice over in settings/accessibility/voice over/ copy a link and paste it into Firefox app on IOS. it says "Firefox copied from [app name]" over and over endlessly. it makes app unusable. 

Chrome and Safari only say it once then stop. Please fix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3717)

**Comment by SimonBasca** [comment] 2022-02-04 09:09
Hello @lockwoodnd, thanks for reporting this issue. We've recently fixed this issue on latest main https://github.com/mozilla-mobile/firefox-ios/commit/228b77b9a89f133417cb748fcf720fb01e6b6f1a. Currently when VoiceOver is active and the “Firefox pasted from [app]" or "Paste occurred", voiceover will only say the message once.This should go in the next release.

Marking the issue as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/7476

**Closed by SimonBasca** 2022-02-04 09:09 UTC
Labels: Bug 🐞
