### ISSUE TITLE
FXIOS-1919 ⁃ [regression] [iPad] Cannot create/add a new tab when in floating window mode

### ISSUE THREAD

**Issue by DCzajkowski** [mozilla-mobile/firefox-ios#8649] opened 2021-06-06 20:40 UTC
## Steps to reproduce

Open any app. Drag Firefox from the dock to become a floating window.
 
### Expected behavior

The UI fits the window and the "add new tab" button is visible.

### Actual behavior

A "plus" icon to add a new tab is not visible.

### Device & build information
* Device: iPad
* Build version: Firefox Daylight 34.0 (4920)

### Notes
Attachments: 
![EA70D50D-F0E2-47FF-B8E3-939E671C9C95](https://user-images.githubusercontent.com/4501047/120939371-162b2180-c718-11eb-8a5a-8176584affd1.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1919)

**Comment by SimonBasca** [comment] 2021-06-07 09:08
Confirming that this is an issue but only in this view. After stretching the view for Firefox to split screen the buttons are visible.

**Comment by dnarcese** [comment] 2021-06-08 20:47
Duplicate of #8545

**Closed by dnarcese** 2021-06-08 20:47 UTC
Labels: Bug 🐞
