### ISSUE TITLE
FXIOS-1596 ⁃ Tab titles disappear after a while

### ISSUE THREAD

**Issue by Lorenzos24** [mozilla-mobile/firefox-ios#8153] opened 2021-03-16 08:14 UTC
## Steps to reproduce
1. Open at least 5-10 tabs;
2. Leave Firefox in background and use different apps;
3. After reopening Firefox, some of the previously-opened tabs don't show titles anymore. 

### Expected behavior
I expect to continue to see tab titles after reopening Firefox, like it happens on Safari, Chrome and Microsoft Edge.

### Actual behavior
Tab titles aren't shown. This makes impossible to use "Tab research" function (on the top of the tabs page) and it makes harder to find the right synced tab on other devices, as the link is shown instead of the tab title in the "Synced tab" section of Firefox for desktop Library. 

### Device & build information
* Device: iPhone SE 2020
* Build version: Firefox Daylight 32.1 (3961)
### Notes
Attachments: 
Visualization of open tabs (some of the tabs don't show anything, some of them show the link instead of the title)
![IMG_2959 2](https://user-images.githubusercontent.com/80746406/111276370-8eada500-8637-11eb-93c3-57eb52565388.jpg)

Visualization of synced tab on other devices (actually Firefox for Mac 86.0.1)
![Schermata 2021-03-16 alle 08 55 01](https://user-images.githubusercontent.com/80746406/111276411-9bca9400-8637-11eb-804d-511b6ae0ab5b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2777)

**Comment by SimonBasca** [comment] 2021-04-26 12:24
Note: Still reproducible on v34.0 (4551) in both Chronological tabs and Tabs Tray

**Comment by dnarcese** [comment] 2021-08-05 18:33
Duplicate of #8942

**Closed by dnarcese** 2021-08-05 18:33 UTC
Labels: Bug 🐞, P2
