### ISSUE TITLE
FXIOS-1547 ⁃ Reader view icon disappears after use

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#8074] opened 2021-03-04 04:57 UTC
## Steps to reproduce
1. Open a website 
2. Select reader view
3. Deselect reader view

### Expected behavior
The reader view icon is visible and the appearance controls go away 

### Actual behavior
The reader view icon disappears and the appearance controls remain at the top of the screen

### Device & build information
* Device: iPhone 12 Pro, iOS 14.4
* Build version: Firefox Daylight 32.0 (3841)

### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/43795363/109913583-e2051800-7c73-11eb-91f8-80f295a030d4.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1547)

**Comment by SimonBasca** [comment] 2021-03-04 08:41
This is a duplicate of #7566.

**Comment by eliserichards** [comment] 2021-03-31 23:33
I am no longer able to reproduce this on Firefox Daylight 33.0 (4119)

**Comment by SimonBasca** [comment] 2021-04-01 08:14
Closing as works for me. Let's re-open if the issue is reproduced again.

**Closed by SimonBasca** 2021-04-01 08:14 UTC
Labels: Bug 🐞, P2
