### ISSUE TITLE
[intermittent] Blank Screen is displayed when launching Firefox

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#23259] opened 2024-11-20 14:09 UTC
**Steps**
1. Launch Firefox.
2. Observe the screen.

**Expected behavior**
FF should launch without any issues and the homescreen should be displayed.

**Actual behavior**
Firefox launches and a blank page is displayed.

**Device & build information**

* Device: iPhone 15 Pro (18.2)
* Build version: v9000 (47809) and main.
* First seen version: N/A

https://github.com/user-attachments/assets/12aed079-c0e2-4e9f-8eeb-e852ebc860fd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10622)

**Comment by abodea** [comment] 2024-11-20 14:11
We had another scenario:
Having FF in the background for a longer time > Update to the latest v9000 > Open Firefox > and a blank home page is displayed. 

![image](https://github.com/user-attachments/assets/0c637e06-38b3-4d7f-a25d-f31f8a53f2e6)

**Comment by data-sync-user** [comment] 2024-11-20 19:12
➤ Matt Reagan commented:

I’ve been testing a variety of launch flows, including various upgrade or install paths of the v9000 (47809) build. So far I can’t replicate the blank homepage issue. I’m testing primarily on an iPhone 12 mini.

**Comment by data-sync-user** [comment] 2024-11-29 18:16
➤ Isabella commented:

Matt Reagan I may have accidentally got this reproducing on my iOS 18 sim today while working on another bug that’s blocking 133.1 release. After I cleaned derived data + reset my sim it went away though, so there’s a chance maybe I just had bad state…

But from what I could see, it looked like Denying unprivileged request was getting triggered because the uuid was missing from the internal home URL (so isAuthorized was returning false). 

Not sure how I could get into a state like this, but it happened every single time on launch once it was occurring, until I did the clean. 

At the time, I was in the middle of populating webpage history so I could work on a history panel scrolling crash, so I was just clicking through a bunch of wikipedia links. And then I think I tried opening a new tab and going to another website, then checking history again. Then I must’ve gone back to home, tried relaunching, and saw the blank homepage bug. It was 100% reducible when I tried relaunching several more times to a selected homepage. It also occurred if I opened another new tab, selected it, and restarted the app. So it was occurring with all home tabs while in this state. 🤔 

!Screenshot 2024-11-29 at 11.48.50 AM.png|width=2672,height=1454,alt="Screenshot 2024-11-29 at 11.48.50 AM.png"!

**Comment by data-sync-user** [comment] 2024-11-29 18:26
➤ Isabella commented:

Ugh, just after I typed that, it started happening again!! But it’s only happening to tab 3 in this video (not tab 4, for example). It’s the exact same code path though.

I’d have to dig into the code more to understand why a tab might only have internal://local/about/home#panel=0 for the URL instead of the UUID as well so it’s an authorized internal URL (like internal://local/about/home?uuidkey=8F0792DC-32F8-4EC5-9F38-BB279D75DF23#panel=0)

!blank homescreen tab 3.mp4|width=41.66666666666667%,alt="blank homescreen tab 3.mp4"!

**Comment by data-sync-user** [comment] 2024-11-29 22:47
➤ Laurie Marceau commented:

I encountered the bug this afternoon Isabella is mentioning, and went on to debug this a bit. As mentioned in this thread ( https://mozilla.slack.com/archives/C05C9RET70F/p1732903408628029 ) by Sorin, the bug started happening after the[ audio/leak webview fix|https://mozilla.slack.com/archives/C05C9RET70F/p1732906963140739?thread_ts=1732903408.628029&cid=C05C9RET70F] (issue is here ( https://mozilla-hub.atlassian.net/browse/FXIOS-10335 ), PR is here ( https://github.com/mozilla-mobile/firefox-ios/pull/23243/files )).

I opened a small PR here ( https://github.com/mozilla-mobile/firefox-ios/pull/23495 ) with some explanation of my attempt. Let’s discuss next week about it!

**Comment by data-sync-user** [comment] 2024-12-03 00:00
➤ Matt Reagan commented:

Thanks Laurie Marceau & Isabella for digging into this and for adding the notes. Sending to Laurie since it looks like there is a PR up.

**Comment by S3od22** [comment] 2024-12-03 01:25
‫أُرسلت من الـ iPhone‬‫في 2024-12-03 الساعة 3:01 ص، كتب/كتبت ‏Data Sync User ***@***.***>:‬﻿
➤ Matt Reagan commented:
Thanks Laurie Marceau & Isabella for digging into this and for adding the notes. Sending to Laurie since it looks like there is a PR up.

**Comment by data-sync-user** [comment] 2024-12-10 09:40
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v134 (48607), with iPhone 15 (17.6).

**Closed** 2024-12-10 09:40 UTC
Labels: Bug 🐞, S3
