### ISSUE TITLE
Unable to exit password screen

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#13454] opened 2023-03-03 19:43 UTC
## Steps to reproduce
1. Tap hamburger 🍔  menu and tap _Passwords_.
2. Enter iPhone passcode.

### Expected behavior
There should be a way to exit the password page.

*Workaround*: Access the same page via 🍔 ➡️ _Settings_ ➡️ _Password_. Now we've the ⬅️ _Settings_ link from the navigation bar.
![Simulator Screen Shot - iPhone 14 - 2023-03-03 at 14 38 11](https://user-images.githubusercontent.com/1740517/222811159-3af44301-9000-4a68-84be-2d5f28beec60.png)

### Actual behavior
There's no "Done" or "⬅️ Settings" from the navigation bar.
![Simulator Screen Shot - iPhone 14 - 2023-03-02 at 17 58 04](https://user-images.githubusercontent.com/1740517/222810168-cdfb9f3b-d834-4781-a123-34dc831b0e85.png)

### Device & build information
* Device : iPhone 14 iOS simulator
* Build version: 111.0 (1)
* First seen version: Feb 28
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5909)

**Comment by abodea** [comment] 2023-03-06 08:25
Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13447.

**Closed by abodea** 2023-03-06 08:25 UTC
Labels: Bug 🐞
