### ISSUE TITLE
Uneven horizontal margins on "Customize Homepage" button 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19017] opened 2024-03-05 15:26 UTC
## Steps to reproduce
1. Navigate to the homepage screen
1. Inspect the "Customize Homepage" button

### Expected behavior
Margins are equal on the leading and trailing edges of the "Customize Homepage" button

### Actual behavior
The leading edge margin has more spacing than the trailing edge margin on the "Customize Homepage" button

### Device & build information
* Device: iPhone 15 Pro, iPad Air (5th gen) (iOS / iPadOS 17.2)
* Build version: 125.0 (1)
* First seen version: N/A

### Notes
* Most noticeable on iPad

|iPhone|iPad|
|----|----|
|![width=1179,height=2556](https://github.com/mozilla-mobile/firefox-ios/assets/15353801/0a19e981-708a-44e9-8eef-4eeecf67ed8e)|!5th|thumbnail!|

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8552)

**Comment by cyndichin** [comment] 2024-03-05 15:27
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/18995 to sync with JIRA

**Comment by data-sync-user** [comment] 2024-03-07 13:48
➤ Cyndi Chin commented:

Please confirm that the margins are now equal, thank you!

**Comment by data-sync-user** [comment] 2024-03-12 16:46
➤ Alina Moldovan commented:

Validated this issue using v9000 (39713) and iPhone 14+ (16.0.3), iPhone 15+ (17.4), Ipad Pro 4th Gen (17.2). 

The margins are equal now

**Comment by data-sync-user** [comment] 2024-03-20 09:42
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone 15 (17.0) and iPad Air 3rd gen (17.3).

**Closed** 2024-03-20 09:42 UTC
Labels: Contributor OK, Bug 🐞, Contributor Fix
