### ISSUE TITLE
Theming incorrectly switches from "Light" to "Dark" after closing FF/putting FF in background

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18421] opened 2024-01-26 14:36 UTC
**Steps to reproduce**
1. Go to FF settings-->Theme--> turn off "Use System Light/Dark Mode" toggle
2. Change the theme to "Light"
3. Background or force close the app, reopen it and observe the theming.

**Expected behavior**
The theming is still "Light".

**Actual behavior**
The theming changes to "Dark".

**Device & build information**
* Device: iPhone 15(17.0)
* Build version: v123(38120). Also on v9000 (38130).
* First seen version: v123(38120)

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/bfaaa74b-f5ab-4c5e-b15d-447b55334f49

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8309)

**Comment by data-sync-user** [comment] 2024-01-26 19:33
➤ Roux Buciu commented:

The cause of this is seriously convoluted!

**Comment by data-sync-user** [comment] 2024-01-31 14:32
➤ Alina Moldovan commented:

Validated as fixed using FF v123 (38283) and iPhone 15+ (17.0.2)

**Comment by data-sync-user** [comment] 2024-02-05 08:32
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123(38491), with iPhone 15 (17.0).

**Closed by data-sync-user** 2024-02-05 08:32 UTC
Labels: Bug 🐞, S2
