### ISSUE TITLE
Amazon Sponsored tile is still available after setting Amazon as default search engine

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10773] opened 2022-05-17 09:19 UTC
v9000(9585)

Prerequisites:

* Make sure you have Amazon as sponsored tile available.

Steps:

1. Open Firefox.
1. Go to Settings -> Search and change the default search engine to Amazon.
1. Return to the homepage and observe the Top Sites area.

Expected:

* Amazon tile should not be displayed because the default search engine was changed to Amazon.

Actual: 

* The tile is still displayed.

Note: 

1. On Desktop, Amazon tile is not displayed when the default search engine is changed to Amazon.
1. This issue existed on Fenix too and was fixed recently fixed. See https://github.com/mozilla-mobile/fenix/issues/24262.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4251)

**Comment by data-sync-user** [comment] 2023-07-06 12:36
➤ Alina Moldovan commented:

Validated this issue using v116 (32373) and iPhone 14+ (16.0.3). The issue still reproduces please see the screenshot: 

!Skype_Picture_14.jpeg|width=428,height=926!

Nishant Patel since the bug still reproduces I moved the status from ‘QA needed’ to ‘In Progress’.

**Comment by data-sync-user** [comment] 2023-07-12 12:46
➤ Alina Moldovan commented:

Revalidated this issue using v9000 (32586) and  v116 (32618). The issue still reproduces 

Nishant Patel Changing the status to “in progress“

**Comment by data-sync-user** [comment] 2023-07-12 13:53
➤ Nishant Patel commented:

Hi Alina! Could you write the STR? I don’t see this issue happening on main .

**Comment by data-sync-user** [comment] 2023-07-12 14:19
➤ Alina Moldovan commented:

[^RPReplay-Final1692281491.MP4]

**Comment by data-sync-user** [comment] 2023-07-12 14:21
➤ Alina Moldovan commented:

Nishant Patel I added the video below. 

steps to reproduce are: 

  1. clean install FF 
  2. change the default search engine to amazon
  3. check the top sites area on the homepage

**Comment by data-sync-user** [comment] 2023-07-13 13:56
➤ Nishant Patel commented:

Just a clarification based on the video - the AMZN sponsored tile won’t appear. But if AMZN is preexisting in the top sites source, then THAT one appears. 

We can fix that in this ticket.

**Comment by data-sync-user** [comment] 2023-07-13 14:43
➤ Laurie Marceau commented:

Nishant Patel Only sponsored tiles should be filtered, so I think this is the wanted behavior. 

Frencency top sites, pinned tiles or default top sites should not be filtered.

**Comment by data-sync-user** [comment] 2023-07-14 12:52
➤ Alina Moldovan commented:

Laurie Marceau  Nishant Patel  thank you for the details. 

Could you please help me to trigger the sponsored tiles, to be able to regress this issue?  Even if the sponsored tires are checked in setting - homepage they don’t appear in shortcuts area. 

Also I check the same functionality on FF desktop and it seems that amazon tile is filtered even if it is not a sponsored tile: 

!Mozilla Firefox 2023-07-14 15-48-37.mp4|width=1600,height=928!

**Comment by data-sync-user** [comment] 2023-07-14 13:48
➤ Laurie Marceau commented:

Sponsored tiles will appear differently depending on the region you’re in. You can maybe try with a VPN to be in a different region 🤔 I’ll ping Daniela Arcese on this issue for the comparison with Desktop.

**Comment by data-sync-user** [comment] 2023-07-14 16:30
➤ Daniela Arcese commented:

Let’s leave it as is

**Comment by data-sync-user** [comment] 2023-08-14 12:15
➤ Alina Moldovan commented:

Managed to validate this issue using the VPN connection and FF v117 (33495)

I can confirm that Expedia sponsored tile was filtered out when Expedia was set as default search engine. 

For Amazon, the sponsored tile was replaced by Amazon tile, so it is still available in shortcuts list. 

Laurie Marceau Daniela Arcese  if this behavior is ok with you I can close this issue. 

!IMG_0360.MOV|width=33.333333333333336%!

!IMG_0361.MOV|width=33.333333333333336%!

**Comment by data-sync-user** [comment] 2023-08-14 16:02
➤ Laurie Marceau commented:

Looks good to me Alina Moldovan !

**Closed** 2023-08-17 12:23 UTC
