### ISSUE TITLE
[Tabs Groups][iPad] The 1st tab from the grouped tabs is not selected after tapping on in it

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9515] opened 2021-11-17 14:41 UTC
## Steps to reproduce
1. Enable grouped tabs
2. Type "video" in the URL and hit go
3. Type "video" in the URL and hit go
4. Open tabs tray
5. Tap on the 1st tab from the grouped tabs
6. Open tabs tray
### Expected behavior
- The 1st tab from the grouped tabs should be selected
### Actual behavior
- The 1st tab from the grouped tabs is not selected
### Device & build information
* Device: iPad Pro (14.8)
* Build version: v95 (6631) and 9000 (6746)
### Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7555475/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3436)

**Comment by dnarcese** [comment] 2021-11-18 17:44
@SimonBasca can you reproduce this when the two tabs are different? It is hard to tell what is happening here because the tabs are exactly the same. It's possible this isn't a bug, and the tabs in the tab tray are just being rearranged.

**Comment by SimonBasca** [comment] 2021-11-18 18:01
@dnarcese if the tabs are not the same they will not be displayed in the the same group. You can notice that in tabs tray the selection moves from the second tab to the first one but in tab tray the second tab remains selected.

**Comment by data-sync-user** [comment] 2021-12-02 17:59
➤ Daniela Arcese commented:

This should be fixed by https://mozilla-hub.atlassian.net/browse/FXIOS-3458 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3458|smart-link )

**Comment by data-sync-user** [comment] 2021-12-24 11:43
➤ Simion Basca commented:

Verified fix on main 627116c214d9d74bb5a391f59999cd4eb1f68eee

**Closed by data-sync-user** 2021-12-24 11:43 UTC
Labels: Bug 🐞
