### ISSUE TITLE
Login/Password Edits Not Reflected in View

### ISSUE THREAD

**Issue by kelvins64** [mozilla-mobile/firefox-ios#10213] opened 2022-03-14 03:29 UTC
## Steps to reproduce
Passwords Menu --> Select a saved login --> Edit
Make a modification to the Username or Password field
Press Done

### Expected behavior
Changes are reflected in the view.

### Actual behavior
Changes appear to revert to their original values; however, returning to the "Logins & Passwords" menu and revisiting the login entry shows that changes do, in fact, persist. 

### Device & build information
* Device: iPhone 12 iOS 15.3.1
* Build version: Firefox 98.0
### Notes

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3899)

**Comment by gutley** [comment] 2022-03-14 10:02
Just checked here and the description is not quite right. For me the underlying info does change, but the view is out of date with reality. Closing the 'Logins & Passwords" view shows the correct data.

**Comment by gutley** [comment] 2022-03-14 10:11
Here's a screen recording from the Simulator, nut the same happens on real device

https://user-images.githubusercontent.com/2040690/158151335-758ea3c7-59e7-43ed-a386-a8801117ccd5.mov

g

**Comment by gutley** [comment] 2022-03-14 10:47
I can see what is happening here:

``` swift
    @objc func doneEditing() {
        isEditingFieldData = false
        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .edit, target: self, action: #selector(edit))

        defer {
            // Required to get UI to reload with changed state
            tableView.reloadData()
        }

        // Only update if user made changes
        guard let username = usernameField?.text, let password = passwordField?.text else { return }
        
        guard username != login.decryptedUsername || password != login.decryptedPassword else { return }

        let updatedLogin = LoginEntry(
            fromLoginEntryFlattened: LoginEntryFlattened(
                id: login.id,
                hostname: login.hostname,
                password: password,
                username: username,
                httpRealm: login.httpRealm,
                formSubmitUrl: login.formSubmitUrl,
                usernameField: login.usernameField,
                passwordField: login.passwordField
            )
        )

        if updatedLogin.isValid.isSuccess {
            _ = profile.logins.updateLogin(id: login.id, login: updatedLogin)
        }
    }
```

By the time `reloadData` is called, the updated details haven't actually been updated yet as `updateLogin` happens async, so its just displaying the old value.

My suggestion would be to update the table's internal data to the new value prior ro `updateLogin` and then listen out for a failure to update and then restore the truth if something went wrong.

You could try to listen out for success and then reload data, but if there is any user-perceivable delay un updating then it will look weird with he old value hanging around.

I have used the 'assume the best, cater for the worst` style of UI updating in the past and it works well in keeping the ui responsive.

**Comment by kelvins64** [comment] 2022-03-14 18:20
Thanks for looking in to this. You're right, it does turn out that the view just isn't updating. I will update the description to reflect this.

**Comment by SimonBasca** [comment] 2022-03-16 08:59
This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/8860. I am closing this one in favor of https://github.com/mozilla-mobile/firefox-ios/issues/8860 as that one has the proper labels set. 
@gutley I've left a comment withe the details of your investigation. Thanks for looking into this.

**Closed by SimonBasca** 2022-03-16 08:59 UTC
Labels: Bug 🐞
