### ISSUE TITLE
App crashes when closing all tabs.

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#17130] opened 2023-11-02 09:49 UTC
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).

## Steps to reproduce
Open the app.
Open at least 2 tabs.
Go to open tabs screen and select to close all the tabs.

### Expected behavior
The app should close the tabs successfully. 
### Actual behavior
The app crashes. See logs attached.

### Device & build information
* Device: iPhone 14 Pro, iOS 17.0
* Build version: 121.0(1)

### Notes
Issue is not reproducing all the time.
[crash report.pdf](https://github.com/mozilla-mobile/firefox-ios/files/13237216/crash.report.pdf)

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7683)

**Comment by abodea** [comment] 2023-11-02 09:55
Hello, please note that on the TestFlight build v9000 (latest nightly) I was not able to reproduce this issue with iPhone 13 Pro (15.7.1), iPhone 14 (17), and iPhone SE (16.6).

**Comment by dnarcese** [comment] 2023-11-02 18:55
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/16810

**Closed by dnarcese** 2023-11-02 18:55 UTC
Labels: Crash, eng:bug-auto-found, S1
