### ISSUE TITLE
FXIOS-1897 ⁃ Audio recording not supported in Firefox

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8598] opened 2021-05-28 13:13 UTC
## Steps to reproduce
1. Launch latest main branch fa52d3d9be4
2. Go to vocaroo.com.
3. Tap on the "recording button"
### Expected behavior
- Permission dialog to use microphone should be displayed.   
### Actual behavior
- Unsupported browser error message is displayed. 
### Device & build information
* Device: iPhone SE 14.4
* Build version: main branch fa52d3d9be4
### Notes
- Working in Safari.
Attachments: 
![image](https://user-images.githubusercontent.com/32130829/119989258-a60df480-bfcf-11eb-8f14-d03103a635ac.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1897)

**Comment by dnarcese** [comment] 2021-05-28 19:16
@SimonBasca can you try going to System Settings > Firefox and change the Microphone permission there? This might be an issue because that permission has previously been denied.

**Comment by SimonBasca** [comment] 2021-06-03 18:40
Retested on latest main bfb2bb. When I go to Fennec in iOS settings there are no microphone right that can be enabled. 

![image](https://user-images.githubusercontent.com/32130829/120695256-da901d80-c4b3-11eb-8128-0589253c98dc.png)

Also note that on v34.0(4920) this issue is not reproducible. I can't say for sure if this is a bug on the main branch or it something that cannot be enabled for local builds.

**Comment by data-sync-user** [comment] 2021-06-11 10:16
➤ Simion Basca commented:

Closing as this issue is not reproducible on v34.1 (5146)

**Closed** 2021-06-11 10:16 UTC
Labels: Bug 🐞
