### ISSUE TITLE
Tabs sent to iPhone via Sync not showing URL in urlbar.

### ISSUE THREAD

**Issue by mhoye** [mozilla-mobile/firefox-ios#11882] opened 2022-09-12 14:00 UTC
## Steps to reproduce

Starting from my desktop, with Sync enabled on desktop Nightly  and my iPhone,  I right click a tab and choose send to device -> my phone.

### Expected behavior

The tab arrives, looking and acting like every other tab.

### Actual behavior

The tab arrives and is displayed correctly, but the URL bar isn't filled - even on a reload - so I cannot copy and paste the URL as I'd expect.

### Device & build information

* Windows 11 desktop + Firefox Nightly, all up to date.
* iPhone 10 and current Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4919)

**Comment by dnarcese** [comment] 2022-09-13 18:30
@mhoye is this happening for you everytime or only sometimes?

**Comment by data-sync-user** [comment] 2022-11-30 21:23
➤ Yoana Rios Diaz commented:

Tested with Firefox Desktop Version 107.0.1 and Nightly Version 109.0a1 (2022-11-30) and I couldn’t reproduce the tab arrived and URL is filled in URL Bar while open tab from notification with app on background and foreground.

Simion Basca can you check if you can reproduce this issue?

**Comment by SimonBasca** [comment] 2022-12-19 13:56
I was unable to reproduce the issue on the latest beta v109 (24458) or latest main 9000 (24587).

**Comment by csuciu** [comment] 2022-12-22 19:16
@mhoye are you still able to reproduce this issue using the latest builds?

**Comment by SimonBasca** [comment] 2023-01-31 10:06
I was unable to reproduce on nightly v9000 (26871) on iPhone 12 Pro (16.2). Let's close this for now and re-open if the issue reproducible again

**Closed by SimonBasca** 2023-01-31 10:06 UTC
Labels: Bug 🐞
