### ISSUE TITLE
Unable to delete inactive tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8922] opened 2021-07-29 12:34 UTC
## Steps to reproduce
1. Have some tabs in the Inactive list
2. Swipe left to close it (similar to behaviour in the History panel)
### Expected behavior
- User should be able to close tab via swipe gesture.
### Actual behavior
- There is no possibility to close the inactive tab as mentioned in [FXIOS-1738](https://mozilla-hub.atlassian.net/browse/FXIOS-1738).
### Device & build information
* Device: iPhone Xr (14.5.1)
* Build version: 36.0 (5673)
### Notes
Attachments:

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3010)

**Comment by data-sync-user** [comment] 2021-07-29 16:40
➤ Daniela Arcese commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-3006 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3006|smart-link )

**Comment by dnarcese** [comment] 2022-05-26 19:23
Closing as this is now implemented

**Closed by dnarcese** 2022-05-26 19:23 UTC
Labels: Bug 🐞
