### ISSUE TITLE
FXIOS-1066 ⁃ Firefox crashes at startup on v29.0 on iOS 14.0.1

### ISSUE THREAD

**Issue by lolo2bdx** [mozilla-mobile/firefox-ios#7508] opened 2020-10-17 17:58 UTC
## Steps to reproduce
Launch Firefox

### Expected behavior
After a short waiting time (during which the Firefox logo is displayed), Firefox is correctly launched and usable.

### Actual behavior
After a short waiting time (during which the Firefox logo is displayed), Firefox crashes.

### Device & build information
* Device: iPhone SE (2016) with iOS 14.0.1
* Build version: v29.0
    1. Notes
Attachments: a log of the crash 
[Client-2020-10-17-124746.zip](https://github.com/mozilla-mobile/firefox-ios/files/5396218/Client-2020-10-17-124746.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1066)

**Comment by lolo2bdx** [comment] 2020-10-17 21:41
I have reinstalled Firefox, while preserving the data on the iPhone, and the problem remains.

**Comment by athomasmoz** [comment] 2020-10-23 20:24
@lolo2bdx Thank you for logging. Does this only happen directly after upgrade or does it happen every time you open the app now that you're on v29?

**Comment by lolo2bdx** [comment] 2020-10-26 12:21
Hi @athomasmoz and thank you for your reply.

Since I've updated to v29, it happens every time I open then app.
And it occurs if the app was in background of if this app was not launched.

**Comment by athomasmoz** [comment] 2020-10-26 15:57
@SimonBasca Do you have the same device to try it on? I can't reproduce, but I'm seeing reviews with this same concern come in for v29

**Comment by nbhasin2** [comment] 2020-10-26 17:32
Hi, @lolo2bdx could I request crash id from Firefox App.

- Open Firefox 
- Settings 
- Under About section tab on `Firefox Daylight...` 5 times
- After menu expands scrolldown and copy `Sentry ID` by just tapping on it. 

Its a log shot because Firefox crashes but this ID will give me more ways to further debug this issue.

**Comment by lolo2bdx** [comment] 2020-10-26 21:02
Hi @nbhasin2 ,
I am sorry, I could not go the Settings of the Firefox app, because the app crashes before the bottom bar appears.
Is there another way to get this ID ?

**Comment by SimonBasca** [comment] 2020-10-27 15:53
We've started testing this. So far we haven't found STR and were unable to reproduce it. Testing on iPhone SE (iOS 14.1).

**Comment by lolo2bdx** [comment] 2020-10-28 13:56
If it can help, I can add some elements.
First, I have tested to launch the Firefox app on iOS 14.1, and the problem remains.

Then, my iPhone has the following characteristics : 
- 57.4 GB of 59.6 are used
- the size of the "documents and data" of the Firefox app is 720 MB (yes, that's a lot of open tabs :-) )

Maybe can I improve the size of the free space (by removing some apps or music) to see if this has an effect ?

**Comment by athomasmoz** [comment] 2020-10-28 22:43
@lolo2bdx Thank you for sharing all the extra info to help us resolve this issue. I have one more question for you, do you remember if you were logged in to Firefox before you updated and started experiencing this issue?

**Comment by lolo2bdx** [comment] 2020-10-30 00:40
Hi @athomasmoz, and no, I was not logged in to Firefox. Sorry.

**Comment by lolo2bdx** [comment] 2020-10-30 00:43
I've done another test : removing all the music from my iPhone (which represents 17.7 GB).
So, now, I have 39.7 GB of 59.6 used.

And the problem remains : Firefox still crashes at startup.

**Comment by lolo2bdx** [comment] 2020-10-30 00:49
Another element that may help you : as far as I remember, when I updated Firefox to v29.0, Firefox was in background.
And before putting Firefox in background, I was in the middle of a long Youtube video.
I hope it can help you.

**Comment by lolo2bdx** [comment] 2021-03-01 00:27
Since the v32.0, it does not crash anymore at startup ! 
So it looks that this problem is solved !

**Comment by SimonBasca** [comment] 2021-03-01 08:47
Thanks for the feedback @lolo2bdx. I'll close this issue as fixed on v32.0 3841.

**Closed by SimonBasca** 2021-03-01 08:47 UTC
Labels: Bug 🐞, Needs QA, P1
