### ISSUE TITLE
Crashing when bookmarks are opened 

### ISSUE THREAD

**Issue by naynono** [mozilla-mobile/firefox-ios#12329] opened 2022-11-06 21:34 UTC
## Steps to reproduce
Open app, tap on bookmarks (star) 

### Expected behavior
App should show bookmarks, let me scroll through them and open bookmarked sites

### Actual behavior
App shows bookmarks and crashes immediately 

### Device & build information
* Device: apple iphone 11
* Build version: iphone software 15.6.1., firefox ios 106
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5216)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5216

**Comment by lmarceau** [comment] 2022-11-07 15:37
@naynono Thanks for opening this issue. Trying to understand a bit more this issue, could you tell us if you're logged in a Firefox Sync account or not?

**Comment by naynono** [comment] 2022-11-07 15:48
> @naynono Thanks for opening this issue. Trying to understand a bit more this issue, could you tell us if you're logged in a Firefox Sync account or not?

Im not logged into a sync account.

**Comment by dnarcese** [comment] 2022-11-10 20:27
duplicate of #12093

**Closed by dnarcese** 2022-11-10 20:27 UTC
Labels: Bug 🐞
