### ISSUE TITLE
Always open external links directly

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#9720] opened 2022-01-03 19:55 UTC
### User Problem
> Currently if it's been more than 4 hours since I've used Firefox and I click on a link from an external app, Firefox opens but does not take me to the requested site. Instead the homepage is displayed and the requested site is displayed in the Jump back in section. This is unexpected because no other web browser on mobile or desktop works like that and it's undesirable because it is confusing and requires an extra user action to view the page.

Recently I clicked a link from the Maps app and instead of being taken to the restaurant website I was presented with this view:

![image](https://user-images.githubusercontent.com/107992/147973993-d4d03c4d-8bd6-4cc4-a924-28c786e917d3.png)

### Ideas for Solution
> If the user opens Firefox via a link in an external app we should ignore the 4 hr homescreen rule and just open the requested page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3576)

**Comment by athomasmoz** [comment] 2022-01-04 17:19
**Steps to reproduce**

1. Open some tabs
2. Leave the app backgrounded for 4+ hours
3. Open Firefox through external link or QR code

**Actual Behaviour:**
Opens to new tab and the link opens in background

**Expected Behaviour:**
Opens to the link

**Comment by data-sync-user** [comment] 2022-01-06 10:20
➤ Simion Basca commented:

I was unable to reproduce the issue on v96.0 (7278) and on v40.2 on iPhone Xr(15.1). 
This issue should be fixed and landed on v40.2 https://mozilla-hub.atlassian.net/browse/FXIOS-3485 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3485|smart-link )

**Comment by data-sync-user** [comment] 2022-01-06 10:33
➤ Simion Basca commented:

Ashley Thomas I think it’s safe to close this one. Let me know if you think this would require extra testing.

**Closed** 2022-01-07 08:51 UTC
Labels: Bug 🐞

**Comment by mollyrealized** [comment] 2022-07-28 00:35
Is it possible that this bug reverted?  If I click on an App Store link that begins with http or https, it opens it in Firefox, which offers to open it in the appropriate app - but does not "always open external links directly" as the title would suggest.  I cannot find a relevant setting with this name, as in Firefox Android.

**Comment by SimonBasca** [comment] 2022-07-28 07:43
@mollyrealized could you please submit a new issue with "steps to reproduce", "actual results", "expected results" and a video of the issue?

**Comment by mollyrealized** [comment] 2022-07-29 02:24
@SimonBasca before I write it up, I may simply have a semantic misunderstanding.  In Firefox for Android, there is a setting where it will directly pass along a URL to an external app, if said app normally handles the link -- for example, an Instagram link might be passed along to and open in the Instagram app.  Does this setting exist in Firefox iOS?  For example, if I click on an App Store link in an e-mail, it opens it in Firefox, and rather than it immediately going to the App Store app, a yes/no question is posed.

**Comment by SimonBasca** [comment] 2022-08-04 13:34
@mollyrealized there is no setting in Firefox iOS where it will directly pass along a URL to an external app as far as I know.

**Comment by mollyrealized** [comment] 2022-08-04 19:59
@SimonBasca I see.  Do you think it would be worthwhile for me to open this as a feature request, for feature parity with Firefox's Android version, or do you know already if it's not possible on iOS?

**Comment by SimonBasca** [comment] 2022-08-08 10:01
@mollyrealized I'm uncertain if this is doable in iOS. Maybe @dnarcese could give you a proper answer if it worth logging a feature request.

**Comment by electricRGB** [comment] 2022-08-08 13:00
On iOS, if URLs of a certain format get opened directly in the respective app, if the app is installed on your phone. However, like I said, that has certain requirements so we'd have to manipulate the URL, possibly. Not sure how Android does it so we'd have to investigate that.. So you might want to open a feature request to do that, for sure.

**Comment by SimonBasca** [comment] 2022-08-08 13:32
@mollyrealized I've logged the feature request here: https://github.com/mozilla-mobile/firefox-ios/issues/11534/. Feel free to add more details to it if you think it's necessary.
