### ISSUE TITLE
Shortcuts' display updates only after homepage refresh

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18540] opened 2024-02-02 14:41 UTC
**Steps to reproduce**

1. Make sure you have multiple websites added to shortcuts.
1. Go to Customize homepage-->Shortcuts--->change the number of rows, return to homepage and observe if the display is updated.

**Expected behavior**
The shortcuts' row display is updated according to the setting change.

 **Actual behavior**
The shortcuts' row display doesn't update automatically, only after homepage refresh.

**Device & build information**

* Device: iPhone 15 (17.0)
* Build version: v123(38400)
* First seen version: v123(38400)

 Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/bf9153bf-b1b2-4210-9735-f22bea4bbfc7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8371)

**Comment by data-sync-user** [comment] 2024-04-19 07:40
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40917), with iPhone 15 (17.4).

**Closed by data-sync-user** 2024-04-19 07:40 UTC
Labels: Bug 🐞, Contributor Fix, S3

**Comment by data-sync-user** [comment] 2024-04-22 13:08
➤ Diana Andreea Barladeanu commented:

The issue is still reproducible on v126(41006), with iPhone 15 (17.4).

**Comment by data-sync-user** [comment] 2024-05-10 07:43
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (41731), with iPhone 15 (17.4).

**Comment by data-sync-user** [comment] 2024-05-14 07:18
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (41813), with iPhone 15 (17.4).
