### ISSUE TITLE
[Tab tray refactor] Keyboard is not raised up when the tab is opened from tab tray

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18672] opened 2024-02-12 10:21 UTC
**Prerequisites** 
Fresh install FF ---> new tab is set to FF home. 
Go to FF secret settings ---> Experiments ---> enable “Rollout of tab tray refactor - iOS" feature

**Steps to reproduce**

1. Go to tabs tray and tap on "+" to open a new tab
2 Observe keyboard behavior

**Expected behavior**
Keyboard is raised up when the new tab is opened from tab tray.

**Actual behavior**
Keyboard is NOT raised up when the new tab is opened from tab tray. This behavior applies both to normal and private tabs.

**Device & build information**

* Device: iPhone SE (17.0)
* Build version: v9000 (38710), v123 (38665)
* First seen version: v9000 (38710), v123 (38665)
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/db61ee2f-6114-418b-bf2b-d636bbfac1f2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8421)

**Comment by clarmso** [comment] 2024-02-20 22:22
I could reproduce the issue on private tabs from iPad via XCUITest `testKeyboardRaisedWhenTabOpenedFromTabTray()`.

**Comment by data-sync-user** [comment] 2024-02-22 21:37
➤ Clare So commented:

Matthew Reagan I confirm that the test testKeyboardRaisedWhenTabOpenedFromTabTray passes locally and on Jenkins/MacStadium today.

**Comment by data-sync-user** [comment] 2024-02-22 21:47
➤ Clare So commented:

Matthew Reagan The same test still fails on iPad Air (5th generation) simulator.

**Comment by data-sync-user** [comment] 2024-02-23 19:12
➤ Matthew Reagan commented:

Clare So I can see that the automated test fails on 5th gen simulator also, but I can’t actually replicate any issues when testing the client directly in the 5th gen sim with either private or normal tabs (attached a video). So I think this is a problem with the test. When I watched it running it looked like perhaps there was a slight delay for the keyboard appearance and the check might have timed out too quickly, but I can’t replicate any actual bugs in normal use in the client. So I think we probably need to address this from the testing side.

For this ticket, it’s marked as High priority but as I mentioned I can’t actually see any issues that users will have during normal use so we might want to address the failing CI/UI test in a separate Jira. But LMK if you have any thoughts on how you’d like to handle that (cc Norberto Andres Furlan)

5th gen sim recording:

!client.mov|width=444,height=640!

**Comment by data-sync-user** [comment] 2024-02-23 21:47
➤ Clare So commented:

💡 I can manually reproduce the issue only if the new tab is set to “blank page”. The failing test in question does change the new tab setting to “blank page”.

!Screen Recording 2024-02-23 at 4.42.58 PM.mov|width=1140,height=1664!

Since the description of the bug does not specify the new page setting, should I open a separate bug?

**Comment by data-sync-user** [comment] 2024-02-23 22:22
➤ Matthew Reagan commented:

Taking another look, thanks Clare So

**Comment by data-sync-user** [comment] 2024-02-23 23:29
➤ Matthew Reagan commented:

Note: it looks like the issue may be that the locationTextField of the URLBarView is becoming nil before it can be made first responder, possibly by some code that is calling into removeLocationTextField in this flow.

**Comment by data-sync-user** [comment] 2024-02-27 19:25
➤ Matthew Reagan commented:

This should be fixed now for all iPad devices/sims. Please LMK if anyone can see any further issues around this. cc Clare So 

(QA testing note: it would be really helpful if we could also do some general regression testing around various flows involving the focus of the location field / URL bar when doing things like switching tabs or adding new tabs, removing + undoing tabs etc.)

**Comment by data-sync-user** [comment] 2024-03-14 09:11
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39777), with iPhone 15 (17.0) and iPad Air 3rd gen (17.3).

**Comment by data-sync-user** [comment] 2024-03-19 08:49
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39892), with iPhone 15 (17.0).

**Closed by data-sync-user** 2024-03-19 08:49 UTC
Labels: Bug 🐞, S3
