### ISSUE TITLE
[iPad]Top chrome hides on scrolling down and cannot be restored when scrolling with trackpad

### ISSUE THREAD

**Issue by wmorrel** [mozilla-mobile/firefox-ios#8868] opened 2021-07-17 17:16 UTC
## Steps to reproduce
Open a new tab.
Scroll to the bottom of the page.
As you scroll, the top chrome (tab bar and URL bar) will auto-collapse and hide.
When you scroll back up to the top, you cannot get them to come back.
**This only seems to happen when navigating with the touchpad on an iPad with an Apple Magic Keyboard. Using your finger on the screen seems to override this problem and bring the chrome back when you scroll up by swiping down with your finger.**

### Expected behavior
Scrolling up with uncollapse the tab and URL bars.

### Actual behavior
Scrolling up does not uncollapse the tab and URL bars, which remain hidden and inaccessible.

### Device & build information
* Device: iPad Pro 12.9-inch 5th generation
* Build version: Firefox Daylight 35.0 (5448)

### Notes
Attachments: 
<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/10011642/126044773-1381e1da-ffc6-4c7a-afff-6503590c2541.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2973)

**Comment by dnarcese** [comment] 2021-08-03 20:27
Duplicate of #7860

**Closed by dnarcese** 2021-08-03 20:27 UTC
Labels: Bug 🐞
