### ISSUE TITLE
Firefox opens two tabs instead of one when an Apple Magic/Folio Keyboard is connected

### ISSUE THREAD

**Issue by lokan** [mozilla-mobile/firefox-ios#8978] opened 2021-08-08 10:22 UTC
## Steps to reproduce

cmd + T on a physical keyboard (tested with an Apple Folio and an Apple Magic Keyboard)
When the bug happens once with a cmd + T, it will happens too pressing the "+" button on top of the URL.
As soon as the keyboard is disconnected, pressing "+" only opens one tab.
Connecting the keyboard again and pressing "+" will open one tab.
cmd + T on the keyboard again, and you'll have two tabs ;-)

### Expected behavior

Firefox should open a new tab and make it the active tab.

### Actual behavior

Firefox opens two tabs and make the first one active.

### Device & build information
* Device: iPad 11" Cellular 2020 w/ iPad OS 15 Public Bêta
* Build version: Firefof Daylight 35.0 (5448)
### Notes
Attachments: 
I recorded my screen…
https://www.youtube.com/watch?v=GVq5YNjfJdc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3056)

**Comment by dnarcese** [comment] 2021-08-09 19:32
Duplicate of #7519

**Closed by dnarcese** 2021-08-09 19:32 UTC
Labels: Bug 🐞
