### ISSUE TITLE
L10n: "Keys" from Strings.swift file are duplicated and/or don't follow convention

### ISSUE THREAD

**Issue by nishant2718** [mozilla-mobile/firefox-ios#9605] opened 2021-12-08 19:25 UTC
# Overview
The LocalizationTools exporter has issues with some strings inside Strings.swift. This indicates that there are duplicated Keys being used with different comments, and also shows that some Keys don't follow the standard of `String.Key.Format` we've settled on. 

Duplicated keys end up showing two or more distinct comments, which causes translation issues/difficulties. They should be corrected ASAP. 

Here's most of them:

```
Key "Onboarding.WhatsNew.Title" used with multiple values. Value "What’s New in Firefox" kept. Value "Personalized Firefox Homepage" ignored.
Key "SendTo.Cancel.Button" used with multiple values. Value "Cancel" kept. Value "Close" ignored.
Key "Settings.DisplayTheme.SwitchTitle" used with multiple values. Value "Automatically" kept. Value "Automatic" ignored.
genstrings: warning: Key "TodayWidget.QuickViewGalleryTitle" used with multiple comments "Quick View title user is picking a widget to add." & "Title for Quick View widget in Gallery View where user can add it to home screen"
genstrings: warning: Key "Add to Reading List" used with multiple comments "Accessibility label for action adding current page to reading list." & "Name for button adding current article to reading list in reader mode"
genstrings: warning: Key "Bookmarks" used with multiple comments "Panel accessibility label" & "Toggle bookmarks syncing setting"
genstrings: warning: Key "Default Search Engine" used with multiple comments "Accessibility label for default search engine setting." & "Title for default search engine picker." & "Title for default search engine settings section."
genstrings: warning: Key "History" used with multiple comments "Panel accessibility label" & "Toggle history syncing setting"
genstrings: warning: Key "Mark as Read" used with multiple comments "Name for Mark as read button in reader mode" & "Title for the button that marks a reading list item as read"
genstrings: warning: Key "Mark as Unread" used with multiple comments "Name for Mark as unread button in reader mode" & "Title for the button that marks a reading list item as unread"
genstrings: warning: Key "New Tab" used with multiple comments "Accessibility label for the New Tab button in the tab toolbar." & "Accessibility Label for the tab toolbar New tab button"
genstrings: warning: Key "Onboarding.WhatsNew.Title" used with multiple comments "On the onboarding card, letting users know what's new in this version of Firefox, this is the title for the Jump Back In bullet point on the card" & "The title for the new onboarding card letting users know what is new in Firefox iOS"
genstrings: warning: Key "Search" used with multiple comments "Accessibility Label for the tab toolbar Search button" & "Navigation title for search settings." & "Open search section of settings"
genstrings: warning: Key "SendTo.Cancel.Button" used with multiple comments "Button title for cancelling share screen" & "Close button in top navigation bar"
genstrings: warning: Key "Settings.DisplayTheme.SwitchTitle" used with multiple comments "Display (theme) settings label to show if automatically switch theme is enabled." & "Display (theme) settings switch to choose whether to set the dark mode manually, or automatically based on the brightness slider."
genstrings: warning: Key "Show Tabs" used with multiple comments "Accessibility label for the tabs button in the (top) tab toolbar" & "Accessibility Label for the tabs button in the tab toolbar"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3502)

**Comment by lmarceau** [comment] 2023-01-19 17:51
I think those warnings were fixed by @flodolo a couple months ago

**Comment by flodolo** [comment] 2023-01-19 18:04
Yes, this is a dupe of #11667

**Closed** 2023-01-19 18:23 UTC
Labels: Bug 🐞
