### ISSUE TITLE
Edge of first tab in top tabs is cut off

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#9781] opened 2022-01-13 21:02 UTC
## Steps to reproduce
On iPad, observe the first tab
The left edge is faded and does not have a straight edge
### Expected behavior
Tab should have a definitive edge
### Actual behavior
![Screen Shot 2022-01-13 at 3 20 10 PM](https://user-images.githubusercontent.com/11432165/149408527-3c0cd041-0b90-4c90-b8fc-eb2bf5f4503c.png)

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3625)

**Comment by finebel** [comment] 2022-01-25 17:14
The described behaviour is caused by the `TopTabFader` View. This view causes the edges of the first and last (if there are enough) tab to be faded. To have definitive edges the `TopTabFader` could probably be removed.
This behaviour was introduced back in 2016 in #1946.
The attached screenshots there document the behaviour as well.

Old first tab:
![Screenshot 2022-01-25 at 16 46 22](https://user-images.githubusercontent.com/46824694/151025105-35632060-4448-4a16-8702-e013dd0141a0.png)

Old last tab:
![Screenshot 2022-01-25 at 16 47 01](https://user-images.githubusercontent.com/46824694/151025599-d24b4e93-3cca-4049-af1e-a762483abff6.png)

New first tab:
![Screenshot 2022-01-25 at 18 12 31](https://user-images.githubusercontent.com/46824694/151025636-8bf8b548-53fe-44d7-8e6b-221bbf3955b1.png)

New last tab:
![Screenshot 2022-01-25 at 18 12 05](https://user-images.githubusercontent.com/46824694/151025666-291fa54f-c3b9-4125-9e1f-d4cc67bc95c2.png)

**Comment by abodea** [comment] 2022-02-03 11:25
Verified as fixed on the latest 9000 (7720) with iPad mini 5 (14.1)

**Closed by abodea** 2022-02-03 11:25 UTC
Labels: Contributor OK, Bug 🐞, P3, Contributor Fix

**Comment by data-sync-user** [comment] 2022-02-03 11:39
➤ Andrei Bodea commented:

Verified as fixed on the latest 9000 (7720) with iPad mini 5 (14.1)

**Comment by SimonBasca** [comment] 2022-02-15 14:05
Verified fix on v98.0 (8023).
