### ISSUE TITLE
[SPIKE] Firefox for iOS is forgetting login information and cookies after refreshing a tab

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/firefox-ios#12279] opened 2022-11-01 20:20 UTC
Users are reporting that Firefox for iOS is not consistently remembering their login details or cookie preferences in websites that require a login. Ex. forums, email providers, social media 

After you log in, if you switch to another app for a moment or refresh the tab, you'll appear logged out. 
Sometimes if you refresh the website several times, you'll appear logged back in. 

## Steps to reproduce
1. Open Firefox for iOS 
2. Go to a website and log in (ex. twitter) 
3. Switch to a different app OR switch to another tab OR refresh the tab 

### Expected behavior
Users should remain logged in since they haven't cleared their browsing data 

### Actual behavior
You appear logged out 

### Device & build information
OS 16.1 
Firefox v106 

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5192)

**Comment by jr-johnson-support** [comment] 2022-11-01 21:10
https://user-images.githubusercontent.com/58608126/199342223-cf61a8e6-9a67-47d3-828e-eb3ffc129d5d.MP4

**Comment by oneofthedamons** [comment] 2022-11-06 05:40
I'm seeing something similarly intermittently with Twitter in the last few weeks. In my failure mode I click a link on the Twitter "Your Highlights" email newsletter and I'm redirected to mobile.twitter.com/i/sms_login telling me I need to sign-in. If I reload a different Twitter page in another tab, the page shows normally indicating I am signed-in. If I follow the original emailed link again, it loads without issue.

**Comment by dnarcese** [comment] 2022-11-10 20:32
@SimonBasca are you able to check this on iOS 15 to determine if it is an iOS bug?

**Comment by hikari-no-yume** [comment] 2022-11-11 20:48
I've been getting this for a while now. I find that most of the time if I visit a site requiring a login, it'll show up with me not logged-in until I refresh the page.

**Comment by SimonBasca** [comment] 2022-11-14 12:50
I am constantly reproducing the site cookies being cleared after STR on iPhone 12 Pro 16.0.2 on Firefox 107 (21907) and iPhone SE (14.8) on Firefox 107 (21907).

1. Visit a page (in my case beatport.com)
2. Accept site cookies or login to beatport.com
3. Close the app from app switcher
4. Open the app

- The site cookies are cleared after restarting the app and the user requires to log in . 
- Note that the issue is not reproducible on every site. I was unable to reproduce the issue on bandcamp.com or twitter.com
- Safari has the same behavior for "beatport.com".

https://user-images.githubusercontent.com/32130829/201664428-02fc67ad-9a0e-482c-bb37-bab1b5a68d3d.mp4

**Comment by GenderCompass** [comment] 2022-11-14 14:41
This is constantly happening to me too on Google. It also as a result makes the website appear in light mode.

Steps to reproduce: 
1. Open Google, you should be logged in and in dark mode if that's your default setting.
2. Close out of the app
3. Open Firefox again and go back to Google
4. Google will now be in light mode and you won't be logged in.

**Comment by GenderCompass** [comment] 2022-11-14 14:53
This is constantly happening to me too on Google. It also as a result makes the website appear in light mode.

Steps to reproduce: 
1. Open Google, you should be logged in and in dark mode if that's your default setting.
2. Close out of the app
3. Open Firefox again and go back to Google
4. Google will now be in light mode and you won't be logged in.
https://imgur.com/a/xB2Ia6f

**Comment by BrainStone** [comment] 2022-12-03 13:10
One thing of note is that this only happens to the currently open tab. All other tabs are fine.

To me it sounds like FF is no longer able to write the files on closing properly. Probably due to iOS giving apps less to do their closing routines. It might be necesarry to save the session and cookie data more frequently.

**Comment by lmarceau** [comment] 2022-12-05 14:32
Thank you for you comments, this will be looked at soon!

**Comment by malfroid** [comment] 2022-12-18 09:24
Bug is still present in version 108.1. This bug makes Firefox unusable for me; having to log in again and again every day on sites with MFA is just too much overhead. I switched to Safari.

**Comment by esperecyan** [comment] 2022-12-21 00:31
pixiv asked for a very long Google reCAPTCHA every day and it was very time consuming.
So, I linked Twitter from pixiv.
However, when I tried to log in with Twitter when my session expired, I got a token error on Twitter.
When I closed the tab where the problem occurred and opened a new tab, I was able to successfully login with Twitter.

**Closed** 2022-12-22 15:07 UTC
Labels: Bug 🐞

**Comment by Sebazzz** [comment] 2022-12-24 12:13
Sorry, issue still exists in the app store update of 22 December.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Data Sync User ***@***.***>
Verzonden: Thursday, December 22, 2022 4:07:43 PM
Aan: mozilla-mobile/firefox-ios ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [mozilla-mobile/firefox-ios] [SPIKE] Firefox for iOS is forgetting login information and cookies after refreshing a tab (Issue #12279)


Closed #12279<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmozilla-mobile%2Ffirefox-ios%2Fissues%2F12279&data=05%7C01%7C%7Cd2504df42d894d68a52108dae42e471c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638073184660774095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hhGaAGoz%2BNuT5PobJYMmq5D4zn%2FopTZNwqf0Ltdyj1k%3D&reserved=0> as completed.

**Comment by esperecyan** [comment] 2022-12-26 01:28
Why was the issue closed?
This bug continues on Firefox 108.1 (24234) on iOS, and in the worst case, sessions are disconnected every few seconds.

**Comment by hikari-no-yume** [comment] 2022-12-26 08:41
They renamed the issue to begin with “[SPIKE]” before closing this and this was synced from some other system. I think this means they did an initial investigation and that's finished now, but they're still working on the fix. @lmarceau am I right about that?

**Comment by adudenamedruby** [comment] 2022-12-27 14:24
Hey ya'll, @hikari-no-yume is correct. We've done an investigation into what's happening, and the issue is a bit more complex that originally thought. I'll be updating the ticket in a bit with the results of the spike. We'll get to this in the next sprint or two. You'll find the actual work happening under #12740 :)

**Comment by locolau** [comment] 2023-04-28 08:20
Issue still exists.

**Comment by Sebazzz** [comment] 2023-05-01 15:28
Yes, I've also noticed it. The issue still occurs from time to time.

**Comment by davidvaneekelen** [comment] 2023-06-23 08:03
This issue still persists on FF 114.2 and iOS 16.5

**Comment by ahohns** [comment] 2023-06-29 05:12
I still have this issue too, FF 114.3 iOS 16.5. Not sure why this was closed.

**Comment by locolau** [comment] 2023-06-30 10:33
Can this be opened and updated? The issue is still there, on almost every site.

**Comment by mcfilib** [comment] 2023-07-04 09:09
this is still broken

**Comment by fadenb** [comment] 2023-07-14 08:43
For me it just started a few days ago with Firefox 115.0 (32242) on iOS 16.5.1

**Comment by tszewcow** [comment] 2023-07-19 06:46
Bumping up, issue is reproducible on iPhone X and iPhone 11 with iOS 16.5.1 / FF 115.0.

**Comment by spitfirex86** [comment] 2023-07-24 10:37
Also experiencing this issue, Firefox 115.1 (32781) on iOS 16.5.1

**Comment by tihomirbz** [comment] 2023-07-30 15:54
This is still happening on Firefox 115.1 and iOS 16.5.1

**Comment by christophehad** [comment] 2023-08-11 22:26
Related open issue: https://github.com/mozilla-mobile/firefox-ios/issues/11994
