### ISSUE TITLE
Cannot clear a specific website from history when searching

### ISSUE THREAD

**Issue by hhowdii** [mozilla-mobile/firefox-ios#11662] opened 2022-08-22 09:51 UTC
## Steps to reproduce
Go to History.
Enter a search term.

### Expected behavior
You should be able to swipe to delete an item from History. 

### Actual behavior
After you have entered a search term, you will no longer be able to swipe on an item to remove it from History. If you swipe _before_ searching an item, you will be able to swipe and delete an item. Only when the search bar at the bottom is visible are you not allowed to swipe on an item. 

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox Daylight 103.1 (15076)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4798)

**Comment by dnarcese** [comment] 2022-09-13 18:49
Duplicate of #11290

**Closed by dnarcese** 2022-09-13 18:49 UTC
Labels: Bug 🐞
