### ISSUE TITLE
Going back a page loses place and jumps back to top

### ISSUE THREAD

**Issue by darren12345** [mozilla-mobile/firefox-ios#17107] opened 2023-11-01 18:15 UTC
## Steps to reproduce
1. Browse a website.
2. Follow a link.
3. Go back to previous page (either swipe left or use back arrow). 

### Expected behavior
Position in previous page should be preserved. 

### Actual behavior
Position jumps back to top of page. 

### Device & build information
* iphone SE 2020, iOS 17.1
* Firefox 119.1 (35574)
* First seen version: ? Unsure. Recent. 
### Notes
Particularly noticeable on bbc.co.uk/news and stackexchange.com

Attached video of it occurring. 

https://github.com/mozilla-mobile/firefox-ios/assets/12751052/f1941093-c7fc-49bc-a36b-590ca8b1bec9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7671)

**Comment by dnarcese** [comment] 2023-11-02 18:45
Duplicate of #16643

**Closed by dnarcese** 2023-11-02 18:45 UTC
Labels: Bug 🐞
