### ISSUE TITLE
Keyword search shortcuts no longer work

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5169] opened 2019-06-24 15:52 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1560985

This broke in recent betas (sorry I don't have a better idea; probably the past month-ish). Bug 1253656 looks like it's where this was first implemented. Perhaps it's helpful to point out another regression here: bug 1471277.

I'm on Beta 18.0 Build 15590.

**Comment by farhanpatel** [comment] 2019-06-25 16:09
Here is the relevant A-S issue 
https://github.com/mozilla/application-services/issues/953

**Comment by farhanpatel** [comment] 2019-06-25 16:10
Dupe of https://github.com/mozilla-mobile/firefox-ios/issues/4779

**Closed by farhanpatel** 2019-06-25 16:10 UTC
