### ISSUE TITLE
Sometimes user should accept cookies twice in order to take effect on goole.com page 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15944] opened 2023-08-08 12:09 UTC
## Steps to reproduce
1. Navigate to private browsing and open google.com page (please note that issue reproduces on normal browsing mode also)
2. Cookie pop-up is displayed 
3. Tap Accept all 

### Expected behavior
The pop-up disappear 

### Actual behavior
User must tap twice the "Accept all" button in order for the button to take effect  

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v116.1 (33291) 
* First seen version:
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/7c089458-5151-46f5-b1fc-6d70cfab15ce

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7175)

**Comment by data-sync-user** [comment] 2023-08-08 12:58
➤ Yoana Rios Diaz commented:

This is a duplicate of the original bug

**Comment by dnarcese** [comment] 2023-08-10 18:57
Duplicate #11994

**Closed by dnarcese** 2023-08-10 18:57 UTC
Labels: Bug 🐞, S3
