### ISSUE TITLE
Cookies not saved after a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13520] opened 2023-03-09 15:24 UTC
Steps to get the app in this stage are not clear yet, but after the app gets into this stage the bug reproduces constantly. We manage to put the app into this stage twice during the testing session. 
It might me related to the info from this[ test](https://testrail.stage.mozaws.net/index.php?/tests/view/4795261)
## Steps to reproduce
1. Access news.google.com
2. Accept cookies 
3. Close the app 
4. Relaunch the app 
5. news.google.com tab opens  

### Expected behavior
Cookies are already accepted  

### Actual behavior
You're asked to accept the cookies again (Please see the attached video)

### Device & build information
* Device : iPhone 14 Plus (16.0.3) 
* Build version:  v111 (29345)  
* First seen version: v111 (29345)  
### Notes
- the issue was tested for news.google.com, bbc.com, youtube.com (user is logged out even if the login details are kept)
- the only workaround is to reinstall app 
- while running the steps into the above test we encounter a random crash (Please see the attached logs).

Attachments: 

https://user-images.githubusercontent.com/124251579/224068525-2f5db1d7-0a39-4683-97f0-8707d311dd7e.mp4

https://user-images.githubusercontent.com/124251579/224069301-03c7ab2e-441e-4585-b340-c2f03ce3133e.mp4

[aggregated.diskwrites_resource-2023-03-09-135054.zip](https://github.com/mozilla-mobile/firefox-ios/files/10933333/aggregated.diskwrites_resource-2023-03-09-135054.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5951)

**Comment by yoanarios** [comment] 2023-03-09 20:49
This issue is reproducible in v110.2 so it shouldn't block the v111 release.

**Comment by yoanarios** [comment] 2023-03-09 20:54
# Steps to reproduce:

1. Open new private tab
2. Open website with cookie banner Ex: (news.google.com, bbc.com, youtube.com, bing.com)
3. Let the private tab open without accepting the cookies
4. Open a new regular tab and open the same website that is open in private mode
5. Accept cookies 
6. Close the app
7. Relaunch the app

### Expected behavior
Cookies are already accepted

### Actual behavior
You're asked to accept the cookies again (Please see the attached video)

**Comment by alinamoldovan84** [comment] 2023-03-10 12:00
We investigate more this issue and here are our findings:

Steps to reproduce:
1. Clean install 
2. Open an website with cookie banner but let the banner opened
3. While cookie banner is still opened,  navigate to a private tab (it is not needed to open a website)
4. Navigate back to the tab opened at step 2 
5. Accept cookies 
6. Close the app 
7. Relaunch the app 
=> results: You're asked to accept the cookies again

Notes: 
Not able to reproduce this issue for iOS 15.7.1 nor 14.0.1 but it seems reproducible for iOS 16.x.x
I was able to reproduce this issue with Safari, also (using the same steps to reproduce).
The issue seems related with [11994](https://github.com/mozilla-mobile/firefox-ios/issues/11994), [12232](https://github.com/mozilla-mobile/firefox-ios/issues/12232) and [12279](https://github.com/mozilla-mobile/firefox-ios/issues/12279)

**Comment by data-sync-user** [comment] 2023-03-14 14:33
➤ Yoana Rios Diaz commented:

The issue is only reproducible in the selected tab being restored. Ex if we have 3 tabs with bbc.com ( http://bbc.com ) open. We accept the cookies and restore the app only for the selected tab the cookie banner will show again and if the user reload the banner disappear. If we switch to the other 2 previously tabs the banner doesn’t show. 
So the issue is related to the tab restore process only for the selected tab the cookie store is empty (probably a race condition).
This part of the code is very flaky and is being refactored already, after a sync with Orla Mitchell we think it makes more sense to wait for the refactoring to fix this issue for good that to find a partial patch that could cause side effects

**Comment by wvreeven** [comment] 2023-05-08 08:42
Disabling the "close private tabs" Firefox setting has fixed this for me. See https://github.com/mozilla-mobile/firefox-ios/issues/12232

**Comment by locolau** [comment] 2023-06-30 10:34
The issue is still here.

**Comment by yoanarios** [comment] 2023-07-27 19:19
Closing as a duplicate of #11994

**Closed by yoanarios** 2023-07-27 19:19 UTC
Labels: Bug 🐞, S1

**Comment by fwieringen** [comment] 2025-04-22 07:48
Can confirm that this issue is still here on IOS 18.5 and Firefox 137.2 (53903).

1. Close firefox.
2. Reopen firefox with a link to a page where you are sure that you're logged in.
3. Site is not logged in.
4. Refresh after 5 seconds.
5. Site is logged in.

Turned off the "Close private tabs" option.

1. Firefox behaves correctly and cookies are loaded.
