### ISSUE TITLE
[Toolbar redesign] [iPad] - URL is not selected when the user taps on it 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#22430] opened 2024-10-07 16:12 UTC
## Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

## Steps to reproduce
1. Install FF.
1. Make sure that "show search suggestions" toggle is enabled in settings.
1. Access a website.
1. Tap on the url.
1. Observe.

### Expected behavior
The url is selected , the keyboard pops up and the search suggestions are displayed.

### Actual behavior
The url is NOT selected , the keyboard pops up and the search suggestions are NOT displayed (logged as separate [bug](https://github.com/mozilla-mobile/firefox-ios/issues/22415)).

### Device & build information
* Device: iPad Pro 4th Gen (17.2) 
* Build version: v9000 (46086) 
* First seen version: ? 
### Notes
* This issue doesn't reproduce on iPhones 

###Attachments: 

https://github.com/user-attachments/assets/288a4d64-53e5-486a-9fc0-d138040584db

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10250)

**Comment by data-sync-user** [comment] 2024-10-08 11:26
➤ Sorin Paraipan commented:

A fix for this went in with the issue: https://mozilla-hub.atlassian.net/browse/FXIOS-10222 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10222|smart-link ) .

**Comment by cpeterso** [comment] 2024-10-15 05:19
Is this bug a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/22145?

**Comment by data-sync-user** [comment] 2024-10-25 11:33
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPad Air 3rd gen (17.5).

**Comment by data-sync-user** [comment] 2024-11-05 10:34
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47063), with iPad Air 3rd gen (17.5).

**Closed by data-sync-user** 2024-11-05 10:34 UTC
Labels: Bug 🐞, S3, Toolbar redesign📲
