### ISSUE TITLE
Spike in errors for `pocket.open_story_position`

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#8795] opened 2021-07-05 09:54 UTC
## Steps to reproduce

Since 2021-06-22 we're seeing a spike in reported errors from the [`pocket.open_story_position`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/pocket_open_story_position?channel=org.mozilla.ios.Firefox&ping=metrics) metric.
All data lands in the `__other__` bucket, see this [Looker Explore](https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=9If2VwAOrdclKMZTXS63IL&toggle=vis).

This code was added in #8662.
The metric is recorded [in the telemetry wrapper](https://github.com/mozilla-mobile/firefox-ios/blob/3b9c2d558f08e80d13b073c5433c1e0718c00460/Client/Telemetry/TelemetryWrapper.swift#L524).
This is called from the [home view here](https://github.com/mozilla-mobile/firefox-ios/blob/3b9c2d558f08e80d13b073c5433c1e0718c00460/Client/Frontend/Home/FirefoxHomeViewController.swift#L817):

```swift
TelemetryWrapper.recordEvent(category: .action, method: .tap, object: .pocketStory, value: nil, extras: [key : "\(index)"])
```

The problem is that `index` is a number and is then used as the label. However [labels need to start with an alphabetic character (`[a-z]`)](https://mozilla.github.io/glean/book/reference/metrics/index.html#label-format). Invalid labels record an error and are counted for the `__other__` label. 
As it stands the recorded data cannot answer the posed questions.

### Expected behavior

Correctly recording the data.

### Actual behavior

Always recording to the `__other__` label, thus not providing any useful data.

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2927)

**Comment by data-sync-user** [comment] 2021-07-08 17:22
➤ Daniela Arcese commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-2910 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2910|smart-link )

**Closed** 2021-08-16 15:43 UTC
Labels: Bug 🐞
