### ISSUE TITLE
[Intermittent] The History content page is displayed in a wrong color

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#20358] opened 2024-05-21 13:46 UTC
## Steps to reproduce
1. Open 2 or more tabs in PB.
2. Close All tabs.
3. Check the History settings from the hamburger menu.
### Expected behavior
The history content page should be displayed in the same color as the browser dark/light/priavate browsing mode.
### Actual behavior
The History content page is displayed in purple instead of light/dark.
### Device & build information
* Device: iPhone 15 Pro (17.4.1). 
* Build version: 126.1 (41973) 
* First seen version: N/A 
### Notes
Please note that this was reproduced on the automated tests.
Might be related to this [test.](https://github.com/mozilla-mobile/firefox-ios/blob/177be175c62d7329b2f43806c6922b8eaae9532b/firefox-ios/firefox-ios-tests/Tests/XCUITests/HistoryTests.swift#L310)
I was not able to reproduce it on a real device.
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/fe1f5da1-6ce0-4b70-9b86-242ed619172d)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9191)

**Comment by MattLichtenstein** [comment] 2024-06-05 15:21
Issue seems to be resolved on 127.0 / 128.0

Can consistently reproduce with the following steps on 126.1 / 126.2 with the `felt-privacy-simplified-UI` feature flag enabled

1. Create a new private browsing tab
2. Open and close the history sheet (it should be purple, which is expected)
3. Remove the private browsing tab and go back to a regular tab
4. Reopen the history sheet

Notes:
- It does not seem to matter how you create and remove the private browsing tab, as long as you are opening the history sheet in between
- You can also mess up the theming by doing the inverse (starting on regular tabs, opening history sheet, switching to a private tab, reopening history sheet) - see attachment

<img src="https://github.com/mozilla-mobile/firefox-ios/assets/15353801/922a4cae-b25e-4a21-8f75-55c83756f52c" width="250" height="500">

**Comment by MattLichtenstein** [comment] 2024-06-05 16:27
Looks like this was fixed as part of [FXIOS-8957](https://mozilla-hub.atlassian.net/browse/FXIOS-8957)/#19787  in [this patch](https://github.com/mozilla-mobile/firefox-ios/commit/b0ff2056840b4f5c830ded377f1c2b4951a494f3)

Verified as fixed by QA in v127

**Closed** 2024-10-28 02:47 UTC
Labels: Bug 🐞, S3
