### ISSUE TITLE
[messaging system] `expired` telemetry events are sent each time the browser could have displayed an expired message

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#13950] opened 2023-04-13 08:28 UTC
## Preconditions
* Have the **Firefox Release 112 (29983)** installed through TestFlight.

## Steps to reproduce
1. Open the Firefox build from prerequisites.
1. Open the Settings menu.
1. Enable Secret Menu (tap the Firefox 112.0 (29983) line 5 times).
1. Tap Experiments then tap Edit.
1. Toggle `Use Preview Collection` and close and reopen Firefox twice.
1. Open the Settings menu and enable Secret Menu.
1. Go back and tap Experiments.
1. Tap the "Viewpoint 1 Week Expansion test" experiment and force enroll in any of the branches.
1. Close the app and set the device time to two days in the future.
1. Open Firefox using a telemetry command (eg. `firefox://glean?logPings=true&sendPing=events&debugViewTag=cmuresan-11` opened in Safari).
1. Dismiss the Survey message that appears and search the telemetry events using the debug tag (eg. `https://debug-ping-preview.firebaseapp.com/pings/cmuresan-11`).
1. Reopen Firefox using the same telemetry command and send it to background.
1. Search the telemetry events using the debug tag.

### Expected behavior
* Step 12: An `expired` telemetry event is sent when any of the buttons are pressed on the message.
* Step 14: No extra events are displayed for the message.

### Actual behavior
* Step 12 & Step 14: An `expired` telemetry event is sent.

### Device & build information
* Device: iPhone Xr - iOS 16.2
* Device: iPhone 13 mini - iOS 16.2
* Build version: Firefox Beta 112.0 (29983)

### Notes
* The issue is also reproducible with the Set to Default message from the homescreen.
* The `expired` telemetry event is sent each time the browser is reopened.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6183)

**Comment by data-sync-user** [comment] 2023-05-06 15:09
➤ Roux Buciu commented:

Moved this to sprint 23.2.3 as it has lower priority that the Onboarding Project work

**Comment by data-sync-user** [comment] 2023-06-21 11:28
➤ Roux Buciu commented:

Nishant Bhasin I believe this was meant to go to Winnie Teichmann . I’ve moved it over to her. 🙂

**Comment by data-sync-user** [comment] 2023-12-19 14:16
➤ Ciprian Muresan commented:

I have retested the issue on Firefox build from the latest main using a simulated device. The issue is no longer reproducible and only one expired event is sent for the message. Based on this, I think we can close this issue.

**Closed** 2023-12-19 14:19 UTC
Labels: Bug 🐞, S3
