### ISSUE TITLE
Implement the new pairing / FxA sign in screens and the possibility to login with QR Code

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#5855] opened 2019-12-04 15:12 UTC
### Why/User Benefit/User Problem
As a Firefox user, I want to be able to log in via QR Code from `https://firefox.com/pair`.
### Acceptance Criteria (how do I know when I’m done?)
After tapping on the `Sign in to Sync` button the new pairing / FxA sign-in screen is displayed with two options:
- Ready to scan
- Use email instead
### Attachments
![Screenshot_20191204-165953](https://user-images.githubusercontent.com/42831109/70154400-1bd62000-16b9-11ea-8195-9d966abf3abd.jpg)

**Comment by athomasmoz** [comment] 2020-02-12 19:03
Design ticket #6114

**Comment by athomasmoz** [comment] 2020-03-19 21:59
Closing as duplicate of #6114

**Closed by athomasmoz** 2020-03-19 21:59 UTC
Labels: Feature 🎁, Needs UX 🎨
