### ISSUE TITLE
Tab title disappears

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [mozilla-mobile/firefox-ios#13366] opened 2023-02-25 13:01 UTC
## Steps to reproduce
Just open tabs and switch between them. The titles do not appear

### Expected behavior
Tab titles appear properly

### Actual behavior
Tab titles are blank, and inconsistently.

### Device & build information
* Device : iPadOS 16.2
* Build version: 110.0
* First seen version: ?
    1. Notes
Attachments: 

![image](https://user-images.githubusercontent.com/97137197/221358189-57801caa-a5f6-44e8-963c-c2c357790a49.jpeg)
![image](https://user-images.githubusercontent.com/97137197/221358247-f4197a39-8c97-4ed8-bca7-ca83f0bdc058.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5852)

**Comment by canova** [comment] 2023-04-08 14:10
This has been an issue on my iPad lately as well. After doing some testing, I realized that this happens when I use private tabs. It doesn't happen (as far as I tested) otherwise.
I managed to create an STR that reproduces very consistenly on my iPad.

Here's the STR:a
1. Open Firefox and open a few tabs and navigate to some websites.
2. Switch to private window and open a few private tabs as well.
3. Swipe up / use home button to return to iOS home screen.
4. Return to Firefox again.
5. See that some (sometimes all) private tab titles are gone now.
6. Switch back to normal tabs. See that some (or sometimes all) non-private tab titles are gone as well.

I don't know the source code, but I feel like when we send the app to background we run a code and when we return from background we don't recover it fully.

**Comment by data-sync-user** [comment] 2023-05-02 14:35
➤ Daniela Arcese commented:

CLosing as duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-5913 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5913|smart-link )

**Closed by data-sync-user** 2023-05-02 14:35 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2023-05-02 14:47
➤ Nazım Can Altınova commented:

Hi Daniela Arcese , I fixed this issue on PR #13908 ( https://github.com/mozilla-mobile/firefox-ios/pull/13908 ) 3 weeks ago. I think this ticket should have been closed as fixed. And possibly we can close the other ticket as a duplicate of this instead.
