### ISSUE TITLE
Accessing Table view's visibleCells while being updated.

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#13570] opened 2023-03-14 13:50 UTC
Looking at the console while clicking the hamburger (3-lines) menu shows this message every time the menu is displayed:

**2023-03-14 13:31:53.056271+0000 Client[44503:448756] [Assert] Attempted to access the table view's visibleCells while they were in the process of being updated, which is not allowed. Make a symbolic breakpoint at UITableViewAlertForVisibleCellsAccessDuringUpdate to catch this in the debugger and see what caused this to occur. Perhaps you are trying to ask the table view for the visible cells from inside a table view callback about a specific row? Table view: <UITableView: 0x7fa038873400; frame = (0 0; 400 608.5); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x60000121a880>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600001cef920>; contentOffset: {0, 0}; contentSize: {400, 630.5}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <Client.PhotonActionSheet: 0x7fa038900400>>**

Having added the breakpoint I see it is being called from the 1st line of `PhotonActionSheet.setMainMenuTableViewHeight()`:
```swift
    private func setMainMenuTableViewHeight() {
        let visibleCellsHeight = getViewsHeightSum(views: tableView.visibleCells)
```

Here's the full stack trace:
```
    frame #0: 0x0000000109f81bb5 UIKitCore`UITableViewAlertForVisibleCellsAccessDuringUpdate
    frame #1: 0x0000000109f81b48 UIKitCore`-[UITableView _visibleCellsUsingPresentationValues:] + 555
  * frame #2: 0x00000001023d6fcf Client`PhotonActionSheet.setMainMenuTableViewHeight(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:355:69
    frame #3: 0x00000001023d6d66 Client`PhotonActionSheet.setTableViewHeight(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:343:13
    frame #4: 0x00000001023d2694 Client`PhotonActionSheet.viewDidLayoutSubviews(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:168:9
    frame #5: 0x00000001023d26bc Client`@objc PhotonActionSheet.viewDidLayoutSubviews() at <compiler-generated>:0
    frame #6: 0x000000010a3487b3 UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2837
    frame #7: 0x00007ff80898b02c QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 526
    frame #8: 0x000000010a333cde UIKitCore`-[UIView(Hierarchy) layoutBelowIfNeeded] + 1447
    frame #9: 0x000000010a373b4c UIKitCore`-[_UIPopoverView _setFrame:arrowOffset:] + 861
    frame #10: 0x00000001092dd29a UIKitCore`__73-[UIPopoverPresentationController _setPopoverFrame:animated:coordinator:]_block_invoke + 215
    frame #11: 0x00000001092dd079 UIKitCore`-[UIPopoverPresentationController _setPopoverFrame:animated:coordinator:] + 464
    frame #12: 0x00000001092e5046 UIKitCore`-[UIPopoverPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 1161
    frame #13: 0x0000000109412759 UIKitCore`-[UIViewController setPreferredContentSize:] + 468
    frame #14: 0x00000001023d63f1 Client`PhotonActionSheet.observeValue(keyPath="contentSize", object=0x00007fa01f931e00, change=2 key/value pairs, context=nil, self=0x00007fa01f84bc00) at PhotonActionSheet.swift:317:38
    frame #15: 0x00000001023d6667 Client`@objc PhotonActionSheet.observeValue(forKeyPath:of:change:context:) at <compiler-generated>:0
    frame #16: 0x00007ff800be1e93 Foundation`NSKeyValueNotifyObserver + 304
    frame #17: 0x00007ff800be56f0 Foundation`NSKeyValueDidChange + 462
    frame #18: 0x00007ff800be4f5f Foundation`-[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 797
    frame #19: 0x00007ff800be58b5 Foundation`-[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 68
    frame #20: 0x00007ff800bdf8e8 Foundation`_NSSetSizeValueAndNotify + 306
    frame #21: 0x0000000109f9171f UIKitCore`-[UITableView setContentSize:skipContentOffsetAdjustment:] + 99
    frame #22: 0x000000010a2cc91a UIKitCore`-[UIScrollView performWhileAnimatingAutomaticContentOffsetAdjustments:] + 42
    frame #23: 0x0000000109fb6115 UIKitCore`-[UITableView _applyContentSizeDeltaImmediately:] + 358
    frame #24: 0x0000000109f6c6c2 UIKitCore`-[UITableView _updateVisibleCellsNow:] + 3084
    frame #25: 0x0000000109f81b29 UIKitCore`-[UITableView _visibleCellsUsingPresentationValues:] + 524
    frame #26: 0x00000001023d6fcf Client`PhotonActionSheet.setMainMenuTableViewHeight(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:355:69
    frame #27: 0x00000001023d6d66 Client`PhotonActionSheet.setTableViewHeight(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:343:13
    frame #28: 0x00000001023d2694 Client`PhotonActionSheet.viewDidLayoutSubviews(self=0x00007fa01f84bc00) at PhotonActionSheet.swift:168:9
    frame #29: 0x00000001023d26bc Client`@objc PhotonActionSheet.viewDidLayoutSubviews() at <compiler-generated>:0
    frame #30: 0x000000010a3487b3 UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2837
    frame #31: 0x00007ff80898b02c QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 526
    frame #32: 0x00007ff8089965b9 QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 65
    frame #33: 0x00007ff8088a7b0c QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double, double*) + 626
    frame #34: 0x00007ff8088df69b QuartzCore`CA::Transaction::commit() + 735
    frame #35: 0x0000000109d4a35b UIKitCore`_afterCACommitHandler + 105
    frame #36: 0x00007ff800387055 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #37: 0x00007ff8003819c2 CoreFoundation`__CFRunLoopDoObservers + 515
    frame #38: 0x00007ff800381f0d CoreFoundation`__CFRunLoopRun + 1161
    frame #39: 0x00007ff8003816a7 CoreFoundation`CFRunLoopRunSpecific + 560
    frame #40: 0x00007ff809cb128a GraphicsServices`GSEventRunModal + 139
    frame #41: 0x0000000109d15ad3 UIKitCore`-[UIApplication _run] + 994
    frame #42: 0x0000000109d1a9ef UIKitCore`UIApplicationMain + 123
    frame #43: 0x0000000102770ed6 Client`main at main.swift:25:5
    frame #44: 0x0000000104da52bf dyld_sim`start_sim + 10
    frame #45: 0x0000000108a07310 dyld`start + 2432
```

Not sure if this is easy to fix or not, but its usually a good idea to avoid such warnings form UIKit.

(BTW this is from main and 110.2 branches)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5970)

**Comment by lmarceau** [comment] 2023-03-14 14:56
Yes indeed, there's an existing ticket so I'll close this one as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/10548

**Closed by lmarceau** 2023-03-14 14:56 UTC
