### ISSUE TITLE
FXIOS-1579 ⁃ [Bug] Inverted colors after enabling "Night Mode" on duckduckgo.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8122] opened 2021-03-11 11:04 UTC
## Prerequisites
Device Appearance Setting should be set to Dark
Firefox Theme should be set to use System Light/Dark Mode

## Steps to reproduce
1. Navigate to duckduckgo.com
2. Enabled "Night Mode" from the ☰ button
3. Check the website's appearance

### Expected behavior
The website should be properly displayed (black background)

### Actual behavior
Inverted color, the website turns white

### Device & build information
* Device: iPhone 10 (iOS 13.4)
* Build version: Firefox v32.1 (3937)

### Notes
► Video 
![IMG-0265](https://user-images.githubusercontent.com/51314259/110777853-47579b00-826a-11eb-8bf3-53136d44d365.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1579)

**Comment by dnarcese** [comment] 2021-03-11 18:17
Closing as this is intended behaviour currently, until we change how night mode works. Night mode just inverts the colours, so because DDG has its own dark mode, our night mode will then invert that. It isn't yet smart enough to know if the page is already dark.

**Closed by dnarcese** 2021-03-11 18:17 UTC
Labels: Bug 🐞
