### ISSUE TITLE
Open Tabs - An extra tab appears after dragging the tabs.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9756] opened 2022-01-11 12:51 UTC
## Steps to reproduce
Precondition: At least three tabs are open.
1. Open the firefox browser
2. Tap "Open Tabs" button
3. Drag any tab outside the window
4. Close this tab by tapping the X button
5. Drag any tab in the window
### Expected behavior
The tab is dragged. No more changes in the window.
### Actual behavior
An extra tab appears after dragging the tabs.
### Device & build information
* Device: Apple iPhone SE (2016) - iOS 15.0.2
* Build version: firefox daylight 40.2(7167)

https://user-images.githubusercontent.com/66958331/148945713-d9d84f22-02c7-41b9-a084-139b9f65e58d.mp4

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3607)

**Comment by SimonBasca** [comment] 2022-01-11 12:53
This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9717. It's verified fix on v96.0 (7278).

**Closed by SimonBasca** 2022-01-11 12:53 UTC
Labels: Bug 🐞
