### ISSUE TITLE
FXIOS-1007 ⁃ Significant regression in tab restore in recent builds

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#7448] opened 2020-10-04 22:56 UTC
At least twice since installing the latest build I've had my tabs lost — once the evening of 2020-09-30, once today. It has been several years since this regressed. First lost about 70 tabs. Second lost 11 tabs, so this is not a high-volume issue.

This should be a release blocker: it takes some amount of wizardry (hurry to another device, open the Synced Tabs sidebar, find your iPhone, open all in tabs) to recover your working set.

### Device & build information
* Device: iPhone X
* Build version: 2719, but probably the version before, too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2569)

**Comment by aaronraimist** [comment] 2020-10-05 05:44
I also got this bug a few times on the last couple 29.0 TestFlight builds

**Comment by athomasmoz** [comment] 2020-10-05 15:11
@SimonBasca can you try reproducing this one?

**Comment by SimonBasca** [comment] 2020-10-06 11:40
@rnewman by "lost tabs" are you referring that the tabs are closed and gone from tabs tray or that a number of tabs are displayed blank with the empty URL?

**Comment by rnewman** [comment] 2020-10-06 13:26
@SimonBasca tab restore fails: all open tabs are closed.

Just happened to me again:

* open a bunch of tabs.
* go to sleep for eight hours.
* click a GitHub notification email in Outlook. 
* all tabs gone, restore dialog gets instantly dismissed by the external link opening.

**Comment by rnewman** [comment] 2020-10-06 13:27
#7447 covers the inability to recover via the dialog.

**Comment by rnewman** [comment] 2020-10-06 13:41
I see this as the only worrying pattern in the log:

```
preserveTabs(_:selectedTab:) > PreserveTabs write ok: true, bytes: 3076
2020-10-06 06:22:37.284 [Debug] [TabManagerStore.swift:91] preserveTabs(_:selectedTab:) > PreserveTabs write ok: true, bytes: 3115
2020-10-06 06:22:38.255 [Debug] [SentryIntegration.swift:186] printMessage(message:extra:) > Sentry: Tab snapshot error , errorDescription: An unknown error occurred
2020-10-06 06:22:38.857 [Debug] [TabManagerStore.swift:91] preserveTabs(_:selectedTab:) > PreserveTabs write ok: true, bytes: 3124
2020-10-06 06:22:39.302 [Debug] [MetadataParserHelper.swift:38] tab(_:didChangeURL:) > Page contains no metadata!
2020-10-06 06:22:40.978 [Debug] [LoginsHelper.swift:264] requestLogins(_:url:) > Found 2 logins.
2020-10-06 06:22:41.201 [Debug] [TabManagerStore.swift:91] preserveTabs(_:selectedTab:) > PreserveTabs write ok: true, bytes: 3048
```

**Comment by SimonBasca** [comment] 2020-10-08 15:21
We were unable to reproduce this issue on 29.0 (2785) but we are still trying using the STR from https://github.com/mozilla-mobile/firefox-ios/issues/7448#issuecomment-704267676.

**Comment by SimonBasca** [comment] 2020-10-09 14:56
We are still unable to reproduce this issue on v29.0 (2817). @rnewman could you please let me know if this issue is still happening on your side on v29.0 (2817)?

**Comment by rnewman** [comment] 2020-10-09 15:40
I will let you know if it happens again.

**Comment by rnewman** [comment] 2020-10-10 00:51
![99D50522-279F-47E1-8CD2-A2036B2C040C](https://user-images.githubusercontent.com/91722/95641573-10315380-0a58-11eb-9d3a-20c955ab9dcc.png)

**Comment by rnewman** [comment] 2020-10-14 15:04
This has happened to me twice in the last 24h.

**Comment by athomasmoz** [comment] 2020-10-14 15:25
@rnewman thanks for following up. We've been struggling to reproduce this, what OS and Firefox version are you on?

**Comment by rnewman** [comment] 2020-10-14 15:27
Build 2817, OS 13.7, iPhone X.

**Comment by rnewman** [comment] 2020-10-14 15:34
I would typically debug this by just stepping through the entire restore process, looking for what could throw that error, and then broaden that search to include lying API contracts — we found several times over the years non-optional values that were “secretly optional” in WKWebView, and who knows how they might differ during Xcode changes.

I would also head off and fix the sibling issue about offering to try again while an external link is being loaded — the auto-dismiss of the dialog is the really bad data loss, quite apart from the initial failure to restore. That should be extremely easy to simulate with a one-line code change.

**Comment by SimonBasca** [comment] 2020-10-15 12:35
@athomasmoz I was unable to reproduce any crash but I was able to reproduce the tab restoration issue by following these steps:

1. Have a bunch of tabs open
2. Force crash the app from Settings -> Debug menu
3. While the app is still closed due to the crash, open a link from external app.

Actual results:
- The tab restoration dialog is dismissed upon opening the app and all the tabs are closed.

Note:
- This is reproducible on iOS 14.0 and iOS 13.7.

I am guessing that what @rnewman is experiencing on iOS 13.7, is that Firefox is crashing in background and upon opening a link from Outlook the tab restoration dialog gets dismissed.

Also note that on iOS 13.7, this issue it is easily reproduce by opening a link from external app (e.g.Outlook) because Outlook has a option to open links directly in Firefox.

**Comment by rnewman** [comment] 2020-10-15 14:21
What you describe is filed as #7447, FWIW. This bug is for the crash and inability to restore.

**Comment by data-sync-user** [comment] 2020-10-21 16:23
➤ Nishant Bhasin commented:

I wasn't able to reproduce this issue but  made a PR for #7447 and its merged now. Also made sure folks have the latest beta. Please let me know if 2860 still produces this issue and if there are any STR for it.

**Comment by csuciu** [comment] 2020-10-22 14:24
Verifying as fixed on latest master.

**Comment by csuciu** [comment] 2020-10-22 14:28
Filed a followup bug: https://github.com/mozilla-mobile/firefox-ios/issues/7537

**Comment by lmarceau** [comment] 2022-11-21 20:22
Closing this issue as part of cleanup 🧹. Let me know if this shouldn't be the case.

**Closed by lmarceau** 2022-11-21 20:22 UTC
Labels: Bug 🐞, P1, QA Verified, Crash
