### ISSUE TITLE
ipadOS - Hardware Keyboard - cmd-t opens two tabs

### ISSUE THREAD

**Issue by pyrho** [mozilla-mobile/firefox-ios#8824] opened 2021-07-10 17:31 UTC
## Steps to reproduce
- Install firefox from app store
- Launch firefox
- Press CMD-T via a hardware keyboard (in my case a magic keyboard, but I suspect this could happen with any keyboard).

### Expected behavior
One new tab is opened.

### Actual behavior
Two tabs are opened.

### Device & build information
* Device: iPad Pro (11-inch) (3rd generation)
* Build version: Firefox Daylight 34.2 (5301)

### Notes
Attachments: 
https://user-images.githubusercontent.com/145502/125171581-481b2200-e1b5-11eb-9aca-eab5488e03ef.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2940)

**Comment by SimonBasca** [comment] 2021-07-12 08:45
Thanks for the feedback. This issue is a duplicate of #7519

**Closed by SimonBasca** 2021-07-12 08:45 UTC
Labels: Bug 🐞
