### ISSUE TITLE
Long time for cookies to load after starting the browser due to the 'Close Private Tabs' option enabled.

### ISSUE THREAD

**Issue by alcortazzo** [mozilla-mobile/firefox-ios#14030] opened 2023-04-19 19:17 UTC
## Steps to reproduce
1) Download fresh Firefox from App Store.
2) Login to Google account (for example).
3) Do a test search on Google to make sure that we are logged into Google.
4) Enable 'Close Private Tabs' option.
5) Manually close tabs and Firefox using multitasking.
6) Open Firefox and immediately go to Google and do a search.
7) See that Google page opens without cookies, without a session, and with a white default theme.
8) If you refresh the page for a while, you will see that after a while, Firefox will load cookies and the session. 

### Expected behavior
Since I use regular tabs (not private tabs), the option 'Close Private Tabs' should not affect them, only private tabs.

### Actual behavior
Firefox may take a while to load cookies after you start the browser if the 'Close Private Tabs' option is enabled.

### Device & build information
* Device: iPhone 13, iOS 16.4.1
* Build version: Firefox 112.1 (30078)
* First seen version: I'm using an iOS device starting with iOS 16.3 and Firefox ~110 (maybe 111). And this bug has been there all this time.

### Notes
Attachments:
**Here are the video and timecodes:**
- `00:00 - 00:34` — I'm showing the normal behavior of the browser and how it immediately loads cookies after a restart.
- `00:34 - 00:46` — I'm enabling 'Close Private Tabs' option.
- `00:46 - 01:04` — Here I show how the browser cannot load cookies after restarting the browser.
- `01:04 - 01:38` and `01:48 - 02:03` -- Here I show what happens if I refresh the page for a while. After a while, the browser loads cookies.
- `02:15 - 02:53` — Here I turn off the "Close private tabs" option again and show that everything works fine again.

https://user-images.githubusercontent.com/42177346/233177194-0651379f-12ab-4912-a938-7f6b370e809d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6229)

**Comment by dnarcese** [comment] 2023-04-20 18:36
CLosing as duplicate of #13520

**Closed by dnarcese** 2023-04-20 18:36 UTC
Labels: Bug 🐞

**Comment by locolau** [comment] 2023-06-30 10:34
The issue is still here.

**Comment by fwieringen** [comment] 2025-04-22 07:48
Can confirm that this issue is still here on IOS 18.5 and Firefox 137.2 (53903).

1. Close firefox.
2. Reopen firefox with a link to a page where you are sure that you're logged in.
3. Site is not logged in.
4. Refresh after 5 seconds.
5. Site is logged in.

Turned off the "Close private tabs" option.

1. Firefox behaves correctly and cookies are loaded.
