### ISSUE TITLE
[Toolbar Redesign] - Missing search icon in landscape mode

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#22549] opened 2024-10-15 07:41 UTC
## Steps to reproduce
Open app and change orientation to landscape 
### Expected behavior
Search icon should be visible on the toolbar
### Actual behavior
Search icon  is missing from the toolbar
### Device & build information
* Device: iPhone 15 Pro (17.5)
* Build version: 133.0
* First seen version: Yes
### Notes
Attachments: 
<img width="812" alt="Screenshot 2024-10-15 at 10 38 55" src="https://github.com/user-attachments/assets/0b1d3c01-979f-43d7-92e7-febfbbb3a567">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10293)

**Comment by data-sync-user** [comment] 2024-10-15 12:56
➤ Winnie Teichmann commented:

Dragos Bigu When you say search icon do you mean the search engine icon?

**Comment by dragosb01** [comment] 2024-10-15 12:58
<img width="366" alt="Screenshot 2024-10-15 at 15 58 28" src="https://github.com/user-attachments/assets/be28c916-5ebc-4333-8174-afa8c2f01fd7">

**Comment by dragosb01** [comment] 2024-10-15 12:59
> ➤ Winnie Teichmann commented:
> 
> Dragos Bigu When you say search icon do you mean the search engine icon?

No, the magnifying glass located below when in portrait mode

**Comment by data-sync-user** [comment] 2024-10-15 15:44
➤ Matt Lichtenstein commented:

Dragos Bigu I believe this is an intentional design decision since the magnifying glass simply focuses the location text field, making it redundant to put it adjacent to the text field.

cc Aarjav Pandya to confirm

**Comment by data-sync-user** [comment] 2024-10-15 15:48
➤ Aarjav Pandya commented:

Correct. This is intentional.

**Comment by data-sync-user** [comment] 2024-10-15 15:52
➤ Matt Lichtenstein commented:

Closing, as this is expected behavior.

**Closed by data-sync-user** 2024-10-15 15:52 UTC
Labels: Bug 🐞, eng:bug-auto-found, Toolbar redesign📲
