### ISSUE TITLE
[Experiment][Intermittent] If the Firefox app resumes from background after 48h and another 48 have passed the notification is triggered

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/firefox-ios#14808] opened 2023-06-08 11:58 UTC
**[Affected versions]:**
- Firefox Beta 9000 (31343)

**[Affected Platforms]:**
- iOS 15.6 - iPhone 13 mini

**[Steps to reproduce]:**
1. Open the Firefox build.
2. From the Onboarding enable the notification.
3. Close and reopen the Firefox build.
4. From Firefox Settings, tap 5 times on "Firefox 9000 (31343) to enable debug mode.
5. Tap on the "Experiments" option then tap on the "Release iOS re-engagement notifications ..." experiment.
6. Tap on the Control branch. 
7. Sent the Firefox App in the background.
8. Open the iOS Settings -> General -> Time & Date -> Disable the "Set Automatically" option and manually change the date 2 days and 2 minutes in the future.
9. Open the Firefox app, from Firefox Settings, tap 5 times on "Firefox 9000 (31343) to enable debug mode.
10. Tap on the "Experiments" option then tap on the "Release iOS re-engagement notifications ..." experiment.
11. Tap on the Treatment C branch. 
12. Sent the Firefox App in the background.
13. Open the iOS Settings -> General -> Time & Date -> Disable the "Set Automatically" option and manually change the date 2 days and 2 minutes in the future.
14. Close the iOS Settings and wait a few minutes.

**[Expected results]:**
- The notification is NOT triggered.

**[Actual results]:**
- The notification is triggered.

**[Notes]**:
- Here is a screen recording of the issue: [Gdoc](https://drive.google.com/file/d/1cou1CtuyDdOjYCC0b1sGa1UOXu2_xEBR/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6622)

**Comment by data-sync-user** [comment] 2023-06-21 09:37
➤ Winnie Teichmann commented:

Cosmin Muntean could you please test if this is still reproducible? I think the cause was fixed with https://mozilla-hub.atlassian.net/browse/FXIOS-6651 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6651|smart-link )

**Comment by data-sync-user** [comment] 2023-06-23 12:10
➤ Cosmin Muntean commented:

I have verified this issue with the latest Beta 900 (32062) build on iPhone 13 mini (iOS 16.5).

  * With this build, I cannot reproduce the issue anymore. However, not sure if I cannot reproduce this issue because it is fixed or because it is intermittent.
But since I haven't managed to reproduce it with 6 tries I think we are safe to close this one.

**Closed** 2023-06-23 12:28 UTC
Labels: Bug 🐞, S3
