### ISSUE TITLE
[iPad] The URL bar should is focused on the first run while onboarding is displayed

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10850] opened 2022-05-25 08:53 UTC
## Steps to reproduce
1. Clean install Firefox v9000 (9758)
### Expected behavior
- The URL bar should not be focused on the first run.
### Actual behavior
- The URL bar is  focused on the first run.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: v9000 (9758)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/170222872-bd48f0fd-199f-4947-986b-eacf0809924a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4291)

**Comment by dnarcese** [comment] 2022-05-26 19:48
On iPhone, when a user finishes onboarding the keyboard will not popup. We need to decide on one behaviour and make it consistent across iPad and iPhone

**Comment by TwizzyIndy** [comment] 2022-09-10 07:19
As we presented `IntroViewController` as `.formSheet` in `BrowserViewController` below, we can make sure the `presentedController` is presenting as `IntroViewController` in `enterOverlayMode`. And then `self?.urlBar.leaveOverlayMode()` to dismiss the keyboard on iPad. I attached the video I've made changes.

https://github.com/mozilla-mobile/firefox-ios/blob/80a14f81216def268a956bb5fc0dd3c9c5b8d388/Client/Frontend/Browser/BrowserViewController.swift#L2252-L2265

https://github.com/mozilla-mobile/firefox-ios/blob/80a14f81216def268a956bb5fc0dd3c9c5b8d388/Client/Frontend/Browser/BrowserViewController.swift#L1006-L1017

Here is my changes:
```swift
    private func enterOverlayMode() {
        if let viewcontroller = presentedViewController as? OnViewDismissable {
            print("\(#function) presentedViewController is dismissable!")
            viewcontroller.onViewDismissed = { [weak self] in
                let shouldEnterOverlay = self?.tabManager.selectedTab?.url.flatMap { InternalURL($0)?.isAboutHomeURL } ?? false
                if shouldEnterOverlay {
                    self?.urlBar.enterOverlayMode(nil, pasted: false, search: false)
                }
            }
        } else if presentedViewController is IntroViewController {
            self.urlBar.leaveOverlayMode()
        } else {
            self.urlBar.enterOverlayMode(nil, pasted: false, search: false)
        }
    }
```


https://user-images.githubusercontent.com/6712795/189473533-8939e65c-95e1-4347-a40a-02e32d90a902.mov

**Comment by data-sync-user** [comment] 2022-09-23 16:38
➤ Andrei Bodea commented:

This issue still occurs on v106 (*19594*).

**Comment by TwizzyIndy** [comment] 2022-09-24 10:53
@abodea I just tested v106 on iPad Pro(iOS 15.6.1) and couldn't reproduce it. Is there anything I should know about your tested device?

https://user-images.githubusercontent.com/6712795/192093941-fa88ac18-dbbb-48d0-b6d5-2fae0290d9a6.mp4

**Comment by SimonBasca** [comment] 2022-09-26 13:54
@TwizzyIndy we can close this as verified fix since the issue is no longer reproducible following the steps to reproduce on version  106(19594).

Note that while testing this issue we've found two other issues:
1. https://github.com/mozilla-mobile/firefox-ios/issues/12026
2. https://github.com/mozilla-mobile/firefox-ios/issues/12027

**Comment by data-sync-user** [comment] 2022-09-26 13:58
➤ Simion Basca commented:

Winnie Teichmann should we move this to QA Verify? It’s marked as “In Progress” but the PR is already merged.

**Comment by TwizzyIndy** [comment] 2022-09-26 14:11
@SimonBasca I feel really sorry about that. I will take a look at them.

**Comment by data-sync-user** [comment] 2022-09-26 14:40
➤ Winnie Teichmann commented:

Simion Basca I marked as in progress because Andrei Bodea told me the issue is still occurring and I wanted to fix it. Let me verify.

**Comment by data-sync-user** [comment] 2022-09-27 08:59
➤ Simion Basca commented:

Thanks Winnie Teichmann I will close this as completed since the issue is no longer reproducible for both the new and old onboarding when clean installing the app. 
Note that this case is still reproducible : https://mozilla-hub.atlassian.net/browse/FXIOS-5000 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5000|smart-link )

**Closed by data-sync-user** 2022-09-27 08:59 UTC
Labels: Bug 🐞, Contributor Fix, iPad
