### ISSUE TITLE
Replace disabled back button with close-tab button

### ISSUE THREAD

**Issue by julKali** [mozilla-mobile/firefox-ios#10167] opened 2022-03-06 21:49 UTC
### User Problem
When a link is opened in a new tab, both back and forward buttons in the bottom left corner are disabled (as there is no history for this new tab). However, often I just want to quickly read the page's content or do some short interaction and subsequently return to the original page, by closing the new tab again. To do this, I have to go to the tab screen, close the current tab and click on the original one.

### Ideas for Solution
In my view, replacing the back button with a close-tab button if there is no previous page would significantly ease the process described above without significant changes to other UI interactions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3864)

**Comment by SimonBasca** [comment] 2022-03-07 09:35
Thanks for the suggestion @julKali. I think this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9617. I will highlight this feature request with the team for triage. 
Note that we have a way of closing the opened tab by long pressing on the tab counter.

**Closed by SimonBasca** 2022-03-07 09:35 UTC
Labels: Feature-Request
