### ISSUE TITLE
[Experiment] Set Browser as Default message is still displayed if Firefox is set as default before opening the app

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#12483] opened 2022-11-24 14:48 UTC
## Preconditions
- Have the **Firefox Release 108 (22703)** available through TestFlight.

## Steps to reproduce

1. Install Firefox Release from TestFlight but do not open it.
2. Open the iOS Settings and scroll down to the bottom of the list.
3. Tap the Firefox option and tap the Default Browser App option.
4. Select Firefox from the list.
5. Open Firefox and dismiss the Onboarding slides.
6. Observe the top part of the homepage.

### Expected behavior
- The Top Sites section is the first section displayed.

### Actual behavior
- The Set Firefox as Default message is displayed.

## Device & build information
* Device: iPhone XR - iOS 15.3.1
* Build version: Firefox Release 108 (22703)

### Notes
- The issue is reproducible on the `iOS Message Experiment: Default Browser Card Testing` experiment in all branches.
- The issue is reproducible with the default message.
- The issue is also reproducible if Firefox is set as default from the settings menu after it was opened.

Attachments: 

https://user-images.githubusercontent.com/18304511/203806536-10f50815-850e-41ba-93b9-962430ec1e6c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5315)

**Comment by nishant2718** [comment] 2022-11-29 21:57
hi! just wanted some clarity on this one - is this an app upgrade to v108? or a fresh install?

Also, this issue isn't caused by the experiment. Even before we integrated GleanPlumbMessageManager into this part of the app, we didn't have a foolproof way to tell if we're the default browser. Detecting if we are default isn't an API provided to us, so we may not be able to address this ticket either. 

UserDefaults keys are used to give us a somewhat reliable indication of whether we're default. Not the best, but one somewhat accurate solution. If these keys weren't set, we can't really do much about it. 

@dnarcese

**Comment by dnarcese** [comment] 2022-12-01 21:34
Our only way of knowing if you have set firefox as default is if you open a link outside of the app. 
@nishant2718 is checking that that case works. If it does, I don't see this as a blocker.

**Comment by nishant2718** [comment] 2022-12-14 21:49
Could this one get retested? I'm not seeing this happen now and it looks like the codepaths are fine too. 

On [initialization](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/Application/NavigationRouter.swift#L115) of the NavigationPath, we see [it enter here](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/Application/NavigationRouter.swift#L159), which leads to a call into [RatingPromptManager for detecting](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/Application/NavigationRouter.swift#L161
) default browser.

That [gets set as true](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/RatingPromptManager.swift#L75
), and THEN GleanPlumbContextProvider returns whether its default by [accessing the same UserDefaults key](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/Experiments/Messaging/GleanPlumbContextProvider.swift#L22).

So, the context of whether it gets set as default occurs first. Then HomePageViewModel asks for whether that [banner should show](https://github.com/mozilla-mobile/firefox-ios/blob/1f411ec5be2090e36786dcca89a8f3fc88d8edc4/Client/Frontend/Home/HomepageViewModel.swift#L212) (technically, it's asking if that section should show).

So to me, it looks like alls working as expected from that STR.

**Comment by nishant2718** [comment] 2022-12-14 21:51
It could be the case that there are certain race conditions that lead to different behavior as well. I would hope those are minimal, but can't guarantee anything there.

**Comment by data-sync-user** [comment] 2023-01-10 21:21
➤ Orla Mitchell commented:

Closing this issue as without an update from Apple it’s not something we have the ability to address.

**Closed by data-sync-user** 2023-01-10 21:21 UTC
Labels: Bug 🐞, Needs-QA, S2

**Comment by SoftVision-CiprianMuresan** [comment] 2023-01-12 13:58
Sorry for taking so long to reply. The issue is not reproducible if Firefox is opened using a link outside the app. Initially I assumed that we could detect the default change before opening the app or at least as the app is opened.
