### ISSUE TITLE
Pinch to zoom out causes refresh

### ISSUE THREAD

**Issue by croozer2000** [mozilla-mobile/firefox-ios#12725] opened 2022-12-18 22:01 UTC
When pinching to zoom out Firefox will refresh the page. Similarly to pulling down the page all the way.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5456)

**Comment by lmarceau** [comment] 2022-12-19 15:15
Hello, thanks for opening the issue. I'll close this since this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11007. Thanks!

**Closed by lmarceau** 2022-12-19 15:15 UTC
Labels: Bug 🐞
