### ISSUE TITLE
A new private tab is open instead of a normal browsing tab after restarting the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11548] opened 2022-08-09 12:25 UTC
## Steps to reproduce
1. Open a new private tab
2. Tap on tabs tray
3. Switch to normal browsing
4. Tap on the normal browsing tab
5. Close the app from app switcher
6. Launch the app
### Expected behavior
- Normal browsing is open
### Actual behavior
- A new private tab is open in Private browsing
### Device & build information
* Device: iPhone 13 mini 15.4
* Build version: 104.0 (15278)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/183645621-dda3d7cb-3a71-4509-939d-8170e70c9b8d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4727)

**Comment by SimonBasca** [comment] 2022-08-09 12:36
Note that while reproducing this issue, the browsing session can get mixed up. Also after reproducing this issue, closing and opening tabs can lead to a crash

## Crash Log
[Client-2022-08-09-152321.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9290355/Client-2022-08-09-152321.ips.zip)

## Video
https://user-images.githubusercontent.com/32130829/183648252-4ffceadc-bcda-4c6e-83d3-a63709a5ba6e.mp4

**Comment by dnarcese** [comment] 2022-08-18 19:49
duplicate of #11292

**Closed by dnarcese** 2022-08-18 19:49 UTC
Labels: Bug 🐞, Crash
