### ISSUE TITLE
undefined is not an object (evaluating 'webkit.messageHandlers.contextMenuMessageHandler.postMessage')

### ISSUE THREAD

**Issue by chocnut** [mozilla-mobile/firefox-ios#5818] opened 2019-11-27 13:23 UTC
We keep getting this event in our sentry. Does anyone know what is this error about? Thank you!

**Comment by Tobbe** [comment] 2019-12-02 06:17
Same here!
It's a Create-React-App typescript application, and we don't have `postMessage` anywhere in our own code

Here are our dependencies (minus two private packages I didn't want to post here) and devdeps:

```
  "dependencies": {
    "@types/google.analytics": "0.0.40",
    "@types/jest": "24.0.18",
    "@types/jump.js": "^1.0.2",
    "@types/lodash": "^4.14.144",
    "@types/node": "12.7.12",
    "@types/react": "16.9.5",
    "@types/react-dom": "16.9.1",
    "@types/react-redux": "^7.1.4",
    "@types/react-router-dom": "^5.1.0",
    "@types/redux": "^3.6.0",
    "@types/ua-parser-js": "^0.7.33",
    "body-scroll-lock": "^2.3.8",
    "classnames": "^2.2.5",
    "d3-interpolate-path": "^2.0.1",
    "jump.js": "^1.0.2",
    "node-sass": "^4.13.0",
    "qrcode.react": "^0.9.2",
    "query-string": "^6.4.2",
    "react": "^16.10.2",
    "react-animate-height": "^2.0.7",
    "react-app-polyfill": "^0.2.2",
    "react-dom": "^16.10.2",
    "react-flatpickr": "^3.7.1",
    "react-json-tree": "^0.11.2",
    "react-json-view": "^1.19.1",
    "react-number-format": "^4.2.0",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.1.2",
    "react-router-redux": "^4.0.7",
    "react-scripts": "3.2.0",
    "redux": "^4.0.1",
    "typescript": "3.6.4",
    "ua-parser-js": "^0.7.20"
  },
  "devDependencies": {
    "csvtojson": "^1.1.9",
    "moment": "^2.19.1",
    "node-sass-chokidar": "^1.3.4",
    "raven-js": "^3.27.0"
  },
```

**Comment by CryptoSmileee** [comment] 2019-12-05 14:59
We have the same problem. We are using Rollbar instead of Sentry.

**Comment by punarinta** [comment] 2019-12-08 09:22
Same here. Does anyone know if this can be safely ignored? It doesn't seem to have any visual or functional effect.

**Comment by chocnut** [comment] 2019-12-09 01:39
@punarinta, for now, I've added this to ignoreErrors list of Sentry confi

**Comment by anderssv** [comment] 2019-12-09 07:55
Also occurring at our site, only on "Firefox iOS 14.0". Using React create app as well.

**Comment by frankPairs** [comment] 2019-12-09 09:54
Same issue here. Is there any clue about the root of the problem? thanks!

**Comment by Tobbe** [comment] 2020-01-07 09:44
Could it be fixed by this? https://github.com/brave/brave-ios/issues/2026

**Comment by dnarcese** [comment] 2020-03-02 22:29
I'm not seeing this error on Firefox

**Comment by StudioMaX** [comment] 2020-03-03 07:57
Not sure if this will help someone. This error catched at this line in Sentry:
https://github.com/getsentry/sentry-javascript/blob/5.12.1/packages/browser/src/helpers.ts#L96
![изображение](https://user-images.githubusercontent.com/9878458/75753547-3cb01f00-5d55-11ea-8c14-dbfd1b29b376.png)
Raw exception:
```
TypeError: undefined is not an object (evaluating 'webkit.messageHandlers.contextMenuMessageHandler.postMessage')
  at ignoreOnError(./node_modules/@sentry/browser/esm/helpers.js:81:25)
```

**User-Agent**: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/21.0 Mobile/15E148 Safari/605.1.15`

Sentry's additional arguments:
```js
[
  {
    currentTarget: [object Window], 
    isTrusted: [object TouchEvent], 
    target: *some_div_here*
    type: touchstart
  }
]
```

```
browser: Firefox iOS 21.0
browser.name: Firefox iOS
device: iPhone
device.family: iPhone
environment: production
handled: yes
level: error
mechanism: instrument
os: iOS 13.3.1
os.name: iOS
```

**Comment by nbhasin2** [comment] 2020-03-05 19:39
Hi, does anyone have steps to reproduce this? Will be closing this otherwise as I don't errors on my end. cc @chocnut @Tobbe

**Comment by Tobbe** [comment] 2020-03-06 05:25
No, can't reproduce. It has always been coming from our visitors. We have /ignore on that error now. Last time we logged it was Feb 13, by then we had gotten it 110 times. I don't have an iPhone myself to try to reproduce it with.

**Comment by nbhasin2** [comment] 2020-03-06 18:02
Ah, going to close this as we don't have steps to reproduce. Suggestion would be to open a new one if you find steps with more information.

**Closed by nbhasin2** 2020-03-06 18:02 UTC
Labels: 2, P2, eng-ready
