### ISSUE TITLE
Sync crash is our top v29 crash but we don't have these crash symbolicated so there is no way to debug it.

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7588] opened 2020-10-28 17:12 UTC
None of the sync crashes are symbolicated 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/8919439/97471385-0ac07e00-191f-11eb-8869-3ff54de01dcd.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/8919439/97471456-23309880-191f-11eb-8e94-874219cb83a8.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2613)

**Comment by athomasmoz** [comment] 2020-10-28 17:15
We suspect this is the cause of #7508 based on the high crash rate.

**Comment by nbhasin2** [comment] 2021-02-25 17:41
This also seems to be a cause for https://github.com/mozilla-mobile/firefox-ios/issues/8026

**Comment by data-sync-user** [comment] 2021-03-02 21:40
➤ Ashley Thomas commented:

May be resolved with FXIOS-1504 (#8006)

**Comment by data-sync-user** [comment] 2022-06-16 18:31
➤ Laurie Marceau commented:

I don’t see this crash anymore (non symbolicated crashes in Sync). Nishant Bhasin it seems we could close this? What do you think?

**Comment by lmarceau** [comment] 2022-06-16 20:21
Closing since Sync crashes are tracked with other tickets:
- https://github.com/mozilla-mobile/firefox-ios/issues/9484
- https://github.com/mozilla-mobile/firefox-ios/issues/9879

**Closed by lmarceau** 2022-06-16 20:21 UTC
Labels: P2, Crash
