### ISSUE TITLE
The tab count is not updated after opening a new tab

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#17477] opened 2023-11-27 08:44 UTC
## Steps to reproduce
1. Add item to Reading List
2. Long tap on the item just saved in reading list
3. Select to open in New Tab 
### Expected behavior
There should be two tabs open
### Actual behavior
As it can be observed on the screenshots, the tab count is equal to 1, even if on tab tray there are 2 tabs opened.
### Device & build information
* Device: ? <iPhone 15 Pro iOS 17.0>
* Build version: ? <122.0(1), 121.0>
* First seen version: ? Yes
### Notes
Attachments: 
<
<img width="393" alt="Screenshot 2023-11-27 at 10 42 25" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/a3363331-9853-422c-9a2a-5dc0585ebb16">
<img width="374" alt="Screenshot 2023-11-27 at 10 42 35" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/e5eca24b-952a-45e5-b69d-3aea5c21e650">
>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7833)

**Comment by data-sync-user** [comment] 2023-11-27 18:24
➤ Orla Mitchell commented:

I wasn’t able to reproduce this. Is it happening only in the UI tests or is it also reproducible running on a device or simulator in a non test environment?

**Comment by dragosb01** [comment] 2023-11-28 07:04
> ➤ Orla Mitchell commented:
> 
> I wasn’t able to reproduce this. Is it happening only in the UI tests or is it also reproducible running on a device or simulator in a non test environment?

This test was discovered by the UI automation tests and it can reproduced by running testOpenSavedForReadingLongPressInNewTab test.

**Comment by clarmso** [comment] 2023-12-07 21:48
Duplicate of #17679

**Closed by clarmso** 2023-12-07 21:48 UTC
Labels: Bug 🐞, eng:automation, Regression, eng:bug-auto-found
