### ISSUE TITLE
Bookmarks can be added without domain

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11432] opened 2022-07-28 10:59 UTC
## Steps to reproduce
1. Go to the bookmark panel
2. Tap "Edit"
3. Tap "+" button
4. Tap on "New Bookmark"
5. Type a title
6. Type the URL without domain (e.g https://google)
### Expected behavior
- Bookmarks should not be added without domain.
### Actual behavior
- Bookmarks can be added without domain.
### Device & build information
* Device: iPhone 12 Pro (15.5)
* Build version: 104.0 (14377)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/181489734-f60af198-cb87-423c-b895-4a72807b6749.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4644)

**Comment by junbio** [comment] 2022-08-01 16:52
You can edit Safari and Firefox desktop bookmarks to remove the domain and they won't complain.

**Comment by dnarcese** [comment] 2022-09-15 19:28
This is intended behaviour, closing.

**Closed by dnarcese** 2022-09-15 19:28 UTC
Labels: Bug 🐞
