### ISSUE TITLE
"Connect device" QR code scan shows a blank page for incorrect QR codes

### ISSUE THREAD

**Issue by amminer** [mozilla-mobile/firefox-ios#19626] opened 2024-04-03 15:05 UTC
## Steps to reproduce

On device one (Linux Mint Desktop, Firefox 124.0.1):
* Install Firefox
* Log in to firefox
* Application menu -> account -> Connect another device
* Note that the QR code that comes up is to download the app, not to sign in on an already installed device - fine, so when I scan this QR code with a device I want to connect, the device I want to connect should tell me I have the wrong QR code, right?

On device two (iOS, Firefox 124.3):
* Install Firefox
* Application menu -> Sync and save data -> Ready to scan
* Scan the (incorrect) QR code that's displayed on device one.

### Expected behavior

I expect to get some kind of error message or page that tells me I have a bad QR code. Maybe it even recognizes that I've mistaken the "download app" QR code for the "sync new device" QR code and tells me as much.

### Actual behavior

I get a blank white page with no explanation of what's happened. If I haven't had my coffee yet, I might just give up and go back to Chrome instead of recognizing that I scanned the wrong QR code.

### Device & build information

* Device: iPhone 14 Pro, iOS 17.3.1
* Build version: OS build 21D61
* First seen version: New to me, haven't ever tried Firefox iOS before today.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8894)

**Comment by data-sync-user** [comment] 2024-04-04 19:12
➤ Norberto Andres Furlan commented:

Michael Verdi to discuss in our next sync

**Comment by data-sync-user** [comment] 2024-04-11 19:51
➤ Norberto Andres Furlan commented:

Chris Peterson to follow up on this one.

**Comment by cpeterso** [comment] 2024-04-11 19:56
Thanks for reporting this problem. The "Connect Firefox on another device" page is definitely confusing. I'll follow up with the Firefox Sync team.

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/4b0de357-e8c1-4ef4-bad7-8e683b5a24dd)

**Comment by cpeterso** [comment] 2024-04-11 21:41
See also https://github.com/mozilla-mobile/firefox-ios/issues/12599 (from 2022!)

**Comment by data-sync-user** [comment] 2024-04-11 21:43
➤ Chris Peterson commented:

Closing this bug as a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/12599 ( https://github.com/mozilla-mobile/firefox-ios/issues/12599|smart-link ) (from 2022!)

**Closed** 2024-04-11 21:42 UTC
Labels: Bug 🐞

**Comment by amminer** [comment] 2024-04-12 02:32
@cpeterso My pleasure! Happy to have drawn attention to it, sorry I missed the 2022 issue.
