### ISSUE TITLE
[Experiment] The Viewpoint Survey's "Dismiss" button is overlapping with the message when the text size is set to 100%

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#12923] opened 2023-01-11 13:32 UTC
**[Prerequisites]:**
- Have a browser profile enrolled in the Viewpoint Survey experiment on the treatment branch.
- Have the phone’s text size set to 100%.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Observe the viewpoint survey’s message.

**[Expected result]:**
- The survey message and its elements are displayed correctly.

**[Actual result]:**
- The dismiss button is overlapping with the message’s text.

### Device & build information
* Device: iPhone 11 - iOS 16.2

**[Affected versions]:**
- Firefox Release 109.0 (25540)
- Firefox Release 108.1 (24234)
- Firefox Release 107.3 (23248)
- Firefox Release 106.2 (21661)

**[Notes]:**
- The issue is reproducible on the following languages: ES, PL, PT-PT, 
- The dismiss button is not overlapped, but colliding with the text on the following languages: EN, FR, JA
- The issue is NOT reproducible on the following languages: DE, RU, PT-BR, ZH-TW, ZH-CN
- The issue is NOT reproducible when using a smaller or larger text size than 100%.
- The issue is reproducible in both Portrait and Landscape orientations.
- Attached a screenshot of the issue:

![EEEAB41B-9E4B-4B36-9EA6-B2E520762855](https://user-images.githubusercontent.com/40393891/211818813-9742f970-1277-49f1-ad8e-9068f4e61da7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5584)

**Comment by dnarcese** [comment] 2023-01-12 19:43
This is happening here because we do not have a title in the message. Looking for UX advice on what the best solution should be

**Comment by ewachowiak** [comment] 2023-01-23 19:36
@dnarcese Can you please provide the current english body & button copy? I can suggest a headline to resolve the issue.

**Comment by dnarcese** [comment] 2023-01-23 21:29
This is a Viewpoint survey run by the UR team, so we would have to discuss with them if they want to add a title. The body text is "Please help Firefox by taking this short survey". 
The other solution is to change the constraints so that the text does not ever hit the button. But then would need advisory on whether we need to change the margins on both sides to keep it even.

**Comment by ewachowiak** [comment] 2023-01-23 21:58
@lime124  Please advise: I can work on providing a content solution to this problem (adding a title) or UX design can provide guidelines on how to change the margins for this use case.

**Comment by data-sync-user** [comment] 2023-01-23 22:16
➤ Emily Wachowiak commented:

Tiffanie Shakespeare Please see the comment below.

**Comment by ewachowiak** [comment] 2023-01-24 15:26
@dnarcese is the button text "Take Survey"?

**Comment by dnarcese** [comment] 2023-01-24 15:59
@ewachowiak yes

**Comment by lime124** [comment] 2023-01-24 16:23
Emily and I talked offline and she'll work with UR to find a title to
adhere to current patterns of how we use this component.

**Comment by ewachowiak** [comment] 2023-01-24 19:19
@dnarcese I cleared the following headline with Rosanne: "Help Us Make Firefox Better" [iOS] and "Help us make Firefox better" [Android].

1. Can we get this update released on Android and iOS?
2. What would be the timing of this release?
3. Does translation of this string need to be handled outside of the release process?

**Comment by dnarcese** [comment] 2023-01-24 20:56
@ewachowiak this survey is something that the UR team sets up, so they would be the ones you need to coordinate with. They use the messaging framework so are not tied to a release. Also not sure how they handle localization.

**Comment by ewachowiak** [comment] 2023-01-24 21:36
Ok, I've reached out to El and filled out this document as requested by their team for translation. https://docs.google.com/spreadsheets/d/1bdFL0QrSNhCPDNgPZvB40NvhLtJNQkF4Fthy-hVaxcM/edit#gid=0

The UR team will be in charge of updating and deploying this.

**Closed** 2023-03-14 00:53 UTC
Labels: Bug 🐞, Needs-UX

**Comment by SoftVision-CiprianMuresan** [comment] 2023-10-23 12:04
Marking this issue as `wontfix` as the issue is still reproducible with all the Viewpoint Survey experiments until May (including). The issue is no longer reproducible with the Surveys from June onward because those use the `survey` surface.
