### ISSUE TITLE
Removing unused strings from previous releases

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12157] opened 2022-10-17 21:02 UTC
**Problem**

We remove unused strings from `main` before the release happen. This potentially means we’ll remove strings to be translated too soon from Pontoon.

**Discussion**

We should wait for a particular release to be done before we remove the string from our strings file. Android tag them as `moz:removed` with the version number, and at the end of each release someone cleans that up. We need a process to have this in place on our side as well.

**Android implementation**

Their documentation: [https://github.com/mozilla-mobile/fenix/wiki/Removing-strings](https://github.com/mozilla-mobile/fenix/wiki/Removing-strings|smart-link)

Some examples in PRs:

* [https://github.com/mozilla-l10n/android-l10n/commit/f5ae74a890e756297e9f9bae253356a7b376b856](https://github.com/mozilla-l10n/android-l10n/commit/f5ae74a890e756297e9f9bae253356a7b376b856|smart-link)
* [https://github.com/mozilla-l10n/android-l10n/pull/503/files](https://github.com/mozilla-l10n/android-l10n/pull/503/files|smart-link)
* [https://github.com/mozilla-l10n/android-l10n/pull/495/files](https://github.com/mozilla-l10n/android-l10n/pull/495/files|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5094)

**Comment by Delphine** [comment] 2023-06-20 22:57
This seems to have fallen through the cracks, after an All-Hands discussion between iOS and l10n teams.

Apparently this is currently still done manually by iOS devs (ie removing unused strings for each release) but the process is not documented (or automated) yet, so this can lead to issues down the road (such as removing strings too early, or too late, or not at all)

It's important we remove strings like Android does for various reasons - one of them being that if strings remain while they are no longer in use, localizers are still spending time working them on Pontoon.

I see Android's documentation above has moved to the monorepo, so now it lives here: https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/docs/Working-with-Strings.md

CC @dnarcese and @jevans-mozilla for visibility

**Comment by lmarceau** [comment] 2023-06-28 19:51
Had some discussion with Delphine on this. My current understanding is the following; 

Android uplift strings imports from main to release branches, where in our case we point the string import automation script to run against the release branch directly. This means theoretically that strings that are removed in main will not be removed from the release branch, but only IF our timing for string import/export stay the same as is (which could easily become a problem in the future). If our string export (from Firefox iOS -> l10n) was happening earlier, or the string import towards the release branch (l10n -> Firefox iOS) was happening later, we could mistakingly remove strings from release branches since the string would not exist anymore in the l10n repository. 

### An example
Let's say in our example that a developer removes a string for v116 that is used in v115.
1. The developer removes the strings from the `main` branch, which is v116
2. The string export (Firefox iOS -> l10n) hasn't happened yet, and so string import pointing to release branch aren't affected, the v115 string is still there.
3. The last string import towards the v115 release branch is done on hard freeze day. As stated in point 2, the v115 string is not removed.
4. The string export (Firefox iOS -> l10n) is done **after** the v115 hard code freeze day. The v115 string is then removed from l10n.

In the example, if steps 3 and 4 are inverted, we would remove the string from v115 which is still in use there. This means our process is currently very time sensitive. If hard freeze day was delayed for some reason and string import happened later than we would have issues with our strings which could prevent us from importing strings toward the release branch.

### An easy fix
The easy fix would be to keep strings in our `Strings.swift` file even if they aren't used in `main` anymore, and remove then once the release has been made as Android is doing. This mean would be a manual process, and so is error prone. An ideal way would be to automate it.

**Comment by Delphine** [comment] 2023-06-28 21:42
I guess then the issue is when strings change during the release cycle, since they are now imported weekly.
I'm not sure though if the specific scenario above avoids issues, flagging @flodolo for more info in case

**Comment by flodolo** [comment] 2023-07-19 08:43
> The string export (Firefox iOS -> l10n) is done after the v115 hard code freeze day. The v115 string is then removed from l10n.

This is not correct. The string export used to be manually run by developers, it's now [automated and running weekly](https://github.com/mozilla-l10n/firefoxios-l10n/blob/main/.github/workflows/import_strings.yml).

So, in your example, if you remove a string from `main` early in the cycle because unused in v116, we'll very likely remove it also for v115. 

> The easy fix would be to keep strings in our Strings.swift file even if they aren't used in main anymore, and remove then once the release has been made as Android is doing. This mean would be a manual process, and so is error prone. An ideal way would be to automate it.

I agree.

**Comment by Delphine** [comment] 2023-08-01 18:45
Hi @lmarceau  - circling back on this to check on next steps and timeline so we can then close this issue :) Please let me know! thanks

**Comment by data-sync-user** [comment] 2023-08-10 15:54
➤ Laurie Marceau commented:

I documented the process in https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-add-and-modify-Strings ( https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-add-and-modify-Strings|smart-link ) , hopefully this reflects properly what we need

**Closed** 2023-08-10 19:38 UTC
