### ISSUE TITLE
Hamburger menu slow to open after going from the homepage to a webpage

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12234] opened 2022-10-26 15:12 UTC
## Steps to reproduce v1
1. Go to Homepage.
2. Open hamburger menu.
3. Tap on the "Help" button.
4. In the support page that opens try to open again the hamburger menu.

## Steps to reproduce v2
1. Go to Homepage.
2. Open hamburger menu 
           => The menu opens instantly.
4. Dismiss the menu and go to to a webpage via search bar.
5. Try to open the menu immediately after the page loads.

### Expected behavior
The menu opens instantly.
### Actual behavior
It takes up to 10 seconds for the menu to open.
### Device & build information
* Device: iPhone 6S 
* Build version: v107 (20813)
                          v106 (20303)
### Notes
1. From what I noticed this happens when the menu switches from the Homepage to the webpage version.
2. Wasn't able to reproduce on newer devices (iPhone 12, 13)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5158)

**Comment by dnarcese** [comment] 2022-10-27 19:21
duplicate of #12235

**Closed by dnarcese** 2022-10-27 19:21 UTC
Labels: Bug 🐞

**Comment by dnarcese** [comment] 2022-10-27 19:23
@csuciu which iOS version were you seeing this on?
