### ISSUE TITLE
 Firefox iOS crashes when deleting website data

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6818] opened 2020-06-19 09:59 UTC
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

Steps to reproduce:

I'm using Firefox 26.0 (18099) on iOS 12.1.1.

    Open Settings
    Go to Data Management -> Web Site Data
    Search for something, e.g. 'google'
    Delete the entries one by one

Actual results:

    After clicking 'Delete', the corresponding entry sometimes doesn't disappear
    After deleting a few entries, Firefox crashes

Expected results:

    Deleted entries immediately disappear
    No crash

VIa : https://bugzilla.mozilla.org/show_bug.cgi?id=1645961

Video : https://bugzilla.mozilla.org/attachment.cgi?id=9156889

**Comment by athomasmoz** [comment] 2020-07-03 16:48
@SimonBasca can you try this one. Nish wasn't able to reproduce and automated test is not failing.

**Comment by SimonBasca** [comment] 2020-07-06 07:53
I was unable to reproduce this issue. I tested on both iOS 12.x and iOS 13.x but with no success of reproducing. The reporter, which was able to reproduce this constantly was using Firefox 26.0 (18099) on iOS 12.1.1. 

In the past we had some memory issues that caused different crashes and I asked the reporter about the memory usage. Here is the reply :  

"Probably not very accurate, but I just installed an app called 'Lirum Info Lite', searched again for 'Google' in Web Site Data, then quickly switched to this app, and here are the numbers:

Total: 2GB
Free: 140.4109MB
Active: 539.3940MB
Wired: 315.0643MB
Inactive: 503.9227MB

The usage looks alright I guess?"

**Comment by SimonBasca** [comment] 2020-07-06 09:48
We have a report that seems to be related to this #6875.

**Comment by garvankeeley** [comment] 2020-07-16 15:58
This fix https://github.com/mozilla-mobile/firefox-ios/pull/6876 for #6875 seems like a big improvement in keeping this listview properly, and seems like this better sync between data source and the list might fix this crash.

Closing for now because it isn't repro'ing, and my hope that PR fixed any edge-case.

**Closed by garvankeeley** 2020-07-16 15:58 UTC
Labels: Bug 🐞
