### ISSUE TITLE
Theming System - URL Bar - Dark mode - Tabs tray button doesn't turn blue while it is tapped  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14858] opened 2023-06-09 12:45 UTC
## Steps to reproduce

- Fresh install the FF app while device is in Dark mode
- Open a web page 
- Tap on the tabs tray button 

### Expected behavior
The button turns blue while it is tapped. The behavior must be consistent with the other buttons on the URL bar (Please see the video attached)

### Actual behavior
The button doesn't turn blue while it is tapped. 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 115 (31602)
* First seen version: ? 
### Notes
same issue reproduces on iPad also  

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/40582858-235c-44ec-89b6-26e2d6ea6e22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6649)

**Comment by data-sync-user** [comment] 2023-06-29 18:52
➤ Laurie Marceau commented:

For QA, I think this was fixed by another ticket. Can be tested for v116

**Comment by data-sync-user** [comment] 2023-07-07 10:54
➤ Alina Moldovan commented:

Validated this issue using FF v116 (32475) and iPhone 14+ (16.0.3) and iPad Air 3rd Gen (16.3.1) 

Not able to reproduce this issue anymore

**Closed by data-sync-user** 2023-07-07 10:54 UTC
Labels: Bug 🐞, S4, Theming System
