### ISSUE TITLE
Black welcome text of Reading List when in night mode

### ISSUE THREAD

**Issue by arvinshen** [mozilla-mobile/firefox-ios#10838] opened 2022-05-21 22:40 UTC
## Steps to reproduce
* 'Use System Light/Dark Mode' system theme settings turned on
* Default iOS appearance set to 'Light'
* Turn on Night Mode
* Go to Reading List

### Expected behavior
* White text with dark background

### Actual behavior
* Black text with dark background

Device & build information

* Device: iPhone 13 Pro (15.5)
* Build version: 101.0 (9619)

Attachments:
![Simulator Screen Shot - iPhone 13 Pro - 2022-05-21 at 15 01 24](https://user-images.githubusercontent.com/36750649/169671106-4205b794-5dcc-4369-ae1a-cafd32e9493a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4286)

**Comment by data-sync-user** [comment] 2022-05-26 19:52
➤ Daniela Arcese commented:

Looks like the library panel text and icons are following the system theme instead of the app theme.

**Comment by SimonBasca** [comment] 2022-10-31 15:46
This issue is no longer reproducible on v9000 (21167) or v106 (20813). It was possibly fixed by https://github.com/mozilla-mobile/firefox-ios/issues/11825. Please re-open if it's still an issue on your side.

**Closed by SimonBasca** 2022-10-31 15:46 UTC
