### ISSUE TITLE
Old tabs not showing not only thumbnails, but also URLs and/or titles

### ISSUE THREAD

**Issue by mehov** [mozilla-mobile/firefox-ios#8984] opened 2021-08-11 04:24 UTC
Hi everyone, 

Related issues:

- #7819
- #8524

In my case, not only the previews are not displaying, but also the URLs and/or titles, so I figured it may be a different issue.

## Steps to reproduce

Have a bunch of old tabs that survived app restarts, device reboots and iPadOS upgrades.

### Expected behavior

Knowing which tab leads where

### Actual behavior

Only the favicons are showing. 

![IMG_75C4ED7454FE-1](https://user-images.githubusercontent.com/7813306/128966474-70f1d735-40bb-4859-b9e3-ce1ec17193c0.jpeg)

(You can see the same behaviour in the aforementioned #8524.)

### Device & build information
* Device: iPad OS 13.? → 14.7
* Build version: ?

### Notes

Luckily, this time the favicons seem to match the website it goes to when I tap on any of these tabs (I remember seeing tabs use wrong favicons previously). So that confirms the browser remembers the website I had in a given tab. 

Another thing I noticed, after I go to one of these blank tabs, and then go back to the tab switcher and close the tab, the browser moves the blue "cursor" onto the next tab I have in the grid, and after a few moments, that tab restores and shows its title:

![IMG_88FE511D642B-1](https://user-images.githubusercontent.com/7813306/128968149-e3147797-3333-49b3-b231-46e9c354b89e.jpeg)

Judging by the delay, it may be re-fetching the title from the actual website, so that may mean a different title from what I had when I initially went to that tab, as well as making a duplicate hit to that page, which may be unwanted in some cases (e.g. privacy/security reasons: the tab was initially opened in a different country or over a VPN connection, which now happens to be off).

Another way for me to figure out what a given blank tab thumbnail holds would have been to press and hold it, and that could potentially give me an option to copy the URL, but currently it doesn't seem to do that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3064)

**Comment by dnarcese** [comment] 2021-08-11 17:05
Closing as duplicate of #8942

**Closed by dnarcese** 2021-08-11 17:05 UTC
Labels: Bug 🐞
