### ISSUE TITLE
Wrong favicon size in bookmarks and shortcuts

### ISSUE THREAD

**Issue by LMattsson** [mozilla-mobile/firefox-ios#12534] opened 2022-11-29 12:34 UTC
## Steps to reproduce
1. Open test.html in Firefox on iPadOS
2. Select 'Add ⭐' to add it as a bookmark
3. Open Bookmarks and see that a large favicon is displayed in a small size

### Expected behavior
Since icon size 64 is provided by the ICO, and it's pretty close in size, it should have been chosen.

### Actual behavior
The icon is displayed as 56x56px, but Firefox chooses the icon size 192x192px.

### Device & build information
* Device: iPad mini (6th generation)
* Build version: 107.0 (21907)

### Notes
The attached ICO used by test.html has icons labelled with their respective sizes in green text.

Attachments: 
[test.zip](https://github.com/mozilla-mobile/firefox-ios/files/10113040/test.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5350)

**Comment by LMattsson** [comment] 2022-11-29 12:38
Screenshot of the issue
![firefox_bookmarks](https://user-images.githubusercontent.com/70215710/204531020-b574602d-5b1b-448b-807c-efe3a78911ef.png)

Note that the same thing as with bookmarks happens with shortcuts on the new tab page.

**Comment by lmarceau** [comment] 2022-11-29 15:44
Current favicon system prefers high res icons to then scale it down whenever it's needed. If we have the high resolution, the low resolution icon isn't saved. I'll close this issue as this works as intended, we're not looking to pursuing that level of optimization at this point for favicons. Thank you!

**Comment by LMattsson** [comment] 2022-11-30 13:45
Note that Firefox on iPadOS uses icons of different sizes. 
We used this set of icons:
* apple-touch-icons: 76, 80, 114, 120, 152, 167, 180
* ICO icons: 16, 24, 32, 48, 64, 96, 144, 192

This resulted in the 80x80 icon being used for the tab, and the 180x180 icon being used for the "Share" pop-up (see the screenshot in #12546). As above, the 192 icon was used for bookmarks and shortcuts.

I understand your point and think it's fair. However, this puts us in a difficult position since we want to design our icon differently depending on the size. 

If customised icons isn't possible in Firefox on iOS, we would need a special icon designed for any size just for Firefox on iOS. How could we make sure that this special icon is chosen only for Firefox on iOS?

**Comment by lmarceau** [comment] 2022-11-30 16:13
Thanks @LMattsson, I understand the issue better. I'm looking into how we could adjust current solution, and if it's feasible to adjust in the short term, or if this would be more of a long term improvement. I'll reopen the ticket for now.

**Comment by OrlaM** [comment] 2023-03-07 15:01
I have created a feature request ticket outlining what needs to change with the favicon system in order to address this. I will close this issue in favour of that one because it outlines what work needs to be done.

**Closed by OrlaM** 2023-03-07 15:01 UTC
Labels: Bug 🐞
