### ISSUE TITLE
Slashed lock icon displayed on Reader Mode

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#16400] opened 2023-09-14 18:47 UTC
## Steps to reproduce
1. Open a news website. (I picked [https://www.cbc.ca](https://www.cbc.ca/).)
1. Open a new article.
1. Click :scroll: icon from the awesome bar for reader mode.

### Expected behavior
No lock icon should show when in reader mode

### Actual behavior
Slashed lock icon is displayed on Reader Mode.

### Device & build information
* Device: iPhone 14 16.4 Simulator
* Build version: Nightly (Sept 14)
* First seen version: Not sure

*# 
*## Notes

Note that no slashed icon is displayed on non-reader mode.

Attachments: 

![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/12806159-1701-4b5b-a8aa-7c5657571a86)

![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/66f746eb-0946-4813-9f69-63d48d7ab894)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7402)

**Comment by cpeterso** [comment] 2023-09-15 04:29
I think this bug is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/10623.

**Comment by CHEFSUSHIWILL1** [comment] 2023-09-15 12:42
Thank You For Being So Help Phone @sirn @badboy @dnarcese @clarmso @cpeterso

**Comment by CHEFSUSHIWILL1** [comment] 2023-09-15 12:42
@cpeterso @clarmso @dnarcese @badboy @sirn

**Comment by csuciu** [comment] 2024-02-26 11:09
This is fixed in the latest version.

**Closed by csuciu** 2024-02-26 11:09 UTC
Labels: Contributor OK, Bug 🐞
