### ISSUE TITLE
The fake link fails to be generated in the child page

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#15903] opened 2023-08-04 10:59 UTC
## Steps to reproduce
The following steps are based on the automation test affected
1. Reach settings and disable block popups
2. Open "test-mozilla-org.html" (can be found here https://github.com/mozilla-mobile/firefox-ios/tree/main/test-fixtures)
3. Open as a child windows "test-window-opener.html" (same link as above)
### Expected behavior
A fake link used to be visible on 116. See screenshot
### Actual behavior
The page is blank, no fake link is generated. See screenshot
### Device & build information
* Device: iPhone 14 Pro Max, iOS 16.4
* Build version: 117
* First seen version: 117
### Notes
Affected automation test: testWriteToChildPopupTab

Attachments: 

<img width="384" alt="116" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/ac7c38f3-4ae7-468f-8b8f-3357cb5a942e">
<img width="384" alt="117" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/96e01920-c010-49e2-b036-036b224144ce">

**Comment by clarmso** [comment] 2023-08-08 15:45
Yes, this issue is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/15914

**Closed by clarmso** 2023-08-08 15:45 UTC
Labels: Bug 🐞, Regression, eng:bug-auto-found
