### ISSUE TITLE
[regression] Sharing to Firefox with “Load in Background” no longer works

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#23110] opened 2024-11-14 03:05 UTC
## Steps to reproduce

1. In another app, open the iOS Share menu for some web link. 
1. Select "Firefox Beta" (though technically I am using Firefox Nightly 9000 (47503), not Beta.)
1. Select “Load in Background”. (If you instead select "Open in Firefox", then the shared link will open in Firefox as expected.)
1. Switch to Firefox Beta. 

### Expected behavior

The shared link should open in a new tab. 

### Actual behavior

The shared tab doesn’t open.

This regression is a recurrence of https://github.com/mozilla-mobile/firefox-ios/issues/12414 from Fx 108.

### Device & build information

* Device: iPhone 15 Plus running iOS 18.1
* Build version: Nightly 9000 (47503)
* First seen version: This bug is a regression in Nightly 9000 (47350). The previous Nightly build, 9000 (47291), works correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10547)

**Comment by cpeterso** [comment] 2024-11-14 03:48
It is 100% consistent for me with one caveat about Twitter:

* In the Twitter app, I can reproduce when long-pressing and sharing a link directly in a tweet, but NOT if I open the link within the Twitter app and then share from Twitter's WebView (i.e. "Load in Background" works from Twitter's WebView).
* But sharing from Instagram's WebView does NOT work.
* Sharing a link from an email in the Gmail app doesn't work.

**Comment by data-sync-user** [comment] 2024-11-28 00:39
➤ Chris Peterson commented:

I’m going to close this bug because I can no longer it, even when testing the build I originally reproduced this bug in.

I don’t know what changed. I did update from iOS 18.1 to 18.1.1 since reporting this bug, but I doubt that fixes this issue.

**Closed** 2024-11-28 00:39 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2024-11-28 00:46
➤ Chris Peterson commented:

While I can no longer reproduce this “Load in background” issue, now the Share menu’s “Open in Firefox” no longer works for me:

https://github.com/mozilla-mobile/firefox-ios/issues/23443 ( https://github.com/mozilla-mobile/firefox-ios/issues/23443 )

**Comment by cpeterso** [comment] 2025-01-25 22:20
I reopened this bug because I can reproduce it again when trying to share a video from the YouTube app to Firefox using “Load in Background”.

Device: iPhone 15 Plus running iOS 18.2.1

**Comment by data-sync-user** [comment] 2025-01-27 17:13
➤ Matt Reagan commented:

Note: the older comments regarding the Beta vs main build test results can likely be ignored for this newer regression, looks like a different underlying culprit.

**Comment by data-sync-user** [comment] 2025-02-17 14:52
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v136(51014), with iPhone 15 (17.6) and iPad Air 3rd gen (18.2).

!RPReplay_Final1739803884.mp4|width=590,height=1280,alt="RPReplay_Final1739803884.mp4"!
