### ISSUE TITLE
FXIOS-927 ⁃ [iOS 14] Pin to Top Site is not working

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7346] opened 2020-09-18 14:27 UTC
## Steps to reproduce
1. Clean install Firefox
2. Go to "google.com"
3. Open Page Action menu
4. Tap "Pin Top Site"
### Expected behavior
- "google.com" should have been pinned to Top Sites
### Actual behavior
- "google.com" is not pinned to Top Sites
### Device & build information
* Device: iPhone Xr
* Build version: 6746b5f
### Notes
- Not reproducible on main 6746b5fe running iOS 13.7
- Not reproducible on 28.2 (2470) running iOS 14.0
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-927)

**Comment by data-sync-user** [comment] 2020-09-22 15:12
➤ Ashley Thomas commented:

On iOS14, if you background and come back to app it gets pinned to top site

**Comment by slinging89** [comment] 2020-09-22 15:15
么。这种are you talking to me

**Comment by boek** [comment] 2020-09-23 04:12
Took a shot at looking into this and it looks like the query called [here](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Widgets/PhotonActionSheet/PageActionMenu.swift#L99) which calls [this](https://github.com/mozilla-mobile/firefox-ios/blob/main/Storage/SQL/SQLiteHistory.swift#L148) isn't getting any results. I pulled the sqlite database from my phone and for some reason the history item is there but there is nothing in the `view_favicons_widest` view. 

Also I tried reproducing
> On iOS14, if you background and come back to app it gets pinned to top site
and wasn't able to get it pinned

**Comment by dnarcese** [comment] 2020-09-24 17:34
Fixed in https://github.com/mozilla-mobile/firefox-ios/issues/7346

**Closed by dnarcese** 2020-09-24 17:34 UTC
Labels: Bug 🐞, P1, iOS14

**Comment by SimonBasca** [comment] 2020-09-25 11:46
Verified fix on main 8f59ee4e2.
