### ISSUE TITLE
FXIOS-850 ⁃ Tab Sending doesn’t work, “Tap to Begin”

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/firefox-ios#7265] opened 2020-09-04 02:09 UTC
## Describe the bug
1. Open a tab on Firefox Windows.
2. Send Tab to iPhone.

### Expected behavior
I get to my tab on my iPhone.

### Actual behavior
I get a "Firefox Sync: Tap to begin" notification, and tapping it opens Firefox and opens no tabs. 

### Device & build information
* Device: iPhone XS, iOS 14 Public Beta 6
* Build version: 28.1 (19225)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-850)

**Comment by marijane** [comment] 2020-11-13 00:53
I have been observing the behavior described in this issue starting some time this week.
I signed in and out of my Firefox Sync account but that has not resolved the problem.

Device: iPhone XS, iOS 14.2
Firefox version: 29.1 (3022)

**Comment by SimonBasca** [comment] 2020-11-18 16:56
I am currently unable to reproduce this issue on Firefox 29.1 (3022) and on latest beta 29.2 (3120). 
@marijane I am wondering if there is any change to sync settings that you've done before this issue started occurring?

**Comment by marijane** [comment] 2020-11-18 17:19
@SimonBasca No, I had not made any changes to the sync settings.  I think the last change I made to the phone environment prior to observing this problem was an iOS upgrade.

**Comment by marijane** [comment] 2020-11-18 17:19
Also, while I cannot send tabs to my phone, I can send tabs from it, so it's not a two-way problem.

**Comment by lolrepeatlol** [comment] 2020-11-18 17:22
By the way, I don't have this issue anymore, it randomly stopped.

**Comment by SimonBasca** [comment] 2020-12-21 11:57
Closing for now and will re-open if consistent STR are found.

**Closed by SimonBasca** 2020-12-21 11:57 UTC
