### ISSUE TITLE
FXIOS-1831 ⁃ Map link opens unlimited number of new tabs

### ISSUE THREAD

**Issue by mtreichel** [mozilla-mobile/firefox-ios#8506] opened 2021-05-14 18:57 UTC
The link just below the map on this site

https://www.tripadvisor.com/Restaurant_Review-g298484-d11913521-Reviews-Fitness_cafe_Onegin-Moscow_Central_Russia.html

opens an unlimited number of new tabs in very rapid sequence. This can only be stopped by killing the app. 

* Device: iPhone 11
* Build version: Firefox Daylight 33.1 (4629)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1831)

**Comment by SimonBasca** [comment] 2021-05-17 08:51
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/7466

**Closed by SimonBasca** 2021-05-17 08:51 UTC
Labels: Bug 🐞
