### ISSUE TITLE
Screenshots on Tabs have become low resolution to the point of glitchy

### ISSUE THREAD

**Issue by mgaudet** [mozilla-mobile/firefox-ios#14515] opened 2023-05-23 15:22 UTC
## Steps to reproduce

Have tabs open

### Expected behavior

Tab screenshots are appropriately high resolution

### Actual behavior

Tabs screenshots are low res / over-compressed looking; see screenshot below. 

### Device & build information
* Device: ? iPhone 13 Pro, 
* Build version: Firefox 113.1 (30885)
* First seen version:  Unsure, but this is recent? (2 weeks?)
### Notes
Attachments: 

![Screenshot 2023-05-20 at 9 01 58 AM](https://github.com/mozilla-mobile/firefox-ios/assets/2906003/8fb184b7-7564-4144-9c89-6aa131dee8dc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6452)

**Comment by OrlaM** [comment] 2023-05-23 18:09
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13855
A fix for this is included int he next version, v114.

**Closed by OrlaM** 2023-05-23 18:09 UTC
Labels: Bug 🐞
