### ISSUE TITLE
The iOS Re-engagement Notification is redisplayed after a user taps it

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla-mobile/firefox-ios#14920] opened 2023-06-13 12:27 UTC
**[Affected versions]:**

* Firefox Beta 9000 (31690)

**[Affected Platforms]:**

* iOS 16.2

**[Affected Devices]:**

* iPhone Xr

**[Prerequisites]:**

* Have Firefox notifications enabled.

**[Steps to reproduce]:**

1. Open the browser and tap the hamburger menu button from the bottom-right part of the screen.
1. Select the "Settings" option and scroll down to the bottom part of the menu.
1. Tap the "Firefox Beta 9000 (31690)" option 5 times.
1. Scroll down to the "Debug" section and select the "Experiments" option.
1. Tap the "Edit" button from the top-right part of the screen.
1. Tap on the "Use Preview Collection" radio button and restart the app.
1. Repeat steps from 1 to 5.
1. Tap the "Reset" button from the bottom part of the screen.
1. Tap the "Back" button from the top-left part of the page.
1. Tap the "[mcoman] [QA-1886] Feature configuration testing for notifications on iOS" experiment and select the "treatment-k" branch.
1. Restart the app and send it to the background.
1. Change the system time to 2 days and 2 minutes in the future.
1. Tap on the Firefox notification and send the browser to the background.
1. Change the system time to 2 days and 2 minutes in the future.
1. Observe the behavior.

**[Expected result]:**

* The Firefox notification is no longer triggered.

**[Actual result]:**

* The Firefox notification is triggered.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6686)

**Comment by data-sync-user** [comment] 2023-06-21 09:36
➤ Winnie Teichmann commented:

Marius Coman could you please test if this is still reproducible? I think the cause was fixed with https://mozilla-hub.atlassian.net/browse/FXIOS-6651 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6651|smart-link )

**Comment by data-sync-user** [comment] 2023-06-22 09:21
➤ Marius Coman commented:

Hi, Winnie Teichmann! I have tested this issue using the same steps as before and it seems that is still reproducible. The notification is triggered even if a tap action was previously performed on it.

Tested using  Firefox 9000 (32023) and Firefox 115.0 (31980) installed on a iPhone Xr device (iOS 16.2).

**Comment by data-sync-user** [comment] 2024-03-20 18:00
➤ Norberto Andres Furlan commented:

Andrei Bodea Alina Moldovan can you check if this issue is still reproducible? I am not able to reproduce. If not, lets close it. Thanks!

**Closed** 2024-03-20 18:01 UTC
Labels: Bug 🐞, S2
