### ISSUE TITLE
FXIOS-1192 ⁃ PDFs shared from Firefox with Pocket don’t show up in the Pocket app

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#7632] opened 2020-11-07 08:54 UTC
## Steps to reproduce

0. Have a Pocket account and the Pocket iOS app installed. 
1. Open a PDF in Firefox iOS, such as https://rifters.com/real/shorts/PeterWatts_Hotshot.pdf
2. Open “Share Page With” menu. 
3. Share with Pocket. 
4. Open the Pocket iOS app. 

### Expected behavior

The shared PDF should show up in my Pocket article list. 

### Actual behavior

The shared PDF does not show up in my Pocket article list.

I believe this is a Firefox iOS bug, not a Pocket bug. If I open the same PDF in Safari and share it with Pocket from Safari, the PDF shots up in my Pocket article list as expected. I’m also 90% confident this is a recent regression and that sharing PDFs from Firefox to Pocket used to work correctly.

### Device & build information
* Device: iPhone 8 running iOS 14.1
* Build version: Firefox Beta 29.0 (2817) and Pocket 7.28.3

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1192)

**Comment by dnarcese** [comment] 2021-02-04 17:24
Investigate whether this is affecting other apps and not just Pocket

**Comment by SimonBasca** [comment] 2021-02-05 12:01
I believe this issue might be similar to https://github.com/mozilla-mobile/firefox-ios/issues/7933#issuecomment-773898912 because we are not sharing the URL correctly from Firefox.

I am unable to share PDF files via messenger apps but I was able to share to the PDF from Firefox to "Books".

**Comment by bentsionmp** [comment] 2021-02-06 18:36
It happens to every single file not just PDFs if I download a file (TeamViewer_Setup.exe for example) and want to share it from the browser it will send a link with the path:

file:///private/var/mobile/Containers/Data/Application/A2ED0D25-A722-4516-AB70-4CDBD36FDB7A/Documents/Downloads/TeamViewer_Setup.exe

instead of sending the actual file.
On safari it's easily done with no problem.

**Comment by dnarcese** [comment] 2021-02-18 16:56
Closing as a dupe of #7933

**Closed by dnarcese** 2021-02-18 16:56 UTC
Labels: Bug 🐞
