### ISSUE TITLE
Firefox gets stuck and then crashes when multitasking outside of FF and then back

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19277] opened 2024-03-18 16:30 UTC
## Steps to reproduce
1. Launch FF and access https://63p8v.csb.app/.
1. Tap on the username field.
1. Tap on the Use saved password.
1. Tap on the manage passwords.
1. Multitask the device settings and change the theme.
1. Multitask back to Firefox. 
### Expected behavior
The FF settings should be displayed and the theme changed.
### Actual behavior
Firefox gets stuck and then crashes when multitasking outside of FF and then back
### Device & build information

* Device: iPhone 15 Pro (17.3) 
* Build version: v124 (39709) 
* First seen version: N/A 
### Notes
[Sentry](https://mozilla.sentry.io/issues/3914209929/?environment=Production&project=6176941&query=release%3Aorg.mozilla.ios.Firefox%40124.0%2B%2839709%29&referrer=release-issue-stream).
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/111f901c-e507-41cd-912e-786014abbe1c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8691)

**Comment by data-sync-user** [comment] 2024-03-21 16:38
➤ Matt Reagan commented:

It looks like this is likely the merge which ended up causing the issue: https://github.com/mozilla-mobile/firefox-ios/pull/19016/files ( https://github.com/mozilla-mobile/firefox-ios/pull/19016/files|smart-link )  

If I revert that change I can no longer replicate, but with that change in place I can reproduce reliably

**Comment by data-sync-user** [comment] 2024-03-25 13:19
➤ Alina Moldovan commented:

No able to reproduce this issue anymore using v9000 (40044) and iPhone 14+ (16.0.3)

**Comment by data-sync-user** [comment] 2024-03-26 09:08
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v124.2 (40108), with iPhone 15 (17.0).

Unable to reproduce the crash anymore.

**Closed** 2024-03-26 17:10 UTC
Labels: Bug 🐞, Crash, S1, Password Autofill
