### ISSUE TITLE
Back, Forward, Reload, and URL bar missing

### ISSUE THREAD

**Issue by troglodytes00** [mozilla-mobile/firefox-ios#11389] opened 2022-07-24 16:02 UTC
## Steps to reproduce
Intermittent issue, but happens regularly enough to be annoying in a single session.    Seems to happen with sites like reddit.com.  Open reddit, click on a post, and new tab opens.  Click on tab, scroll back and forth through post, sometimes the Back, Forward, Reload, and URL bar collapse and then returns based on scrolling direction.   But, occasionally it doesn't.  Can swipe to go back.  Can't tap on header to cause Back, Forward, Reload, and URL bar to return.

### Expected behavior
Back, Forward, Reload, and URL bar behaves correctly.

### Actual behavior
Back, Forward, Reload, and URL bar intermittently are shown.

### Device & build information
* Device: iPad Pro 12.9 2nd-gen  w/ iPadOS 15.5
* Build version:  102.2

### Notes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4624)

**Comment by dnarcese** [comment] 2022-09-15 19:36
Duplicate of #9657

**Closed by dnarcese** 2022-09-15 19:36 UTC
Labels: Bug 🐞
