### ISSUE TITLE
[Tab tray refactor] PB section is not selected in the tabs tray section when opening a website from the homepage while being in the PB

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#18743] opened 2024-02-16 13:48 UTC
## Steps to reproduce
1. Launch FF and set PB from the homepage.
1. Open any website.
1. Access the tabs tray and observe if PB is selected at the top.
### Expected behavior
PB should be selected in the tabs tray.
### Actual behavior
PB section is not selected in the tabs tray section when opening a website from the homepage while being in the PB.
### Device & build information

* Device: iPad mini 5 (16.7.2). 
* Build version: 123 (38801). 
* First seen version: N/A. 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/05321f0b-eeac-49b0-b51a-c3f88d6d3942

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8451)

**Comment by data-sync-user** [comment] 2024-02-27 12:17
➤ Andrei Bodea commented:

Hello, Sophie Aminsure thing! This still with the experiment on, right?

**Comment by data-sync-user** [comment] 2024-02-27 20:06
➤ Sophie Amin commented:

Andrei Bodea yes! I tested with the tab tray refactor enabled and couldn’t repro.

**Comment by data-sync-user** [comment] 2024-02-28 06:34
➤ Dragos Bigu commented:

Sophie Amin this issue is reproducing on iPad. testCloseAllTabsPrivateModeUndo automation test is failing due to this issue.

**Comment by data-sync-user** [comment] 2024-03-18 13:48
➤ Alina Moldovan commented:

This issue still reproducers using v9000 (39865)

**Comment by data-sync-user** [comment] 2024-04-01 08:35
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40250), with iPhone 15 (17.0).

**Closed by data-sync-user** 2024-04-01 08:35 UTC
Labels: Bug 🐞, S2
