### ISSUE TITLE
Newest added bookmark is not displayed at the top of the homepage list (intermittent)

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20950] opened 2024-07-10 08:44 UTC
**Steps to reproduce**

1. Make sure you have several saved bookmarks and that they are displayed on homepage.
1. Add a new bookmark and observe the bookmark homepage list.

**Expected behavior**
The newest added bookmark is displayed first in the list.

**Actual behavior**
The newest added bookmark is NOT displayed first in the list (seems to be consistently added on the 3rd position).

**Device & build information**

* Device: iPhone 15 (17.5), iPhone SE (17.5)
* Build version: v129 (43415)
* First seen version: ? 

Notes
This issue doesn't seem to reproduce on iPad.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/afaeaa3a-03a9-4893-89ba-9ea8a81ffa80

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9463)

**Comment by data-sync-user** [comment] 2024-07-11 19:06
➤ Norberto Andres Furlan commented:

Sophie Amin can you take a look to this one?

**Comment by data-sync-user** [comment] 2024-07-26 23:08
➤ Sophie Amin commented:

Diana Andreea Barladeanu Hi Diana, I can’t repro this one. Tried a couple scenerios after watching your recording a few times and no luck. Do you have any other info on how to repro this?

**Comment by data-sync-user** [comment] 2024-07-29 06:07
➤ Diana Andreea Barladeanu commented:

Hi Sophie Amin ! I haven’t reproduced it either since then, there were no special conditions. I think we can close this ticket and open another one if we encounter this issue again.

**Closed** 2024-10-20 04:31 UTC
Labels: Bug 🐞, S3
