### ISSUE TITLE
Wrong animation when removing several history items quickly by swiping left

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4735] opened 2019-04-08 21:42 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1542256

Seen on latest beta: 14696

Steps
1. Have several entries in history list
2. Remove three or more quickly by swiping left

Actual
There is a red line appearing when swiping to remove a history entry

Expected
The animation for the red remove button should be shown correctly.
Please see video file: https://youtu.be/Jxgtigzk8BI

**Comment by isabelrios** [comment] 2019-04-30 16:54
Closing this since I'm not able to reproduce on v17.x beta 14949. There is a crash happening though following same steps. I will open a new issue for that.

**Closed by isabelrios** 2019-04-30 16:54 UTC
Labels: Bug 🐞, Needs QA 🔎, P2 ✌️
