### ISSUE TITLE
FXIOS-793 ⁃ Update Firefox for iOS push certificate

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#7203] opened 2020-08-25 14:11 UTC
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-793)

**Comment by athomasmoz** [comment] 2020-08-25 19:05
Closing as duplicate of #7195

**Closed by athomasmoz** 2020-08-25 19:05 UTC
