### ISSUE TITLE
Bug: Attentive mode should be dismissed when home page interacted with

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#7608] opened 2020-11-02 20:35 UTC
## Steps to reproduce
1. Tap the address bar (or open a new tab). Search bar should be focused with keyboard up
1. Scroll the home page 
1. Click on any blank space on the home page

### Expected behavior
In both 2 & 3, the address bar should be unfocused and keyboard should disappear, similar to what happens when you click the back arrow

### Actual behavior
Clicking on the home page does nothing. The address bar is still focused and keyboard still visible. 

Scrolling the home page dismisses the keyboard, but the address bar is still focused, as indicated by the blue ring around it. 

![width=200,height=183](https://user-images.githubusercontent.com/51007/97916443-d97cfd80-1db7-11eb-87b1-ef4f2682fb48.gif)

### Device & build information
* Device: all

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2621)

**Comment by SimonBasca** [comment] 2021-01-11 12:46
@dnarcese @chriscoderdr it seems that after 9a1c3ba landed a few regressions were introduce: #7833, #7834,  #7835, #7836. The introduced issues are affecting user experience and should be fixed before #7608 lands on beta.

**Comment by dnarcese** [comment] 2021-01-11 21:26
I reverted 9a1c3ba until these issues are fixed. Thanks for catching these.

**Comment by athomasmoz** [comment] 2021-01-14 16:59
Closing #7833, #7834, #7835, #7836 since this change has been reverted. The issues in those tickets should be addressed before publishing this one.

**Comment by SimonBasca** [comment] 2021-06-14 11:09
After following the STR I am still able to reproduce the issue on v34.1 (5167) or main b440c9b126 . Should we re-open the issue or log a new one?

**Comment by nbhasin2** [comment] 2021-06-14 12:14
@SimonBasca yeah lets reopen this issue as I had to revert the fix

**Comment by data-sync-user** [comment] 2021-06-15 17:38
➤ Daniela Arcese commented:

Let's timebox investigation to a 2 and then come up with a proposal for a longer-term solution.

**Comment by data-sync-user** [comment] 2021-09-20 12:00
➤ Nishant Patel commented:

Daniela Arcese how should it behave when attentive mode is triggered from the URLBar?

**Comment by data-sync-user** [comment] 2021-09-20 15:19
➤ Daniela Arcese commented:

{quote}Daniela Arcese how should it behave when attentive mode is triggered from the URLBar?{quote}

No behaviour change here

**Comment by data-sync-user** [comment] 2021-09-27 12:01
➤ Catalin Suciu commented:

Verifying as fixed on v38.0 (6122) for the case when the phone is in portrait mode. For when it’s in landscape this issue is still reproducible (see https://mozilla-hub.atlassian.net/browse/FXIOS-3208 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3208|smart-link ) )

**Closed** 2021-11-16 21:41 UTC
Labels: Bug 🐞, P2, QA Verified, eng-ready
