### ISSUE TITLE
Shortcut icons flash when opening Firefox

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#12214] opened 2022-10-25 14:22 UTC
## Steps to reproduce

1. Quit Firefox
2. Start Firefox
3. Watch the various icons in the shortcuts section blink

### Expected behavior
The icon should not blink.
### Actual behavior
The icons are blinking
### Device & build information
* Device: iPhone 12 Pro
* Build version: 106.0 (20303)
### Notes
Attachments: 

https://user-images.githubusercontent.com/107992/197799699-c700c75d-78a8-44f1-baeb-20341254e8fe.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5148)

**Comment by mhoye** [comment] 2022-10-25 14:48
I am also seeing this on an iPhone Xs, iOS 16.0 (20A362) and can reproduce it using the same STRs provided.

**Comment by csuciu** [comment] 2022-10-26 14:31
@yoanarios I'm not sure if this is the same issue, but the icons from the "Recently visited" section are also blinking when staring the app while tabs are loading in the background.

If it's not the same issue, please let me know and I'll file a new one.

This is visible on slower devices. I tested on an iPhone 6S running iOS 15.7.

https://user-images.githubusercontent.com/1866605/198054409-7323d488-b258-4b30-807e-a02771499753.mp4

**Comment by data-sync-user** [comment] 2022-10-28 21:16
➤ Yoana Rios Diaz commented:

Note for QA:
This fix was implemented in the past and reverted because there were some Sponsored Top Sites fav icons not being loaded correctly. When testing this ticket can we do more in depth test to confirm this is not happening anymore.
This PR also fix the issue were some fav icons have a background color 

!Simulator Screen Shot - iPhone 13 Pro - 2022-10-27 at 13.23.52.png|width=41.666666666666664%!

**Comment by data-sync-user** [comment] 2022-11-14 14:22
➤ Simion Basca commented:

Marking as verified fix on v9000 (21972)

**Closed by data-sync-user** 2022-11-14 14:22 UTC
Labels: Bug 🐞
