### ISSUE TITLE
Request Flooding when opening app

### ISSUE THREAD

**Issue by kg-2** [mozilla-mobile/firefox-ios#12617] opened 2022-12-07 17:35 UTC
## Steps to reproduce
open firefox on iphone 
### Actual behavior
Immediately upon opening, a server that I run is inundated with requests which triggers 429 errors. Other websites also receive requests. For example I get duplicate emails thanking me for downloading previously downloaded products. This behavior is observed using 2 different phones with 2 different firefox accounts.  If I scroll through the synced tabs page I get considerably more requests. 
### Device & build information
* Device: iphone 14 pro ios 16.1.2
* Build version: 107.2 (22549)
### Notes
Here is an example request:
URI: /login
METHOD: GET  	
AGENT: ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0',)

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5391)

**Comment by FrostTheFox** [comment] 2022-12-10 02:23
Seeing the same issue but worse. From my testing, this can actually occur on nearly every page load. I can reproduce this on both the latest release version 107.3 and the latest TestFlight beta 108.0 (23855). I'm seeing at least 3 extra requests per page refresh in many instances, and sometimes even more on loading new pages (most I've seen messing around is 8). It is the same user agent of `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0` on most of the extra requests, but some of them I see `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`.

The behavior is increasingly worse if you have multiple tabs open. Refreshing a single page also generates at least a couple of these extra requests to the next tab's URL for whatever reason. If all tabs are loaded, switching between them also seems to generate requests. Closing & reopening the app normally before it is terminated sends requests to seemingly 2 random tabs. Terminating the app & reopening with multiple tabs open seemingly sends numerous requests to each of the open tabs. The behavior differs some depending on which tab was last open. It seems like being parked on the 1st tab makes the most requests in any case, which maybe is a clue as to what's going on.

This is quite a problem. The nature of our website often leads to users having multiple tabs open, which with this bug means numerous requests to different URLs which causes them to reach our rate limits very quickly (with enough tabs or with heavy pages, it can even be immediately after opening the app!) We're receiving a lot of reports from Firefox iOS users who are running into this problem with normal usage.

Screenshots of traffic captures:
* 1 tab open, refreshing page: https://thunderfox.nl/sharex/sj1E407crWonCWw9ebte.png
* 5 tabs open, refreshing 1st tab: https://thunderfox.nl/sharex/fVd2i0VDFMOFwZVk7Dbt.png
* 5 tabs open, opening & closing w/o termination: https://thunderfox.nl/sharex/wDj8MDwr4MhimuVPyjqM.png
* 5 tabs open, terminating & reopening app: https://thunderfox.nl/sharex/4JhLKHdl7OwmgxC4MFb1.png

**Comment by OrlaM** [comment] 2022-12-10 02:33
We had to regress some of the caching behaviour for favicons because of a recent issue we had with some crashing and severe performance issues so we expected some degradation in this area but these examples seem extreme. 
We are working on a more holistic fix for how the app handles favicons in general and are hoping to have that out in version 110, so this issue will definitely be dealt with by then, but this seems bad enough that waiting for 110 is probably too long. I'll see if there is anything we can do in the short term to at least reduce the severity of the issue in the mean time.

**Comment by herrbischoff** [comment] 2022-12-10 14:51
I possibly ran into this issue due to a project of mine that got popular on Hacker News. At peak access, this DDoS'd my server to a standstill. As I'm writing this, I still get half a dozen identical accesses per second per IP address. Each access transfers the entire page content.

If this bug is indeed the source of the access flood, it is entirely unacceptable.

I'd also like to know why this app is using misleading user agent strings. If it identified itself correctly, it would be easy to throttle those accesses.

**Comment by kg-2** [comment] 2022-12-11 15:50
> We had to regress some of the caching behaviour for favicons because of a recent issue we had with some crashing and severe performance issues so we expected some degradation in this area but these examples seem extreme. We are working on a more holistic fix for how the app handles favicons in general and are hoping to have that out in version 110, so this issue will definitely be dealt with by then, but this seems bad enough that waiting for 110 is probably too long. I'll see if there is anything we can do in the short term to at least reduce the severity of the issue in the mean time.

I would just like to clarify that it's not just requests for icons, it's all URLs.

**Comment by easrng** [comment] 2022-12-12 23:13
Looks like the `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0` user agent is [also used by iMessage](https://stackoverflow.com/a/42094099/11831068), maybe it's some iOS framework that makes these requests?

**Comment by kg-2** [comment] 2022-12-16 13:46
I'm surprised that a bug that turns firefox into a DDOS botnet isn't getting more attention from the maintainers....

**Comment by q2r5** [comment] 2022-12-16 14:24
I feel this may be caused by the use of `LPMetadataProvider`. I can't be certain, but commenting out the relevant calls stopped the 429 errors from happening for me.

**Comment by lmarceau** [comment] 2022-12-16 15:24
Hi @kg-2, we're investigating - although you won't see progress on Github. We're tracking in Jira. Thanks!

**Comment by data-sync-user** [comment] 2022-12-20 17:32
➤ Orla Mitchell commented:

For QA please verify that hero images on the home page still work as expected.

**Comment by data-sync-user** [comment] 2023-01-05 13:44
➤ Simion Basca commented:

Verifying as fix on v109 (25431). The hero image is correctly displayed and has proper functionality.

**Closed by data-sync-user** 2023-01-05 13:44 UTC
Labels: Bug 🐞

**Comment by vshatylo** [comment] 2023-02-07 10:27
Flooding still reproduces with v109 

conditions for reproduce a bit different: a soon server retrieves not 200 response status then other tabs sends request

**Comment by lmarceau** [comment] 2023-02-07 16:55
Hi @vshatylo, thanks for raising this. We potentially have a fix for this in 110. Would you mind telling us if this is fixed or not in this release? Version 110 should be released next week.

**Comment by vshatylo** [comment] 2023-02-07 18:52
Hi @lmarceau, 
Thanks for update. will check with 110.

**Comment by FrostTheFox** [comment] 2023-02-15 07:27
Hello again, I have done some testing on the latest TestFlight build, v111 (28148). I am no longer seeing the issue occurring when closing down the app and relaunching, nor when moving around between tabs or anything (or at least, if it is occurring, very rarely and enough that it mixes in with most other traffic going through the proxy).

That being said, I have found some more occurrences and I would say it's still problematic in terms of hitting rate limiting. Reminder that in all of these first screenshots, I am filtering out only requests to /works/. First of all, simply navigating to new pages triggers 3 total GETs to the requested page: https://thunderfox.nl/sharex/tkO5LjvNjt7KmbbTi8qp.png

Navigating to new pages which results in a redirect makes even more requests: https://thunderfox.nl/sharex/b5XQKOSSkVRTjVq6WB18.png In this example, I navigated to the page once, which should be 1 request for the redirect, and 1 request to the location returned by the server. Instead, what we have are 3 requests to the initial URL, and 9 resulting requests to the server's returned location. Compare this to Safari: https://thunderfox.nl/sharex/FOWwK26FV0aj4X7hLK9i.png

These duplicate requests come from both `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0` and `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15` The duplicate favicon.ico requests in the above screenshot are `Client/28148 CFNetwork/1402.0.8 Darwin/22.2.0`

Note that there are also duplicated requests to the root /favicon.ico, /apple-touch-icon.png and apple-touch-icon-precomposed.png going on here: https://thunderfox.nl/sharex/iS6mtg1qJTxAX7CU7bKL.png The UA here is: `com.apple.WebKit.Networking/8614.3.7.0.6 CFNetwork/1402.0.8 Darwin/22.2.0` For us, these are served by our caching layer and as such, isn't as important for the rate-limiting. However, for someone who might just have some simple rate-limiting setup on their nginx, this could still factor in, and it's still a waste of bandwidth for the client. I believe we are still seeing this to a degree that it is affecting users.

**Comment by OrlaM** [comment] 2023-02-23 20:22
@FrostTheFox Thanks for the update. I've opened a new ticket with the repo steps you have outlined. I believe this is a different root cause than the original issue and is in an area we are currently in the process of refactoring so I'm hoping we can incorporate a fix into that work.
