### ISSUE TITLE
FXIOS-505 ⁃ [Chronological tabs] iOS status bar is not visible in Tabs Tray

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6772] opened 2020-06-10 08:41 UTC
## Steps to reproduce
1. Set theme to Dark
2. Open tabs tray
### Expected behavior
- iOS status bar is not visible in Tabs Tray when the theme is set to Dark
### Device & build information
* Device: iPhone Xr (13.4)
* Build version: 18218
### Notes
Attachments: 
![Screen Shot 2020-06-10 at 11 32 17](https://user-images.githubusercontent.com/32130829/84246436-4cd35980-ab0f-11ea-81f7-8d2a73486be0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2451)

**Comment by SimonBasca** [comment] 2020-07-16 13:39
This is also reproducible on latest commit 6988e8fcf1ea after following the STR:

1. Open tabs tray
2. Press the Lock screen button
3. Unlock the device.

**Comment by SimonBasca** [comment] 2020-07-22 16:57
@dnarcese can you please take a look to see if this is something that needs fixed before code freeze.

**Comment by dnarcese** [comment] 2020-07-22 22:21
> @dnarcese can you please take a look to see if this is something that needs fixed before code freeze.

Since this is still only in beta, it shouldn't need to get in for code freeze.

**Comment by data-sync-user** [comment] 2020-10-08 20:00
➤ Ashley Thomas commented:

Reproducible with new steps. Closing and re-opening the tab tray fixes it

**Closed** 2021-11-01 20:24 UTC
Labels: Bug 🐞
