### ISSUE TITLE
Crash when clearing a website’s data twice in quick succession 

### ISSUE THREAD

**Issue by ErinCall** [mozilla-mobile/firefox-ios#7031] opened 2020-07-24 15:52 UTC
## Steps to reproduce

1. Go to Settings -> Data Management -> Website Data
1. Filter to a website whose data you want to clear
    * I don’t know whether using the search bar is actually relevant, but it’s what I did so I’m including it
1. Tap the ⛔️ button
1. Tap the “Delete” button
    * At this point, the list entry slides back to its original position, just as it would if you’d tapped elsewhere on the screen. There’s a brief delay before it disappears from the list. 
1. [assume you missed the delete button since you have bad aim and that happens a lot]
1. Hit the ⛔️ and “Delete” buttons again

### Expected behavior

The website’s data is deleted and you can go back to enjoying your lovely browser 🙂

### Actual behavior

The website’s data is deleted, but the app crashes. 

### Device & build information
* Device: iPhone 8 plus; iOS 13.5.1
* Build version: 27.0

### Notes
I tried to reproduce this a couple of times, but I wasn’t able to get through step 6. When it happened to me there was a relatively long delay (1–2 seconds) between “tap Delete” and “list entry disappears,” but in my later attempts it was over too quickly for me to hit all the buttons.

**Comment by garvankeeley** [comment] 2020-07-28 15:34
There was some fixes for v28, we should re-check

**Comment by SimonBasca** [comment] 2020-08-11 13:25
On version 27.0, there seems to be an issue as described at step 4) which could cause a crash which I am not reproducing. 

The issue at step 4) is not reproducible on v28. 

My opinion is that this issue is fixed by https://github.com/mozilla-mobile/firefox-ios/issues/6875. 

@garvankeeley feel free to re-open if you consider it' still an issue.

**Closed by SimonBasca** 2020-08-11 13:25 UTC
Labels: Bug 🐞, Needs QA
