### ISSUE TITLE
FXIOS-1583 ⁃ [Bug] Tapping the new tab button from the Tabs Tray should launch a new search session while the "New tab" option is set to "Firefox Home" 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8126] opened 2021-03-11 14:56 UTC
## Prerequisites
The "New Tab" general setting should be set to "Firefox Home"
You can either use the default Tabs Tray or Chronological Tabs Tray

## Steps to reproduce
1. Open the Tabs Tray
2. Tap the open a new tab

### Expected behavior
Similar behavior as performing a new search from the widget
Tapping the "Open a new tab " should launch a new search session as long as the "New tab" option is set to "Firefox Home" 

### Actual behavior
"Firefox Home" is opened 

### Device & build information
* Device: All

### Notes
This behavior is also implemented in Fenix

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1583)

**Comment by SimonBasca** [comment] 2021-03-15 09:05
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/8126

**Closed by SimonBasca** 2021-03-15 09:05 UTC
Labels: Feature-Request

**Comment by wachabaha** [comment] 2021-03-15 09:07
- @
