### ISSUE TITLE
URLs from links not opening consistently

### ISSUE THREAD

**Issue by befriendabacterium** [mozilla-mobile/firefox-ios#19263] opened 2024-03-18 09:34 UTC
## Steps to reproduce

Try to open a link from WhatsApp or another app.

### Expected behavior

Link opens

### Device & build information
* Device: iPhone 13 mini, 17.3.1
* Build version: 123.4
* First seen version: New to this version but this is my first installed version.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8681)

**Comment by befriendabacterium** [comment] 2024-03-18 09:35
Just to clarify, this appears to be the same issue as https://github.com/mozilla-mobile/firefox-ios/issues/19262 - feel free to close/merge

**Comment by abodea** [comment] 2024-03-18 09:46
Hi @befriendabacterium thank you for your report. 
Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/19262.

**Closed by abodea** 2024-03-18 09:46 UTC
Labels: Bug 🐞
