### ISSUE TITLE
Youtube continues to play after tab closed.

### ISSUE THREAD

**Issue by mister-igor** [mozilla-mobile/firefox-ios#15599] opened 2023-07-16 23:36 UTC
## Steps to reproduce
Play video.  Close tab. Audio continues.  No PIP displayed. 

### Expected behavior
Playback should cease.

### Actual behavior
Playback continues

### Device & build information
I am using Firefox 115.0 (32242) on iPadOS 15.3.1 iPad Pro 5th gen.

When I close a tab that is playing it continues until I kill Firefox completely.

No PIP is displayed

Safari operates correctly.

Started happening after immediately after update to current Firefox version.

Not logged into youtube.

* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7020)

**Comment by Absentity** [comment] 2023-07-19 21:41
Same issue is happening for me. It’s like the tab continues to live on even though it’s closed.

1. Tap link in Messages for a TikTok video, opens the page in a new tab in Firefox
2. Tap the tabs button, swipe away the tab
3. Audio for the video and “next up” videos continues to play until I kill the app

- Device: iPhone 14 Pro Max
- iOS version: 16.5.1 (c)
- Build version: Firefox 115.0 (32242)
- First seen version: Firefox 115.0 (32242)

**Comment by nook24** [comment] 2023-07-23 13:07
I can confirm, this happens on my iPhone and iPad. I was also able to reproduce this with an private tab

**Comment by mister-igor** [comment] 2023-07-26 15:46
15.1 does not fix this issue.   Not just a youtube problem: closing a tab does not stop execution of whatever script or action that was initiated in the tab and memory is not released.

**Comment by lmarceau** [comment] 2023-07-26 21:45
Hello @mister-igor, we are working on a fix for this. Since there are multiple github issues opened for this it's a bit harder to track, but progress is currently tracked in #15722. Thank you!

**Comment by data-sync-user** [comment] 2023-07-27 18:28
➤ Laurie Marceau commented:

I’ll close this issue so we have only one issue to track this problem. Please see https://mozilla-hub.atlassian.net/browse/FXIOS-7075 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7075|smart-link ) https://github.com/mozilla-mobile/firefox-ios/issues/15722 ( https://github.com/mozilla-mobile/firefox-ios/issues/15722|smart-link ) for progress and QA on the matter.

**Closed by data-sync-user** 2023-07-27 18:28 UTC

**Comment by furqanhamid12** [comment] 2025-05-17 06:01
That sounds frustrating! I’ve experienced similar issues, especially after updates, it could be a bug tied to Firefox’s handling of media playback on iPadOS. Hopefully, the dev team can patch this soon, as Safari doesn’t seem to have the same issue.
