### ISSUE TITLE
Active tab shows title of private tab

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#17679] opened 2023-12-07 20:58 UTC
## Steps to reproduce
When viewing the New Tabs menu, the active tab is displayed with the title of the first Private Browsing tab. I've noticed this happening both when opening the app and when switching from private browsing. Usually the tab also previews a blank page instead of its actual contents, even when just a homepage, and sometimes opening it just displays the blank page until refreshed somehow.

### Device & build information
Device: iPhone 11, iOS 16.5.1
Build version: Firefox 116.2 (33536)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7925)

**Comment by dnarcese** [comment] 2023-12-07 20:59
split from #16167

**Comment by data-sync-user** [comment] 2023-12-12 15:41
➤ Nishant Bhasin commented:

This should ideally be part of v121 weekly if we can fix it and should be marked as such after v121 goes out

**Comment by data-sync-user** [comment] 2023-12-21 09:34
➤ Sorin Paraipan commented:

Could not reproduce it, I’ll nicely ask the QA Team to also take a look at it.

**Closed** 2024-03-20 17:58 UTC
Labels: Bug 🐞
