### ISSUE TITLE
Close all tabs in normal mode shows preview for previously-closed private tab

### ISSUE THREAD

**Issue by drootang** [mozilla-mobile/firefox-ios#6949] opened 2020-07-10 12:51 UTC
## Steps to reproduce
1. Enter private browsing mode
2. Open a new page and browse to mozilla.org
3. Tap the tab switcher icon
4. Manually close the mozilla tab by tapping the x in its corner
5. Exit private browsing mode
6. Tap the trashcan icon to close all tabs
7. Observe that the tab's preview shows mozilla.org leaking private browsing data after it was closed and private mode exited

### Expected behavior
The blank tab in step 6 should remain blank

### Actual behavior
The tab seen in step 6 contains the web-page preview for a page visited in private browsing mode

### Device & build information
* Device: iPhone 8
* Build version: Version 27.0 (18428)
### Notes
Attachments:

**Comment by garvankeeley** [comment] 2020-07-10 16:53
I can't repro this, at step 7, all the tabs in the tab tray disappear, then a new tab opens and the tab tray exits automatically and the newly created tab is selected. Can you screenshot what you see? Thanks

**Comment by drootang** [comment] 2020-07-10 17:03
![2765D012-C517-4886-AD2D-374466E59F06](https://user-images.githubusercontent.com/951660/87180004-b3ce6480-c2ad-11ea-819e-c54fd16c4833.png)

**Comment by garvankeeley** [comment] 2020-07-10 17:17
Yikes. Did you have to press the garbage can button for this bug to happen? What do you see before you press that button? (can you screenshot that?)

**Comment by drootang** [comment] 2020-07-10 18:45
Yes, I do have to tap the trash can icon. Before that it looks as expected—a blank tab (screenshot below). 

![773B56F1-71FC-4885-B706-1FFFD1087F02](https://user-images.githubusercontent.com/951660/87187945-fdbe4700-c2bb-11ea-8520-80836d0936b5.png)

**Comment by garvankeeley** [comment] 2020-07-10 18:58
Thanks for the detailed info! I’ll work on reproducing it

**Comment by SimonBasca** [comment] 2020-07-14 15:38
Reproducible on latest master  010453407 and release v27.0 (18428)
Preconditions:
- Enable "Close private tabs when leaving private browsing"
- Open a new tab and go to amazon.com

Steps to reproduce:
1. Open a tab in private browsing and go to "mozilla.org"
2. Close the app from app switcher
3. Re-open the app
4. Open tabs tray
5. Close the empty private tab
6. Open a new private tab and go to "mozilla.org"
7. Open tabs tray and close the private tab
8 Switch to normal browsing
9. Tap the "Close all tabs" button

Video: 
[Issue.MP4.zip](https://github.com/mozilla-mobile/firefox-ios/files/4919724/Issue.MP4.zip)

**Comment by garvankeeley** [comment] 2020-07-21 17:09
Seems to be fixed by https://github.com/mozilla-mobile/firefox-ios/pull/6998

**Closed** 2020-07-21 17:51 UTC
Labels: 2, Bug 🐞, P1

**Comment by SimonBasca** [comment] 2020-07-22 17:09
Verified fix on master 48c25860b
