### ISSUE TITLE
FXIOS-452 ⁃ Support user agent customization / about:config

### ISSUE THREAD

**Issue by howeik** [mozilla-mobile/firefox-ios#6618] opened 2020-05-16 08:37 UTC
### Why/User Benefit/User Problem

I’m a lifelong Firefox user (#teamquantum) and love how customizable it is so have been using it on my iPad.

However, there are some sites that don’t load quite right that slight tweaks to my user agent would fix. I tried to use `about:config` but found that this wasn’t implemented. It would be awesome to have some advanced customization settings via `about:config` available for the ios app, and I think it would really set it apart from the other major browsers. 

### Acceptance Criteria (how do I know when I’m done?)

`about:config` works, or there’s some other setting for user agent customization.

### Not included

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2425)

**Comment by dalnk** [comment] 2020-05-16 08:39
🥰 need this in my life

**Comment by data-sync-user** [comment] 2021-07-08 18:42
➤ Daniela Arcese commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-2895 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2895|smart-link )

**Closed** 2021-11-01 20:13 UTC
Labels: Feature-Request
