### ISSUE TITLE
iPadOS  - Cannot close tabs by clicking "x"

### ISSUE THREAD

**Issue by PapiPeppers** [mozilla-mobile/firefox-ios#8613] opened 2021-05-31 22:58 UTC
## Steps to reproduce

Open any website in a new tab
Attempt to click the "x" to close the tab or any other open tab

### Expected behavior

Tab closed

### Actual behavior

Tab remains open and loading bar appears to act as if tab was reloaded; can see blue bar quickly progress across screen but page stays static overall

### Device & build information
* Device: ipad pro 11 (2021 m1 version) running iPadOS 14.7 dev beta
* Build version: Firefox Daylight 34.0 (4920)

https://user-images.githubusercontent.com/57047860/120247614-276cbd80-c242-11eb-965e-cf0bbb4c6ad1.mov

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2033)

**Comment by dnarcese** [comment] 2021-06-03 16:49
This could be related to the beta iOS. Going to leave this open to see if we get more reports.

**Comment by taylorthurlow** [comment] 2021-06-08 00:39
> This could be related to the beta iOS. Going to leave this open to see if we get more reports.

I am experiencing this exact issue on iOS 14.5 on an iPad Air 4. Firefox Daylight 34.0 (4920).

**Comment by SimonBasca** [comment] 2021-06-08 09:01
I am unable to reproduce this issue with latest main 70fdda04e and v34.0 (4920). @taylorthurlow could you post a video of the issue? I am unable to see the initial one.

**Comment by taylorthurlow** [comment] 2021-06-08 16:08
> I am unable to reproduce this issue with latest main 70fdda04e and v34.0 (4920). @taylorthurlow could you post a video of the issue? I am unable to see the initial one.

Sure, see attached.

https://user-images.githubusercontent.com/761640/121219608-baa48500-c838-11eb-92a0-d84098a9e3a5.MOV

**Comment by taylorthurlow** [comment] 2021-06-10 17:48
@dnarcese No this is with accessibility mode enabled to so you can see where I'm tapping. The gray circle will only move if I tap the screen. This problem occurs with that feature off too.

**Comment by dnarcese** [comment] 2021-06-10 17:49
@taylorthurlow got it, thank you

**Comment by taylorthurlow** [comment] 2021-06-10 17:50
@dnarcese No problem, just let me know if I can provide any other info.

**Comment by PapiPeppers** [comment] 2021-06-10 19:11
This is no longer an issue for me. I'm running the newest iPadOS 15 dev beta.

**Comment by taylorthurlow** [comment] 2021-06-10 19:55
I've since upgraded to iPadOS 14.6 and the issue is the same for me.

**Comment by SimonBasca** [comment] 2021-06-11 06:53
Still unable to reproduce this issue 70fdda0 and v34.0 (4920). On my side the closing the tabs work fine with hardware mouse and by tapping on the "X" symbol. 

@taylorthurlow is this reproducible also by tapping on the "X" or only with hardware mouse. Also does this issue occur after closing and re-launching Firefox?

**Comment by paulmorabito** [comment] 2021-06-12 13:36
I’m running IPadOS 14.6 with latest Firefox on a 2021/5th gen 12.9 IPad Pro with a Logitech IPad Combo Touch Keyboard/Trackpad. Have exactly the same problem with closing tabs. Also notice hitting return key on URL bar or in search often opens a new blank tab.

**Comment by laluciol** [comment] 2021-06-14 19:39
Hi
I am running **iOS 14.6** on a iPad Mini 5th generation, with latest **Firefox version Daylight 34.0 (4920)** and i am **experiencing this issue for the past 3days or so**. 
I don't use that ipad frequently and don t follow much the update cycle for iOS/Firefox, but that's the situation currently.
I am not using any keyboard or mouse. 
I have not changed the settings for a while.

Regards

**Comment by SimonBasca** [comment] 2021-06-15 12:17
I am still unable to reproduce this issue. On my side the tabs can be closed correctly by tapping on the "X" icon. Will keep trying to reproduce the issue.

**Comment by paulmorabito** [comment] 2021-06-15 12:59
> I am still unable to reproduce this issue. On my side the tabs can be closed correctly by tapping on the "X" icon. Will keep trying to reproduce the issue.

Touch works for me but using trackpad doesn't.

**Comment by laluciol** [comment] 2021-06-16 04:52
Hi
Here a video of the issue from 1 device. (including YouTube playing background...sorry for that ;-) )

https://user-images.githubusercontent.com/26889310/122159874-49d01f00-ce6f-11eb-82fe-7b41c052eab2.mov

**Comment by data-sync-user** [comment] 2021-06-25 07:05
➤ Daniela Arcese commented:

Let’s timebox an investigation to a 2.

**Comment by jimpassmore** [comment] 2021-07-17 13:29
Still seeing this 17 July 2021.  
iPad 7, Firefox Daylight 34.2, iPadOS 14.6
Note there are also multiple pages at support.mozilla.org bringing this up.  Search the Firefox for iOS section for “tab close” and 5 of the first 10 hits complain of this bug.

**Comment by nishant2718** [comment] 2021-08-03 20:41
I'm not seeing this issue on iPadOS 14.6 on the current main (https://github.com/mozilla-mobile/firefox-ios/commit/4aa1660dabd96c3a8a4807c060a23848e681ee27). 

Is anyone still seeing this bug? What are some steps to reproduce? Additional info also helps like: are you logged into your Firefox account, rotated the iPad, backgrounded the app etc.

**Comment by dethier1958** [comment] 2021-08-03 21:39
I am having the same problem, exactly as shown in the videos above. I have Firefox 35.0 (5448) on an iPad Pro 10.5 inch  running iPad OS 14.7.1 ...

Every once in a while I can close a tab that has just been opened but it often takes several taps, as if the button is very small or in the wrong location on the tab.

**Comment by paulmorabito** [comment] 2021-08-04 06:53
> I'm not seeing this issue on iPadOS 14.6 on the current main ([4aa1660](https://github.com/mozilla-mobile/firefox-ios/commit/4aa1660dabd96c3a8a4807c060a23848e681ee27)).
> 
> Is anyone still seeing this bug? What are some steps to reproduce? Additional info also helps like: are you logged into your Firefox account, rotated the iPad, backgrounded the app etc.

IPad Pro 2021 12.9, IPadOS 15 beta 4. Latest Firefox. Can't close any tabs by touch or by mouse. Only way to do it is go into the tabs view and then i can close by touch but still not mouse. Signed into firefox account and using on landscape mode.

**Comment by MuchHustle** [comment] 2021-08-19 06:21
I still have this same problem as does everyone I know with an iPad or iPhone and ios 14.4 and up. I keep expecting an update that will fix this, daily, for 2 months now. Daily frustration (anger too) yet I still use Firefox out of habit. That changes now. I’m uninstalling right now.
iPad Air 4 - 14.7.1
Firefox Daylight 36.0 (5732)

**Comment by mandadzhiev** [comment] 2021-08-28 11:04
I also have this issue on an iPad Mini Gen5, iPadOS 14.7.1, Firefox 36.0.

SUPER frustrating!

**Comment by dnarcese** [comment] 2022-01-20 20:11
@SimonBasca would you be able to take a deeper look at this issue? We are still getting user reviews about it but are not sure how to reproduce.

**Comment by SimonBasca** [comment] 2022-02-14 13:02
I was still unable to reproduce this issue on the current release v97.0 (7635) or on the latest main 4e8f7049d3653bf701366df309a06afc4fde0536 on iPad Pro (15.2).

We are currently unable to test on older builds. Are users still experiencing this issue on v97.0 (7635) with iPad devices using iOS (15.x)?

**Comment by laluciol** [comment] 2022-02-14 15:35
Hi
For me, it stopped after updating to iOS 15. something (sorry can not remember which one)So, i can report that, for iOS 15.3 on iPad and with the latest Firefox available for that OS as of 14/02/2022, it is not an issue anymore
Regards
    On Monday, February 14, 2022, 02:03:01 PM GMT+1, SimonBasca ***@***.***> wrote:  
 
 


I was still unable to reproduce this issue on the current release v97.0 (7635) or on the latest main 4e8f704 on iPad Pro (15.2).

We are currently unable to test on older builds. Are users still experiencing this issue on v97.0 (7635) with iPad devices using iOS (15.x)?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by paulmorabito** [comment] 2022-02-15 19:46
Am using IPadOS 15.4 beta 2 with latest Firefox. Just tested and it seems to be working fine now.

**Comment by SimonBasca** [comment] 2022-02-16 08:28
Thanks for the help @paulmorabito and @laluciol. @dnarcese let's close the issue for now and re-open if it's reproducible again.

**Closed by SimonBasca** 2022-02-16 08:28 UTC
Labels: Bug 🐞, Needs-QA, P1, iPad
