### ISSUE TITLE
The Hamburger Menu Takes A Long Time To Open

### ISSUE THREAD

**Issue by GenderCompass** [mozilla-mobile/firefox-ios#12073] opened 2022-10-05 17:02 UTC
## Steps to reproduce
Click on the hamburger menu while on a website

### Expected behavior
It opens instantly

### Actual behavior
It takes several seconds to open

### Device & build information
* Device: iPhone SE (2020)
* Build version: Firefox 105.0 (18490)
### Notes
I clicked the hamburger menu right as I started screen recording. It took 15 seconds for it to open.
Attachments: https://imgur.com/a/y5rg0iy

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5039)

**Comment by gutley** [comment] 2022-10-06 09:17
Is this on every website you try?

**Comment by GenderCompass** [comment] 2022-10-06 14:40
> Is this on every website you try?

No, it can happen on any website but it doesn't happen every time.

**Comment by SimonBasca** [comment] 2022-10-14 11:08
@GenderCompass is this only specific to the hamburger menu or the entire UI is slow to respond ?

**Comment by GenderCompass** [comment] 2022-10-14 15:18
> @GenderCompass is this only specific to the hamburger menu or the entire UI is slow to respond ?

Everything else responds immediately. It's only the hamburger menu that does this.

**Comment by dnarcese** [comment] 2022-10-27 19:51
duplicate of #12235

**Closed by dnarcese** 2022-10-27 19:51 UTC
Labels: Bug 🐞
