### ISSUE TITLE
"glean error invalid label" is displayed in the metrics ping

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11148] opened 2022-06-27 12:12 UTC
## Steps to reproduce
1. Clean install Firefox 9000 (11853)
2. Change the wallpaper from the onboarding
3. Send the events ping and check the glean dashboard
### Actual behavior
- "glean error invalid label" is displayed in the metrics ping
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 9000 (11853)
### Notes
Attachments:
 
<img width="444" alt="Screen Shot 2022-06-27 at 15 00 55" src="https://user-images.githubusercontent.com/32130829/175938332-4c81ea35-a3be-41b7-bffd-481aad18212a.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4472)

**Comment by nishant2718** [comment] 2022-07-21 13:04
This invalid label is from https://github.com/mozilla-mobile/firefox-ios/issues/10669. Glean docs state we should be able to send a label without defining it in Metrics.yaml because it's treated as an optional. We've notified Telemetry Engineers of this issue, possibly being unhandled for iOS on Glean side.

**Comment by lmarceau** [comment] 2022-07-21 15:23
This will be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11347

**Comment by data-sync-user** [comment] 2022-07-26 15:39
➤ Laurie Marceau commented:

Closing this as this was part of https://mozilla-hub.atlassian.net/browse/FXIOS-4198 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4198|smart-link )

**Closed by data-sync-user** 2022-07-26 15:39 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2022-07-26 15:42
➤ Simion Basca commented:

Laurie Marceau I was still able to reproduce this issue on v103.0 (13910)

!image-20220726-154217.png|width=544,height=236!

**Comment by data-sync-user** [comment] 2022-07-26 15:54
➤ Laurie Marceau commented:

Simion Basca Just realized this was included in v104 and not v103. So if this is tested on v104 this should be good there. I put it back in QA needed!

**Comment by data-sync-user** [comment] 2022-08-05 12:20
➤ Simion Basca commented:

Marking as verified fix on v104.0 (14880)
