### ISSUE TITLE
Too many tabs are open when initiating Firefox browser for iOS.

### ISSUE THREAD

**Issue by photoparity** [mozilla-mobile/firefox-ios#10415] opened 2022-04-05 22:34 UTC
## Steps to reproduce

Just open the browser

### Expected behavior

Only one tab or homepage should be present when initiating a session.

### Actual behavior

Two or more tabs are open when initiating Firefox for iOS.

### Device & build information
* Device: ?

iPhone 11

* Build version: ?

Firefox Daylight 98.2 (8475)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4062)

**Comment by lmarceau** [comment] 2022-04-06 13:58
Hi @photoparity, thanks for opening the ticket. Would you mind having a look at which options you have under HomePage > Opening Screen? There's three options, it's either "Homepage", "Last tab" or "Homepage after four hours"

**Comment by photoparity** [comment] 2022-04-06 17:11
I have this set to “Homepage.”

It was set to “Homepage After Four Hours.”  I changed this and it worked for a couple of times.

Then I changed so the home page had a wallpaper. After that change, it again started opening too many tabs. 

Something is screwy with the coding.

**Comment by photoparity** [comment] 2022-04-06 17:16
I set the wallpaper back to what it was when I filed this report. It still opens too many tabs.

**Comment by photoparity** [comment] 2022-04-07 01:42
I noticed that multiple tabs are being opened on another occasion. 

I typically delete tabs and private data when closing out the browser. When the private data is erased, another tab has been opened. 

I then close both tabs and then the browser.

**Comment by data-sync-user** [comment] 2022-04-14 19:36
➤ Daniela Arcese commented:

This should be fixed in v99

**Closed** 2022-04-14 19:42 UTC
Labels: Bug 🐞

**Comment by photoparity** [comment] 2022-04-14 19:51
THIS HAS NOT BEEN RESOLVED.  TOO MANY TABS ARE BEING OPENED AT THE STRANGEST TIME. I DELETE PRIVATE DATA IN SETTINGS ONLY TO FIND THERE ARE NOW TWO TABS OPEN WHEN ONLY ONE WAS AS I ENTERED SETTINGS. 

WHY HAVE YOU CLOSED THIS ISSUE?  IT IS CLEARLY UNRESOLVED.

**Comment by dnarcese** [comment] 2022-04-14 20:39
@photoparity are you on v99 now and still consistently seeing the issue?

**Comment by BradTheHero** [comment] 2022-04-14 20:55
I dunno. I like two tabs. Like, one is so lonely.

**Comment by photoparity** [comment] 2022-04-14 21:20
As you can see from the attached, when I went to the “What’s New,” two tabs are open. The version number is 99 as you suggest is the one with the fix. 

There should only be one tab. 

I sent you images of what happens when I clear the private data. Again two tabs open. This is consistent across all use of this browser. You guys seriously screwed this up a couple of iterations ago. I can’t attest to exactly when this issue cropped up. 

It is quite annoying as multiple tabs open for no discernible reason which takes up both storage on the phone ssd and its RAM.

**Comment by photoparity** [comment] 2022-04-14 21:20
Your sarcasm is unwarranted.

**Comment by photoparity** [comment] 2022-04-14 21:32
Here’s an image with the version number.

**Comment by lmarceau** [comment] 2022-04-14 21:33
@photoparity 
Please link your attachments directly in the Github ticket. Email reply doesn't attach anything on the ticket.

**Comment by electricRGB** [comment] 2022-04-14 21:42
Heya. Not sure what the issue is here... so I just want to clarify in case I'm misunderstanding.
You're closing all tabs (except for one because there must always be an open tab) and then closing firefox? And when you open it again, later on, there are two homepage tabs open, with your setting on "Homepage" for the Opening Screen settings?

**Comment by photoparity** [comment] 2022-04-14 21:48
I will upload the images.  I was just advised they weren't attached to my
earlier replies.

Jim

**Comment by photoparity** [comment] 2022-04-14 21:50
![IMG_0706](https://user-images.githubusercontent.com/103078382/163482342-08751085-9aec-4135-9e4f-c96365edd866.PNG)
![IMG_0707](https://user-images.githubusercontent.com/103078382/163482344-5ba26d4b-899d-44dd-b8e9-efcf2bb6cfba.PNG)
![IMG_0708](https://user-images.githubusercontent.com/103078382/163482347-ef9db627-b622-4c04-99bc-f17850cbd779.PNG)
![IMG_0709](https://user-images.githubusercontent.com/103078382/163482349-eb75216d-ce9d-4dea-af46-2e047663825a.PNG)
![IMG_0717](https://user-images.githubusercontent.com/103078382/163482352-057ad765-5322-4dc4-af01-8b0787031732.PNG)

**Comment by photoparity** [comment] 2022-04-14 21:58
![IMG_0718](https://user-images.githubusercontent.com/103078382/163483191-d4ebcb56-8764-49f8-aced-139ddc82fb49.PNG)

**Comment by photoparity** [comment] 2022-04-14 21:58
That last setting was as recommended by one of your correspondents earlier.

**Comment by photoparity** [comment] 2022-04-14 23:46
I have set my settings to “Homepage” when opening the browser. Opened a page from the drop down “Bookmarks”. Instead of opening in the current tab, the selected bookmark opened in another tab. 

Again. Duplicate tabs without any discernible reason. 

This issue is far from fixed.

**Comment by lmarceau** [comment] 2022-04-18 13:45
@photoparity 
It seems more than one issue is referred here. Title states "when initiating the Firefox browser for iOS" which indicates an issue when the application is opened. The last message describes an issue when a bookmark is selected by saying "Opened a page from the drop down “Bookmarks”". A ticket should only refer to one issue at a time. 

So I wanna ask you, which issue are you trying to describe? 
1. An issue when Firefox is launched from the Apple home screen?
2. An issue happening when a bookmark is selected?

**Comment by photoparity** [comment] 2022-10-11 07:18
That’s the thing: it’s happening at all sorts of odd moments. I’ve even had it open two tabs when the browser is launched. 

Every action I do, it doesn’t open just one tab. 

I’ve noticed this on launch of the browser, selecting a bookmark, clearing private data.  It isn’t one issue; it’s several. On some occasions I’m finding even three tabs open when I personally didn’t initiate the action. 

Only one tab should be functional unless a tab is opened by the user THAT IS NOT HAPPENING as the browser randomly opens a second tab or even more. 

As I’m on my phone using this, it’s difficult to document as I don’t have a way of recording the steps to replicate the issue. I’ve tried giving you screen captures which were uploaded but that doesn’t seem to have clarified matters. 

There is something wrong in total with this browser after several of the most recent updates. Random generation of tabs is not acceptable.
