### ISSUE TITLE
[FxA Upgrade] Account name is not updated in browser menus

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6226] opened 2020-03-05 16:51 UTC
**Build:** 
FF Beta 23.1 (17361)

**Device information**
iOS: iPhone X(13.2.2)

**Steps to reproduce:**
1. Sign in to sync with a new account on Ff browser.
2. Navigate to Settings>Firefox Account> Manage account page and add a Display name. 
3. Return to Firefox Account menu and view account name. 
4. Perform the same check for browser hamburger menu. 

**Expected result:** 
Adding a display name in Manage account page should be reflected in the rest of the browser menus. 

**Actual results:**
Account email address is still displayed. 

NOTE: Update occurs after account sign out and sign back in. 

![Account-name](https://user-images.githubusercontent.com/53306802/76004328-fbb13980-5f11-11ea-8ab7-4b1f209d17ac.gif)

**Comment by garvankeeley** [comment] 2020-03-05 17:07
Duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/6190

**Closed by garvankeeley** 2020-03-05 17:07 UTC
