### ISSUE TITLE
Tab bar disappears after some use on older iPad

### ISSUE THREAD

**Issue by oneofthedamons** [mozilla-mobile/firefox-ios#10237] opened 2022-03-15 21:54 UTC
## Steps to reproduce
Using Firefox with 26 open tabs. After some time, the tab bar disappears, so that only the current tab is available.

### Expected behavior
The tab bar always should be available.

### Actual behavior
To change tab, open a new tab or show the tab preview window, Firefox must be force-quit and restarted.

### Device & build information
* Device: iPad Pro 9.7-inch (iPad6,4)
* Build version: version 98.0 (8233)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3923)

**Comment by lmarceau** [comment] 2022-03-15 22:27
This probably relates to https://github.com/mozilla-mobile/firefox-ios/issues/10188
Not in regards to how to reproduce, but the root cause of the issue

**Comment by lmarceau** [comment] 2022-03-16 22:17
Since the fix for #10188 was merged, I'll bring this in as ready to test to see if this is also fixed at the same time.

**Comment by data-sync-user** [comment] 2022-03-22 09:46
➤ Simion Basca commented:

We’ve tested the fix for https://github.com/mozilla-mobile/firefox-ios/issues/10188 ( https://github.com/mozilla-mobile/firefox-ios/issues/10188|smart-link ) on v98.2 (8475). During the testing round we haven’t encountered any issues related to top tabs disappearing. I’m closing this issue as fixed.

**Closed** 2022-03-22 09:45 UTC
Labels: Bug 🐞, Contributor Fix
