### ISSUE TITLE
Reader mode in Hebrew language incorrect showing content

### ISSUE THREAD

**Issue by ilyak83** [mozilla-mobile/firefox-ios#14611] opened 2023-05-29 08:51 UTC
![Screenshot_1](https://github.com/mozilla-mobile/firefox-ios/assets/37582972/51181312-2019-4fbe-9a92-a3f88b0a6c55)
When enabling the reader mode for Hebrew content all the text shift form left to right instead form right to left.
Please see the attached screenshot - on the left side its correct original view and on the right side is incorrect view.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6513)

**Comment by atfelix** [comment] 2023-09-14 13:16
I'm investigating this issue but I'm running into a separate issue whenever I attempt to tap the reader mode button.  I get a screen that says `Could not connect to the server`.  I've run `npm install` and `npm run build`.  Is there something else I need to do enable reader mode on the simulator?

![Could not connect to the server.  NSURLErrorDomain. Try again button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/c7e91804-465e-44d0-8d37-88da2f150b3c)

**Comment by thatswinnie** [comment] 2023-09-14 14:57
@atfelix I ran into the same issue. A restart of my Mac solved the issue. Reader mode needs a certain port to work correctly and sometimes the port is not freed correctly after another app or another simulator uses it. A restart clears all the port usage and reader mode starts working again.
Could you try if that solves it for you as well?

**Comment by atfelix** [comment] 2023-09-14 16:08
@thatswinnie:  That worked.  Thank you.  Is there some way to free the port than restarting?

**Comment by atfelix** [comment] 2023-09-15 01:25
I think I understand the cause of this issue.  You can see the issue in any right-to-left language article on wikipedia or BBC news.  The title of the article is always character direction left-to-right because the following line doesn't specify `dir`:

https://github.com/mozilla-mobile/firefox-ios/blob/c867ca690d1908754735a7a1cf2058a75d879f5a/Client/Frontend/Reader/Resources/Reader.html#L17

[mozilla/readability](https://github.com/mozilla/readability) now provide direction and language, which we can use to update `Reader.html`.  However, there's a slight catch.  The site provided above (ynet news) won't work out of the box as readability doesn't know which direction to use for the article.

If a site provides the direction, then there's nothing we need to except update `Reader.html`.

There are a few approaches we could take:

1. Do nothing:  If a site doesn't provide a direction, then we don't modify the site.
1. Use the language to infer the direction:  We could use a combination of the language and  [`Locale`][locale], specifically [`Locale.language.characterDirection`][character-direction] to infer the direction.  This may be trickier than expected as character direction is one of 5 possibilities:  unknown, left-to-right, right-to-left, top-to-bottom and bottom-to-top.  It's obvious what to do in second and third cases but not in the other cases.  We could do nothing again as there's not much we can do.
1. Only allow reader mode if the direction is provided.  This solution, while fixing the issue, could lead to lots of sites no longer having a reader mode.

[locale]: https://developer.apple.com/documentation/foundation/locale
[character-direction]: https://developer.apple.com/documentation/foundation/locale/language/3952356-characterdirection

**Comment by atfelix** [comment] 2023-09-15 11:59
I should note that Firefox for Mac does not provide a reader mode button for ynet news articles (or at least I haven't found an article that has one)

**Comment by data-sync-user** [comment] 2023-09-25 08:47
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (34498), with iPhone SE (16.6.1). 

To be rechecked once the v119 build is officially released.

**Closed by data-sync-user** 2023-09-25 08:47 UTC
Labels: Contributor OK, Bug 🐞
