### ISSUE TITLE
Tab location reverts to previous arrangement

### ISSUE THREAD

**Issue by ShonFrazier** [mozilla-mobile/firefox-ios#17949] opened 2023-12-29 20:44 UTC
## Steps to reproduce
Add multiple tabs, showing different pages
Drag the far right tab to the far left
Tap any other tab

### Expected behavior
Tab arrangement should remain in new order, selected tab becomes active

### Actual behavior
Tab arrangement reverts to previous layout, selected tab becomes active 

### Device & build information
* Device: iPad mini (6th generation), 17.1.2
* Build version: 17.1.2
* First seen version: 17.1.2

### Notes
Attachments: 

@

https://github.com/mozilla-mobile/firefox-ios/assets/1297081/d665f6fd-c528-4066-986d-f10fcafbdabf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8049)

**Comment by dnarcese** [comment] 2024-01-04 20:32
duplicate of #16333

**Closed by dnarcese** 2024-01-04 20:32 UTC
Labels: Bug 🐞
