### ISSUE TITLE
[META] iOS 13: Support multi windows on iPadOS

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#5195] opened 2019-06-27 19:22 UTC
Vision:
Enable users to view & interact with multiple browser windows at a time

Why:
On desktop, users can look at 2 different sites at the same time by opening them in separate windows & resizing them to be side by side. This enables use cases like playing a sports game while browsing the web, or reading an online paper while capturing notes in a Google doc. With the introduction of [Multiple Windows on iOS 13](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/multiple-windows/), we can now offer this capability to users on iPads

Requirements:
https://docs.google.com/document/d/16GK_Vvgx0PsJyksQ1TYGEU-ws5LdJJT-wTr7JLLCzg0/edit#

Notes:
iPadOS on iOS 13 now supports having two windows for the same app open side by side. This requires supporting some new APIs. Not sure how much work this will be in TabManager and TabDisplay but this would be helpful to have for users on iPad

**Comment by athomasmoz** [comment] 2019-11-25 22:58
Preferred solution is to treat this as the same instance of the browser, that you can see twice. So both windows have the same list of tabs in them. Need to determine if that's possible

**Comment by GJRobert** [comment] 2019-12-15 15:42
> Preferred solution is to treat this as the same instance of the browser, that you can see twice. So both windows have the same list of tabs in them. Need to determine if that's feasible

Why not doing all different windows with different sets of tabs, like Safari does?

**Comment by jimcullenaus** [comment] 2019-12-16 12:30
Hey this was originally planned for the December 3 release. I’m wondering where it’s at now. Having this feature would be enough for me to switch to Firefox as it has proven to be a really useful feature in Safari allowing the iPad to behave a lot more like a desktop with much greater sorting ability.

On that note, 

> Preferred solution is to treat this as the same instance of the browser, that you can see twice

This would be a complete disaster. It would completely defeat the purpose of the feature for me. There is much less value in two tabs side-by-side per se than there is in simply greater ability to organise which tabs are available at any given time.

**Comment by athomasmoz** [comment] 2020-04-29 22:37
Closing as duplicate of #5816

**Closed by athomasmoz** 2020-04-29 22:37 UTC
Labels: Feature 🎁, Needs UX Feedback 🎨, P2, Should, iOS13
