### ISSUE TITLE
child directories not properly visible when editing bookmarks on iOS

### ISSUE THREAD

**Issue by tymek100** [mozilla-mobile/firefox-ios#14110] opened 2023-04-25 08:46 UTC
## Steps to reproduce
Add new bookmark, and then click Edit location

### Expected behavior
child directories should be OBVIOUSLY visible as child directories

### Actual behavior
currently all directories (parents and children) shows as one plain list, which is confusing. the only difference is the line below them, which is shorter on child directories, but it's still confusing and not obvious enough

### Device & build information
iPhone 12, iOS 16.3.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6262)

**Comment by lmarceau** [comment] 2023-04-25 14:50
Hello, I think this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13054

**Closed** 2023-04-27 19:54 UTC
Labels: Bug 🐞
