### ISSUE TITLE
Resumed download after suspend concatenates entire file with partial file (?)

### ISSUE THREAD

**Issue by anohren** [mozilla-mobile/firefox-ios#20206] opened 2024-05-11 11:43 UTC
## Steps to reproduce
Not sure if it's reproducible. 

1. Started downloading https://downloads.scummvm.org/frs/scummvm/2.8.1/scummvm-2.8.1-win32.exe and https://downloads.scummvm.org/frs/scummvm/2.8.1/scummvm-2.8.1-win32.zip using links on https://scummvm.org/downloads/
2. Let the phone screen lock activate automatically
3. When unlocking phone later (app in foreground) the downloads seemed to pick up where they left off, according to the progress bar toast
4. Ended up with non-runnable exe and non-extractable zip, both significantly larger than expected (198 and 187 MB respectively)

### Expected behavior
Resumed download results in non-corrupt files

### Actual behavior
Files too large and unusable. 

I thought I'd be able to find the exact byte offset where the start of the file repeated through `hexdump` and `grep` but there was only one occurrence of the first bytes `4d 5a 50 00`. 

Then I noticed that those bytes spell out "MZP", and I immediately thought "Mozilla partial...?"

### Device & build information
* Device: iPhone 8, iOS 16.7.6 
* Build version: Firefox 125.2 (41035) 
* First seen version: never seen before 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9110)

**Comment by mattreaganmozilla** [comment] 2024-05-23 22:52
@anohren I tried to replicate on a few different downloads including one of the linked .zip files above, but I wasn't able to see any issues after pausing / resuming. I could see that the file size was listed incorrectly on the download progress bar, which is a known (but separate) issue. But the resulting files for me were not corrupted. (Sidenote: the `MZP` ascii bytes you noticed are not something the iOS client would be doing directly, it looks like just a coincidence in some potentially bad or corrupt data).

Can you let me know if you have encountered this on any further downloads? Going to send to QA to see if they can verify or replicate this at all.

**Comment by data-sync-user** [comment] 2024-05-23 22:54
➤ Matt Reagan commented:

Andrei Bodea Can you please see if QA is able to replicate? I haven’t been able to reproduce the issue so far.

**Comment by anohren** [comment] 2024-06-02 13:12
I haven't experienced it with any other downloads. I seldom download large files though. 

The file sizes were obviously oversized both in iOS and Debian, so not related to the Firefox UI (oversized in relation to stated sizes on the page, as well as to subsequent download results). 

I'm prepared to attribute it to the server if it's not reproducible.

**Comment by data-sync-user** [comment] 2024-06-05 13:03
➤ Andrei Bodea commented:

Hello, Matt ReaganI could not reproduce this issue on v127 (42448) with iPhone 15 Pro (17.5.1).

**Comment by mattreaganmozilla** [comment] 2024-06-05 17:06
Thank you, I think given the above it is safe to close this ticket for now but if anyone runs into this or has questions LMK.

**Closed by mattreaganmozilla** 2024-06-05 17:06 UTC
Labels: Bug 🐞
