### ISSUE TITLE
FXIOS-1706 ⁃ 247sports.com - login is not performed when credentials are pre-registered

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8328] opened 2021-04-14 03:56 UTC
## Steps to reproduce
1. Go to https://247sports.com/college/duke/login/
2. with an account pre-saved

### Expected behavior
login in the site

### Actual behavior
The login is not perfomed if the credentials are previously saved and autofilled.
If I delete/edit the credentials and manually type them the login is performed.

### Device & build information
* Device: iPad
* Build version: 14.2.2
### Notes
see https://github.com/webcompat/web-bugs/issues/69550

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1706)

**Comment by SimonBasca** [comment] 2021-04-14 08:52
Seems like this issue is a duplicate of #8003.

**Comment by SimonBasca** [comment] 2021-04-14 08:54
@karlcow fell free to re-open if you believe this is a different issue.

**Closed by SimonBasca** 2021-04-14 08:54 UTC
Labels: Bug 🐞

**Comment by digitarenet** [comment] 2021-05-04 11:28
Also in this website the same issue with previously saved credentials:

 https://app.clickup.com/login
