### ISSUE TITLE
IOS Mozilla mobile: Cookie jar doesn't open at launch

### ISSUE THREAD

**Issue by eguun** [mozilla-mobile/firefox-ios#16423] opened 2023-09-16 11:17 UTC
Any first new page opened just after mozilla firefox-mobile fresh start does not use stored cookies.
The 2nd page open (or refresh of the 1st page) opens/uses the cookie jar.
It looks like a bug.

## Steps to reproduce
* in IOS close app mobile mozilla firefox
* open app mobile mozilla forefox (default page is homepage)
* open any new page where cookies are supposed to be stored and user already opted-in to have cookie stored (eg: Google search engine)
* cookies are not loaded and webpage prompts if user wants to store cookies and log-in

### Expected behavior
Cookie jar available as of firefox-mobile app start, and used from 1st pageload onwards

### Actual behavior
Cookie jar is only available after firefox-mobile has loaded a first webpage

### Device & build information
* Device: iPhone IOS v16.6.1
* Build version: Firefox mobile v 117.2 (33911)
* First seen version: unknown

### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7409)

**Comment by data-sync-user** [comment] 2023-12-14 19:47
➤ Norberto Andres Furlan commented:

Andrei Bodea can you confirm that this issue is fixed? Thanks!

**Comment by eguun** [comment] 2023-12-14 19:54
Thanks for the update. 
today, version 120.4 (36613) still exhibits this behavior

**Comment by data-sync-user** [comment] 2023-12-14 20:43
➤ Norberto Andres Furlan commented:

Thanks! We will prioritize accordingly. Andrei Bodea can you conduct a test to see how often is this happening?

**Comment by abodea** [comment] 2023-12-15 10:37
Hello, thank you for this report @eguun!

Can you please provide a video with the issue you are reproducing?
I do believe you are missing some steps -> Can you please explain where are you checking the Cookies? Please note that on the App Store, there is only one [Cookie Jar ](https://apps.apple.com/us/app/cookie-jar/id6443647590) app but this is doing nothing on other web browsers or is not doing anything at all. 

I just followed the steps you mentioned and for example, I did access a website where I already opted-in to have cookies stored but the prompt was not displayed for the second time, even on a clean restart of Firefox. 

Can you please attach a video to see exactly what you are referring to because it might not be a Firefox bug?

**Comment by abodea** [comment] 2023-12-15 15:29
Oh, a video would have helped me from the start, thank you for sharing now I understand. 
Closing this as a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11994 please note that this is the first issue added regarding this. So if you have any other information please do not hesitate to write in there! 

@afurlan-firefox I added a priority to the OG issue and I believe it will be more than enough if we try to follow up there and maybe have it solved.

**Closed by abodea** 2023-12-15 15:29 UTC
Labels: Bug 🐞
