### ISSUE TITLE
[Enhanced FF suggest settings] - Sponsored and non-sponsored suggestions triggered by the same keyword (mobile suggestions keywords)

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#19039] opened 2024-03-06 10:51 UTC
**Prerequisites**
1. Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment treatment b (mobile suggestions)
2. From FF secret menu, go to Firefox Suggest and tap on "Ingest new suggestions now".
3. "Suggestions from the Web" and "Suggestions from Sponsors" toggles are enabled.

**Steps to reproduce**
1. In the address bar, type "ro" (or "ch",  "fis", "bal")
2. Observe the suggestion list.
 
**Expected behavior**
Either a sponsored or a non sponsored suggestion should be triggered and displayed in the FF suggest list.

**Actual behavior**
Both a sponsored and a non sponsored suggestion are triggered and displayed at the bottom of the FF suggest list.

 **Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v124 (39464)
* First seen version: ? 
* 
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/89ce860d-2c48-4e08-8ae6-b995bb844b01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8564)

**Comment by data-sync-user** [comment] 2024-03-07 05:35
➤ Tif Tran commented:

Closing this one, as it’s a dupe of FXIOS-8549

**Closed** 2024-03-07 05:35 UTC
Labels: Bug 🐞
