### ISSUE TITLE
Toolbar is incorrectly displayed on bottom while in landscape mode

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21600] opened 2024-08-23 14:07 UTC
## Steps to reproduce
1. Make sure the toolbar redesign experiment is enabled
1. Open a webpage 
1. While in portrait mode move the toolbar to be displayed on bottom 
1. Move the device in landscape mode 

### Expected behavior
While in landscape mode the toolbar should be displayed on top 

### Actual behavior
While in landscape mode the toolbar is displayed on bottom

### Device & build information
* Device: 14+ (16.0.3), iPhone 15+ (17.5.1) 
* Build version: v9000 (44546) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/6f525529-c6a2-4ab5-86a5-ec80f14b8d98

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9837)

**Comment by data-sync-user** [comment] 2024-08-27 15:04
➤ Winnie Teichmann commented:

Alina Moldovan The same behavior exists in the release app (tested 127.0, 128.0 and 129.2). I don’t think this is a bug.

**Comment by data-sync-user** [comment] 2024-08-27 15:23
➤ Alina Moldovan commented:

You are right. I haven't noticed this before and unfortunately, we don't have the test to cover this case. 

Do you think we can close this ticket and consider it not a bug or should we ask the design team first?

CC  Norberto Andres Furlan

**Comment by cpeterso** [comment] 2024-11-04 17:37
Safari and Chrome display the toolbar at the top of the screen in landscape mode, regardless of whether the toolbar is configured to show at the bottom of the screen in portrait mode. I thought there was an existing bug/feature request about this, but I can't find it. IIRC, Aarjav recommended honoring the bottom bar setting in both portrait and landscape mode. In that case, we can close this bug as "won't fix".

**Closed** 2024-12-03 12:35 UTC
Labels: Bug 🐞, S3, Toolbar redesign📲

**Comment by data-sync-user** [comment] 2024-12-03 12:36
➤ Alina Moldovan commented:

Closing it as not a bug as per previous comment
