### ISSUE TITLE
hepsiburada - shoe size option not working

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9757] opened 2022-01-11 13:55 UTC
## Steps to reproduce
1. Visit hepsiburada.com
2. Click category
3. Sports outdoors
4. Sports fitness
5. Sportswear accessories
6. Shoes
7. Casual sport shoes
8. Slazenger Kalyana sneaker womens shoes
9. Pick different sizes
10. A phone number pops up to call from phone on some sizes
### Expected behavior
The size picked to be chosen and not a phone number
### Actual behavior
A phone number to call pops up to call
### Device & build information
* Device: Apple iPhone 7 - iOS 15.0.2
* Build version: Firefox Daylight 40.2 (7167)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/148955598-c0de1e21-4809-4bcc-98ea-32c4db2c0d1f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3608)

**Comment by SimonBasca** [comment] 2022-01-11 14:07
Confirming that this is an issue on Firefox v96.0 (7298). The issue is not reproducible in Safari. Thanks for the contribution @BigSamSampson

**Comment by dnarcese** [comment] 2022-01-13 17:47
Duplicate of #9553

**Closed by dnarcese** 2022-01-13 17:47 UTC
Labels: Bug 🐞
