### ISSUE TITLE
The tab opened in normal browsing is visible trough the overlay in app switcher

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13260] opened 2023-02-16 10:28 UTC
## Steps to reproduce
1. Visit a page in normal browsing
2. Open Private Browsing
3. Make sure no tabs are opened in Private Browsing
4. Open app switcher
### Expected behavior
- In Private Browsing, an overlay should be displayed blocking the view.
### Actual behavior
- The tab opened in normal browsing is visible trough the overlay in app switcher.
### Device & build information
* Device: iPhone 14 Pro (16.2)
* Build version: v111 (28263)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/219339697-1544997f-4339-4bc5-99a0-b77c51234a3e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5778)

**Comment by dnarcese** [comment] 2023-02-16 20:25
Since there is no tab open in private mode, technically we are still in normal browsing mode. To fix this bug I think we should just allow the private browsing message to be shown from the app switcher.
![IMG_1012](https://user-images.githubusercontent.com/11432165/219478972-729e2fc6-b99e-4fe1-812d-5b732108fc06.png)

**Comment by mirscode** [comment] 2023-03-05 21:49
I can take this bug up. 

If we want the private browsing message to show up, then it seems to me the issue is in GridTabViewController's `appWillResignActiveNotification()`. We need to add a check for if the `tabManager.privateTabs` is empty.

**Comment by lmarceau** [comment] 2023-03-07 12:15
Reopening since needs QA

**Comment by data-sync-user** [comment] 2023-03-13 14:49
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29455) with{color:#ffffff} {color}iPhone 14 (16.1).
This issue will still be checked when an RC will be created for the fix version.

**Closed** 2023-03-13 14:49 UTC
Labels: Contributor OK, Bug 🐞, Contributor Fix, S4

**Comment by data-sync-user** [comment] 2023-03-16 15:39
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
