### ISSUE TITLE
The `Search` name in settings is misaligned when it's very long on `custom search engine`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13538] opened 2023-03-10 16:01 UTC
## Steps to reproduce
1. Launch FF and reach settings.
2. Access the `Search` section.
3. Add a custom search engine and set a very long name.
4. Reach the settings again.
### Expected behavior
There should be a limit on the characters and the menu correctly aligned.
### Actual behavior
The `Search` name in settings is misaligned when it's very long on `custom search engine`
### Device & build information
* Device: **iPhone 13 Pro (15.7.1).** 
* Build version: **v9000 (29426).** 
* First seen version: N/A 
### Notes
Attachments: 

![image0 (7)](https://user-images.githubusercontent.com/42831109/224363913-c35217a0-1a17-43b9-94b3-ad0cfed13042.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5958)

**Comment by lmarceau** [comment] 2023-03-20 16:37
Note that to fix this issue, we should fix the root cause of the problem, which is that the cell's height isn't adjusted to its content size. Whatever the length or the size of the text, the cell's height should adjust and shouldn't have a fixed height. Since this relate to the settings cell, this is possibly an issue that isn't straightforward to fix since it relates to many cases (I haven't looked at it, but that's my guess).

**Comment by data-sync-user** [comment] 2023-03-29 17:25
➤ Laurie Marceau commented:

For QA, let’s ensure all settings cell (even in subpages) have proper spacing

**Comment by data-sync-user** [comment] 2023-04-11 11:40
➤ Andrei Bodea commented:

Verified as fixed on v9000 (30021) with iPhone 13 Pro (15.7.1).
This issue will also be checked when an official RC build is created for the fix version.

**Closed by data-sync-user** 2023-04-11 11:40 UTC
Labels: Contributor OK, Bug 🐞, access, Contributor Fix, S3
