### ISSUE TITLE
Page extent is wrong: top of every page is hidden by the iOS title bar

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#15116] opened 2023-06-21 18:34 UTC
## Steps to reproduce

Current iOS, iPhone 13 Pro. Probably any phone with a notch.

Broken on current and previous TestFlight, maybe longer.

Load any page with a visible top bar; GitHub is an example.

Expected: you can see the top of the page.
Actual: you have to pinch to zoom to be able to temporarily see that Firefox has the page extents wrong.

![IMG_4227](https://github.com/mozilla-mobile/firefox-ios/assets/91722/8ae09bdb-6ddf-4a89-9b06-415f0e2a3629)
![IMG_4228](https://github.com/mozilla-mobile/firefox-ios/assets/91722/b482afe7-91c0-4133-9cce-18c4ccf67385)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6785)

**Comment by lmarceau** [comment] 2023-06-21 20:58
This relates the bottom URL bar, I'll look to fix this.

**Comment by data-sync-user** [comment] 2023-06-22 19:57
➤ Laurie Marceau commented:

For QA, we can test that with the Experiment Coordinator refactor enabled (from the experiment debug settings) that with the bottom and top URL bar, webpage content is not hidden.

**Comment by data-sync-user** [comment] 2023-06-23 14:50
➤ Andrei Bodea commented:

Verified as fixed on v115 (32059) with iPhone 13 Pro (15.7.1).

**Comment by rnewman** [comment] 2023-07-06 14:22
@lmarceau I now see this issue with the URL bar on bottom. TestFlight 32373.

**Comment by lmarceau** [comment] 2023-07-06 14:30
@rnewman interesting 🤔 Could you go to the debug menu (pressing the version in the settings 5 times will open it), then open "Experiments" and see if you are enrolled in the "iOS Coordinators Rollout 2" ?

**Comment by lmarceau** [comment] 2023-07-06 14:34
I tried being in the experiment and outside of it, with the top and bottom URL bar and haven't seen the issue back yet

**Comment by rnewman** [comment] 2023-07-06 15:15
According to the experiments menu I’m not enrolled in any. I don’t see one named Coordinators.

![IMG_4487](https://github.com/mozilla-mobile/firefox-ios/assets/91722/e806c6ce-ca1b-41c5-81ee-794e8c6ea987)

**Comment by rnewman** [comment] 2023-07-06 15:18
And now I can’t repro — intermittent/racy? I’ll leave it set to Top and see if I can get a screenshot next time it happens.

**Comment by lmarceau** [comment] 2023-07-06 15:22
Ok I'll try to reproduce as well on my side. Apart from Github, I could also get the issue with Wikipedia before the fix. Maybe it's now intermittent as you said for some reasons. I'll investigate in case I can improve it

**Comment by lmarceau** [comment] 2023-07-14 21:09
Could reproduce the issue, have a fix underway for this again.

**Comment by data-sync-user** [comment] 2023-07-17 17:52
➤ Laurie Marceau commented:

For QA, we can test in v116 beta build that with the URL bar at the top or bottom, websites are properly shown in the view port. It can also be tested that wallpaper on homepage are proper (with bottom and top URL bar). No experiments necessary here since coordinators are ON in v116 by default.

**Comment by data-sync-user** [comment] 2023-07-21 10:23
➤ Andrei Bodea commented:

Verified as fixed on v116 (32873) with iPhone 13 Pro (15.7.1).

I verified some websites but also GitHub.

**Closed by data-sync-user** 2023-07-21 10:23 UTC
Labels: Bug 🐞
