### ISSUE TITLE
History items cannot be deleted after searching history

### ISSUE THREAD

**Issue by BionicBison05** [mozilla-mobile/firefox-ios#11504] opened 2022-08-03 15:44 UTC
## Steps to reproduce
- Open the history menu
- Tap the search icon
- Search within history
- Attempt to swipe to delete a history item that appears as a result

### Expected behavior
Swipe to delete works within history search results
### Actual behavior
History items cannot be deleted, even after clearing the history search bar
### Device & build information
* Device: iPhone 12
* Build version: Firefox Daylight 103.0 (13910)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4697)

**Comment by SimonBasca** [comment] 2022-08-04 08:14
This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11290

**Closed by SimonBasca** 2022-08-04 08:14 UTC
Labels: Bug 🐞
