### ISSUE TITLE
`Done` button not working in Settings after activating iOS Settings Coordinator

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15730] opened 2023-07-24 14:33 UTC
## Steps to reproduce
1. Launch FF > Settings > Experiments 
2. Activate the iOS Settings Coordinator.
3. Open Settings
4. Tap on the `Done` button to close it.
### Expected behavior
The done button should work on the settings.
### Actual behavior
The `done` button in settings is not working for the first time after activating the `settings coordinator`
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: v116 (32873) 
* First seen version: N/A 
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/dcfb9884-e886-452f-ae2f-a19f7e7f3d6f)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7077)

**Comment by data-sync-user** [comment] 2023-07-25 14:29
➤ Yoana Rios Diaz commented:

Hi  Andrei Bodea the only way I could reproduce the issue is if I don’t close the app after enabling the Settings coordinator experiment which leaves the app in a “weird” state, my understanding is that we need to close the app after every change in the experiments panel for the change to take proper effect. 

If I follow the same steps but I close the app after enabling Settings Coordinator experiments I can’t reproduce the issue anymore
cc: Laurie Marceau

**Comment by data-sync-user** [comment] 2023-08-09 14:12
➤ Andrei Bodea commented:

Hello, as we are on v117, I think by default the settings coordinator is enabled, I had like 5+fresh installs and I was able to close settings all the time. 
Closing it for now.

**Closed by data-sync-user** 2023-08-09 14:12 UTC
Labels: Bug 🐞, S3
