### ISSUE TITLE
Intense lag when opening new tab and when typing address.

### ISSUE THREAD

**Issue by thomasnilsen** [mozilla-mobile/firefox-ios#17787] opened 2023-12-16 17:54 UTC
## Steps to reproduce
open Firefox. Try to create new tab. Enter address.

### Expected behavior
quickly open new tab an responsive keyboard input.

### Actual behavior
new tab tales forever. When opening and try to enter address there is insane lag. When page start lossing everyrhing seems fine durin browsing in that tab.

### Device & build information
* Device: 15 pro Max last software. Same on 12 pro Max.
* Build version: 434158
* First seen version: ? Last few weeks. Seen same across atleast two build/appstore updates.
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7983)

**Comment by data-sync-user** [comment] 2023-12-18 20:04
➤ Norberto Andres Furlan commented:

Andrei Bodea this is the same issue as https://mozilla-hub.atlassian.net/browse/FXIOS-7988 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7988|smart-link )

**Comment by data-sync-user** [comment] 2023-12-19 13:18
➤ Diana Andreea Barladeanu commented:

Norberto Andres Furlan Verified on v121 (36782), with iPhone 15 (17.1.)

Could not reproduce this issue, I tried with 20+ opened tabs. No keyboard delay encountered.

**Comment by data-sync-user** [comment] 2023-12-20 03:19
➤ Nishant Bhasin commented:

Hi, could someone try with the following config

  * Have almost 200+ tabs opened, you can do this via settings for testing
  * Try to have an account logged into another phone or simulator
  * Make sure to have all sections in Homepage enabled

**Comment by data-sync-user** [comment] 2023-12-20 04:34
➤ Norberto Andres Furlan commented:

Andrei Bodea can you verify with the config that Nish mentioned?

**Comment by data-sync-user** [comment] 2023-12-20 12:35
➤ Andrei Bodea commented:

Hello, Norberto Andres Furlan I can see https://mozilla-hub.atlassian.net/browse/FXIOS-7988?focusedCommentId=810776&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-810776 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7988?focusedCommentId=810776&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-810776|smart-link ) being the same issue but I believe that one was opened by you, should we keep a single issue? On both looks like the same keyboard issue so would be better to focus on a single one.

**Comment by data-sync-user** [comment] 2024-01-01 16:12
➤ Ryan VanderMeulen commented:

Uplifted for 121.1 via https://github.com/mozilla-mobile/firefox-ios/pull/17847 ( https://github.com/mozilla-mobile/firefox-ios/pull/17847|smart-link )

**Comment by data-sync-user** [comment] 2024-05-13 13:03
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (41759), with iPhone 15 (17.4).

No insane lag observed.

**Comment by data-sync-user** [comment] 2024-05-17 09:50
➤ Adina Petridean commented:

Verified as fixed on v127 (41813) with iPhone 14 Pro Max (16.2).No insane lag observed.

**Closed** 2024-10-27 21:25 UTC
Labels: Bug 🐞
