### ISSUE TITLE
Closing tabs in Firefox for iOS reverts back to tab one

### ISSUE THREAD

**Issue by ckeck** [mozilla-mobile/firefox-ios#9145] opened 2021-09-21 04:50 UTC
Hello, I am encountering an issue that has become quite frustrating over the past few months. I’m noticing this issue across three different iOS devices, so I don’t believe it is isolated.

I have several pages/tabs open in Firefox for iOS on these different devices. One with roughly 30 tabs, another with about 40, and the last with about 70 or so.

The problem that I’m having is that my most used tabs are near the end/bottom. The newest windows/tabs I opened essentially. Whenever I close one of these, Firefox “slides” or reverts back to the very first open tab. Often I’m trying to just close a tab and go back to the next most recent window, which means I then get pushed back to tab one, then I’ve got to go back to the tab view and scroll all the way down after every single tab/page I close.

Why is FF not just pulling up the closest tab next to the tab/window I’m closing?

Devices: 2018 iPad Pro, iPhone 11 Pro, iPhone XS (all running iOS 14.8)
FF Version: Firefox Daylight 37.0 (5971)

This has been happening across multiple builds for some time now. Thank you for any assistance!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3185)

**Comment by dnarcese** [comment] 2021-09-23 16:54
Duplicate of #8725

**Closed by dnarcese** 2021-09-23 16:54 UTC
