### ISSUE TITLE
The letter icon is flickering in the Jump in tab when scrolling.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9432] opened 2021-10-29 16:12 UTC
## Steps to reproduce
1. Have a tab open (e.g. https://blockads.fivefilters.org/) 
2. Open a new tab and scroll to the jump in section
### Actual behavior:
- The letter icon is flickering in the Jump in tab when scrolling.
### Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 39.0(6519)
### Notes
Attachments:
https://user-images.githubusercontent.com/32130829/139466306-094a6b65-b50f-4fd9-b1ea-166c25ce6179.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3375)

**Comment by lmarceau** [comment] 2022-08-16 17:25
@SimonBasca I think this is fixed now as a side effect

**Comment by data-sync-user** [comment] 2022-08-17 11:41
➤ Simion Basca commented:

The issue is no longer reproducible on 0edd33a647a5efff980a9c4aa865d5c0d936a54e

**Closed by data-sync-user** 2022-08-17 11:41 UTC
Labels: Bug 🐞, P2
