### ISSUE TITLE
There is no biometric check (unlock) when trying to autofill any credit card

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15129] opened 2023-06-22 08:27 UTC
## Steps to reproduce
1. Launch FF and save a few credit cards.
1. Access `https://checkout.stripe.dev/preview` and tap on the `Card information` field.
1. Tap on the Use saved card.
    1. Expected behavior
The biometric lock should be displayed and the CC section should not be accessible before unlocking it with biometrics.
    1. Actual behavior
The credit card section is displayed bypassing the biometrics.
    1. Device & build information

* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
    1. Notes
Please note that it works when accessing the `manage cards` section - the biometric check is performed there.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/20e25460-2f8c-4008-863f-c6e544d18f60

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6793)

**Comment by nbhasin2** [comment] 2023-06-22 13:17
@abodea Duplicate of [FXIOS-5795](https://mozilla-hub.atlassian.net/browse/FXIOS-5795) maybe?

**Comment by abodea** [comment] 2023-06-22 14:12
Hmm sure we can close it but I was not able to find that one here on GitHub.

**Comment by data-sync-user** [comment] 2023-07-13 20:22
➤ Nishant Bhasin commented:

This should be fixed in the lastest main and also on the release/v116 branch cc Andrei Bodea

**Comment by data-sync-user** [comment] 2023-07-14 10:55
➤ Andrei Bodea commented:

Verified as fixed on v116 (32694) with iPhone 13 Pro (15.7.1).

**Closed by data-sync-user** 2023-07-14 10:54 UTC
Labels: Bug 🐞, S1, credit-card-autofill
