### ISSUE TITLE
Firefox Focus 124.0 crashes on startup on iOS

### ISSUE THREAD

**Issue by SanderGit** [mozilla-mobile/firefox-ios#19287] opened 2024-03-19 07:53 UTC
## Logs
Attached

## Steps to reproduce
Open Firefox Focus 124.0

### Expected behavior
App launches

### Actual behavior
App disappears immediately

### Device & build information
* Device: iPhone 14 with iOS 17.4, iPad Pro 2016 with iPadOS 16.7.5
* Build version: 124.0
*
[Firefox Focus-2024-03-19-064727.txt](https://github.com/mozilla-mobile/firefox-ios/files/14647219/Firefox.Focus-2024-03-19-064727.txt)

### Notes
Attachments: 
Crash report

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8698)

**Comment by isabelrios** [comment] 2024-03-19 08:43
cc @abodea

**Comment by abodea** [comment] 2024-03-19 09:19
Hello thank you for your report @andreusanchez I will check soon and get back with the info I will find.

**Comment by abodea** [comment] 2024-03-19 09:55
@SanderGit can you please provide more steps? Is it only on launch? 
So far I was not able to reproduce it and I did check the AppStore version too. 
I tried on the iPhone 15 Pro (17.3), iPhone 13 Pro (15.7.1), and iPad Pro (15.7). But I did not encounter any crashes.

**Comment by SanderGit** [comment] 2024-03-19 10:42
@abodea It happens immediately on launch. As @andreusanchez writes, it does not happen anymore after changing language (from my default language Dutch) to English.

**Comment by abodea** [comment] 2024-03-19 14:01
Thank you, I was able to reproduce the crash only while having the default language Dutch as you mentioned but the moment I've set it to English it worked well.

**Comment by ceriklee** [comment] 2024-03-20 04:41
I have same issue too. The phenomenon of reproduction is also similar. Changing to English as default language, Firefox Focus app could launch. When I change back to Korean as default language of iPhone, the problem recurs.

iOS 17.4 (iPhone Pro Max 15)

issue happens on default language : Korean (한국어)

**Comment by data-sync-user** [comment] 2024-03-20 11:58
➤ Andrei Bodea commented:

Verified as fixed on v124.1 (39919) with iPhone 15 Pro (17.3.1).

  * Please note that I verified the following languages: (Dutch, Czech, Armenian, Chinese, Hungarian, Icelandic, Latvian, Greek, Catalan, Korean).
  * Focus doesn’t crash on launch anymore.

**Closed by data-sync-user** 2024-03-20 11:58 UTC
Labels: Crash
