### ISSUE TITLE
FXIOS-1511 ⁃ [Crash] App crashes when it is relaunched after device is switched off/on

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8023] opened 2021-02-23 11:30 UTC
## Steps to reproduce
Firefox-iOS is open in background with around 15 tabs open (chron tabs view)
The device runs out of battery
Turn on the device after it is charged
Open Firefox-iOS
### Expected behavior
The app opens as usual
### Actual behavior
The app crashes. This does not happen 100% but I have seen it very often lately

### Device & build information
* Device: iPhone 6s
* Build version: beta 32 (3815), (3814

I will try to find the crash report next time this happens

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1511)

**Comment by isabelrios** [comment] 2021-02-23 11:31
cc @SimonBasca in case you can try to reproduce those steps... it may happen 1/3 of the times or so... thanks

**Comment by SimonBasca** [comment] 2021-02-24 16:05
I was unable to reproduce this issue on iPhone Xr (14.4) on v 32.0 (3823).

**Comment by dnarcese** [comment] 2021-03-18 18:22
Should check if the fix for this also fixes #8088

**Comment by isabelrios** [comment] 2021-03-25 16:50
I have not reproduced this lately, I would say since I updated to v32.1...now I'm on v33 and have not seen it yet...

**Comment by SimonBasca** [comment] 2021-05-24 09:24
I was unable to reproduce this issue. I think this can be closed and we should re-open if it's reproducible again. Tested on iPhone Xr 14.4 (4900)

**Closed by SimonBasca** 2021-05-24 09:24 UTC
Labels: Bug 🐞, Crash, Needs QA, P1, qa-triaged
