### ISSUE TITLE
FXIOS-1917 ⁃ Tab widths shrink each time more tabs are opened.

### ISSUE THREAD

**Issue by jmiguy** [mozilla-mobile/firefox-ios#8647] opened 2021-06-06 16:09 UTC
In the newest version of Firefox, the tab widths keep shrinking as more tabs are opened. I cannot read the tabs or click on them without them closing. This is ridiculous. I'm assuming this is a bug, as this would be a TERRIBLE design. Please put them back the way they were, where the tab widths never change, regardless of how many tabs are opened. Thanks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1917)

**Comment by SimonBasca** [comment] 2021-06-07 08:22
This seems as a duplicate of #8648. Thanks for the feedback.

**Closed by SimonBasca** 2021-06-07 08:22 UTC
