### ISSUE TITLE
App crashes when adding custom search engine

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [mozilla-mobile/firefox-ios#11649] opened 2022-08-19 08:16 UTC
Hey there! Great work!

Unfortunatly with the new update, the app crashes on iphone and ipad if I try to add a new custom search engine. (Whoogle self hostet)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4792)

**Comment by SimonBasca** [comment] 2022-08-19 08:24
Thanks for the feedback. The fix for this problem was merged for v105. Marking as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/11187

**Closed by SimonBasca** 2022-08-19 08:24 UTC
