### ISSUE TITLE
Add ability to set custom identity.sync.tokenserver.uri for self-hosted Sync

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5006] opened 2019-05-20 07:28 UTC
User Agent: Mozilla/5.0 (X11; CrOS x86_64 11316.165.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36

Related issue: https://github.com/mozilla-mobile/firefox-ios/issues/3150

Steps to reproduce:

There is currently no way to specify a custom URL for a Firefox Sync Server (token url) while using the publicly available, Mozilla-hosted Firefox Accounts service.

Actual results:

There is no option to do this.

Expected results:

There should be an option like on Android to specify to custom token URL for self-hosted sync server. This option is available on desktop Firefox and on Firefox for Android.

**Comment by SimonBasca** [comment] 2019-05-20 07:31
**Jerry Heiselman:**
I have attempted to create a fxa-client-configuration file located at https://thor.heiselman.com/.well-known/fxa-client-configuration that mirrors the one served by accounts.firefox.com with the one change being the URL for the sync tokenserver url to point to my own.

When configuring this URL in Firefox on iOS using the method of revealing the hidden Advance Account Settings menu by tapping repeatedly on the Version string in the Settings. I filled in the base URL for my server (https://thor.heiselman.com) and enable the "Use Custom Account Service" option. Once I enable the option, I can see the client request the fxa-client-configuration file from my server successfully, however, it then attempts to load the login page on my server despite the configuration pointing all other services back to the public Firefox service.

**m.m.naseri@gmail.com:**
Can we bump the priority of this bug from a P3? Many people seem to be holding off moving to the FF ecosystem simply because they can’t carry their privately stored data without the additional cost of setting up an account server.

This clearly breaks the user experience and I’d have imagined that after a couple years of back and forth on Github this would’ve received more attention.

**Comment by mmnaseri** [comment] 2019-05-24 04:09
Also mentioned in #3150 (which was closed in favor of the bug in the bugzilla system).

**Comment by jheiselman** [comment] 2019-05-24 08:11
I was the submitter of the Bugzilla report. I am still willing to work with someone here to help resolve this.

**Comment by jellium** [comment] 2019-05-30 16:59
This option (choose what Firefox Sync server to use) should definitely be available on iOS (as it appears to be available on Android). Looking forward to being able to set it up.

**Comment by mwegner** [comment] 2019-05-30 19:49
I recently made the switch to Firefox as my default browser (I think a lot of developer types have it installed, but drift back to their old setups for various comfort/muscle memory reasons). I would absolutely love to have the iOS version support a custom sync server.

There are quite a few "homelab" types that run significant infrastructure at home (i.e. VM hosts), and running something like a custom sync server doesn't add any extra overhead to their tech setup.  I would absolutely run it, but it doesn't make any sense unless all of my Firefox devices can also use it.

**Comment by garvankeeley** [comment] 2019-06-05 18:51
When implemented, ensure URLs are https or localhost. This is a sec requirement from app services.

**Comment by jheiselman** [comment] 2019-06-05 23:39
@garvankeeley if you look at my comment (copied from the original bug), all URLs are HTTPS with valid LE certs.

**Comment by garvankeeley** [comment] 2019-06-13 14:18
On desktop this is set in about:config using `identity.fxaccounts.autoconfig.uri`
Docs: https://moz-services-docs.readthedocs.io/en/latest/howtos/run-fxa.html

**Comment by jheiselman** [comment] 2019-06-13 14:21
@garvankeeley this issue is specifically for Firefox on iOS which has no about:config

**Comment by nook24** [comment] 2019-06-13 15:03
Is there a schedule available for this feature?

>Many people seem to be holding off moving to the FF ecosystem simply because they can’t carry their privately stored data without the additional cost of setting up an account server.

This is exactly the reason why I don't use FF sync on any of my devices. Just because a self-hosted sync server it's not implemented on iOS :(

**Comment by jheiselman** [comment] 2019-06-13 15:06
Same here @nook24. I already have the sync server setup for my Linux desktop. But I don’t use FF on my iPhone because of this. I would in a heartbeat though.

**Comment by garvankeeley** [comment] 2019-06-13 15:45
I have confirmed this works as-intended, but the intention is that the entire stack is being hosted on the custom URL where the config file is.

**Comment by garvankeeley** [comment] 2019-06-13 15:48
Closing this bug as works as-intended, the docs here still apply as to how to use your own fxa and sync stack: https://moz-services-docs.readthedocs.io/en/latest/howtos/run-fxa.html

**Comment by jheiselman** [comment] 2019-06-13 15:52
I’m very disappointed that we (the users) simply aren’t being heard. We *know* it’s working as intended. We want how it works to change. I feel like plenty of people have laid out perfectly valid reasons for the behavior to change. And the lack of willingness to even acknowledge that this leaves iOS at a distinct disadvantage shows a poor attitude towards the Firefox  community as a whole. 

I stand by my offer to help test any changes if anyone is willing to actually listen and attempt to implement this feature request.

**Comment by justindarc** [comment] 2019-06-13 16:00
You are being heard. In fact, we were willing to spend a few hours today investigating this before concluding that this is not solely an iOS issue, but an FxA issue for something that is currently not supported. With limited resources, we have to prioritize issues and feature requests and the overall number of users who want this feature is almost immeasurably small.

**Comment by justindarc** [comment] 2019-06-13 16:03
You are also welcome to run your own full FxA/Sync stack and you can follow the steps outlined here to configure iOS to work with it: https://moz-services-docs.readthedocs.io/en/latest/howtos/run-fxa.html

**Comment by jheiselman** [comment] 2019-06-13 17:16
I will be available to have a discussion around 2:00 pm US/Central and for most of the day after. 

As for running a full stack server, it has been stated by several users that there are specific reasons for some of us to not want to do that.

**Comment by garvankeeley** [comment] 2019-06-13 18:22
This is a discussion to have with the FxA/Sync team, they implemented this feature in the product with the intention that it be consistent with Android behaviour. If more users make this request across the various products then I could see that changing their opinion.

**Comment by nook24** [comment] 2019-06-13 19:09
Thanks for your time and investigation effort. I really appreciate this.

From the [docs](https://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync-1.5.html) :
>Note By default, a server set up using this guide will defer authentication to the Mozilla-hosted accounts server at https://accounts.firefox.com.
>You can safely use the Mozilla-hosted Firefox Accounts server in combination with a self-hosted sync storage server. The authentication and encryption protocols are designed so that the account server does not know the user’s plaintext password, and therefore cannot access their stored sync data.
>
>Alternatively, you can also Run your own Firefox Accounts Server to control all aspects of the system. The process for doing so is currently very experimental and not well documented.

I would say there should be a big fat warning, that the docs will not work for iOS devices.

I had given the `/.well-known/fxa-client-configuration` trick a shot but this didn't work. (As already expected).

>This is a discussion to have with the FxA/Sync team, they implemented this feature in the product with the intention that it be consistent with Android behaviour.

I would really like to know why the option is not available on iOS. Is this an restriction from Apple or so?
I mean, it's available  on Desktop and Android.
Again from the docs:
> Since Firefox 33, Firefox for Android has supported custom sync servers. To configure Android Firefox 44 and later to talk to your new Sync server, just set the “identity.sync.tokenserver.uri” exactly as above before signing in to Firefox Accounts and Sync on your Android device.

Are there just not enough iOS based Firefox users? 

Please don't get me wrong. I don't want to blame anyone why this isn't implemented already. I'm just wondering why there is a different behavior.

**Comment by garvankeeley** [comment] 2019-06-13 19:16
> I would say there should be a big fat warning, that the docs will not work for iOS devices.
 > I had given the `/.well-known/fxa-client-configuration` trick a shot but this didn't work. (As already expected).

Can you indicate what part doesn't work specifically on iOS? If so, I can report this to the FxA/Sync team to investigate further. 
The bug report here indicates that the content server is not on the same host as the `/.well-known/fxa-client-configuration`, which according to the server team, is correct behaviour for all platforms.

> I would really like to know why the option is not available on iOS. Is this an restriction from Apple or so?

Firefox iOS should behave like Desktop and Android, if I can show that it isn't behaving consistently, I can get traction on getting something fixed.

**Comment by jheiselman** [comment] 2019-06-13 19:24
Firefox on iOS doesn't have the ability to use about:config to configure the syncserver (token server) URL. Therefore, it already doesn't have feature parity with Android and desktop versions. This means that iOS users _cannot_ follow the same setup procedure as Android and desktop users.

iOS users only have the option to "Use Custom Account Service". This asks for a single URL at which it will retrieve the /.well-known/fxa-client-configuration. The structure of this file is a listing of the different components with URLs for each piece. The documentation indicates that one can set each value independently.

While Firefox on iOS does query and retrieve the fxa-client-configuration file, it doesn't obey it as far as the different URLs are listed. As stated earlier in this issue, I downloaded the file from the public Firefox Accounts service and changed only the URL for the token server and hosted that changed file on my own server (same one hosting the syncserver). The file contents are as follows:

`{"auth_server_base_url":"https://api.accounts.firefox.com","oauth_server_base_url":"https://oauth.accounts.firefox.com","pairing_server_base_uri":"wss://channelserver.services.mozilla.com","profile_server_base_url":"https://profile.accounts.firefox.com","sync_tokenserver_base_url":"https://thor.heiselman.com/sync/token/1.0/sync/1.5"}`

Firefox on iOS doesn't seem to use any of these other values and instead attend to authorize against the hosting server instead of any of the others listed here.

**Comment by nook24** [comment] 2019-06-13 19:30
1. I installed my Sync Server like described in: https://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync-1.5.html
2. I created an Firefox Sync Account at https://accounts.firefox.com
3. I created: https://sync.nook24.eu/.well-known/fxa-client-configuration
4. On my Desktop Firefox (Mac and Windows) i set `identity.sync.tokenserver.uri` to `https://sync.nook24.eu/token/1.0/sync/1.5` using `about:config`
5. Desktop Sync works.

iOS Setup:
1. Advance Acount Settings
2. Set Custom Account Url to `https://sync.nook24.eu` and enable "Use custom Account Service"
3. Check access.log:
````
xxx.xxx.xxx.xxx - - [13/Jun/2019:21:26:39 +0200] "GET /.well-known/fxa-client-configuration HTTP/1.1" 304 5373 "-" "Client/15323 CFNetwork/976 Darwin/18.2.0"
````
4. Login to Sync ("Bei Sync anmelden") Firefox tries to load the login page from my server:
````
xxx.xxx.xxx.xxx - - [13/Jun/2019:21:27:37 +0200] "GET /signin?service=sync&context=fx_ios_v1 HTTP/1.1" 404 5542 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/17.3b15323 Mobile/16D57 Safari/605.1.15"
````
5. Firefox error: Could not load page ("Seite konnte nicht geladen werden.")

**Comment by garvankeeley** [comment] 2019-06-13 19:39
@vbudhram do you mind looking at the last comment, the user was able to avoid hosting the content server when setting identity.sync.tokenserver.uri on Desktop, but this appears unavoidable on iOS. Should iOS not behave the same?

**Comment by jheiselman** [comment] 2019-06-13 19:59
[These are the exact instructions](https://github.com/mozilla-mobile/firefox-ios/issues/5006#issuecomment-501847415) I followed as well.

**Comment by justindarc** [comment] 2019-06-13 20:12
Ok, after talking with some more FxA folks, it seems that you are correct and this should be supportable as long as we add a *new* pref on iOS explicitly for `identity.sync.tokenserver.uri`. I'll update the title to add clarity here so that this work can get scheduled.

**Comment by nook24** [comment] 2019-06-13 20:16
Sounds good! Looking forward to get this.
Many thanks to all of you.

**Comment by jheiselman** [comment] 2019-06-13 20:18
Thank you justindarc. This looks like it will work great for us!

**Comment by justindarc** [comment] 2019-06-13 20:26
No problem. Sorry for the confusion.

**Comment by justindarc** [comment] 2019-06-17 18:30
WIP pull request: https://github.com/mozilla-mobile/firefox-ios/pull/5158

**Closed** 2019-06-20 17:09 UTC
Labels: Feature 🎁

**Comment by fireglow** [comment] 2019-07-07 04:31
I got the update on iOS today, thanks to all involved for making this happen!
Is it working for everybody as expected?
All I'm seeing is a `GET /mozilla/token/1.0/sync/1.5 HTTP/2.0" 200 893.
Nothing for `/storage/`, no actual syncing.

**Comment by s-fiebig** [comment] 2019-07-07 08:59
Installed the iOS update an hour ago and everything is working as expected. Set the token server, restarted Firefox and logged in to my Firefox account. Syncing is also working in both directions. 
@fireglow My sync server is running under http (at least for now), maybe this makes a difference.

Thanks to all involved for making this happen!

**Comment by nook24** [comment] 2019-07-07 17:10
Works like expected for me, many thanks to all.

This is my setup: https://daniel-ziegler.com/computer/netzwerk/linux/2019/07/07/Firefox-Sync-iOS/

**Comment by Balooforever** [comment] 2019-07-09 15:03
Don't work for me :(
I use the docker ffsync image and a reverse-proxy.
How i can get log from iOS ?

**Comment by jheiselman** [comment] 2019-07-10 02:32
I finally got the chance to test this out and am running into a problem.

I'm running the syncserver from Docker Hub (same as I always have). Firefox on my iPhone is able to set the token server, I'm able to login, and I see the request make it to the sync server. The device is added to my (Mozilla hosted) Firefox Account and my desktop browser pops up a notification saying that the iPhone was added to my account. I am able to send pages back and forth between my two browsers. However, my bookmarks, history, open tabs, and logins/passwords are not syncing.

All of the requests to my sync server are resulting in HTTP 200 status codes and I was using this sync server with my Android phone, so I think everything is setup properly there, but I'd be happy to do some testing/logging if someone points me in a direction.

**Comment by Balooforever** [comment] 2019-07-10 04:56
Same for me @jheiselman , thank for your post, i'm not english : it's hard for me to explain !
I use Docker Hub too and it's doesn't work.

**Comment by captn3m0** [comment] 2019-07-14 21:05
Same issue here. Logs give 200:

``
10.8.0.1 - - [14/Jul/2019:20:59:32 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22306 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 4ms
10.8.0.1 - - [14/Jul/2019:20:59:45 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22325 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 2ms
10.8.0.1 - - [14/Jul/2019:21:00:00 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22339 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 2ms
10.8.0.1 - - [14/Jul/2019:21:00:03 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22340 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 2ms
10.8.0.1 - - [14/Jul/2019:21:00:37 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22360 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 2ms
10.8.0.1 - - [14/Jul/2019:21:00:40 +0000] "GET /token/1.0/sync/1.5 HTTP/2.0" 200 513 "-" "Firefox-iOS-FxA/18.0b15690 (iPhone; iPhone OS 12.3.1) (Firefox)" 22364 "Host-firesync-bb8-fun-0" "http://172.22.0.22:5000" 2ms
```

"Send tab to device" feature works sometimes (with a lot of lag and Firefox restarts). Bookmarks and other content sync doesn't work at all.

**Comment by BirgerK** [comment] 2019-08-25 16:45
@jheiselmann:




Same problem for me.

All other devices (PC, Android) are able to sync. I also see my iOS device on my Firefox devices list.

But the iOS device cannot sync any bookmark or "synced tabs". I can't even send a tab from another device to the iPad, because the iPad doesn't appear on the shown list. (Again: my iPad appears on the devices list on my profile!)

**Comment by fireglow** [comment] 2019-08-25 16:52
Question for those that cannot get sync going:
Are you using **nginx**?

I tried and failed with nginx, had to set up a lighttpd on a dedicated port and switch every device, iOS or not, over to that port. Only then sync worked in iOS.

**Comment by BirgerK** [comment] 2019-08-25 16:54
Yes, nginx. But no chance to change the proxy! Is it missing some headers?

All other devices (PC, Android, Mac) are able to sync without any problems.

**Comment by jheiselman** [comment] 2019-08-25 16:55
@fireglow I am not using nginx. I am using Caddy HTTP server.

Further, for those of us who can’t get it to work, it seems to be the same in that each of us can use it from a PC and Android. It’s only iOS based devices that don’t work. So, I don’t *think* there is something wrong in the web server setup.

**Comment by fireglow** [comment] 2019-08-25 17:09
It has to be something, it'll be interesting to know what server people are having success with, and which servers are failing.

I'm having success with lighttpd with
```
$SERVER["socket"] == "10.0.112.1:8888" {
  ssl.engine  = "enable" 
  ssl.pemfile = "/usr/local/etc/ssl/acme/foo.bar/cert.pem" 
  ssl.privkey = "/usr/local/etc/ssl/acme/foo.bar/key.pem" 
  $HTTP["host"] == "sync.foo.bar" {
    ssl.pemfile = "/usr/local/etc/ssl/acme/sync.foo.bar/cert.pem" 
    ssl.privkey = "/usr/local/etc/ssl/acme/sync.foo.bar/key.pem" 
    proxy.server = ( "" =>
                   ( ( 
                       "host" => "jail_mozillasync",
                       "port" => 5000
                     ) )
                  )
    proxy.forwarded = ( "for"   => 1,
                        "proto" => 1,
                        "host"  => 1,
                      )
  }
}
```

**Comment by jheiselman** [comment] 2019-08-25 17:11
Hmm. Well, I can try swapping out the web layer this evening to see if that makes a difference for me. If it works, then I can see about putting wireshark on it to check out the headers.

**Comment by captn3m0** [comment] 2019-08-26 17:17
I'm running Traefik in front of the syncserver to terminate TLS, it does forward all 3 X-Forwarded headers.

**Comment by Mardiie** [comment] 2019-09-15 00:24
> 
> 
> It has to be something, it'll be interesting to know what server people are having success with, and which servers are failing.
> 
> I'm having success with lighttpd with
> 
> ```
> $SERVER["socket"] == "10.0.112.1:8888" {
>   ssl.engine  = "enable" 
>   ssl.pemfile = "/usr/local/etc/ssl/acme/foo.bar/cert.pem" 
>   ssl.privkey = "/usr/local/etc/ssl/acme/foo.bar/key.pem" 
>   $HTTP["host"] == "sync.foo.bar" {
>     ssl.pemfile = "/usr/local/etc/ssl/acme/sync.foo.bar/cert.pem" 
>     ssl.privkey = "/usr/local/etc/ssl/acme/sync.foo.bar/key.pem" 
>     proxy.server = ( "" =>
>                    ( ( 
>                        "host" => "jail_mozillasync",
>                        "port" => 5000
>                      ) )
>                   )
>     proxy.forwarded = ( "for"   => 1,
>                         "proto" => 1,
>                         "host"  => 1,
>                       )
>   }
> }
> ```

are you by any chance using the account service as well? 
it seems the combo works if you have to believe Mozilla's own guide.
https://mozilla-services.readthedocs.io/en/latest/howtos/run-fxa.html

**Comment by jheiselman** [comment] 2019-09-16 13:02
@Mardiie I am not running the account server. My setup is using the Mozilla-hosted FxA while using a self-hosted sync server.

**Comment by Strayer** [comment] 2019-09-29 06:33
For the record, I’m having the same issue. Login works but nothing syncs. I’m using Traefik in front of syncserver too with let’s encrypt.

**Comment by dprandzioch** [comment] 2019-10-12 05:53
Same problem here. Is it about some configuration of the sync server (e.g. that we have to use FORCE_WSGI_ENVIRON and the seen url does not match the configured application url? Or is it some missing header on the reverse proxy? I use Caddy as a reverse proxy, use LE certificates and forward all the necessary X-Forwarded- headers.

However I have the same problems, send tab to device works but sync is not started, no request to the /storage endpoints are being made. From my Mac it works perfectly.

**Comment by dprandzioch** [comment] 2019-10-12 21:15
Figured it out! HTTP/2.0 seems to be the problem. After forcing http 1.1 in caddy using:

`tls {
    alpn http/1.1
} `

everything works just fine!

I assume this is also the reason why it does not work with nginx as a reverse proxy while it does with lighttpd (where HTTP/2.0 is not turned on). Hope this helps.

**Comment by Findus23** [comment] 2019-10-13 12:24
@dprandzioch 
That would make a lot of sense. Unfortunatly I can't test this as in nginx one can't disable http2 per vhost.

But that would mean that something in firefox-ios is broken to not accept http2, but also don't do a http1.1 request.

**Comment by BobWs** [comment] 2019-10-13 14:28
Unfortunately it is working for me to sync with an ios device. My desktop FF on MacOS and Windows works fine. I can even sync with Waterfox. I'm using docker image from crazy-max https://github.com/crazy-max/docker-firefox-syncserver on a Synology NAS and Reverse proxy of Synology NAS setup properly with http proxy version set to 1.1 but it still wouldn't sync.


![Screen Shot 2019-10-13 at 16 23 39](https://user-images.githubusercontent.com/5485820/66717180-6da7ab80-edd6-11e9-94be-ced3f2e729ea.png)

Any ideas? Has someone solved this problem yet with ios not syncing?

**Comment by fireglow** [comment] 2019-10-14 07:08
> Figured it out! HTTP/2.0 seems to be the problem. 
Wow, amazing! Just tested it with nginx, it works!

For nginx, the `proxy_http_version 1.1;` directive is required:

```
# mozilla syncserver <https://github.com/mozilla-services/docs/blob/master/source/howtos/run-sync-1.5.rst>
# mozillasync
location /mozilla/ {
    # jail mozillasync
    proxy_pass http://jail_mozillasync:5000;
    rewrite ^/mozilla(/.*)$ /$1 break;
    proxy_http_version 1.1;

    # <http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect>
    proxy_redirect off;

    client_body_buffer_size 15M;
    proxy_set_header Host $http_host;
    proxy_set_header X-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 120;
    proxy_connect_timeout 10;
    access_log /var/log/nginx/mozillasync.log superlog;
}
```
(This is for a subdirectory to example.com)

**Comment by BirgerK** [comment] 2019-10-14 10:14
yes, works also for me, when disabling HTTP2 !

**Comment by jheiselman** [comment] 2019-10-15 00:34
I wasn't able to get this working just yet. I have the server offering only http/1.1 when the SNI is set to my hostname, and when I use curl to check it, I can see that http/1.1 is being accepted, but the sync still doesn't work.

Using caddy 2.

**Comment by zsadeghi** [comment] 2019-10-17 00:54
So, besides all the related server configurations, where in the iOS app do you actually set the location of the sync server? about:config on the latest iOS build still brings up an empty page for me and I don't see any settings on the sync setting page in the app.

**Comment by mmnaseri** [comment] 2019-10-17 00:55
So, besides all the related server configurations, where in the iOS app do you actually set the location of the sync server? about:config on the latest iOS build still brings up an empty page for me and I don't see any settings on the sync setting page in the app.

**Comment by jheiselman** [comment] 2019-10-17 00:58
@mmnaseri scroll down and tap the Version line a handful of times. After a few (five?) taps, more menu items will appear including Advanced up under Sign In. In there, you can set a custom sync server or a custom token server.

**Comment by BobWs** [comment] 2019-10-18 14:17
> @mmnaseri scroll down and tap the Version line a handful of times. After a few (five?) taps, more menu items will appear including Advanced up under Sign In. In there, you can set a custom sync server or a custom token server.

Have tried that but still doesn't sync. I'm using FF syncserver from https://github.com/crazy-max/docker-firefox-syncserver on a Synology NAS and Reverse proxy of Synology NAS setup properly with http proxy version set to 1.1

Do you think it is related to a specific version of firefox synserver?

**Comment by Section1977** [comment] 2019-11-10 09:27
same here, please fix
running crazy-max docker all is fine beside Firefox for iOS does not sync bookmarks etc.
Sending a tab works
using Firefox so is not an option for Apple Safari

**Comment by parsifallo** [comment] 2019-12-02 19:28
Same here. Firefox syncs with my private server across Mac, Windows and Android devices but iOS won't work. Using latest version 20.2 (16690)

**Comment by mavidser** [comment] 2019-12-05 15:22
Can anyone confirm that HTTP/2 seems to be the fault? I can't disable HTTP/2 for a specific host (using traefik), but I see that the requests made are HTTP/2, so it's strange that it only expects HTTP/1.1 as the response.

**Comment by BirgerK** [comment] 2019-12-07 17:30
@mavidser yes, in my case it fixed the problem by disabling HTTP2.

**Comment by jheiselman** [comment] 2019-12-07 18:17
Yes, this solved my issue as well. Forcing the connection to HTTP 1.1 fixed it.

**Comment by Mardiie** [comment] 2019-12-07 23:29
While it's nice to have a fix, this isn't really a fix, since your
compromising security for it. This should really be taken care of.

Op za 7 dec. 2019 om 19:17 schreef Jerry Heiselman <notifications@github.com

**Comment by jheiselman** [comment] 2019-12-08 00:40
I’m not sure I’d agree that you’re compromising security. HTTP/2 is more about efficiency. If you secure your server with a certificate, then it’s still encrypted communication. Besides, you can still accept HTTP/2 over the internet and terminate and use HTTP/1.1 just between the front end proxy and the syncserver. 

That said, I agree that this is a workaround at best, not a solution.

**Comment by fireglow** [comment] 2019-12-08 00:45
Just to chime in a little:
Python 2.7, the flavor it Python this software is written in, will go End-of-Life at the end of this month, year, and decade.
Mozilla already has indicated that there will be no rewrite for Python 3.
I gather there's a rewrite of these services in Rust in the works, at https://github.com/mozilla-services/syncstorage-rs
It's as of now unclear to me how all these parts will fit together in a way so us self-hosters will be migrate over.

**Comment by jheiselman** [comment] 2019-12-08 01:26
Fire glow, good point! I hadn’t considered if there was a rewrite in the works. Hopefully the rust version is released soonish.

**Comment by mavidser** [comment] 2019-12-10 12:19
> Besides, you can still accept HTTP/2 over the internet and terminate and use HTTP/1.1 just between the front end proxy and the syncserver.

@jheiselman I was under the impression that since it's only the iOS client which has this issue, HTTP 1.1 is needed on the internet, and doesn't matter on the syncserver. If that's the case, the client problems might still persist with the rust server too.

**Comment by creywood** [comment] 2019-12-12 14:23
Seeing the same issue here; login works and I can see the server being hit but nothing comes across. The same sync server works without issues on Android, desktop Linux and macOS. 

Firefox iOS v20.2, iOS v12.4.4, sync server v1.8.0, nginx v1.10.3.

Sync log from iPad upon attempt to sync:

[iPad-sync-failure-sync.20191212T102735+0100.log](https://github.com/mozilla-mobile/firefox-ios/files/3956102/iPad-sync-failure-sync.20191212T102735%2B0100.log)

Maybe this warrants a separate issue?

**Comment by mmnaseri** [comment] 2020-06-29 01:03
There is now a regression after FF 25 (as reported in #6535) that has broken this workflow, and as such, this feature is not usable on iOS anymore. Not being able to access history/bookmarks on my primary mobile device is a deal breaker for most users.

**Comment by Blitzbirnep** [comment] 2020-07-02 12:53
Any chances to get this fixed?

**Setup**
I have a similar setup as described before. I am self-hosting the sync server Mozilla docker image from [here](https://registry.hub.docker.com/r/mozilla/syncserver) on a synology nas. The reverse proxy is configured without http2 support and uses https protocol with hsts.  

**Issue**
Invalid OAuth parameter: redirect_url with Firfox IOS App 27.0 (18428) when trying to connect to the custom sync server

**Comment by sprangen** [comment] 2020-07-08 21:02
> Any chances to get this fixed?
> 
> **Setup**
> I have a similar setup as described before. I am self-hosting the sync server Mozilla docker image from [here](https://registry.hub.docker.com/r/mozilla/syncserver) on a synology nas. The reverse proxy is configured without http2 support and uses https protocol with hsts.
> 
> **Issue**
> Invalid OAuth parameter: redirect_url with Firfox IOS App 27.0 (18428) when trying to connect to the custom sync server

i can second that. same behaviour here.

**Comment by delacroix0815** [comment] 2020-07-09 19:21
Same here. When trying to active sync after i set a custom sync server, i get two choices:

1. Scan QR-Code provided by stable.dev.lcip.org/pair
or
2. Use Email Address instead

1. when i go to stable.dev.lcip.org/pair, i always get a message like 'are you using your system camera? Then you have to connect out of a Firefox App', and no QR Code is showing up. Also the URL bar changes to 'https://stable.dev.lcip.org/pair/unsupported'.

2. Using the Email Button gives Invalid OAuth parameter: redirect_url

**Comment by parsifallo** [comment] 2020-07-09 19:34
same here

**Comment by HackintoshHD** [comment] 2020-07-25 20:31
Same problem as described by @delacroix0815 above with Firefox/iOS 27.0 (18428) running on iPadOS 13.6.

**Comment by BobWs** [comment] 2020-07-26 06:19
Still the same problem on Synology Nas with this image https://github.com/crazy-max/docker-firefox-syncserver

**Comment by Thlb** [comment] 2020-08-12 23:41
Same here ...

**Comment by jellium** [comment] 2020-09-05 17:55
This issue should be reopened since the feature appears to have been removed on latest versions (not sure when it was actually removed).

**Comment by jheiselman** [comment] 2020-09-05 18:01
It’s not removed, it just doesn’t work. You can still enable the developer settings by tapping repeatedly on the version. There’s still a spot for a Custom Sync Token Server under Advanced Sync Settings. And it seems to actually connect. It just doesn’t sync bookmarks or tabs anymore. The “Send to device” works. That’s pretty much it.

I feel like this feature is just abandoned which is too bad. I may as well switch back to Safari.

**Comment by jellium** [comment] 2020-09-05 18:15
> It’s not removed, it just doesn’t work. You can still enable the developer settings by tapping repeatedly on the version. There’s still a spot for a Custom Sync Token Server under Advanced Sync Settings. And it seems to actually connect. It just doesn’t sync bookmarks or tabs anymore. The “Send to device” works. That’s pretty much it.
> 
> 
> 
> I feel like this feature is just abandoned which is too bad. I may as well switch back to Safari. 

I cannot seem to find the Advanced Sync Settings within the debug mode anymore. That is why I believed the feature  was actually removed. Where is this settings button hidden?

**Comment by jheiselman** [comment] 2020-09-05 18:24
Settings -> Tap Version row under About heading near the bottom. After some number of taps (10?) the debug menus show up at the bottom. Back near the top will be the Advanced Sync Server settings. Note that it will only show up if you are not currently signed in to Sync.

**Comment by Thlb** [comment] 2020-09-05 23:07
@jheiselman This feature is completly broken, given we cannot link a device to a custom sync server anymore (see #6535). What's the point of being able to configure a custom server if you cannot connect to it ?

**Comment by jheiselman** [comment] 2020-09-05 23:11
@Thlb I agree completely. I was just stating that it wasn't removed; just broken. It's been broken for quite some time now and no one seems to be paying any attention to this issue since it was closed. I suppose one should re-open it, but I feel like this isn't something that the Mozilla iOS team cares much about given how it took quite a bit of back and forth to even get someone to add the feature and then it was immediately broken after the next update.

**Comment by Balooforever** [comment] 2020-09-06 06:24
Reopen, still broken ..
Time for change ..

**Comment by nook24** [comment] 2020-09-07 06:22
For all following this issue or find it through web search: @drixter figured out how to restore the custom sync server feature on current iOS versions of Firefox.

Original post: https://github.com/mozilla-mobile/firefox-ios/issues/6535#issuecomment-687747921

Summary: https://github.com/mozilla-mobile/firefox-ios/issues/6535#issuecomment-687751723
