### ISSUE TITLE
The operation couldn't be completed `(MozillaAppServices.AUtofillApiError error 3.)` displayed when trying to update the card information from a payment

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15139] opened 2023-06-22 11:23 UTC
## Steps to reproduce
1. Launch FF and save a few cards.
2. Access https://checkout.stripe.dev/preview and perform a payment with a card that is already saved (but changes the date expiration).
3. Update this card prompt is displayed.
4. Tap on the Yes button. 

### Expected behavior
The card should be updated accordingly.
### Actual behavior
The operation couldn't be completed `(MozillaAppServices.AUtofillApiError error 3.)` displayed when trying to update the card information from a payment.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/28451194-2425-4931-897e-18b08505bcba

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/83a68f4c-7196-4669-9c2b-a3b0abc9c1bc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6799)

**Comment by data-sync-user** [comment] 2023-07-03 13:21
➤ Stefan Vladut commented:

No luck recreating the bug so far, but I’ll keep an eye in case it happens.

**Comment by data-sync-user** [comment] 2023-07-06 14:51
➤ Andrei Bodea commented:

Please note that I was not able to reproduce it anymore, discussed it with Stefan Vladutand we will close this for now. I will re-open it in case I will be able to reproduce it.

**Closed by data-sync-user** 2023-07-06 14:51 UTC
Labels: Bug 🐞, S1, credit-card-autofill
