### ISSUE TITLE
[regression] Some of current web page is visible at the top of the Firefox homepage

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17335] opened 2023-11-16 17:38 UTC
## Steps to reproduce

1. Set Firefox's toolbar setting to the bottom toolbar.
2. Open a colorful web page, such as https://www.adobe.com/
3. Tap focus to the bottom toolbar.
4. The homepage will open so the user can select a new sites or enter a search query. 

### Expected behavior

The current page should not be visible on the homepage.

### Actual behavior

A few lines of the current page are visible at the top of the homepage.

**This bug is a regression in build 9000 (35909).** The homepage doesn't show any rendering artifacts in the previous build, 9000 (36801).

### Device & build information

* Device: iPhone 15 Plus running iOS 17.1.1
* Build version: build 9000 (36105)
* First seen version: build 9000 (35909)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7770)

**Comment by cpeterso** [comment] 2023-11-16 17:43
Screenshot

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/ebf2822a-89ad-4724-b960-1f5a31405b3a)

**Comment by data-sync-user** [comment] 2023-11-16 19:00
➤ Matthew Reagan commented:

I haven’t been able to replicate this yet. Chris Peterson Is this intermittent for you or does it occur reliably each time?

**Comment by lmarceau** [comment] 2023-11-16 19:14
This made me think of ticket https://github.com/mozilla-mobile/firefox-ios/issues/15709. Probably relates to that area

**Comment by cpeterso** [comment] 2023-11-16 19:15
I can reproduce nearly 100% of the time. Maybe it's specific to certain iPhone models or screen sizes? I have an iPhone 15 Plus running iOS 17.1.1.

However, it's not 100% reproducible. I was reproducing the bug reliably on amazon.com earlier today and then the bug stopped reproducing. But if I killed and restarted the app, I was able to reproduce the bug again.

To make the problem easier to see, be sure to scroll down the page so the top few lines of the page are a color other than black or white.

**Comment by data-sync-user** [comment] 2023-11-16 23:56
➤ Matthew Reagan commented:

Looks like there is a fix in review for this https://github.com/mozilla-mobile/firefox-ios/pull/17339 ( https://github.com/mozilla-mobile/firefox-ios/pull/17339|smart-link )

**Comment by data-sync-user** [comment] 2023-11-20 14:24
➤ Andrei Bodea commented:

Hello, Norberto Andres FurlanI’m not really sure if you asked me to verify this issue, to find the steps, or to see if this issue is still reproducible? 
Please note that the steps are provided in the description.  

As the fix is already merged please note the following:
Verified as fixed on v9000 (36168) with iPhone 13 Pro (15.7.1).

Please note that I also tried on 9000 (35909) but still couldn’t reproduce so maybe Chris Petersonwhen you have time can you please check if you can reproduce it anymore on the latest v9000? 

Note that after the first v121 beta build is created I will also verify this issue in that build.

**Closed by data-sync-user** 2023-11-20 14:24 UTC
Labels: Bug 🐞, Contributor Fix

**Comment by cpeterso** [comment] 2023-11-20 19:59
> Verified as fixed on v9000 (36168) with iPhone 13 Pro (15.7.1).

Looks fixed to me, too. I just tested build 9000 (36168) on my iPhone 15 Plus running iOS 17.1.1 and I can no longer reproduce the bug. 🎉

**Comment by data-sync-user** [comment] 2023-11-21 16:32
➤ Norberto Andres Furlan commented:

Andrei Bodea I was asking if the issue was still reproducible, as I wasn’t able to do it. I am still not able to reproduce it so I think we can close it.

**Comment by data-sync-user** [comment] 2023-11-22 10:07
➤ Andrei Bodea commented:

Thank you for the clarification Norberto Andres Furlanyes the issue is closed already as I verified it and also Chris was able to confirm that on his side is also looking good! 
Thx!
