### ISSUE TITLE
Firefox crashes when pressing on the homepage button

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#11552] opened 2022-08-09 13:19 UTC
## Steps to reproduce
1. Launch FF.
2. Open a new website (any from shortcuts).
3. Minimise FF.
4. Resume FF and press the home button.
### Expected behavior
The homepage is correctly displayed.
### Actual behavior
FF crashes when returning to the homepage.
### Device & build information
* Device: **iPhone 13 Pro Max (15.1.1)**
* Build version: **104.0 (15278)**
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/183656193-d82ed1c3-d427-428d-996d-b786d1342a02.mov

[Crashlogs.zip](https://github.com/mozilla-mobile/firefox-ios/files/9290934/Crashlogs.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4731)

**Comment by csuciu** [comment] 2022-08-09 15:56
This issue is not reproducible on the prev v104 build (14880)

**Comment by lmarceau** [comment] 2022-08-09 22:46
@abodea since 15278 introduced some issues, the team decided to go with the tested green build 14834. Thanks 🙏

**Comment by lmarceau** [comment] 2022-08-16 14:50
This should be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by data-sync-user** [comment] 2022-08-17 13:10
➤ Simion Basca commented:

Verified fix on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e

**Closed by data-sync-user** 2022-08-17 13:10 UTC
Labels: Bug 🐞, Crash
