### ISSUE TITLE
FXIOS-1355 ⁃ Library context menu is dismissed when changing device orientation to landscape

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7799] opened 2020-12-30 06:33 UTC
Steps to reproduce

1. Open Firefox app
2. Open the Your Library
3. Click History Page
4. Long press history record 
5. Turn the screen sideways
6. The menu appears to disappear

Expected behavior
It is expected that the menu will not disappear.

Actual behavior
The menu appears to disappear

Device & build information

Device: Apple iPhone 6s Plus - iOS 12.2, LTE
Build version: 30.0 (3279)

[Uploading firefoxmenuhistory.zip…]()

https://user-images.githubusercontent.com/66958331/103334343-f7966f80-4a81-11eb-90b1-9c2b19624382.mp4

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1355)

**Comment by athomasmoz** [comment] 2021-01-07 17:40
Thank you for logging. I'm closing the issue because this is our expected behaviour and is consistent across iOS apps. Please re-open and comment if you find it's causing an issue for you in certain situations

**Closed by athomasmoz** 2021-01-07 17:40 UTC
Labels: Bug 🐞
