### ISSUE TITLE
Blank Screen on Firefox Startup

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6844] opened 2020-06-24 15:15 UTC
STR
- Fresh Install Firefox 27.0 beta and install 
- Open 

Expected 
- Show onboarding screen 

Actual
- Blank screen on 1st launch

**Comment by dnarcese** [comment] 2020-06-24 18:18
For documentation: 
I have not seen this issue yet after ~10 fresh installs. I am on iOS 13.5.1 on iPhone 11

**Comment by SimonBasca** [comment] 2020-06-25 16:06
We tested this on 27.0 (18383) and were unable to reproduce the issue. I noticed it has a patch. @nbhasin2 can this be safely closed?

**Comment by nbhasin2** [comment] 2020-06-25 17:08
@SimonBasca I would say 18383 will have a bug where if you fresh install app and open it without internet. It'll show white screen. That bug is fixed with my patch in build **18428** 

Could you try the above build please. Thanks :)

**Comment by SimonBasca** [comment] 2020-06-26 14:29
Verified fixed on 27.0 (18428).

**Closed by SimonBasca** 2020-06-26 14:29 UTC
Labels: 2, P1
