### ISSUE TITLE
Killing app in incognito causes links to open in incognito

### ISSUE THREAD

**Issue by AWiryaman** [mozilla-mobile/firefox-ios#19195] opened 2024-03-13 16:06 UTC
## Steps to reproduce
1. Open a tab in incognito
1. Kill Firefox
1. Open a link from somewhere else in Firefox
1. See it opens in incognito
1. Close tab
1. Open new non-incognito tab in Firefox
1. Open a link from somewhere else in Firefox
1. See it opens in incognito

### Expected behavior
Should open a non-incognito tab 

### Actual behavior
Opens an incognito tab

### Device & build information
* Device: iPhone 15 Pro, iOS 17.3.1
* Build version: Firefox 123.3 (39412)
* First seen version: Pretty sure this is new since last update
### Notes
Attachments: 
https://drive.google.com/file/d/1EM9-mZNe4UAc9jL9LuaJFENGlXPAzCtM/view?usp=drivesdk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8653)

**Comment by cyndichin** [comment] 2024-03-29 13:25
thank you @AWiryaman for reporting this issue! Will let you know when we have a fix out.

**Comment by data-sync-user** [comment] 2024-04-08 15:28
➤ Cyndi Chin commented:

Andrei Bodea This seems like a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-8601 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8601|smart-link ) .

Can you confirm and verify that the fix also applies to this ticket as well? Thank you!

**Comment by data-sync-user** [comment] 2024-04-09 09:23
➤ Andrei Bodea commented:

Hi, Cyndi Chinyes I did check, closing this as a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-8601 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8601|smart-link ).

**Closed** 2024-04-09 09:23 UTC
Labels: Bug 🐞
