### ISSUE TITLE
Toolbar (Address/Navigation Bar) doesn't reapear on iPad using trackpad/external mouse

### ISSUE THREAD

**Issue by otaviocc** [mozilla-mobile/firefox-ios#10184] opened 2022-03-09 11:28 UTC
## Steps to reproduce

0. Make sure you're using a trackpad or an external mouse (or iPad's [Magic Keyboard](https://www.apple.com/ipad-keyboards/))
1. Open a website.
2. Scroll until the toolbar (address/navigation bar) disappears
3. Scroll all the way to the top.

### Expected behavior

The toolbar (address/navigation bar) should reappear (as it does when using the finger on the screen).

### Actual behavior

The toolbar is still hidden.

### Device & build information

* Device: iPad Pro M1 (iPadOS 15.3.1)
* Build version: Firefox 98.0 (8233)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3877)

**Comment by SimonBasca** [comment] 2022-03-10 10:27
Thanks for the feedback @otaviocc. We're currently tracking this issue at https://github.com/mozilla-mobile/firefox-ios/issues/9657. Marking as duplicate of #9657.

**Closed by SimonBasca** 2022-03-10 10:27 UTC
Labels: Bug 🐞
