### ISSUE TITLE
Implement Screen Time functionalities

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#14975] opened 2023-06-14 20:08 UTC
Originated from https://github.com/mozilla-mobile/firefox-ios/issues/6091

### User Problem
> Why should we implement this? What is the user benefit?

[From Apple](https://developer.apple.com/documentation/screentime); The Screen Time framework gives you the tools you need to help parents and guardians supervise their children’s web usage. Use this framework to:
   - Report web-usage data.
   - Delete history.
   - Take action when a parent or guardian blocks a URL or begins enforcing child restrictions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6706)

**Comment by FilippoZazzeroni** [comment] 2023-06-19 13:49
Hi @lmarceau is it possible to schedule a short meeting or get more documentation in order to implement this feature. I looked at Apple's documentation and it seems quite scarce. I tried to implement the `STWebpageController` too, but i got only a black screen, maybe cause i was building on the simulator.
It's available as well [Family Control](https://developer.apple.com/documentation/familycontrols) from Apple that is a swift ui library to interact with Parental control and Screen time, i think they cover the same topic as documentation you provided. Maybe can be helpful to give it a look at that too. 
Thank you.

**Comment by lmarceau** [comment] 2023-06-19 16:37
Hello @FilippoZazzeroni the black screen could have been caused by another issue we sometimes have on simulators. I would suggest you join the [Element chat](https://chat.mozilla.org/#/room/#fx-ios:mozilla.org) if that's not already done, so we can discuss more easily

**Comment by FilippoZazzeroni** [comment] 2023-06-19 19:42
ok perfect @lmarceau i'm going to join the chat now.

**Comment by lmarceau** [comment] 2023-06-26 16:03
FYI since this information is noted in the PR, we need to make some adjustments to private mode before this feature is considered ready. This change needs to make it to 116

**Comment by data-sync-user** [comment] 2023-06-26 17:46
➤ Laurie Marceau commented:

For QA, it should be tested that Screen Time ( https://support.apple.com/en-ca/HT208982 ) works in normal mode, but private mode isn’t tracked.

**Comment by data-sync-user** [comment] 2023-07-10 12:23
➤ Andrei Bodea commented:

Hello, please note that the screen time is still tracked in PB (for that I opened a website in PB and let it ope) it recorded the screen time.

**Comment by data-sync-user** [comment] 2023-07-10 16:35
➤ Laurie Marceau commented:

Hello Andrei Bodea ! I’ll add some more details on this. What I tried to mean by the “private mode isn’t tracked” is:

  * The website will still be blocked in private mode (as it’s done in Chrome, in the case of Safari private mode disappear whenever Screen time is enabled)
  * The website is not registered in the time breakdown per website in the Screen Time report ( https://osxdaily.com/2021/05/09/see-websites-visited-iphone-ipad-screen-time/ ) (see section “How to view which websites have been visited in iPhone with Screen Time“

Example, if I navigate to wikipedia.org ( http://wikipedia.org ) in private mode, then Wikipedia should not appear in that report. If I blocked Google.com ( http://Google.com ) in my Screen time restricted content, then Google.com ( http://Google.com ) wll be blocked in both normal mode and private mode browsing.

**Comment by data-sync-user** [comment] 2023-07-19 12:11
➤ Andrei Bodea commented:

Verified as fixed on v116 (32820) with iPhone 13 Pro (15.7.1).

I was able to verify everything you mentioned, even when I blocked google.com ( http://google.com ) it worked flawless, and no time screen was recorded anymore, also the PB was not recorded at all. 
Thx, a lot for the explanation Laurie Marceau.

**Closed by data-sync-user** 2023-07-19 12:11 UTC
Labels: Contributor OK, Feature-Request, Contributor Fix

**Comment by jeremylow** [comment] 2023-08-04 13:43
Hi folks,

First of all, I appreciate that this is the expected behavior in iOS; however, I think it would be worthwhile revisiting this feature or at least allowing users to customize whether or not they wish to have it enabled in Firefox. My reasoning for this is that it largely does not work as expected and many users across the web report the same.

**Steps to reproduce**:

* Enable Scheduled Downtime
* Add Firefox to "Always Allowed"
* Open app.
* Navigate to a domain.

**Expected behavior**:

* Website loads

**Actual behavior**:

* Get a Time Limit interstitial.

For instance, I enable screen time on a schedule to block notifications from Instagram, Telegram, apps like that that get noisy and I do not want hear a ton of buzzing when I'm trying to fall asleep. However, my web browser is a totally different beast. When I set Screen Time on Firefox to "Always allowed", I would expect that the app fully functions during Scheduled Downtime; this is not the case, because now I have to clear prompts *every time I visit a different domain*. Many others report that this functionality is unexpected or unwanted for them as well:

* https://www.reddit.com/r/ios/comments/rz4bbp/confused_about_how_screen_time_is_supposed_to/
* https://discussions.apple.com/thread/251674386 (611 "Me toos" at the moment of writing this)
* https://apple.stackexchange.com/questions/336824/screen-time-how-to-disable-downtime-limitations-in-safari

Prior to v116, Firefox was my go-to web browser on iOS and my various desktop environments; unfortunately this change either means that I have to disable Scheduled Downtime entirely or stop using Firefox on iOS; since I value my undisturbed sleep more than my web browser, Firefox gets the axe here. If there's a way to disable reporting website usage to the system (i.e., disable this feature), then I can reconsider this.

Thanks for your time and hard work on the browser. I hope you'll allow this behavior to be customizable by the user, even if Apple's inane API stands.

**Comment by argestes** [comment] 2023-10-24 22:14
Issue is closed but not working on MacOS 14.0

**Comment by SSoggyTacoMan** [comment] 2026-05-05 19:19
does this work
