### ISSUE TITLE
Crash with saved password on default search engine

### ISSUE THREAD

**Issue by mixx941** [mozilla-mobile/firefox-ios#10355] opened 2022-03-30 17:16 UTC
## Steps to reproduce

- Set default search engine to one that requires basic HTTP authentication
- Add valid credentials to "Logins & Passwords"
- Attempt to search via Firefox's address bar, or directly visit the URL that is behind auth

### Expected behavior

Firefox should login using the saved credentials and perform the search.

### Actual behavior

Firefox crashes. 

A workaround is removing the saved password. Firefox will prompt for credentials and then searching works normally after manually entering them.

### Device & build information
* Device: iPhone 8 with iOS 15.4
* Build version: Firefox 98.2 (8475) - latest from App Store
### Notes
Attachments: 
[firefox_ios_crashes_20220330.zip](https://github.com/mozilla-mobile/firefox-ios/files/8382650/firefox_ios_crashes_20220330.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4020)

**Comment by SimonBasca** [comment] 2022-03-31 08:23
Thanks for the feedback. Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/5757.

**Closed by SimonBasca** 2022-03-31 08:23 UTC
Labels: Bug 🐞
