### ISSUE TITLE
Firefox for iOS doesn't work with "Add to Apple Wallet" on Sun Country airlines

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5479] opened 2019-09-23 08:24 UTC
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1580954

When pressing the "Add to Apple Wallet" button from the boarding pass page on their website, I see a brief flicker of the progress bar, and then nothing happens.

On Safari, it brought up a dialog asking for permission to display a Wallet page, and then presented the screen for adding the boarding pass to the Apple Wallet.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4211)

**Comment by garvankeeley** [comment] 2019-10-01 16:20
Closing as difficult to repro, and awaiting more reports of similar behaviour.

**Comment by JoshApos** [comment] 2021-12-18 21:50
I'm having this issue as well. No 'Add to Apple Wallet' buttons or links work.

**Comment by lmarceau** [comment] 2022-03-08 17:17
@bigpanda666 There's a fix for apple wallet that will come in v98 (which will be released soon). This is tagged in https://github.com/mozilla-mobile/firefox-ios/issues/8994 

Please let us know if v98 doesn't fix the issue.

**Comment by 3-fiddy** [comment] 2022-05-07 08:20
Just updated to Firefox 99.3 (9185), 'Add to wallet' link from Odeon UK still doesn't work.

**Comment by cpeterso** [comment] 2022-05-07 19:51
> Just updated to Firefox 99.3 (9185), 'Add to wallet' link from Odeon UK still doesn't work.

@lmarceau - Looks like this bug is still reproducible and should be reopened.

**Comment by lorddumblesurd** [comment] 2022-05-26 13:06
I am having this issue on the quantas.com website where the “add to wallet” button just doesn’t do anything. Firefox Daylight 100.1 (9384)

**Comment by milpie** [comment] 2022-06-01 15:30
Same issue with Ticketmaster website.  Clicking on the 'Add to Apple Wallet' doesn't do anything.  It works in Safari.  (IOS)

**Comment by santiagogf89** [comment] 2022-06-19 18:44
Same issue here, happened several times in the last months. TicketMaster and Lufthansa are the ones I can remember.

**Comment by mushroom-daddy** [comment] 2022-08-06 07:08
I have a similar problem on iOS where clicking on ‘add to Apple wallet’ links for rail tickets (trainline) in the Gmail app are referred to Firefox and then fail to open; with a connection not secure error. I don’t have strict protection enabled in Firefox, and playing with the settings doesn’t seem to have any beneficial affect. If I reset to Safari as default browser the process works just fine.

**Comment by lmarceau** [comment] 2022-09-01 18:20
We have multitple wallet issues opened. Closing this one here in favor of https://github.com/mozilla-mobile/firefox-ios/issues/8994.

**Closed by lmarceau** 2022-09-01 18:20 UTC
Labels: Bug 🐞

**Comment by vorwd** [comment] 2022-09-17 08:12
I am also having this issue. Most
Updated Firefox and running IOS 16. Works fine in safari.

**Comment by dewey4iv** [comment] 2023-08-10 17:04
Using version 116.0 doesn't seem to have resolved this issue.
