### ISSUE TITLE
Wrong tab is closed when swiping to close

### ISSUE THREAD

**Issue by vladh** [mozilla-mobile/firefox-ios#10165] opened 2022-03-05 21:51 UTC
## Steps to reproduce

1. Open 5 or more tabs
2. Go to the screen that lists open tabs
3. Swipe left to close the last tab

### Expected behavior

The last tab is closed, i.e. the tab that was swiped on

### Actual behavior

A different tab is closed. The closing animation is displayed on the tab which is incorrectly closed, instead of on the tab that is actually being swiped on. The closed tab seems to often be the fourth-last tab, but is occasionally a completely different tab.

This incorrect behaviour only happens perhaps 2% of the time. It seems to happen more often if one has many open tabs (e.g. 100+), but it does happen with any number of tabs as far as I can tell.

### Device & build information

* Device: iPhone XR
* Build version: Firefox Daylight 97.0 (7635)

### Notes

I am signed into my Firefox account and have all syncing options turned on. I have, however, stopped using Firefox on mobile because of this bug.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3862)

**Comment by SimonBasca** [comment] 2022-03-08 11:34
Thanks for the feedback @vladh. Unfortunately I was unable to reproduce the issue following the STR on Firefox Daylight 97.0 (7635). If you could provide a video of the issue it would help us reproduce it. Also after step 3) is the first tab actually closed or it's jut not displayed in tabs tray? 

We have two similar issues that are being tracked : #10172 and #8958. Is your issue the same as https://github.com/mozilla-mobile/firefox-ios/issues/10172?

**Comment by vladh** [comment] 2022-03-08 11:41
Hey @SimonBasca! My issue is unlike those two other issues, in that the incorrect tab is actually closed, and that incorrect tab is not necessarily the first tab. I'll do my best to reproduce the issue and provide a video.

**Comment by SimonBasca** [comment] 2022-03-08 11:44
Thanks @vladh, It might help also to see what your "homepage" or "new tab "settings are. If you go to Settings -> Homepage and Settings -> New tab and post a screenshot.

**Comment by vladh** [comment] 2022-03-08 11:49
Sure, here you go:

![IMG_0125](https://user-images.githubusercontent.com/291640/157232652-387a1338-cbf6-4086-b767-b7c7b62bb1c1.PNG)

![IMG_0126](https://user-images.githubusercontent.com/291640/157232670-8570bdd8-fbd6-4b9b-ae5c-d82965f1b351.PNG)

**Comment by vladh** [comment] 2022-03-08 12:13
@SimonBasca I've successfully recorded a video of me reproducing the bug. Note that at the end, I am attempting to close the _last_ tab.

https://user-images.githubusercontent.com/291640/157236121-303e3a9d-5c38-4e3b-8f68-585d13b77f97.mov

**Comment by SimonBasca** [comment] 2022-03-08 12:47
I was able to reproduce the issue more easily by following these STR: 
1. Set network conditioner to "very bad network" in order to load pages slow
2. Have a few tabs opened and visit a few pages
3. Open tabs tray 
4. Open a new tab
5. Visit "amazon.com"
6. While the page is loading, open tabs tray and swipe left or right on the tab that's loading

Actual results:
- After the "amazon.com" page load the swipe gesture will jump to a different tab from tabs tray. 

Note: 
- This is also happening if the network conditioner is not set to "very bad network" in order to load pages slow. 

Thanks for the help @vladh. 

https://user-images.githubusercontent.com/32130829/157241005-b38d775f-e2cb-4131-94ed-e0e75e25a9d3.mp4

**Comment by ianawilson** [comment] 2022-04-24 19:04
I have been having this issue intermittently for months. It’s hard to know exactly what happens; I sometimes swipe and the tab that actually closes is far enough above that it’s not visible. It seems to be usually a couple of rows up, but I’m not sure. The videos above are very similar to my experience. If there’s more info I can provide from my experience I’d be happy to. Thanks!

**Comment by ianawilson** [comment] 2022-05-03 14:02
Today I experienced the swipe jumping between a few tabs. I was closing the last tab of 9, and during a single swipe (I scrubbed back and forth a little without lifting my finger), it jumped to and animated the closing of tabs 8, 7, and 6.

**Comment by timwis** [comment] 2022-05-29 09:05
This has been happening to me about 40% of the time since I started using Firefox iOS about a year or so ago. It's incredibly frustrating. Has it been acknowledged as a bug?

**Comment by data-sync-user** [comment] 2022-06-23 09:44
➤ Simion Basca commented:

Verified fix on main 6aaca8a5c4ba01029db4239fffe6fee63465c111

**Closed** 2022-07-07 13:28 UTC
Labels: Bug 🐞, QA Verified
