### ISSUE TITLE
Seemingly infinite browser tabs opened when tapping on Apple Maps link 

### ISSUE THREAD

**Issue by tiQu** [mozilla-mobile/firefox-ios#8750] opened 2021-06-22 03:04 UTC
## Steps to reproduce
- Firefox is OS default browser 
- Apple Maps app is out of date (never used), hence a click on a street address opens in a browser app
- Browsing in incognito mode 

### Expected behavior
- open system prompt to restore Maps app (works in Safari)

### Actual behavior
- seemingly infinite browser tabs opened, all of which are empty 

### Device & build information
* Device: iPhone 7 iOS 14.4.2
* Build version: ?
### Notes
Attachments:

**Comment by SimonBasca** [comment] 2021-06-22 08:10
Hello thanks for logging this issue? Could you please let me know on what Firefox version are you reproducing the issue?

**Comment by tiQu** [comment] 2021-06-22 12:48
Hello, thanks for the response! According to the settings menu I’m using Firefox Daylight 34.1 (5186).

**Comment by SimonBasca** [comment] 2021-06-22 15:15
This should have been fixed in #7466. On my side following the Steps To Reproduce I am unable to reproduce the issue on v34.1 (5186). 

1. Open Firefox in Private Browsing
2. Background Firefox 
3. Tap on a address location that was previous saved in Notes (e.g 287 Manor Street 
Elkhart, IN 46514)

On my side the system prompt to restore Maps app is displayed.

@tiQu are you trying a different scenario?

**Comment by tiQu** [comment] 2021-06-22 19:46
I was opening the address from Messages. 

To double check the expected behaviour I switched the standard browser to Safari after submitting this issue, and after switching back to Firefox it now works as expected.

Thanks for looking into this!

**Comment by SimonBasca** [comment] 2021-06-23 07:39
Thanks for the feedback. Closing as works for me.

**Closed by SimonBasca** 2021-06-23 07:39 UTC
Labels: Bug 🐞, qa-triaged
