### ISSUE TITLE
Top tabs / URL bar should be revealed when scrolling to the top using a mouse or trackpad

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9657] opened 2021-12-17 11:30 UTC
## Steps to reproduce
1. Scroll down a page
2. Scroll to the top of the page
### Expected behavior
- Top tabs bar should be revealed when scrolling to the top
### Actual behavior
- The top bar is reveled only after hovering.
### Device & build information
* Device: iPad air 3 (15.1)
* Build version: 02047ef01d
### Notes
Attachments: 
https://user-images.githubusercontent.com/32130829/146538383-ed59f5d1-1229-460f-a595-70659686b6ea.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3538)

**Comment by lmarceau** [comment] 2021-12-20 23:14
@SimonBasca I tried reproducing in a simulator and couldn't. Do you see this happen when you have a mouse connected? Or keyboard? Wondering if this is a real device only issue.

**Comment by SimonBasca** [comment] 2021-12-21 09:34
@lmarceau this is what i noticed. I think the issue is only reproducible when having a mouse connected.  Scrolling to the top of the page will not reveal the top tabs bar. When you hover the mouse pointer over the hidden top tabs, the top tabs bar is not revealed. After horizontally moving the pointer over the top tabs bar, it will be revealed.

**Comment by lmarceau** [comment] 2021-12-21 15:17
Ok I can't test this since I haven't receive my iPad yet 🥲 Fingers crossed after the Holidays I'll be able to test it. Thanks!

**Comment by lantzleiweke** [comment] 2022-06-15 03:02
Could I request an update on this issue?

I’m using a Logitech Combo Touch keyboard and am experiencing the same behavior - tab bar does not expose on scroll if I use the touchpad.

Thanks!

**Comment by lmarceau** [comment] 2022-06-15 13:24
Hi @lantzleiweke, other priority work got done and there's no update on this issue. cc: @dnarcese

**Comment by data-sync-user** [comment] 2022-11-02 12:20
➤ Simion Basca commented:

Marking as verified fix on v9000 (21404). Scrolling to the top of the page will now reveal the top tabs bar when using a hardware mouse.

**Closed by data-sync-user** 2022-11-02 12:20 UTC
Labels: Bug 🐞, P2, QA Verified, iPad

**Comment by data-sync-user** [comment] 2022-11-16 11:19
➤ Simion Basca commented:

Verifying as fix on 108 (22078)
