### ISSUE TITLE
Command+L deselects location bar when comand is de-pressed

### ISSUE THREAD

**Issue by sabberworm** [mozilla-mobile/firefox-ios#8851] opened 2021-07-14 07:59 UTC
## Steps to reproduce

Press cmd+L when on a web page.

### Expected behavior

The location bar is selected and ready for typing.

### Actual behavior

The location bar is selected briefly (until the command key is released) but then de-selected again.

I slowed down the presses considerably in the attached video. The sequence is:

1. Press command
2. Press L
3. Location bar selects
4. Release L
5. Release command
6. Location bar deselects (but focus ring remains – doesn’t accept key presses, however)

### Device & build information
* Device: iPad Pro 12.9 (2018)
* Build version: Firefox Daylight 35.0 (5448)

### Notes

This seems to be a recent change of behaviour as I use this shortcut frequently and it used to work fine.

Attachments: 

https://user-images.githubusercontent.com/47652/125583373-9b82a225-efde-4dbc-a470-2ba49c5dcb19.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2958)

**Comment by data-sync-user** [comment] 2021-12-07 16:10
➤ Nishant Patel commented:

Tested on iOS 14.6, iPad Air on 

main 
commit 42920ddd1913c63137f7f2ee5f32d02fc868db0d (official/update-br-new-xcode-version, main)and this is not reproducible for me. I can update to iOS15 and check there as well - please let me know.

**Comment by lmarceau** [comment] 2021-12-07 17:30
@SimonBasca Would you be able to test this ticket? We're having some difficulties reproducing.

**Comment by SimonBasca** [comment] 2021-12-08 09:56
I am unable to reproduce this issue on latest main 90e6b4fa2051e on iPad Air 3 (15.1).

**Comment by sabberworm** [comment] 2021-12-09 12:49
I can still reproduce this with the latest release v40, though I don’t know what revision that’s based on…

**Comment by SimonBasca** [comment] 2021-12-09 14:26
I also tried reproducing on v40.0 (6920) and was unable to reproduce.

@sabberworm are you using the "New Tab as Blank Page" settings? If so could you please try reproducing with "New Tab -> Firefox Home" and let me know the results.

**Comment by sabberworm** [comment] 2021-12-09 21:10
I can confirm that Firefox Home is the only page where it consistently works as expected. But on other pages it almost never works, regardless of what is set for new tabs.

**Comment by lmarceau** [comment] 2022-01-14 18:37
I can't reproduce on iPad mini 15.1 - with or without hardware mouse, on latest main `dd5e01`. @sabberworm on which OS are you (under Settings > General > Software version)?

**Comment by data-sync-user** [comment] 2022-01-25 17:19
➤ Daniela Arcese commented:

Closing as we can’t reproduce. Will re-open if we get more reports

**Closed by data-sync-user** 2022-01-25 17:19 UTC
Labels: Bug 🐞, iPad

**Comment by sabberworm** [comment] 2022-01-26 17:01
I’m on iPad OS 14.8. Firefox 96. Don’t know whether that already includes dd5e01 or not, though…
However, I can still reproduce. Maybe a hardware mouse isn’t sufficient… Though I’m careful not to touch the trackpad… makes no difference.

**Comment by lmarceau** [comment] 2022-01-26 17:38
@sabberworm Are you able to reproduce without the track pad being connected?

**Comment by sabberworm** [comment] 2022-01-26 19:49
I can confirm that when I use only a bluetooth keyboard and disconnect the magic keyboard (which contains the trackpad), it’s no longer reproducible. Unfortunately I don’t have a standalone trackpad handy to confirm that it’s the trackpad itself, not some other aspect of the magic keyboard that’s causing the issue.

**Comment by lmarceau** [comment] 2022-01-26 23:39
Interesting! @sabberworm Do you have a "normal" keyboard that you could connect to the iPad, and try it with that? If it's not reproducible then, that would mean the trackpad seems to be the cause of the bug? 🤔 I need to look if there's some differences on how to handle with a normal mouse VS a track pad.
