### ISSUE TITLE
Scroll position is not preserved at back tap

### ISSUE THREAD

**Issue by romu70** [mozilla-mobile/firefox-ios#11854] opened 2022-09-09 06:57 UTC
## Steps to reproduce

1. Browse Twitter
2. Tap to open a tweet with a thread
3. Scroll down this thread
4. Tap the Back button

### Expected behavior

You should come back to the tweet you first tapped 

### Actual behavior

You come back to a position in your Twitter feed which reflects the location you were into the thread you scrolled.

Example: Let's say you tapped a tweet with a thread and scrolled down to around 10 tweets into the thread. Whet you tap Back, you get to a location which is around the original tweet (the one with the thread) + 10 tweets....Instead of getting back to the original tweet.

As a result, you have to scroll up to get back to your original location in the feed.

### Device & build information
* Device: iPhone 12 mini
* Build version: 104.1 16952
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4900)

**Comment by SimonBasca** [comment] 2022-09-09 10:15
Thanks for the feedback @romu70. We currently have this tracked as https://github.com/mozilla-mobile/firefox-ios/issues/8270 so I am closing it as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/8270

**Closed by SimonBasca** 2022-09-09 10:15 UTC
Labels: Bug 🐞

**Comment by romu70** [comment] 2022-09-09 10:16
Great. Thanks @SimonBasca .
