### ISSUE TITLE
[regression] Black flash on page when rotating device to landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15432] opened 2023-07-07 16:15 UTC
## Steps to reproduce

1. Load a web page. 
2. Rotate the device to portrait orientation. 
3. Rotate the device to landscape orientation. 

### Expected behavior

The page should be rendered in landscape orientation without a black flash. 

### Actual behavior

The page flashes black before rendering in landscape orientation. See the attached recording. 

### Device & build information

**I think this bug is a regression starting in build 9000 (32291).** I don’t see the black flash in build 9000 (31868). 

* Device: iPhone 12 running iOS 16.5.1
* Build version: 9000 (32291)
* First seen version: 9000 (32291)

### Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/629193/c7a29a68-d2bb-4df5-827c-fd797913080b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6946)

**Comment by lmarceau** [comment] 2023-07-07 17:58
This is also in Beta v116 32475.

**Comment by lmarceau** [comment] 2023-07-07 18:54
I found the cause, it relates to screen time that was recently added 🤔 Investigating how we can fix this rotation issue.

**Comment by lmarceau** [comment] 2023-07-10 17:57
Should be fixed in next v116 Beta!

**Comment by data-sync-user** [comment] 2023-07-13 11:16
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).

**Closed by data-sync-user** 2023-07-13 11:16 UTC
Labels: Bug 🐞
