### ISSUE TITLE
The "Jump back" CFR is incorrectly displayed on visited page if it's triggered while in edit mode

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12120] opened 2022-10-13 11:32 UTC
## Steps to reproduce
1. Clean install the app and open it.
2. Dismiss the URL bar CFR and the Default browser card
3. Visit a page.
4. Tap on the search bar.
                 => The search bar is focused and the Homapage is displayed
6. Wait for a couple of seconds.
### Expected behavior
The "Jump back" CFR should not be displayed while in edit mode.
### Actual behavior
When the Jump back CFR is displayed the edit mode is dismissed and previous visited page is displayed.
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments: 

https://user-images.githubusercontent.com/1866605/195584826-1bd99e76-9d82-4746-b0f5-2a6f046d30df.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5076)

**Comment by electricRGB** [comment] 2022-10-17 16:29
Hmmm. This is an interesting bug. It will be a bit tricky to fix because, we don't have an entry-point for the CFR, and can't just say, if in edit mode, don't show it, because then we'd never see it. So we'd need to create an entry point into the homepage saying, essentially, "Hey, I'm here from the awesome bar rather than a new tab, or from having tapped the homepage button."

**Comment by data-sync-user** [comment] 2022-10-19 12:58
➤ Andrei Bodea commented:

Verified as fixed on v9000 (20530) with iPhone 13 Pro (15.1.1).

Note that the Jump Back CFR was no longer displayed in the edit mode.

**Closed** 2022-10-19 12:58 UTC
Labels: Bug 🐞

**Comment by data-sync-user** [comment] 2022-11-16 11:01
➤ Simion Basca commented:

Closing as fixed on 108 (22078)
Note that we’ve found a possible regression https://github.com/mozilla-mobile/firefox-ios/issues/12406 ( https://github.com/mozilla-mobile/firefox-ios/issues/12406|smart-link )
