### ISSUE TITLE
Turning off content blocker crashes the app

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22352] opened 2024-10-02 21:25 UTC
## Steps to reproduce
_Note: steps require a debug build, since the crash is due to a debug-only assert. (See related Jira comments)_

1. Open Firefox iOS.
1. Navigate to a website.
1. Tap the lock :lock: icon from the awesome bar.
1. Turn off "Enhanced Tracking Protection".

Caught be automated test `TrackingProtectionTests/testLockIconMenu()`.

The app can't start again after the crash.

Note that the issue causes no other tests could start after the crash.

### Expected behavior
The app does not crash.

### Actual behavior
The app crashes.

From the XCUITest, the following error message is shown:

```java
Assertion Failure at :0:org.mozilla.ios.Fennec crashed in ContentBlocker.compileContentRuleListCompletion(dispatchGroup:rule:error:) (0.00s)
```

### Device & build information
* Device: iPhone 15 iOS 17.5 simulator
* Build version: 
* First seen version: Oct 2, 2024. On a6239d14617bb093e7feeb233debb17757f8ab98

*# 
*## Notes
Attachments: 
Video:

[https://github.com/user-attachments/assets/cf8a43e7-b842-41a0-994f-c73fb23978a7](https://github.com/user-attachments/assets/cf8a43e7-b842-41a0-994f-c73fb23978a7)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-10211)

**Comment by data-sync-user** [comment] 2024-10-03 16:15
➤ Matt Reagan commented:

QA/testing note: this crash was the result of an assertionFailure, which only crashes the app in Debug builds. So it was crashing on CI but I don’t believe there will be any steps to replicate in our nightly builds. 

As such it’s probably fine to just close this since it’s been confirmed by dev/automation, however if any questions LMK. Andrei Bodea

**Comment by data-sync-user** [comment] 2024-10-22 08:22
➤ Andrei Bodea commented:

Thank you Matt Reagan!

Clare Socan you please confirm and close this issue based on the Matt comment below?
Also, Clare Sobased on your video please note that this bug is related to the https://mozilla-hub.atlassian.net/browse/FXIOS-8342 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8342|smart-link ) feature and in this case, we need to set a Parent for the issue in Jira, as this is not a general bug and we were not able to reproduce it without that feature. 

Please note Clare Sothat this feature was not yet tested so this issue cannot get into the 132, maybe the fix version should be changed or if the change only affected the  CI builds, it can be closed.

**Comment by data-sync-user** [comment] 2024-10-23 13:11
➤ Clare So commented:

I confirmed that the crash no longer occurs during test automation for release/v132 and main. The particular test passes on both release/v132 and main.

**Closed** 2024-10-23 13:25 UTC
Labels: Bug 🐞, Crash, eng:bug-auto-found
