### ISSUE TITLE
Fix bug in sync function error handling

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#15946] opened 2023-08-08 15:30 UTC
While checking for push issues, @tarikeshaq found [this low-volume crasher](https://mozilla.sentry.io/issues/4371878746/?project=6176941&query=release%3Aorg.mozilla.ios.Firefox%40116.0%2B%2833174%29&referrer=release-issue-stream) in the error handling of the `RustSyncManagerAPI.sync` function.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7176)

**Comment by data-sync-user** [comment] 2023-08-25 11:01
➤ Andrei Bodea commented:

Verified as fixed in v117 (33736) with iPhone 13 Pro (15.7.1), iPad Pro (16.0.4).

I was not able to reproduce any crash, I’ve checked the sentry link but not much success.

**Closed by data-sync-user** 2023-08-25 11:01 UTC
