### ISSUE TITLE
Add link to home screen option not available

### ISSUE THREAD

**Issue by DRA6N** [mozilla-mobile/firefox-ios#15172] opened 2023-06-23 16:12 UTC
The ability to add a link to the home screen is not present on my firefox app. 

## Steps to reproduce
Highlighted the URL and tapped on "Share", also tried going through settings > share. Neither give the option to add to home screen

### Expected behavior
Add current URL to home screen

### Actual behavior
No option available

### Device & build information
* Device: ? 
iPhone 13 Pro Max
* Build version: ? 
iOS 16.3.1
### Notes
Firefox app version 114.2
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/9896716/a322fd34-6ba8-4834-9197-e7c65425a13f)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6815)

**Comment by OrlaM** [comment] 2023-06-23 16:15
If you click on edit actions at the bottom is it by any chance listed as an option in there?

**Comment by DRA6N** [comment] 2023-06-23 16:17
> If you click on edit actions at the bottom is it by any chance listed as an option in there?

Negative, see screen shot:
![image](https://github.com/mozilla-mobile/firefox-ios/assets/9896716/3183ca97-9a38-423d-b537-d53c89d5e7bd)

**Comment by OrlaM** [comment] 2023-06-23 16:17
Thanks for confirming!

**Comment by AH-SWG** [comment] 2023-06-26 09:08
I'll confirm this bug report for if you have iOS version below 16.5.1.
I had the same options minus the Pinterest one (since I don't have that app).

Device: iPhone SE 2nd gen (2020)
iOS version: 16.0
Firefox version: 141.3 (31916)

After updating to iOS 16.5.1, the option to add to homescreen with the Share button appeared.

**Comment by lmarceau** [comment] 2023-06-26 15:25
@DRA6N can you upgrade your OS? This specific functionality is only available on OS greater than 16.4.

**Comment by OrlaM** [comment] 2023-06-29 16:00
Good catch, I forgot this was only added in a minor release.
@abodea can you verify this works in the latest version on iOS 16.4 or above and we can close it out?

**Comment by matthewkdies** [comment] 2023-11-26 15:00
I can confirm that running the latest iOS (17.1.1) and version of Firefox iOS (120.1), this option is still not available.

**Comment by Kylotan** [comment] 2023-12-07 16:13
Can also confirm on Firefox 120.3 (36471) on iOS 17.1.2, running on an iPhone 11 Pro.

**Comment by plwt** [comment] 2023-12-17 22:40
SUMO Forum question: https://support.mozilla.org/en-US/questions/1434223

**Comment by gerroon** [comment] 2023-12-20 16:55
I am using IOS 17.2 and it is not there. Safari offers this function in 17.2

**Comment by jensimmons** [comment] 2023-12-23 15:29
Support for Add to Home Screen needs to be added to Firefox on iOS. It won't appear if the Firefox team does not add support. 

From the [Safari 16.4 beta announcement](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/) 
> In iOS and iPadOS 16.4, third-party browsers can now offer their users the ability to add websites and web apps to the Home Screen from the Share menu.
> Applications on iOS and iPadOS present the Share menu by creating a UIActivityViewController with an array of activityItems. For “Add to Home Screen” to be included in the Share menu the following must be true:
	1	The application has the com.apple.developer.web-browser managed entitlement
	2	A WKWebView is included in the array of activityItems
	3	The WKWebView is displaying a document with an HTTP or HTTPS URL
	4	If the device is an iPad, it must not be configured as a Shared iPad

This can be added to Firefox at any time. It is not dependent on any particular recent release of iOS. As long as a user has iOS 16.4 or greater, it will work.

**Comment by ssmaynard29** [comment] 2023-12-27 19:45
It looks like this issue has been going on since at least June 2023. The option to "Add to Home Screen" from the Share menu on Firefox is just not there. It is available on every other browser on Ipad.(ie..Chrome,Safari...etc)  Are the developers of Firefox aware of this issue?  If so, When might a fix for this problem be available?

**Comment by razvanlitianu** [comment] 2024-01-03 08:43
hey @ssmaynard29 there is a fix that landed [here](https://github.com/mozilla-mobile/firefox-ios/pull/17837) and you can expect it to work in the next release.

**Comment by ssmaynard29** [comment] 2024-01-03 15:01
Thank you for this info...will try on next release.On Jan 3, 2024, at 3:43 AM, Litianu Razvan ***@***.***> wrote:﻿
hey @ssmaynard29 there is a fix that landed here and you can expect it to work in the next release.

**Comment by data-sync-user** [comment] 2024-01-04 14:24
➤ Andrei Bodea commented:

Verified as fixed on v122 (37313) with iPhone 15 Pro (17.1.2).

**Closed** 2024-01-04 14:24 UTC
Labels: Bug 🐞, S2

**Comment by ssmaynard29** [comment] 2024-01-04 14:57
My Firefox for ipad is still v121. Any info when it will be updated to v122?On Jan 4, 2024, at 9:24 AM, Data Sync User ***@***.***> wrote:﻿
➤ Andrei Bodea commented:
Verified as fixed on v122 (37313) with iPhone 15 Pro (17.1.2).

**Comment by abodea** [comment] 2024-01-04 15:07
Hello @ssmaynard29 thanks for your message!
There is some time until v122 will be released but I will check with the team and maybe we can include this faster in the RC build.

**Comment by ModalityZ** [comment] 2025-03-04 10:54
Although I see an option to install my PWA using Firefox on recent iOS and Android releases, I can't find a similar option when on Windows 11, macOS 15.2, nor Kubuntu 22.04. There is no button in the address bar, either. Is this by design?
