### ISSUE TITLE
FXIOS-851 ⁃ URL not pinned when Pin to Top Sites selected from address bar

### ISSUE THREAD

**Issue by pcrook** [mozilla-mobile/firefox-ios#7266] opened 2020-09-04 02:44 UTC
When trying to pin a URL to the Top Sites of the home page:
1 - I enter a URL into the address bar and go to the site.
2 - I select “...” from within the address bar and a menu drops down.
3 - I select “Pin to Top Sites” from the menu. A blue bar rises from the bottom of the screen with the text “Pinned to Top Sites”.
4 - I tap the “+” button to create a new tab and display the home page.  The site I pinned does not appear on the tab.
5 - I restart Firefox and the URL still does not appear on the home tab.

Device: iPad Pro (11-inch)
OS: iPadOS 13.6 (17G68)
Firefox: Version 28.1 (19225)

Workaround: 
1 - Create a bookmark for the URL. (Tap “...”, select “Bookmark This Page”)
2 - Pin. (Select bookmarks icon, Bookmarks menu appears, long press bookmark within Recent Bookmarks, second menu appears, select “Pin to Top Sites” from second menu)
Result: Site is properly pinned on home page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-851)

**Comment by SimonBasca** [comment] 2020-09-07 12:43
This is reproducible when trying to pin a site in Private Browsing. I was unable to reproduce in Normal Browsing on iPhone Xr 13.6, Firefox v28.1 (19225).

Similar reports here: https://bugzilla.mozilla.org/show_bug.cgi?id=1663255

**Comment by dnarcese** [comment] 2020-09-29 18:12
Dupe #7346. Should be fixed.

**Closed by dnarcese** 2020-09-29 18:12 UTC
Labels: Bug 🐞

**Comment by pcrook** [comment] 2020-09-29 19:41
This is not fixed in Firefox 28.2 (2470).  What version is it fixed in?

Thanks,

Paul Crook

**Comment by dnarcese** [comment] 2020-09-29 19:44
It will be fixed in Firefox v29.0 or if you are on Beta, it is in build 2667.

**Comment by pcrook** [comment] 2020-09-29 19:47
I’ll test again when 29.0 arrives.  Thanks Daniela.
