### ISSUE TITLE
adding to wallet doesn't work

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-ios#11656] opened 2022-08-19 18:06 UTC
## Steps to reproduce
Pre-req - firefox is default browser

1. have something in your email that you want to add to wallet - for me it was my plane ticket
2. tap the add to wallet button in the email
3. observe

### Expected behavior
I am able to add my plane ticket to wallet with no issue

### Actual behavior
Tapping on the button, launches Firefox to a blank page and nothing further happens. The work around I had to do was copy the URL and paste it into safari. When I did that, I was able to add my plane ticket to wallet. 

### Device & build information
* Device: iphone 
* Build version: 103.1
### Notes
Attachments: 
![IMG_B580662C21D1-1](https://user-images.githubusercontent.com/287322/185680434-7b2efcf7-33a5-4653-804e-78c9e9af5aab.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4795)

**Comment by cpeterso** [comment] 2022-08-20 05:41
I think this a a duplicate of issue https://github.com/mozilla-mobile/firefox-ios/issues/5479 or https://github.com/mozilla-mobile/firefox-ios/issues/5479

**Comment by lime124** [comment] 2022-08-20 20:09
The one nuance I see, which idk if it matters, is in my case I started in
an email rather than a website.

**Comment by lmarceau** [comment] 2022-09-01 18:20
We have multitple wallet issues opened. Closing this one here in favor of https://github.com/mozilla-mobile/firefox-ios/issues/8994.

**Closed by lmarceau** 2022-09-01 18:20 UTC
Labels: Bug 🐞
