### ISSUE TITLE
Session restore fails to load pages in reader view

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16845] opened 2023-10-15 23:06 UTC
## Steps to reproduce
1. Open a web page, such as https://en.m.wikipedia.org/wiki/Mozilla
1. Tap the toolbar’s reader view icon. 
1. The page would now be rendered in reader view. 
1. Force quit the Firefox app. 
1. Reopen the Firefox app (and switch to the article tab, if it wasn’t automatically focused when opening the app),

### Expected behavior
The article should be rendered in reader view. 

### Actual behavior
The reader view toolbar is down but the web page is blank. See the attached screenshot.

You must navigate back to the non-reader view page and the re-enter reader view to see the article in reader view. 

### Device & build information
* Device: iPhone 15 Plus running iOS 17.0.3
* Build version: TestFlight 9000 (35165)
* First seen version: This is not a recent regression: I can reproduce this bug in the oldest TestFlight build available on my phone, 116.0 (32820).

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/55a7b57c-8b41-4ebf-86cf-549666b8b2b8)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-7571)

**Comment by dicarobinho** [comment] 2024-06-03 09:43
Hi @cpeterso,

Do you still have this issue? :) 

I can't reproduce it.

iPhone 15 Plus, 17.4

https://github.com/mozilla-mobile/firefox-ios/assets/61138287/fa0b4f59-d73d-4108-8349-060434442525

**Comment by cpeterso** [comment] 2024-06-03 16:48
@dicarobinho - I can still reproduce this bug in Fx 126.1 on iOS 17.5.1. AFAICT, your screen recording doesn't show the "Force quit the Firefox app" and "Reopen the Firefox app" steps from my steps to reproduce in this bug's first comment.

**Comment by dicarobinho** [comment] 2024-06-04 07:20
@cpeterso That is right. Going to check it again. Thank you.

**Comment by data-sync-user** [comment] 2024-06-05 11:51
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (42506), with iPhome 15 (17.4.1).

!RPReplay_Final1717588117.mp4|width=590,height=1280,alt="RPReplay_Final1717588117.mp4"!

**Comment by data-sync-user** [comment] 2024-06-14 14:50
➤ Adina Petridean commented:

Verified as fixed on Firefox 128.0 (42711), with iPhone 14 Pro Max (16.2).

**Closed** 2024-10-13 05:17 UTC
Labels: Bug 🐞
