### ISSUE TITLE
Password not saved on Logins & Password tabs

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9456] opened 2021-11-03 06:45 UTC
## Steps to reproduce

1. Open the firefox browser 
2. Access http://facebook.com/
3. Tap on sign in
4. The password is saved.
5. Tap on settings
6. Tap on Logins & Password

### Device & build information
* Device: iPhone 7 Plus (14.4)
* Build version:  firefox daylight  38.1(6216)
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3397)

**Comment by dnarcese** [comment] 2021-11-04 16:31
Removing the video so your personal info is not exposed :)

**Comment by dnarcese** [comment] 2021-11-04 16:34
Duplicate of #7583

**Closed by dnarcese** 2021-11-04 16:34 UTC
Labels: Bug 🐞
