### ISSUE TITLE
Tracking protection doesn't remove Learn More button when switching from Strict to Standard

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11476] opened 2022-08-02 13:33 UTC
In Settings > Tracking Protection when switching from Strict to Standard there is an extra Learn More button displayed in random positions. The button originally was displayed under the Strict cell and is not getting removed properly when switching protection modes (see video).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4675)

**Comment by dnarcese** [comment] 2022-10-20 18:46
Duplicate of #12179

**Closed by dnarcese** 2022-10-20 18:46 UTC
