### ISSUE TITLE
Clicking X in address bar as page loads reloads the page

### ISSUE THREAD

**Issue by djfuzzy** [mozilla-mobile/firefox-ios#9153] opened 2021-09-22 14:10 UTC
## Steps to reproduce
1. Browse to a website
2. As it loads, click the X button in the address bar.

### Expected behavior
The page reloads

### Actual behavior
The page load should stop

### Device & build information
* Device: iPhone 12
* Build version: 5971
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3193)

**Comment by dnarcese** [comment] 2021-09-23 16:44
duplicate of #8988

**Closed by dnarcese** 2021-09-23 16:44 UTC
Labels: Bug 🐞
