### ISSUE TITLE
Firefox opens last page instead of the new one 

### ISSUE THREAD

**Issue by mohovkm** [mozilla-mobile/firefox-ios#16663] opened 2023-09-30 16:06 UTC
External links should be opened in the new tab, however they are not, instead last visited tab opens. 
Such need exist with bank online payment where the last step is to return on the seller page  from the bank app and finish payment. However Firefox starts to break this flow (first error observed around month ago). 

Safari works fine, so it depends singly on browser. 
Firefox 117.3 ( 34056)
iOS 16.6.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7504)

**Comment by data-sync-user** [comment] 2023-10-05 18:09
➤ Daniela Arcese commented:

Orla Mitchell would this have been fixed with coordinators?

**Comment by data-sync-user** [comment] 2023-10-05 21:35
➤ Orla Mitchell commented:

Daniela Arcese No, but it will be fixed by https://mozilla-hub.atlassian.net/browse/FXIOS-7314 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7314|smart-link )

**Comment by data-sync-user** [comment] 2023-11-07 22:28
➤ Matthew Reagan commented:

Daniela Arcese Orla Mitchell Can you possibly provide a bit more context and/or repro steps for this; I’m not 100% clear on expected vs. current behavior. Thank you

**Comment by data-sync-user** [comment] 2023-11-08 17:32
➤ Daniela Arcese commented:

Matthew Reagan when you open a link from another app (and firefox is default browser), the link should open in a new tab instead of changing the URL of the currently active tab.

**Comment by data-sync-user** [comment] 2023-11-08 18:15
➤ Matthew Reagan commented:

{quote}when you open a link from another app (and firefox is default browser), the link should open in a new tab{quote}

Daniela Arcese That’s the behavior I see when testing, do you know if anyone is still repro’ing this issue? I haven’t been able to replicate in the release build or the latest dev branch; I think this may have already been addressed by another ticket.  (cc Andrei Bodea Orla Mitchell)

**Comment by data-sync-user** [comment] 2023-11-09 18:45
➤ Daniela Arcese commented:

Andrei Bodea can you help to reproduce? If unable, we can close this.

**Comment by data-sync-user** [comment] 2023-11-10 15:38
➤ Andrei Bodea commented:

Hello, Daniela ArceseFor example I have FF as default browser and I opened a link from Slack, it opened correctly in Firefox in a new tab.

But in the description, we can see that is mentioned a payment, I can’t share the video as it’s with my real credit card but for example, when I tried to purchase something from a website, it opened the bank online confirmation in the same tab like a new screen and not in a new tab so I’m not really sure might be very rare cases.
But when I opened a link from an external app, a new tab was created for that page correctly.

**Comment by data-sync-user** [comment] 2023-11-10 18:22
➤ Matthew Reagan commented:

{quote}when I tried to purchase something from a website, it opened the bank online confirmation in the same tab like a new screen and not in a new tab{quote}

Andrei Bodea Can you possibly clarify this a bit further? The ticket description mentions ‘external links’ which I had interpreted as deeplinks (URLs being sent to Firefox via another app). When you went through the above payment flow + bank confirmation what apps were you using? Or were you stepping through a payment flow within a website (already in Firefox)?

**Comment by data-sync-user** [comment] 2023-11-15 21:08
➤ Matthew Reagan commented:

{quote}when I tried to purchase something from a website, it opened the bank online confirmation in the same tab like a new screen
…
but when I opened a link from an external app, a new tab was created for that page correctly.{quote}

Andrei Bodea (cc Orla Mitchell) Can you provide repro steps for the first behavior (if that’s a defect)? Was hoping to clarify the specific action items for this ticket. Thank you

**Comment by data-sync-user** [comment] 2023-11-21 19:27
➤ Matthew Reagan commented:

This is currently the last open task for the Event Queue epic, but I’m not clear whether there are remaining action items here; I haven’t observed any behaviors yet where the client is incorrectly opening incoming links on the final page. Going to move to QA for confirmation, Andrei Bodea (cc Orla Mitchell) please LMK if there are specific steps which replicate any incorrect behaviors around this. Thank you

**Comment by data-sync-user** [comment] 2023-11-22 10:05
➤ Andrei Bodea commented:

Hello Matthew Reagan, regarding  

!image-20231122-100333.png|width=1133,height=82!

Yes, I was logged in to a website (in that case for a game) and I did buy something there while being in Firefox, so what you said there is correct yes. 

I will take a look and try to verify this issue if it’s related only to the external links, because I won’t make any other payment with my personal credit card to test this.

**Comment by mohovkm** [comment] 2023-11-22 10:11
Hey, team! I’m using the same device, but Firefox has been updated - now it’s 119.2 (35943)

Just to confirm , I didn’t see such issue for a several weeks, which is nice.

**Closed** 2024-01-08 18:00 UTC
Labels: Bug 🐞
