### ISSUE TITLE
Firefox on iPadOS keeps resolving incoming.telemetry.mozilla.org with telemetry disabled

### ISSUE THREAD

**Issue by cnf** [mozilla-mobile/firefox-ios#11142] opened 2022-06-26 12:32 UTC
## Steps to reproduce
On iPadOS (15.5 for me), run Firefox with "Send Usage Data" and "Studies" disabled.

Have some way to track DNS queries, and you will see it trying to resolve `incoming.telemetry.mozilla.org` every 20 seconds or so.
### Expected behavior
When telemetry is disabled, it should be disabled.

### Actual behavior
When telemetry is disabled, it keeps accessing telemetry.

### Device & build information
* Device: iPad Air 5th gen 
* Build version: Firefox Daylight 101.1 (10346)
### Notes
I don't know if it actually tried to contact the servers, as the DNS query is blocked, but it should not try to resolve to start with, with telemetry disabled.

Attachments: 
![Screenshot 2022-06-26 143054](https://user-images.githubusercontent.com/252949/175814234-18b9bbe4-2af6-4e6c-a7bb-c4845ce3fb24.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4468)

**Comment by dnarcese** [comment] 2022-06-30 18:53
@travis79 do you know what the correct behaviour here should be?

**Comment by travis79** [comment] 2022-06-30 20:07
With the endpoint blocked, Glean doesn't currently give up on trying to send the deletion-request ping so I expect you would see evidence of repeated attempted connections to the telemetry endpoint, only affected by the back off and throttling in the ping sending code.

**Comment by cnf** [comment] 2022-07-01 09:01
It doesn't seem to be backing off, even with an ipad reboot.

I have also allowed the resolving temporarily, and it is still keeps wanting to resolve this endpoint.

Turning telemetry back on and off with the resolving allowed, and it seems to still try and resolve it every few minutes.

If I then again block the resolving, it goes back to trying to resolve it every 20 odd seconds.

**Comment by travis79** [comment] 2022-07-01 12:11
Thank you for the additional information, I agree that what you are describing does not sound like the expected behavior. As I mentioned, when telemetry is disabled any local data that hasn't been sent will be deleted and we should just attempt to send the single request that informs the telemetry endpoint to delete the data, so sending additional requests like you describe shouldn't be happening. I'm currently out for the next few days but I'll cc @Dexterp37 to file an issue to look into this on our team.

Thank you again for bringing this to our attention, I'll be sure and link any associated issues here so you may follow them.

**Comment by cnf** [comment] 2022-07-01 12:16
Thank you @travis79! If you need any additional information, or tests to run, please do let me know.

**Comment by Dexterp37** [comment] 2022-07-04 08:08
> Thank you @travis79! If you need any additional information, or tests to run, please do let me know.

Hi @cnf and thanks for reporting this. As @travis79 hinted at, this is consistent with the expected behaviour of trying hard to send a data deletion request. Is there any chance you could send us the submission paths of the attempted requests? Feel free to share them via email if you don't feel comfortable in sharing them here (aplacitelli _at_ mozilla.com).

**Comment by Dexterp37** [comment] 2022-07-06 16:28
> @travis79 do you know what the correct behaviour here should be?

@dnarcese note that Firefox iOS contains _both_ Glean and legacy telemetry. @travis79 refers to the expected behaviour of Glean.

**Comment by Dexterp37** [comment] 2022-07-07 12:58
> Hi @Dexterp37, what do you mean with submission paths?

I mean the full URLs used in the POST request that triggered the DNS resolution you reported in the initial bug. It would really be helpful for us to understand where Firefox IOS was specifically POSTing to in the incoming.telemetry.mozilla.org

**Comment by cnf** [comment] 2022-07-07 13:09
> I mean the full URLs used in the POST request that triggered the DNS resolution you reported in the initial bug. It would really be helpful for us to understand where Firefox IOS was specifically POSTing to in the incoming.telemetry.mozilla.org

Right, and where do I check this?

**Comment by Dexterp37** [comment] 2022-07-07 13:14
> > I mean the full URLs used in the POST request that triggered the DNS resolution you reported in the initial bug. It would really be helpful for us to understand where Firefox IOS was specifically POSTing to in the incoming.telemetry.mozilla.org
> 
> Right, and where do I check this?

I was hoping the tool you used to intercept/block the DNS requests would provide that bit of information too. If not, don't worry, we'll take it from there :)

**Comment by cnf** [comment] 2022-07-07 13:16
> I was hoping the tool you used to intercept/block the DNS requests would provide that bit of information too. If not, don't worry, we'll take it from there :)

Ah no, I'm afraid it's just adguard home, it's purely DNS based.

Thanks!

**Comment by data-sync-user** [comment] 2022-08-09 17:45
➤ Nishant Patel commented:

Closing this one since it’s the deletion ping that’s getting sent (and repeats until it happens). This is expected behavior.

**Closed** 2022-08-09 17:45 UTC
Labels: Bug 🐞
