### ISSUE TITLE
Password Filter (search)

### ISSUE THREAD

**Issue by aricciuser** [mozilla-mobile/firefox-ios#9666] opened 2021-12-19 18:26 UTC
The lower right hand corner of the screen allows us to pull up the stored passwords. Until a couple days ago, one could use the filter feature to search for saved logins and passwords. However, the filter feature no longer works. When typing in a search term, all passwords lists disappear. Please help correct or trouble shoot this, as it has been an important feature I use when the login and passwords do not populate for a site.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3542)

**Comment by SimonBasca** [comment] 2021-12-20 10:25
@aricciuser thanks for reporting this issue. Could you please specify the device, iOS and version you are experiencing this issue?

**Comment by rbclark** [comment] 2022-01-01 14:18
This seems to be a duplicate of #9477

**Comment by aricciuser** [comment] 2022-01-01 20:40
I have an iphone 12 max pro with the most up to date software.

**Comment by ashyan** [comment] 2022-01-13 06:48
Right now you can get around this by typing 1 letter at a time slowly. You basically have to type 1 letter, wait for it to filyer, then the next letter, wait for it, etc. however continuously typing the name of the website you’re looking for leads it to say no matches found

**Comment by rbclark** [comment] 2022-01-13 11:49
@ashyan this is fixed by #9714

**Comment by data-sync-user** [comment] 2022-01-21 16:02
➤ Simion Basca commented:

I am not able to reproduce the issue on latest main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5.

**Closed by data-sync-user** 2022-01-21 16:02 UTC
Labels: Needs-QA, Contributor Fix
