### ISSUE TITLE
Calling out address bar on a pdf sends page to top, for example swiping down on page

### ISSUE THREAD

**Issue by Prurite** [mozilla-mobile/firefox-ios#17146] opened 2023-11-03 01:37 UTC
## Steps to reproduce
1. Open a multiple page pdf, for example https://api.printnode.com/static/test/pdf/multipage.pdf
1. Scroll to the middle
1. Swipe down a short distance

### Expected behavior
The page goes up a bit, according to the distance swiped

### Actual behavior
Page goes to top

### Device & build information
* Device: iPad Pro M2 (11-inch), iPadOS 17.1 
* Build version: 118.2 (34971) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/44775584/3868ddef-d572-4bfe-941b-9ed697717257

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7688)

**Comment by Prurite** [comment] 2023-11-07 03:43
Issue persists in 119.1 (35574)

**Comment by cpeterso** [comment] 2023-11-08 02:34
I’m experiencing this problem, too. I’m using Firefox 119.1 and TestFlight build 9000 (35801) on an iPhone 15 Plus running iOS 17.1.

I can only reproduce this bug in landscape orientation, not portrait orientation. I see @Prurite’s video is also in landscape orientation. Whether the toolbar is at the top or bottom makes no difference. 

This is a bug in Firefox, not WebKit: scrolling up works correctly in Safari, Chrome, and even Focus 119.0 (17290).

**Comment by Prurite** [comment] 2023-11-09 03:14
> @cpeterso I can only reproduce this bug in landscape orientation, not portrait orientation. Whether the toolbar is at the top or bottom makes no difference.

On iPad, it’s reproducible in landscape, portrait, or Stage Manager with different window sizes.

**Comment by cpeterso** [comment] 2023-11-12 19:41
@Prurite: Do you remember how long you saw this bug before filming this bug report?

I wonder if this bug is a regression from updating to iOS 17.1. This bug feels like a regression because I see it so often that I surely would have reported it before, but I can reproduce the bug in the oldest Firefox TestFlight build I have, version 117 from September.

iOS 17.0 was released on September 22.
iOS 17.1 was released on October 25.
iOS 17.1.1 was released on November 7.

https://en.m.wikipedia.org/wiki/IOS_17

**Comment by cpeterso** [comment] 2023-11-12 21:37
I just tested Firefox 119.1 on iOS 16.7.2 and I could not reproduce the bug. The further supports my hunch that this bug is a regression in either iOS 17.0 or 17.1. I will ask QA if they have a device with iOS 17.0.x to pinpoint whether this was a regression in iOS 17.0 or 17.1.

**Comment by Prurite** [comment] 2023-11-13 06:18
> @cpeterso I wonder if this bug is a regression from updating to iOS 17.1. This bug feels like a regression because I see it so often that I surely would have reported it before, but I can reproduce the bug in the oldest Firefox TestFlight build I have, version 117 from September.

I agree, probably a regression in iOS/iPadOS 17(.1), as it is really annoying and I haven’t encountered this very long.

**Comment by Prurite** [comment] 2023-11-13 06:32
Update: clicking the top of the screen, to call out the address bar, also immediately sends the page to top. Given that swiping down shortly also calls out the address bar, and both gestures work correctly on other pages, maybe it’s something wrong with the address bar and pdf reader?

**Comment by abodea** [comment] 2023-11-13 11:44
Hello, please note that I tried with the following:
- **iPhone 13 Pro (15.7.1)** with v9000 (35991) latest Nightly.

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/45f74209-2d02-4057-b90b-e957ff67deb0


- **iPhone 14 (17.0)** with v9000 (35991) latest Nightly.

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/2e4494ef-bfe4-4a14-95a2-9b98a4abebdd

But I cannot reproduce this issue I tried exactly as it is in the attached video. The only thing that can be noticeable is that the URL bar appears and that the animation is not very smooth (like it's in Safari for example).
I did try many many times but it never jumped right at the top, I tried in both Portrait and Landscape. 

@cpeterso Was the behavior on your device with 16.7.2 similar to my videos attached for each iOS version?

**Comment by cpeterso** [comment] 2023-11-13 20:06
Thanks for testing, @abodea. Your recordings show that you are using the correct steps to reproduce, so if iOS 15.7.1 or 17.0 had this bug, you definitely would have seen it. Your testing confirms this bug was caused by some change in iOS 17.1.

**Comment by Prurite** [comment] 2023-11-17 00:36
@abodea Updated title for better clarity.

**Comment by djerf** [comment] 2023-11-24 21:55
I am experiencing this same bug, which means pdfs are unusable in firefox and i have to copy all pdfs to a different app. 

I have been experiencing this issue for a very long time (years, I cannot even recall when it started) so this is definitely NOT an issue with ios 17. Experiencing this on iphone se 2 and ipad mini 6, all orientations. For me this issue is a permanent feature of firefox, which constantly makes me question why I even bother and dont just switch to safari. Previously the sync with pc and generally liking firefox was worth it, kept hoping the issue i imagined to be bothering many was a high priority to be fixed any day now…

**Comment by groner** [comment] 2023-11-27 21:59
This is a frustrating bug for me as well, but I have only noticed it recently. Maybe since iOS 17.1?

Using an iPhone Pro Max 12.

**Comment by data-sync-user** [comment] 2024-01-11 13:15
➤ Andrei Bodea commented:

Verified as fixed on v122 (37502) with iPhone 15 Pro (17.1.2).

**Closed by data-sync-user** 2024-01-11 13:15 UTC
Labels: Bug 🐞, S3

**Comment by djerf** [comment] 2024-01-12 10:22
Can also verify that this issue is resolved with version 121.1 (37312) on iPhone SE 2 (2020) iOS 17.2.1.

**Comment by Prurite** [comment] 2024-03-12 07:28
Just noticed a similar issue: calling out the dock also sends the page to top. Maybe I should open a new issue?

https://github.com/mozilla-mobile/firefox-ios/assets/44775584/d5e7a32e-8500-46ce-9e62-dadf25fe84d6
