### ISSUE TITLE
v40 not responding

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9604] opened 2021-12-08 18:02 UTC
From https://www.reddit.com/r/firefox/comments/rbkm36/problems_with_latest_ios_update_version_400/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3501)

**Comment by koobs** [comment] 2021-12-08 20:26
Confirming on iPhone 11 Pro Max 14.8.1

Consistent symptoms:

- On initial load and after closing app via app switcher, 5-10 second splash screen time
- on app load, no controls are responsive (URL bar, tab switcher, main menu)
- Using app switcher to switch to another app and back to Firefox, or minimising (swipe up from screen bottom) and returning via app switcher will *sometimes* result in glitch / app state switch enabling some controls at which point:

 - tab switcher responds, can scroll tabs, but switching to a tab does not work
 - main menu works, with almost all menu entries functioning, including changing almost all options controls

Notable exceptions:

 - Clicking "sync" results in progress animation but "continues forever" and does not complete

 - URL bar does not respond to touch

I have attempted to isolate by resetting / changing any responsive options controls to no affect or change in symptoms. Clearing all stored data was done during this isolation.

I have not uninstalled/reinstalled app or rebooted the device in order to maintain app state and to assist debugging.

If a screen recording or enabling Send Usage Data or other in-app debugging options would be useful, let me know.

https://twitter.com/koobs/status/1468394111874965505?s=21

**Comment by koobs** [comment] 2021-12-08 20:30
WFM from iOS 15.2 Beta 4 iPhone 12 Pro user:

https://twitter.com/flds/status/1468535222216048645?s=21

**Comment by electricRGB** [comment] 2021-12-08 21:17
@koobs Heya. Yeah, a screen recording would be useful. I've been trying to repro this today and can't seem to. So seeing it happening would help. If you could also record your settings screen, and then also tap on the "homepage" section in the settings screen and record that.

Enabling Send Usage Data might provide us with more things to look into as well. Currently our crash logs are empty (because it seems like this isn't a crash).

**Comment by electricRGB** [comment] 2021-12-08 21:18
Daylight 40 rollout has been halted as we became aware of the problem. Currently, any new download should be on v40, but we have tried to repro on a new install and cannot.

**Comment by electricRGB** [comment] 2021-12-09 19:42
Data collected so far:
- Reports of issue on both iOS 14 and 15
- Doesn't seem to be isolated to a location (reports of hang on FxHomepage, settings screen, etc)
- Reports seem to be from existing users, possibly suggesting that this might be an issue when upgrading
    - Team hasn't been able to reproduce on fresh install or upgrade
    - New users cannot yet be ruled out to be unaffected
- Further questions have been asked of reporters in this [Reddit thread](https://www.reddit.com/r/firefox/comments/rbkm36/problems_with_latest_ios_update_version_400/) to try and clarify the issue.

Issue as we can identify right now:
- app hangs and controls become unresponsive (with sometimes being responsive and then becoming unresponsive again... not super clear)
- Force closing and restarting the app doesn't seem to solve the problem
- One user reported offloading the app and this still didn't seem to solve their problem

**Comment by data-sync-user** [comment] 2021-12-10 10:55
➤ Isabel Rios Escobar commented:

I got the app crashing once and got the logs (iPad Pro, iOS 15, v40.0) but I’m unable to repro following same steps. If you think the logs are still useful I will share them…

**Comment by electricRGB** [comment] 2021-12-10 14:50
Re-opening until we can confirm issue is close in the field.

**Comment by electricRGB** [comment] 2021-12-10 15:02
Data collected so far:
- Reports of issue seem to not be related to iOS/iPadOS version
    - 14.8.1, 15.0, 15.1, 15.1.1 all have been reported
- Confirmed models with reports don't necessarily indicate this to be solely an "older device" issue
    - iPhone: XR, 8+, SE, 11, 11 Pro Max
    - iPad: Pro
- Doesn't seem to be isolated to a location in the app
    - reports of hang on FxHomepage, settings screen, etc)
- Reports seem to be from existing users, possibly suggesting that this might be an issue when upgrading
    - New users cannot yet be ruled out to be unaffected
- Does not seem to be related to Sync
    - report of issue from user not signed in to Sync
- Does not seem to be related so passwords being saved
    - multiple reports of issue from users with no saved passwords

**Comment by lmarceau** [comment] 2021-12-10 15:21
> Re-opening until we can confirm issue is resolved in the field.

Sorry by merging the PR it automatically closed the issue. That wasn't on purpose. Thanks for reopening!

**Comment by lmarceau** [comment] 2021-12-10 20:18
> Updated data collected so far:
> 
>     * Reports of issue seem to not be related to iOS/iPadOS version
>       
>       * 14.8.1, 15.0, 15.1, 15.1.1 all have been reported
> 
>     * Confirmed models with reports don't necessarily indicate this to be solely an "older device" issue
>       
>       * iPhone: XR, 8+, SE, 11, 11 Pro Max
>       * iPad: Pro
> 
>     * Doesn't seem to be isolated to a location in the app
>       
>       * reports of hang on FxHomepage, settings screen, etc)
> 
>     * Reports seem to be from existing users, possibly suggesting that this might be an issue when upgrading
>       
>       * New users cannot yet be ruled out to be unaffected
> 
>     * Does not seem to be related to Sync
>       
>       * report of issue from user not signed in to Sync
> 
>     * Does not seem to be related to passwords being saved
>       
>       * multiple reports of issue from users with no saved passwords
> 
>     * Possibly related with multiple tabs being open
>       
>       * _Some_ users who have reported have specified that they have open tabs

A lot of users reports they see a white page on startup and nothing loads/nothing can be interacted with.

**Comment by koobs** [comment] 2021-12-10 23:39
Attaching video reproduction on iPhone 11 Pro Max 14.8.1

Notes:

- "Cached load" is always in a "hanged" state regardless of (even responsive) previous state. Eg: home -> reopen

- Close via app switcher and open app has responsive controls (except URL bar).

- Touch in URL bar initiates unresponsive control state. 

https://user-images.githubusercontent.com/1011612/145654137-5ee790f4-2fbf-41e5-933e-d4fa281ee1ca.MOV

**Comment by lmarceau** [comment] 2021-12-11 00:17
@koobs Thanks a lot for the video, this helps us a lot! We're onto some ideas on what could cause this and we'll come up with a solution soon 🙏

**Comment by koobs** [comment] 2021-12-11 00:28
> @koobs Thanks a lot for the video, this helps us a lot! We're onto some ideas on what could cause this and we'll come up with a solution soon 🙏

My pleasure 👍 Note I did addition isolation and reprod, but the video ended up too large. I'll create a shorter version this afternoon for reference, but the additional details are:

- Reading List and Passwords menu item entries initiate the unresponsive state 100% of the time 

- Some, but not all webpages load or create the unresponsive state via web links in Menu and settings, such as "What's New". This is interesting as no pages load via tab switcher, whether in unresponsive state or not.

**Comment by the-vampiire** [comment] 2021-12-11 00:49
I’m able to interact (menus, bookmarks etc) and load a page only when I force touch and select new (or new private) tab. 

However, once the page loads it freezes up the whole app again. Able to view tab list but they are all white. Selecting a tab causes it to freeze as well.

**Comment by csuciu** [comment] 2021-12-13 14:41
@the-vampiire Do so know approximately how many tabs did you have open when this issue occurred?

**Comment by electricRGB** [comment] 2021-12-13 14:55
Issue Update:

We believe we've identified what's causing the issue and are working to resolve it.

Updated data collected so far as of Today
- Reports of issue seem to not be related to iOS/iPadOS version
- Confirmed models with reports don't necessarily indicate this to be solely an "older device" issue
- Reports seem to indicate hang on opening the app, rather than it hanging somewhere else - in other words, something during startup is causing the issue.
- As of today, the only reports we've seen are from existing users,
    - This suggests that the hang is happening on cold start when the user had some sort of previous configuration (seems to be tabs)
    - New users cannot yet be ruled out to be unaffected (but currently there are 0 reports of hangs from anyone that can be inferred to be a new user)
- Does not seem to be related to Sync
    - report of issue from user not signed in to Sync
- Does not seem to be related to passwords being saved
    - multiple reports of issue from users with no saved passwords
- It is likely related to users multiple tabs being open and the new work that `setScreenshot` is doing
    - More users who have reported have specified that they have open tabs
    - Confirmed at least 4 cases where issue occurs and tab count is over 100

**Comment by the-vampiire** [comment] 2021-12-13 21:04
> @the-vampiire Do you know approximately how many tabs did you have open when this issue occurred?

so many it simply shows an infinity symbol 😳

**Comment by the-vampiire** [comment] 2021-12-13 21:06
@SimonBasca how did you update to v40.1? i dont see it in the app store

**Comment by lmarceau** [comment] 2021-12-13 21:38
@the-vampiire v40.1 was in Beta testing on Testflight, but it will be released soon on the App Store! Hopefully Apple reviews it quickly 🤞Thanks a lot for your patience and helping us solving this issue.

**Comment by the-vampiire** [comment] 2021-12-13 22:01
right on. thank you for your code and time

**Comment by koobs** [comment] 2021-12-14 05:18
Confirming hang on cold start or other menu items and URL bar touch is no longer reproducible with 40.1.

However, there appears to be related remaining issues with tab list, switching and page loads.

- cold start shows several tabs that after scrolling, disappear or are reordered(?).

- these tabs appear to be empty and do not load content

- tabs load with a white screen

- after scrolling to the top of tab list and imitating a downward scroll, the list jumps directly to the end of the list again 

Two videos capturing the symptoms, the latter showing tab listings and order changing after scrolling them slightly out of the viewport:

https://user-images.githubusercontent.com/1011612/145937208-a57dc553-8287-4b03-956a-8177ea2d0cb7.MOV

**Closed** 2021-12-14 16:37 UTC
Labels: P1
