### ISSUE TITLE
A second permission prompt is displayed after QR code scan

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20947] opened 2024-07-10 07:10 UTC
**Steps to reproduce**

1. Install FF. Either from Url bar or by long tapping on the FF icon, use QR code scanner to open a webpage (scan the generated URL code from desktop).
1. Observe.

**Expected behavior**
A prompt will be displayed: 'Firefox would like to access the camera. [Don't Allow] [Ok]. Tap [Allow]."
The URL is opened in a new tab and the page is correctly loaded.

**Actual behavior**
A second prompt is displayed, asking for permission to open the respective page.

 **Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v129 (43415)
* First seen version: ? 

Notes
Attachments: 
![ImportedPhoto 742286758 723462](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/60bb5a00-5ab0-4acb-b894-c56d34c755be)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9460)

**Comment by data-sync-user** [comment] 2024-07-10 21:43
➤ Matt Reagan commented:

Diana Andreea Barladeanu Andrei Bodea I haven’t been able to replicate this issue yet; if you have any more specific repro steps or additional info please LMK.

I have added a fix which should correct the problem, though as I mentioned I haven’t been able to verify it directly.

**Comment by data-sync-user** [comment] 2024-07-16 20:42
➤ Matt Reagan commented:

Andrei Bodea Is there possibly some confusion about expected behaviors here? The video you attached only shows a single alert / prompt (which is expected). Can you possibly attach a video that shows the duplicate (2nd) prompt so I can try to repro again?

**Comment by data-sync-user** [comment] 2024-07-17 07:11
➤ Diana Andreea Barladeanu commented:

Hi Matt Reagan ! We didn’t have the “Allow Firefox to open?” prompt before. 

The only prompt we’d see is the 'Firefox would like to access the camera. [Don't Allow] [Ok]. Tap [Allow]." 

This bug refers to the  “Allow Firefox to open?” prompt. Was this introduced recently? Is this intended? Thanks!

**Comment by data-sync-user** [comment] 2024-07-24 07:19
➤ Diana Andreea Barladeanu commented:

Not a bug, as per this ticket https://mozilla-hub.atlassian.net/browse/FXIOS-9403 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9403|smart-link ) . 

Closing as fixed on v129 (43869), with iPhone 15 (17.5).

**Closed** 2024-10-13 07:46 UTC
Labels: Bug 🐞, S3
