### ISSUE TITLE
Shortcut spacing on iPad appears broken

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/firefox-ios#9628] opened 2021-12-13 22:24 UTC
## Summary
The shortcut spacing from v39 to v40.1 has changed. Previously the shortcuts were centered from left-to-right now they are all left-aligned which looks like an unintentional change.

## v39 spacing
![v39](https://user-images.githubusercontent.com/3699494/145898317-bd3be90c-84a1-422c-a4d8-f3bafda917c6.jpg)

## v40.1 spacing
![v40 1](https://user-images.githubusercontent.com/3699494/145898327-2c69bd1c-2f5d-4ffc-8875-424ba2afee89.jpg)

### Device & build information
* Device: iPad Air 3rd Gen 
* Build version: 40.0 +

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3515)

**Comment by data-sync-user** [comment] 2021-12-24 11:16
➤ Simion Basca commented:

This issue is still reproducible on latest main 627116c214d9d74bb5a391f59999cd4eb1f68eee. After changing the view from portrait to landscape the spacing between shortcuts is too large 

!image-20211224-111519.png|width=1024,height=768!

**Comment by data-sync-user** [comment] 2021-12-24 11:20
➤ Simion Basca commented:

This was also introduced in v40.3. Daniela Arcese if you don’t mind, could you please add the appropriate status for this issue if you have time. 🙏

**Comment by data-sync-user** [comment] 2022-01-10 12:56
➤ Simion Basca commented:

This issue is no longer reproducible on v96.0 (7298) and main a3362e72675e9c2386afbbb594d96b9d027b3fbd. It was probably fixed by : https://github.com/mozilla-mobile/firefox-ios/issues/9724 ( https://github.com/mozilla-mobile/firefox-ios/issues/9724|smart-link ) 

Closing as works for me. I will re-open if the issue reproducible again.

**Closed by data-sync-user** 2022-01-10 12:56 UTC
Labels: Bug 🐞
