### ISSUE TITLE
[Toolbar Redesign] Address bar’s X button overlaps the address bar border

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#23622] opened 2024-12-07 05:06 UTC
## Steps to reproduce

1. Load a web page 
2. Tap focus to the address bar. 

### Expected behavior

The address bar’s X button is inside the address bar border. 

![IMG_0576](https://github.com/user-attachments/assets/36fc0fd5-b8e3-4ce5-a8d0-5c2733e64ea2)

### Actual behavior

The address bar’s X button overlaps the address bar border. 

![IMG_0575](https://github.com/user-attachments/assets/6924e881-bfc5-45ed-9126-b3cc59dc4ccd)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.1.2
* Build version: Nightly 9000 (48430)
* First seen version: This bug is regression in Nightly 9000 (48430). The address bar looks correct in the previous build, Nightly 9000 (48181).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10833)

**Comment by existing1029** [comment] 2024-12-07 13:41
Its quite suttle UI issue. I am new to programming so trying to learn what you guys been up to

**Comment by data-sync-user** [comment] 2024-12-10 10:16
➤ Sorin Paraipan commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-10809 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10809|smart-link )  that was already fixed and tested.

**Closed** 2024-12-10 10:17 UTC
Labels: Bug 🐞
