### ISSUE TITLE
Can't get back to webpage when app opens to homepage

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#9803] opened 2022-01-18 18:45 UTC
## Steps to reproduce
1. Open a webpage
2. Leave Firefox alone for 4 hours
3. Open Firefox

### Expected behavior
* The homepage is displayed
* The webpage is still open in another tab

### Actual behavior
* The homepage is displayed, but the tab title is the previous webpage
* The webpage is not open anywhere

### Device & build information
* Device: iPad mini 6
* Build version: 40.2 (7167)
### Notes
Attachments: 
![IMG_AF554065016C-1](https://user-images.githubusercontent.com/107992/149999423-c2aae062-4bcd-45af-a99e-8995d5ac66b3.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3638)

**Comment by data-sync-user** [comment] 2022-03-04 14:12
➤ Simion Basca commented:

Verified fix as part of https://mozilla-hub.atlassian.net/browse/FXIOS-3689 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3689 )

Following the STR will open the home page in a new tab and will keep the webpage opened in a different tab.

**Comment by data-sync-user** [comment] 2022-03-04 14:14
➤ Simion Basca commented:

Yoana Rios Diaz could you please confirm that resolving https://mozilla-hub.atlassian.net/browse/FXIOS-3689 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3689|smart-link )  also fixed this issue? Thanks.

**Comment by data-sync-user** [comment] 2022-03-21 19:31
➤ Nishant Bhasin commented:

I am unable to reproduce this on the current `main` but am happy to look into it further if there are any steps I am missing.

**Comment by data-sync-user** [comment] 2022-03-21 19:38
➤ Nishant Bhasin commented:

I tried multiple cases, open with

  * single home tab
  * mixed tab with one home and other random tabs
  * all random tabs
In all cases, I never saw a different title change.

Simion Basca please let me know if you are still seeing this and I will do more investigation. Maybe my simulator config needs to changes as I perform tests on my own iPad simulator.

**Closed** 2022-03-22 14:44 UTC
Labels: Bug 🐞
