### ISSUE TITLE
`FaviconImageView` shows incorrectly scaled icon, and races to clear the old icon when the cell is reused

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/firefox-ios#13037] opened 2023-01-25 18:47 UTC
## Steps to reproduce
1. Check out the test case in #13036.
1. Build and run Firefox for iOS in the Simulator.
1. Type "amazon", "cali", or "ulta" in the awesomebar.

### Expected behavior
The awesomebar shows a `(Test)` suggestion for Amazon, Wikipedia, or Ulta, with the correct favicon, in the "Firefox Suggest" section. Search engine suggestions in the section above have the magnifying glass icon.

### Actual behavior
1. Amazon has the wrong favicon. (It might be loaded correctly, but zoomed in too far? Ulta is a better example; if you type in "ulta" into the awesomebar, it'll be zoomed in to the "L BE" part of the logo).
1. The last suggestion in the search engine suggestions section ("american airlines" and "amazon stock") briefly shows the wrong Amazon favicon, before flickering back to the magnifying glass.

### Device & build information
* Device: Simulator
* Build version: 3c06c7234aa7b0326b3b3ae24447d2f89cc12ab8 + #13036.

### Notes
Attachments: 

Screen recording of the glitchy behavior:

![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-01-25 at 10 22 38](https://user-images.githubusercontent.com/41387967/214655041-10d98d25-b229-41b6-8938-28a21c3bb0fd.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5650)

**Comment by OrlaM** [comment] 2023-01-26 17:57
For issue 1. I left a comment on the PR with a suggestion on how to address it.
For issue 2. I'm unable to reproduce this anywhere other than on your PR but I can't see anything in your code that might be causing it 🤔 
@SimonBasca would you be able to do some testing around favicons on the search screen to see if you can reproduce this issue in the gif above where the magnifying glass sometimes flashes with a different image?

**Comment by linabutler** [comment] 2023-01-26 22:24
Thank you so much for investigating, @OrlaM!

1. Thanks for catching that! I should have looked closer at how you migrated `TwoLineImageOverlayCell` in 67dbc66970cf77237cfc46ac0b40993c2c1d68c1.
2. So weird, I've never seen it happen for other favicons, either! I wonder, could it be because I'm requesting the icon directly, using the image URL? Like, for an open tab, history, or bookmark, is it possible we fetched and cached the icon when the user first opened the page, so it loads quicker when we show the suggestion—but for Merino suggestions (and the example in the PR), it has to make a request to fetch it while the user is typing?

**Comment by data-sync-user** [comment] 2023-04-27 13:56
➤ Andrei Bodea commented:

Verified as fixed on v9000 (30371) with iPhone 13 Pro (15.7.1).

**Closed by data-sync-user** 2023-04-27 13:56 UTC
Labels: Bug 🐞
