### ISSUE TITLE
FXIOS-1002 ⁃ The tab list always jumps to the beginning after closing the final tab

### ISSUE THREAD

**Issue by dblohm7** [mozilla-mobile/firefox-ios#7441] opened 2020-10-02 21:13 UTC
## Steps to reproduce
1. Have enough tabs open that the tab list needs to be scrolled down to see the final tab. In my case, I have 64 tabs open, but just enough to require scrolling should be sufficient;
2. Open the tab list;
3. Close the final tab in the list.

### Expected behavior
* The tab list doesn't scroll up to the top.

### Actual behavior
* The tab list scrolls up to the top of the list, completely disorienting the user and requiring the user to scroll back down to where they were previously looking.

### Device & build information
* Device: 1st Gen iPhone SE running iOS 14.0.1
* Build version: 28.2 (2470)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2567)

**Comment by SimonBasca** [comment] 2020-10-05 10:01
I am unable to reproduce this behavior on iPhone Xr (14.0) Firefox 29.0 (2470). In my case, after closing a tab, Firefox will select the last used tab. This is the current implementation. 

@dblohm7 could you please try selecting a different tab before closing the final tab in the list? Let me know if you still believe this is an issue.

**Comment by dblohm7** [comment] 2020-10-19 15:51
This is still an issue, but I am not sure exactly how I get into the state where it reproduces.

I *think* something that helps is to switch to private browsing, do some stuff in there, and then switch back to normal browsing, then close the last tab.

**Comment by avogadro23** [comment] 2021-04-06 09:13
Happens to me a lot, seems to be caused by Firefox going being put to sleep by ios when it is not a foreground app. 
iphone X ios 13.3.

**Comment by bnoctis** [comment] 2021-04-28 12:47
Happens a lot to me too. iPhone 11, iOS 14.4, Firefox Daylight 33.0 (4119) but I'm sure it happened across versions. Number of tabs to be closed before it jumps up isn't fixed, sometimes 1 is enough, sometimes up to 5 or 10. I always have tens of tabs open, and it's happening more than not.

**Comment by bnoctis** [comment] 2021-06-02 05:47
Thought of an explanation: There's an "anchor" tab to which the browser goes if currently viewing tab is closed. Then, if a tab is the anchor, AND closed away, the browser resets the anchor to the very FIRST tab in the list. However, it's not always a desired behavior.

**Comment by thecristen** [comment] 2021-06-17 02:27
I have this issue too. I had actually switched to using Safari because of it months ago. 

It's still an issue today, on Firefox Daylight 34.0, I'm on an iPhone 8 running iOS 14.4.2 🤷🏻‍♀️

**Comment by b0wter** [comment] 2021-07-24 15:21
Issue affects me as well. I have about 25 tabs open and when I close a couple of the last ones the first tab will inevitably be selected at some point. Usually takes around 4-5 tabs for me. Some of the tabs have been open quite some time (couple of weeks).

**Closed** 2021-11-01 20:55 UTC
Labels: Bug 🐞, P3

**Comment by Foxxsayy** [comment] 2024-01-11 14:51
I'm on Firefox Android and the default behavior is still often to start at the first tab, meaning you have to scroooooooolll all the way to the first one.
