### ISSUE TITLE
Turn off URL suggestions/autocompletions [IOS]

### ISSUE THREAD

**Issue by Dennismn** [mozilla-mobile/firefox-ios#15716] opened 2023-07-22 14:58 UTC
## Steps to reproduce

When you type in search bar, it gives you bookmark and history suggestions. Aside from the fact that it's incredibly frustrating to search for something, this is also bad for privacy reasons.

Please give us the option to turn this off. We should be allowed to search without the autofill.

https://github.com/mozilla-mobile/firefox-ios/assets/69481233/32c7c548-9e74-4124-b402-158ce730eae7

### Device & build information
* Device: iPhone 13 mini. Latest IOS.
* Build version: 115.0
* First seen version: not sure, but it's been going on for almost a year. It never used to happen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7071)

**Comment by dnarcese** [comment] 2023-08-10 18:40
Duplicate of #14176

**Closed by dnarcese** 2023-08-10 18:40 UTC
Labels: Feature-Request, Bug 🐞
