### ISSUE TITLE
Incorrect notification message is displayed when recieving a tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13235] opened 2023-02-14 12:50 UTC
## Steps to reproduce
1. Send a tab from desktop to iOS
### Expected behavior
- The tab received notification should be displayed.
### Actual behavior
- Incorrect notification message is displayed.
### Device & build information
* Device: iPhone 14 Pro (16.1)
* Build version: 9000 (28110)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/218743580-582eb4bd-49a2-4e33-9304-d6ffce14ba3a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5766)

**Comment by lmarceau** [comment] 2023-02-14 13:40
I think this only happens in Beta and/or Nightly?

**Comment by SimonBasca** [comment] 2023-02-15 08:46
This was only tested and reproduced on latest Nightly since that's where the change from https://github.com/mozilla-mobile/firefox-ios/issues/12954#issuecomment-1407063916 was deployed.

**Comment by SimonBasca** [comment] 2023-02-15 15:37
Also reproducible on v111 (28148)

**Comment by cpeterso** [comment] 2023-02-15 17:36
I can reproduce this bug when sending tabs to Nightly 9000 (28110) on iOS 16.3. My sent tabs did arrive (though I had to force sync in Nightly's settings).

**Comment by tarikeshaq** [comment] 2023-02-15 17:40
I could reproduce this in the latest beta (111). Note that I couldn't reproduce before upgrading, so this is most likely related to something that landed recently.


I'll quickly scan through some patches to see what could have been related here

**Comment by tarikeshaq** [comment] 2023-02-15 18:08
I'm confident the culprit here was https://github.com/mozilla-mobile/firefox-ios/commit/deaee535d1b88f3909ffa7c7afb6ecf20fe68e51

I deleted all the logging code, and the `init` function and send tabs worked on a local build.

I don't think the notification service is doing well with the logger. This most likely has to do something with the fact the NotificationService runs in its own process. cc @lmarceau @OrlaM 

Any fix here we'd want to uplift to 111

**Comment by lmarceau** [comment] 2023-02-21 22:32
Thanks @tarikeshaq, we remove the logger for now until we have a better solution. 
@SimonBasca the fix was merged so we'll get the change in next Nightly build.

**Comment by data-sync-user** [comment] 2023-02-22 08:51
➤ Simion Basca commented:

Marking as verified fix on v9000 (28508)

**Closed by data-sync-user** 2023-02-22 08:50 UTC
Labels: Bug 🐞, S3
