### ISSUE TITLE
Crash on websites that need credentials (https://www.mdc.edu/jobs/work-study/)

### ISSUE THREAD

**Issue by marcelohdez** [mozilla-mobile/firefox-ios#11699] opened 2022-08-24 13:50 UTC
## Steps to reproduce
1. Go to website https://www.mdc.edu/jobs/work-study/
2. Click on "Search work study job listings"
3. Firefox will crash

### Expected behavior
Open a new tab asking for a login, which Safari is able to do.

### Actual behavior
Firefox crashes

### Device & build information
* Device: iPhone 13 Mini, iOS 16 beta 6
* Build version: Firefox Daylight 103.1 (15076)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/76508651/186435487-ba8e9d01-145d-4a27-a5cd-3e05faac66f8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4815)

**Comment by dnarcese** [comment] 2022-09-08 18:57
@SimonBasca are you able to reproduce this reliably? I was not able to - wondering if it might be intermittent

**Comment by SimonBasca** [comment] 2022-09-09 10:02
This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/5757. The app crashes if you have a username and password saved for the site that uses basic authentication. Note that this issue is also reproducible on v104.2 and latest main 58b1a24c6d03077756b8ab43c98d778377ef5346

@marcelohdez  the workaround until we fix this issue is to go to Settings -> Login & Passwords and delete the login save for this website. 

@dnarcese we should probably get https://github.com/mozilla-mobile/firefox-ios/issues/5757 fixed since we had this crash for some time.

Closing this issue as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/5757.

**Closed by SimonBasca** 2022-09-09 10:02 UTC
Labels: Bug 🐞
