### ISSUE TITLE
[regression] Swiping to close a tab no longer works

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#18736] opened 2024-02-16 00:49 UTC
## Steps to reproduce

1. Open a tab. 
2. Open the tab tray view. 
3. Try to swipe the tab thumbnail to close the tab. 

### Expected behavior

The tab should close. 

### Actual behavior

The tab dots not close. The tab thumbnail moves but then bounces back to its original position.

You can still choose the tab by tapping the tab thumbnail’s X button. 

### Device & build information

* Device: iPhone 15 Plus running iOS 17.3.1.
* First seen version: This bug is a regression in TestFlight version 9000 (38793).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8447)

**Comment by abodea** [comment] 2024-02-16 09:45
Hello, please note that this is a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-8418.

**Closed by abodea** 2024-02-16 09:45 UTC
Labels: Bug 🐞
