### ISSUE TITLE
Turna-the link can be opened three times

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9435] opened 2021-11-01 11:47 UTC
## Steps to reproduce
1. Go to app firefox browser
2. Go to https://www.turna.com/
3. Scroll down and tap on download on the app store
4. Tap one more and more
### Expected behavior
the link should open once and send to App Store
### Actual behavior
it opens twice and you can continue and press the third time
### Device & build information
* Device: iphone XR - ios 14.8
* Build version: firefox dalight 38.1.6216
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/139666823-07d123e6-a164-4a7d-ac62-7758f9ec07dd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3378)

**Comment by muhasturk** [comment] 2021-11-01 12:57
technically same issue with https://github.com/mozilla-mobile/firefox-ios/issues/8458

**Comment by dnarcese** [comment] 2021-11-10 19:03
Closing as duplicate of #8458

**Closed by dnarcese** 2021-11-10 19:03 UTC
Labels: Bug 🐞
