### ISSUE TITLE
FXIOS-1665 ⁃ Can't play youtube videos in fullscreen mode on iPad

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/firefox-ios#8267] opened 2021-04-01 19:55 UTC
We've received several reports where it's not possible to play a video in fullscreen mode on youtube.com. A similar issue https://github.com/mozilla-mobile/firefox-ios/issues/5838 has been addressed in the past 

## Steps to reproduce
1. Visit https://www.youtube.com/watch?v=AtRs5gGNbxM in Firefox and press play
2. Click on the fullscreen icon and observe the behavior 

### Expected behavior
Video plays in fullscreen

### Actual behavior
"You browser doesn't support full screen." message is displayed

### Device & build information
* Device:  iPad Pro iOS 14.4.1 
* Build version: Firefox Daylight 33.0

### Notes
Original issue: https://github.com/webcompat/web-bugs/issues/68754

Attachments: 
![IMG_0035](https://user-images.githubusercontent.com/1303908/113345786-f256f400-9300-11eb-98e2-78fbcbb58f24.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1665)

**Comment by data-sync-user** [comment] 2021-05-04 17:25
➤ Ashley Thomas commented:

Increasing the estimate on this one to come up with a solution that could fix the UA issue on a per site basis

**Comment by data-sync-user** [comment] 2021-05-10 19:27
➤ Nishant Bhasin commented:

This is not reproducible on iPad v34 Beta 

I am able to watch videos in full screen so not sure what else should we change in user agent.

cc [~athomas@mozilla.com] 

!image-2021-05-10-15-25-12-800.png|width=329,height=230!

**Comment by badboy** [comment] 2021-05-11 08:15
Just tested on my iPad Pro with Firefox 34.0 (4722) from TestFlight.
The fullscreen button on YouTube videos is still grayed out, when clicked the "Your browser doesn't support full screen" overlay appears.

**Comment by nbhasin2** [comment] 2021-05-11 14:13
@badboy Could you please provide iOS version of your iPad Pro and confirm that this works in Safari?

I am on iOS version 14.0.1 if that helps.

**Comment by nbhasin2** [comment] 2021-05-11 15:34
@badboy Thanks I am able to reproduce it in newer iOS version on iPad

**Comment by SimonBasca** [comment] 2021-05-14 12:03
Verified fix on v34.0 (4795). Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/8485

**Closed by SimonBasca** 2021-05-14 12:03 UTC
Labels: Bug 🐞, P1

**Comment by SimonBasca** [comment] 2021-05-14 12:06
@nbhasin2 could you please confirm this is fixed and can be moved to Done. Thanks

**Comment by badboy** [comment] 2021-05-14 14:02
Works for me!

**Comment by nbhasin2** [comment] 2021-05-14 15:26
> @nbhasin2 could you please confirm this is fixed and can be moved to Done. Thanks

It's fixed @SimonBasca
