### ISSUE TITLE
FXIOS-631 ⁃ Magic Keyboard: Right-click is ignored

### ISSUE THREAD

**Issue by a2sheppy** [mozilla-mobile/firefox-ios#6982] opened 2020-07-15 19:04 UTC
### Why/User Benefit/User Problem

Currently, right-clicks in Firefox iOS are ignored (or perhaps function as a standard click in some cases). This means the application doesn't operate as expected in a Magic Keyboard environment (or any time there's a mouse or trackpad connected, which will be more and more common going forward).

### Acceptance Criteria (how do I know when I’m done?)

*   Right-click should open the appropriate context menu that a force-click would normally open. The menu's contents may also need to be revisited to adapt them somewhat based on the keyboard and trackpad being available.
*   The `auxclick` event should work in web content, and should be generated by right-clicking the trackpad or mouse

### Not included

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2498)

**Comment by garvankeeley** [comment] 2020-07-20 15:38
Do you think two-finger-tap is the same as a right click? I am trying this and not seeing two-finger-taps handled in Safari either (on iOS 13.x). I think the WebView component doesn't handle these. I don't have an input device right now that has a physical right-click button.

**Comment by a2sheppy** [comment] 2020-08-04 23:45
I know it works in some apps; clicking with two fingers on the trackpad does a right-click. This is enabled in the settings app. Go to Trackpad then choose “Two finger secondary click” to enable it.

--  
Eric Shepherd

**Comment by braiam** [comment] 2020-11-01 01:28
@a2sheppy How is the action supposed to be achieved with only touch gestures?

**Comment by a2sheppy** [comment] 2020-11-05 14:47
Right click? This is a trackpad/mouse specific action. It's used equivalently to a force-push or a haptic touch event, where you do a hard or long press on the screen to bring up a contextual menu. The two-finger click (not tap, but click) on the trackpad gives a more precise way to bring up the context menu or otherwise generate an `auxclick` event.

**Comment by bpwned** [comment] 2020-12-19 18:03
I think this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/6808

**Comment by westerlind** [comment] 2021-05-05 18:47
This is a very important feature for anyone using a hardware trackpad or mouse, and without this and #7860, Firefox feels broken on an iPad with for example Apple's Magic Keyboard Case attached to it.
There are more things than these two that could be done to make it feel more at home on an iPad with a Magic Keyboard Case, but these are the really important ones that will push people over to use Safari instead when they are missing.

**Closed** 2021-11-01 20:35 UTC
Labels: Feature-Request
