### ISSUE TITLE
FXIOS-1336 ⁃ Could Not Build on Xcode 12.3

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#7778] opened 2020-12-18 16:39 UTC
## Steps to reproduce
- Install Xcode 12.3 stable from App Store
- Bootstrap project by running 
`sh ./bootstrap.sh`

### Expected behavior
Compile properly

### Actual behavior
"Incompatible Swift version..."

### Device & build information
Xcode 12.3 on macOS 11.1 - 20C69

### Notes
Related
https://github.com/mozilla/application-services/issues/3769

Firefox should follow Xcode stable release versions in order to compile Firefox properly.
Every single stable Xcode version this exact same "Incompatible Swift version" problem occurs.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1336)

**Comment by rfk** [comment] 2020-12-22 05:52
Confirmed that this reproduces in a local build against latest `main` using [these instructions](https://github.com/mozilla/application-services/blob/main/docs/howtos/locally-published-components-in-ios.md).

I added a bit of light diagnostic logging and it looks like `getBookmarksTree` is returning an error, which is being silently ignored by firefox-ios [here](https://github.com/mozilla-mobile/firefox-ios/blob/ca2f5c98dd25b8f3026b2bd976450edff1853172/Client/Frontend/Library/BookmarksPanel.swift#L171). I'll keep digging.

**Comment by isabelrios** [comment] 2020-12-22 14:35
See similar issue open related to build on 12.2 https://github.com/mozilla-mobile/firefox-ios/issues/7728

**Comment by isabelrios** [comment] 2021-01-28 16:57
There is work done fixing this in a branch for now. Check` ios-xcode12-3` branch

**Comment by dnarcese** [comment] 2021-02-03 19:47
This should be fixed now. Will re-open if still not working.

**Closed by dnarcese** 2021-02-03 19:47 UTC
Labels: Bug 🐞
