### ISSUE TITLE
FXIOS-527 ⁃ [v26] English string truncates for ETP

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#6814] opened 2020-06-18 22:29 UTC
## Steps to reproduce

This has been noticed by a localizer by looking at the latest screenshots l10n got here: 
https://drive.google.com/drive/folders/1_CEdEYlWIRTtE7YZCcJksKRt5zyGpFU5

This is the screenshot:
![kuva](https://user-images.githubusercontent.com/399020/85078001-56e10200-b178-11ea-87e4-b0f542543ec7.png)

### Expected behavior
ETP string does not truncate

### Actual behavior
ETP string truncates

CC @brampitoyo

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2464)

**Comment by athomasmoz** [comment] 2020-06-18 22:31
@brampitoyo @betsymi Can you comment on this one? What is the expected behaviour here?

**Comment by TheoChevalier** [comment] 2020-06-19 07:16
Note that this is a dupe of https://github.com/mozilla-mobile/firefox-ios/issues/6355 (and #6415 , #6416)

**Comment by brampitoyo** [comment] 2020-06-22 00:14
@athomasmoz @Delphine My initial thought is that there’s no need to say “Enhanced Tracking Protection is ON for this site” on the header itself.

If have a space for a second line of text, which is caption-sized, then we can say that.

But the header can be shortened to “Enhanced Tracking Protection”, and the toggle will make it clear.

Let’s ask @AmyYLee and @betsymi for their comments.

**Comment by AmyYLee** [comment] 2020-06-22 22:42
@brampitoyo I agree we don't need the "is ON for this site" portion. 
If we have space for a second line that is caption sized maybe we can copy Fenix "Proteions are ON for this site". If not, I agree the toggle would be clear enough. @betsymi to confirm strings.

**Comment by TheoChevalier** [comment] 2020-06-23 06:59
FWIW, “Enhanced Tracking Protection” alone doesn’t fit in French on iPhone X

**Closed** 2021-11-01 20:27 UTC
Labels: Bug 🐞, Needs-UX, Needs-Strings
