### ISSUE TITLE
address bar is inaccessible when using bluetooth keyboard

### ISSUE THREAD

**Issue by stevegula** [mozilla-mobile/firefox-ios#15735] opened 2023-07-24 16:34 UTC
## Steps to reproduce
connect bluetooth keyboard or mouse
open firefox
click address bar

### Expected behavior
I should be able to input text into the address bar

### Actual behavior
The address bar has a minor seizure but fails to accept input

### Device & build information
* Device: ipad mini 6
* Build version: 115.1
* First seen version: Unsure but I found this ticket from 6 months ago #6607

### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7080)

**Comment by data-sync-user** [comment] 2023-09-26 14:25
➤ Nishant Bhasin commented:

Andrei Bodea Could you please check if this is still an issue 

cc Matthew Reagan

**Comment by data-sync-user** [comment] 2023-09-29 18:35
➤ Matthew Reagan commented:

I tested with a bluetooth keyboard and iPad Air, using keyboard shortcuts to activate the address bar and load URLs and switch tabs etc. Wasn’t able to replicate any issues. Attached screen recording for reference.

!RPReplay_Final1696012057_720.mov|width=888,height=1280!

**Comment by data-sync-user** [comment] 2023-09-29 18:37
➤ Matthew Reagan commented:

(Note: not sure what Jira state is appropriate for Cannot Reproduce; I updated ticket to QA Needed but please let me know if that should be different. Thank you) cc Nishant Bhasin

**Comment by data-sync-user** [comment] 2023-10-17 14:34
➤ Andrei Bodea commented:

Hello, please note that I was not able to reproduce this issue on the latest v119 version with iPad Pro.

**Comment by data-sync-user** [comment] 2023-10-23 15:16
➤ Andrei Bodea commented:

As we cannot reproduce this issue, are you okay with closing it? Matthew Reagan Nishant Bhasin

**Closed** 2023-11-01 12:56 UTC
Labels: Bug 🐞

**Comment by opilette** [comment] 2026-06-04 11:50
I use an Ipad Air 4th gen, running iOS 18.6.2, with a Logitech K380 keyboard, and I face the same issue. My current Firefox version is 151.2 (72455). The issue only occurs with Firefox (e.g., my Brave browser works fine). 

Description: When I open a new tab and **load a new page**, for several minutes, I will not be able to input text in the address bar while my keyboard is connected via Bluetooth. And then, randomly, I will be able to click and write. If I load a new page in the same tab, the issue starts gain. The problem has been persisting through different versions of Firefox.
