### ISSUE TITLE
14-day old tabs don't get all moved into inactive section

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10388] opened 2022-04-04 13:02 UTC
## Steps to reproduce
- open 5 tabs 
- change the system time to t+14

### Expected behavior
- all 14-day old tabs are in inactive

### Actual behavior
- 4 tabs are in inactive, one 14-day old tab is not in inactive

### Device & build information
* Device: iPhone 8, 15.4.1
* Build version: 9000 (8686)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4041)

**Comment by dnarcese** [comment] 2022-04-07 17:42
@topotropic is the one that did not get moved the one that was active at the time you changed the date?

**Comment by dnarcese** [comment] 2022-05-26 19:16
Closing this as intended behaviour

**Closed by dnarcese** 2022-05-26 19:16 UTC
Labels: Bug 🐞
