### ISSUE TITLE
“Add to Home Screen” option missing

### ISSUE THREAD

**Issue by darren12345** [mozilla-mobile/firefox-ios#17116] opened 2023-11-01 18:27 UTC
![IMG!UNITO-UNDERSCORE!7929](https://github.com/mozilla-mobile/firefox-ios/assets/12751052/7789c828-aad9-4332-abb0-f9da650b2e16)
![IMG!UNITO-UNDERSCORE!7930](https://github.com/mozilla-mobile/firefox-ios/assets/12751052/52def5a2-b24a-4826-8605-3672a544afed)

## Steps to reproduce
Open share menu. 

### Expected behavior
There is supposed to be an option to add a bookmark to the Home Screen (I understand). 

### Actual behavior
There is no option. 

### Device & build information
* iphone SE 2020, iOS 17.1
* Firefox 119.1 (35574)
* First seen version: since whatever version this was supposed to be introduced. 

Attachments: 
Screenshots of menus.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7679)

**Comment by lmarceau** [comment] 2023-11-01 19:33
Not sure what happened, but I tried in 118.2 and could see the option. Upgraded to 119.1 and cannot see the option anymore.

**Comment by dnarcese** [comment] 2023-11-02 18:44
Duplicate of #16810

**Comment by darren12345** [comment] 2023-11-02 18:51
> Duplicate of #16810

These two issues don’t seem to be related at all.

**Comment by dnarcese** [comment] 2023-11-02 18:54
S

**Comment by dnarcese** [comment] 2023-11-02 18:54
Sorry, commented on the wrong bug

**Comment by darren12345** [comment] 2023-11-02 18:55
> Sorry, commented on the wrong bug

No probs. Thanks.

**Comment by hippler** [comment] 2023-11-23 11:04
Would be very nice to have this feature back soon.

**Comment by matthewkdies** [comment] 2023-11-26 15:01
This is actually a duplicate of #15172.

**Comment by matthewkdies** [comment] 2023-11-26 15:15
In case this issue is viewed as the new main issue (as the other is ~5 months old), I left a comment on the previous showing that this issue still occurs with the latest iOS (17.1.1) and Firefox iOS (120.1) here: https://github.com/mozilla-mobile/firefox-ios/issues/15172#issuecomment-1826806714.

**Closed** 2023-11-27 16:24 UTC
Labels: Contributor OK, Bug 🐞
