### ISSUE TITLE
"Add to Apple Wallet" button does nothing in Firefox on montereybayaquarium.org

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#8994] opened 2021-08-17 00:17 UTC
## Steps to reproduce

1. Buy tickets on https://www.montereybayaquarium.org/
2. View the tickets on the site.
3. Click "Add to Apple Wallet" button.

### Expected behavior

The ticket should open in full screen with an "Add" (to Apple Wallet) button in the upper right corner of the screen. This is what happens in Safari 14.7 and Chrome 92.0.4515.90.

### Actual behavior

In Firefox, the page loading progress bar starts to move, but nothing else happens. Disabling Tracking Protection for the site doesn't fix the problem.

### Device & build information

* Device: iPhone 8 running iOS 14.7.1
* Build version: I can reproduce in both Firefox 35.0 (5448) and Firefox Beta 36.0 (5732).

### Notes

This bug might be a duplicate of issue #5479. That bug was closed as "difficult to repro". This bug is easy to repro, but requires purchasing tickets to visit the Monterey Bay Aquarium. Perhaps there is a test page that can be used to test "Add to Apple Wallet" without buying anything?

I found Apple's Wallet Developer Guide documentation for creating test passes:

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/YourFirst.html

https://stackoverflow.com/questions/52119748/how-to-add-add-to-wallet-button-to-website-to-add-coupons-to-apple-wallet-and

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3077)

**Comment by kcome** [comment] 2021-09-04 06:46
I also couldn't download my COVID19 immunization certificate as an Apple Wallet pass, though I could see an error alert presented. I created a [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9063) for this ticket hoping that might fixes this issue. If not, an extra info is added to the error message alert which might be helpful.

**Comment by JoshApos** [comment] 2021-12-18 21:57
I'm having this issue as well. No 'Add to Apple Wallet' buttons or links work in Firefox iOS. No Wallet dialog/screen appears in order to confirm adding the item. All links that fail in Firefox work as expected in Safari iOS.

**Comment by rcosgrave** [comment] 2022-01-14 18:41
I am also having this issue with an Apple Pass I created (I can share some data about it and give you a card since we are still testing).

My steps:
Generate a QR Code (or just visit the URL) and visit URL in Firefox
...


I can install the same pass from:
Email
Safari
(Didnt try Chrome ;] )

But on Firefox I get an alert "Failed to Add Pass, An error occurred while adding the pass to Wallet. Please try again later."

Spitballing...it seems like Firefox is attempting to force the pass into the Wallet whereas email + Safari gives a preview of the card before you click "Add" to add it to the wallet.

**Comment by data-sync-user** [comment] 2022-03-22 12:32
➤ Simion Basca commented:

Moving this issue to “Done” since there is no way to test it. We’ll keep an eye out for this issue and if we receive other reports we will re-open.

**Comment by lmarceau** [comment] 2022-04-18 13:27
I've received a report that this issue is still reproducible. From the ticketmaster website, when the user clicked on "Add to wallet" nothing was happening. I'll reopen the ticket.

**Comment by robinwhittleton** [comment] 2022-06-18 17:47
I’ve not been able to add to Apple Wallet on a couple of recent sites on Firefox Daylight 101.1 (10346); unfortunately both after booking a hotel room, so it’s difficult to provide rest links.

**Comment by vorwd** [comment] 2022-09-17 08:14
Also having this issue with airline boarding pass (Rex Airlines Australia). Latest Firefox public release on IOS 16. 

Works a treat via safari.

**Comment by lmarceau** [comment] 2022-09-20 14:24
@vorwd I answered your comment here https://github.com/mozilla-mobile/firefox-ios/issues/5479#issuecomment-1252420252. Thanks

**Comment by data-sync-user** [comment] 2022-10-11 14:08
➤ Simion Basca commented:

Currently we don’t have any test site for verification. I will mark this as done and will re-open if the issue is still reproducible when v106 is released.

**Closed by data-sync-user** 2022-10-11 14:08 UTC
Labels: Bug 🐞, P2

**Comment by jgh9** [comment] 2022-10-15 17:33
> ➤ Simion Basca commented:
> 
> Currently we don’t have any test site for verification. I will mark this as done and will re-open if the issue is still reproducible when v106 is released.

I've just experienced issue, as well.  Shared link from Firefox iOS (latest) with Safari and added to wallet. Firefox doesn't resolve link and add to wallet.

Here is link I tried and copied from e-mail.
https://tickets.calpoly.edu/app/pass?ticket_token=1%2Cf5fb5ddb%2C634a245c%2C382940BD-D235-4EC1-8DA6-58B70880F6CE%2CYvUT%2FVJhcE7JW%2FBYbI86i3J5908%3D

**Comment by lmarceau** [comment] 2022-10-17 13:47
Hello @jgh9, on which version are you? The change made will be out with version 106. Thanks!

**Comment by jgh9** [comment] 2022-10-17 15:11
105. Thanks for update!

—
Jason Helfman
Operating Systems Analyst
Information Technology Services – Engineering Services
California Polytechnic State University
San Luis Obispo, CA, 93407
Direct 805-756-6456
***@***.***
________________________________
From: lmarceau ***@***.***>
Sent: Monday, October 17, 2022 6:47:32 AM
To: mozilla-mobile/firefox-ios ***@***.***>
Cc: Jason Helfman ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [mozilla-mobile/firefox-ios] "Add to Apple Wallet" button does nothing in Firefox on montereybayaquarium.org (#8994)


Hello @jgh9<https://github.com/jgh9>, on which version are you? The change made will be out with version 106. Thanks!

**Comment by benjaffe** [comment] 2022-11-06 15:07
This just failed for me on version 106, adding my boarding pass for Delta Airlines to Apple Wallet. Opening in Safari allowed me to add it properly.

**Comment by lmarceau** [comment] 2022-11-07 15:13
@benjaffe I opened a [new issue](https://github.com/mozilla-mobile/firefox-ios/issues/12331) to track this anew. If you have further details about the issue please let us know in there!
