### ISSUE TITLE
Links open in new tab and so I think click hasn't worked

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/firefox-ios#10069] opened 2022-02-19 00:33 UTC
## Steps to reproduce

- go to website
- click on a link
- Expected: new url opens
- Actual: new url opens in a new tab silently so you think that clicking link doesn't work so you click it a bunch more times and then you discover that you have 10 new tabs open.

Frustratingly this is a non-deterministic issue. But it does happen to me every day, feel free to ping me on slack about it.

It regularly happens to me on nytimes.com; but I couldn't reproduce it on there right now. It's currently happening on ayr.com. I'm going to try and make a screencast and post it.

### Device & build information
* Device: iPad
* Build version: Firefox Daylight 97.0 (7635)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3798)

**Comment by data-sync-user** [comment] 2022-02-19 00:40
➤ Sarah Bird commented:

!RPReplay_Final1645231052.mov|thumbnail!

What you can't see is after I scroll down I click "Shop the best sellers" multiple times. You can see that I'm receiving no feedback from the UI that I've done anything till I scroll up and see all the open tabs.

**Comment by data-sync-user** [comment] 2022-02-19 00:41
➤ Sarah Bird commented:

Here's a follow-on video accessing more links in the opened tabs

!RPReplay_Final1645231254.mp4|thumbnail!

**Comment by josh-berry** [comment] 2022-02-20 19:54
I also have this issue. It’s also non-deterministic for me, but happens pretty reliably on certain websites (e.g. safeway.com). On GitHub, sometimes I get even more egregious behavior as follows:

1. Make sure Firefox is your default browser
2. Open a GitHub link from an external app (e.g. by clicking a link in a GitHub notification email from your email app)
3. Firefox launches and tries to load the page
4. Notice that, sometimes, one new tab *per second* will be opened in the background, pointing to the same GitHub issue/PR
5. The repeated opening of tabs will often continue indefinitely until the original tab (opened in step 2) is closed (though IIRC sometimes it continues even after that, and I have to race against the browser to close all the multiplying tabs)

This issue (both the egregious GitHub behavior as well as the more “normal”/common behavior described in the original bug report) is frequent enough, and bad enough for me that it makes it very difficult to use Firefox on iPad in general, because opening a link is now a series of multiple steps (open the link, switch to the tab, close the original tab, etc.).

This issue doesn’t seem to happen, at first, on a fresh, un-synced install of Firefox. But once I’ve signed in to Firefox Sync, it seems to start up again. Even so, it’s intermittent, so I would take the preceding with a grain of salt (it’s possible I just never observed it in a fresh install).

Hope this helps to narrow it down!

**Comment by birdsarah** [comment] 2022-02-21 03:35
Noticed @josh-berry's mention of sync. I just checked and I am not signed into sync on my iPad FF.

**Comment by lmarceau** [comment] 2022-02-24 21:02
Are you using keyboard shortcuts when you get that bug?

**Comment by birdsarah** [comment] 2022-02-24 21:22
For me, no. I'm just tapping on links, this doesn't show in the native screen recording.

**Comment by josh-berry** [comment] 2022-02-24 21:39
I’m also not using keyboard shortcuts and am just tapping on links directly. It happens regardless of whether I have an external keyboard connected to my iPad.

**Comment by birdsarah** [comment] 2022-02-24 21:46
Apologies if I'm stating the obvious; but just to note that our experience on the Mozilla VPN client is that we do get iPad specific bugs so my guess would be this is bug is specific to iPad OS.

**Comment by data-sync-user** [comment] 2022-02-25 19:01
➤ Daniela Arcese commented:

Sarah Bird have you ever connected a keyboard, mouse, trackpad to your iPad? Could something still be connecting while this issue is happening?

**Comment by birdsarah** [comment] 2022-02-25 19:25
Yes. My iPad is always in the following case. https://www.apple.com/shop/product/MXNK2LL/A/smart-keyboard-folio-for-ipad-pro-11-inch-3rd-generation-and-ipad-air-4th-generation-us-english

If it's helpful, DuckDuckGo and Safari do not have do the same. I was thinking maybe I could get Focus and try out this behavior, but it doesn't have tab support so I don't think this it's relevant.

**Comment by birdsarah** [comment] 2022-02-25 19:27
Sorry, I didn't answer the second question. No, my set up doesn't have a "still connecting" aspect. It's always connected to the keyboard and never connected to a mouse or trackpad.

**Comment by birdsarah** [comment] 2022-02-25 19:29
I'm curious on what your theory is Daniela? It's not that the click event doesn't register; it's that it silently opens a new tab.

**Comment by data-sync-user** [comment] 2022-02-25 19:36
➤ Daniela Arcese commented:

Sarah Bird the only thing I can think of that would be interacting is a keyboard shortcut. If you hold down cmd and click a link then it opens in the background so I am wondering if somehow that is getting triggered. Curious if you can try to reproduce without the case on?

**Comment by michielappelman** [comment] 2022-03-08 09:53
I have run into this issue a couple of times as well and always assumed that indeed it had something to do with the Bluetooth connected Magic Keyboard. It just didn't happen all the time.

It did happen just now, but coincidentally another app I was using and Cmd-Tab'ing to and from (https://github.com/blinksh/blink) at some point showed a pop-up saying that the Cmd-key appeared to be stuck. Somehow it detected that, and indeed after hitting Cmd once, the pop up disappeared and the issue in Firefox disappeared.

I don't think it was stuck physically, BTW: it doesn't feel like it and I never experienced that with my Mac for example. Perhaps Firefox just never registered the KeyUp event from the Cmd-key and that's why it thinks it is still pressed? Unfortunately, I have not been able to trigger this situation on purpose.

**Comment by josh-berry** [comment] 2022-03-11 18:33
This is a good find! And indeed, I can confirm that tapping both of the Cmd keys on my keyboard while Firefox is open will cause the behavior to stop and links will go back to navigating as normal.

Interestingly, the behavior still seems to happen even while my external keyboard is disconnected. So I guess somehow the Cmd key stays stuck even when no keyboard is attached.

**Comment by data-sync-user** [comment] 2022-04-01 20:36
➤ Sarah Bird commented:

One hypothesis that I’ve been toying with is the cmd lock issue happens because i cmd-tab between apps. So the way I switch to firefox at least 90% of the time is with cmd tab and the way i cmd tab means that i let go of tab first and so cmd is engaged as i switch to ff.

**Comment by data-sync-user** [comment] 2022-04-01 20:38
➤ Sarah Bird commented:

ok. brain fart. looking at the scroll back clearly mike and others planted this seed in my brain. i’ll let you know if can get to anything reproduce-able.

**Comment by SimonBasca** [comment] 2022-04-04 07:54
Might be related to the issue mentioned here https://github.com/mozilla-mobile/firefox-ios/issues/7519#issuecomment-1020276438.

**Comment by SimonBasca** [comment] 2022-08-31 13:38
@birdsarah Is this issue still reproducible on latest release version 104.1 (16952)?

**Comment by birdsarah** [comment] 2022-09-07 03:18
Thanks for the note @SimonBasca now you mention it, I don't recall seeing it recently. I will keep an eye out.

**Comment by SimonBasca** [comment] 2022-09-07 09:02
Let's close the issue for now and re-open it if ti's reproducible again. Thanks for the help @birdsarah

**Closed by SimonBasca** 2022-09-07 09:02 UTC
Labels: Bug 🐞
