### ISSUE TITLE
iPhone session restore causes internal://local/ replacement

### ISSUE THREAD

**Issue by xX-SunGod-Xx** [mozilla-mobile/firefox-ios#13831] opened 2023-04-02 16:05 UTC
## Steps to reproduce
1. Have a pre-existing session with previous history within a tab
2. Close out of the app
3. Reopen the app

### Expected behavior
Previous history will remain the same and look the same as it did before the app closed 
### Actual behavior
Multiple urls in the previous history will be replaced with internal://local/sessionrestore?url=(url of the previous tab) and appears as a blank tab
### Device & build information
* Device: iPhone 11, iOS 16.4
* Build version: 111.2
* First seen version: 111.0
### Notes
Attachments: 
![IMG_4639](https://user-images.githubusercontent.com/129678517/229364014-a23081f8-afe6-4338-a2dc-9bd06c445279.jpeg)
![IMG_4676](https://user-images.githubusercontent.com/129678517/229364017-1d533e46-8614-47ee-b2f4-089907caf9e7.jpeg)
![IMG_4783](https://user-images.githubusercontent.com/129678517/229364560-5daf0f37-36cd-4c5f-be90-aaacd3223a14.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6116)

**Comment by gutley** [comment] 2023-04-02 20:55
Sounds related to https://github.com/mozilla-mobile/firefox-ios/issues/13729

**Comment by koobs** [comment] 2023-04-07 23:38
First saw sessionrestore:// URLs [1] in both Firefox 111.0 (29345)) and beta (Firefox 112.0 (29529) 17th March. Testing again now, seems percent encoding (#13729), at least spaces, is indeed implicated.

Although I can no longer see sessionrestore:// URLs because page history via back button is no accessible, affected tabs fail to load after closing Firefox via iOS app switcher and opening again.

Reproduction url: https://www.lens.org/lens/search/scholar/list?q=Test%20test

Neg reproduction: https://www.lens.org/lens/search/scholar/list?q=Test

[1] https://twitter.com/koobs/status/1636536143704657920

**Comment by data-sync-user** [comment] 2023-04-17 13:11
➤ Orla Mitchell commented:

Daniela Arcese This might be a good candidate for a rapid release. The same fix also addresses https://mozilla-hub.atlassian.net/browse/FXIOS-6062 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6062|smart-link )

**Closed** 2023-05-10 08:40 UTC
Labels: Bug 🐞
