### ISSUE TITLE
[FxA Upgrade] Tab sent from Android Fenix is not received on iOS 

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6249] opened 2020-03-11 09:22 UTC
**Build:**
Firefox Beta 23.1(17435) and 23.1 (17435)
Fenix 3.2.1 (build #20250350)

**Affected platforms:**
iPhone X (13.3) 
Windows pro 10 64-bit
Android 8.0.0

**Steps to reproduce:**
1. Create an account on iOS Beta 23.1(17435) with all CWTS synced. 
2. Sign in with account on Windows and open about:preferences#sync to double check sync settings have been synced properly. 
3. Also on Windows open Manage Account page and in Devices and Apps section check that iOS device is listed. ( initially the device will be listed and then the Web session as well). 
4. Open a random tab on windows and after perform a Sync Now on both devices and then on Windows right click on tab and select to send it to iOS. 
5. Repeat process with Android. 

**Expected results:**
A notification is received on iOS and when tapping on it you can choose to open it on the desired Firefox version. 

**Actual Results:**
Open tab sent from Desktop to iOS is not received on iOS. No notification although notifications have been allowed. 

**Additional notes:**
1. Verified with the same account logged on **Firefox Release 23.0(17297)** and the tab sent from Desktop is received and opened in browser without a notification being sent while app is in foreground. 
2. In #5890 an error is reported similar to this case. 
3. Send tab from Desktop to Android 8.0.0 on Fenix 3.2.1 (build #20250350) works every time. 

Tab sent from iOS to Desktop is received as expected (notification + the tab being opened on Desktop browser)
![Tab received on Desktop](https://user-images.githubusercontent.com/53306802/76400786-8ddd9580-6389-11ea-9905-c9b5180d02c0.gif)

**Comment by garvankeeley** [comment] 2020-03-11 14:29
How reproducible is this? Is it only on Windows?
I only have a mac, and it is working ok for me.

**Comment by mirunacurtean** [comment] 2020-03-11 14:52
@garvankeeley  Hello, I've edited this in the meantime to also include Android.  This is not 100% reproducible but I've kept investigating. 
By now I've managed to reproduce this with three different accounts, 2 of them having trouble receiving the tab just by following the steps to reproduce. 
On one of the accounts it also happened after the account on iOs was disconnected (either remotely from Desktop or randomly closing and re-opening the app) and after logging in again.  
(A new session/ device is added to the Windows Manage Account>Devices and Apps section.)
Either multiple iOS devices become listed in Send Device list or account becomes disconnected each time the app is minimized and the tab is, understandably, no longer received.

**Comment by abodea** [comment] 2020-03-11 14:56
Hello, I was also able to reproduce this issue quite often on the latest **Firefox Beta 23.1 (17435)** **iPhone 8 (13.2.3)** following the exact steps mentioned in the description.
@garvankeeley can you try sending a tab from desktop RC FF?

**Comment by garvankeeley** [comment] 2020-03-11 15:00
I just sent 5 tabs and they all arrived, using beta 17435 and release firefox desktop on mac.

**Comment by garvankeeley** [comment] 2020-03-11 15:07
I believe the bug requires account disconnection and reconnection, I just tried that and the push notification is not arriving.

**Comment by garvankeeley** [comment] 2020-03-11 16:22
And now I can't reproduce that case, disconnecting and reconnecting the account seems to be working again. Maybe this is a backend problem of some sort. We should try repro this on the current release.

**Comment by garvankeeley** [comment] 2020-03-11 18:16
When debugging I found this related issue which app-services is fixing https://github.com/mozilla/application-services/issues/2792

**Comment by mirunacurtean** [comment] 2020-03-12 12:11
> And now I can't reproduce that case, disconnecting and reconnecting the account seems to be working again. Maybe this is a backend problem of some sort. We should try repro this on the current release.

@garvankeeley 
Re-tested using the latest release available on Test Flight on iOS, Beta 23.1. (17435). 
**On Windows to iOS:**
**New account:**
 (mcurtean+40@mozilla.com) and after sign in and manual sync on iOS and Windows Tab sent from Windows was received and opened instantly on iOS 

**Existing account** (mcurtean+34@mozilla.com) Initially this issue could be reproduced. 
From Manage account disconnect all iOS instances and sing out/sign on back on Desktop and iOS. Sync manually and send tab. 
Tab is not received.  'Sync now' manually again and sent tab is finally opened on iOS. 

![Windows mcurtean34 Send Tab](https://user-images.githubusercontent.com/53306802/76520092-ea64b180-646a-11ea-948b-7b3f5828eb08.gif)

![iOs-mcurtean34-tab-received-after sync](https://user-images.githubusercontent.com/53306802/76520104-ef296580-646a-11ea-9285-0cd03e5f7f45.gif)



**Android to iOS:**
**New account** (mcurtean+41@mozilla.com):
Fennec to iOS - Created acccount on iOS and then sign in on Android. After automatic sync I performed a manual sync as well and then pened and sent tab from Android to iOS. Tab was opened (no notification received) while app was in the foreground. 
Fenix to iOS - Signed in on Fenix with account while it was also logged in on iOS and after manual sync sent tab to iOS. Tab was received opened in iOS browser after performing a manual sync on iOS. (app was in the foreground and no notification was received) 

**Existing account** (mcurtean+34@mozilla.com):
Fennec to iOS - Accounts signed out and signed in and synced again. 
Sent tab from Android is received on iOS only after performing manual sync on iOS. 
Fenix to iOS - Send tab is not received even after re-installing the app and multiple manual syncs. 

Overall, there was a need to perform another sync on iOS to receive the sent tab and on the Fenix to iOS with an existing account(mcurtean+34) send tab still does not work but unfortunately I don't see how to reliably reproduce that issue.

**Comment by garvankeeley** [comment] 2020-03-31 15:10
> Fenix to iOS - Send tab is not received even after re-installing the app and multiple manual syncs.

So this bug remains then? We should focus on this case.

**Comment by garvankeeley** [comment] 2020-04-01 17:56
I am going to close this as Fenix is working to send tab (if there are intermittent issues with this it would be a bug with FxA/Sync servers), but Firefox Android is not working.

**Closed by garvankeeley** 2020-04-01 17:56 UTC
Labels: 5, Bug 🐞

**Comment by garvankeeley** [comment] 2020-04-01 18:00
Outstanding bug is https://github.com/mozilla-mobile/firefox-ios/issues/6351

**Comment by SimonBasca** [comment] 2020-05-05 14:19
Sending a tab from Fenix (latest 05/05) Google Pixel XL Android 10 to iPhone Xr (13.4.1) is working as expected.
