### ISSUE TITLE
Data Management options (`Clear Private Data`) are not saved when setting then On or OFF

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15645] opened 2023-07-19 09:56 UTC
## Steps to reproduce
1. Launch FF access settings > Data Management.
2. Toggle OFF or On any of the options from there.
3. Go back to settings.
4. Re-enter the Data Management section.
### Expected behavior
All the edited options in the Data Management section should be saved even when leaving the section.
### Actual behavior
Data Management options (`Clear Private Data`) are not saved when setting then On or OFF
### Device & build information
* Device: iPhone 13 Pro (15.7.1), iPhone 14+ (16.0.3) 
* Build version: v116 (32820)  
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/a5fe9e82-7401-4ed6-9c5d-e9a7cc0e1987

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7034)

**Comment by data-sync-user** [comment] 2023-07-19 20:20
➤ Laurie Marceau commented:

Note; this change isn’t caused by the changes from settings coordinator, and is present in v115 (so not a new regression). I’ll put this fix in v117.

**Comment by DianaBarladeanu** [comment] 2023-07-27 10:24
Verified as fixed on v9000 (33001) with iPhone SE (16.5).

**Closed** 2023-07-27 10:39 UTC
Labels: Bug 🐞, S3
