### ISSUE TITLE
QR code pairing

### ISSUE THREAD

**Issue by kwillowhawk** [mozilla-mobile/firefox-ios#5201] opened 2019-06-28 07:21 UTC
Skyline commit (v20)

We also plan to make signing into FxA simpler by adopting the scan QR code to sign in feature in Firefox iOS. (Fenix does this now)

**Comment by SimonBasca** [comment] 2019-12-09 16:45
Duplicate of #5855

**Closed** 2019-12-09 18:39 UTC
