### ISSUE TITLE
[UX] Multi-Windows on iPad

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5816] opened 2019-11-26 16:39 UTC
**Vision**

As a user, I want to look at multiple websites at a time, so that I can multi-task

**Acceptance Criteria**

* Users can open an additional Firefox window on iPad with OS 13+
* TBD: is this like a new window on your desktop with its own tabs? Or another view of the same set of tabs?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2211)

**Comment by athomasmoz** [comment] 2019-11-26 17:59
@bryanbell sounds like we may not be able to do this as the same set of tabs.

**Comment by garvankeeley** [comment] 2019-12-11 21:23
Subissue https://github.com/mozilla-mobile/firefox-ios/issues/5898

**Comment by jimcullenaus** [comment] 2020-01-30 02:47
> we may not be able to do this as the same set of tabs

That sounds like a good thing. That’s how windowed applications usually work.

Anyway, is there an update on the ETA of this? Is it still even planned?

**Comment by ferranpujolcamins** [comment] 2021-03-19 12:32
Safari has ￼an independent set of tabs on each window. You can drag and drop tabs across windows.

**Comment by junbio** [comment] 2021-12-21 08:26
> IMO this is a crucial feature to make Firefox for iPadOS a viable alternative to Safari.
> 
> Multiple windows were introduced with iPadOS 13. Two years later, we are now at iPadOS 15, will this ever be implemented or put on a roadmap?

I was working on adding multiple window support to Firefox myself, but a lot of the code assumes a single window and I didn't want to change the code too much if it would cause Mozilla trouble (plus my contributions didn't seem welcome). But it shouldn't be too hard for Mozilla to add multiple window support if they fixed some of those assumptions.

**Comment by lmarceau** [comment] 2021-12-21 16:42
Hello @junbio! I'm concerned that you feel your contribution isn't welcome. Do you see any way we could improve? 

As for multiple window support, that's tech debt that we'll need to address for sure. One way to tackle debt is to introduce small changes at a time to avoid regressions. There's one PR opened at the moment to move to [UISceneDelegate](https://github.com/mozilla-mobile/firefox-ios/pull/9464), which is a start in that direction.

**Comment by whiteonion** [comment] 2022-01-31 16:42
I wish firefox had multiple windows.. kinda makes it not viable at all without it

**Comment by data-sync-user** [comment] 2022-09-21 21:17
➤ Tiffanie Shakespeare commented:

closing as this is a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-3932 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3932|smart-link )

**Comment by Prurite** [comment] 2023-03-06 06:30
It’s 2023 and we have Stage Manager now. Really hope to see this feature so I can work like in desktop.

**Comment by OrlaM** [comment] 2023-03-07 15:06
@Prurite This is very much on our radar and we are actively working on addressing the technical debt that will allow us to enable this feature.

**Comment by data-sync-user** [comment] 2024-01-04 18:47
➤ Matthew Reagan commented:

Note: work on this feature is in progress, currently being tracked by https://mozilla-hub.atlassian.net/browse/FXIOS-7349 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7349|smart-link ).

**Closed** 2024-01-17 11:11 UTC
Labels: Feature-Request, Needs-UX

**Comment by sibbl** [comment] 2024-01-25 10:19
Is there some other Github issue or a public Jira page where we're able to continue following the progress of this feature request?

**Comment by lmarceau** [comment] 2024-01-25 14:34
@sibbl We don't have a public Jira page, but the project is undergoing 👍

**Comment by kubukoz** [comment] 2024-01-25 17:21
perhaps it'd be best to keep this open until it's ready then? It's not really a duplicate if there's no corresponding public ticket.

**Comment by lmarceau** [comment] 2024-01-25 17:49
The duplicated ticket linked is an epic, and epics aren't synced as part of GitHub (since there's no equivalent). I know we currently don't have a way to give contributors visibility on the undergoing projects, but I don't think we should reopen the present ticket, as this one was for UX designers to look at (so not related to code). So even if it's reopened, there won't be any updates on it. In the meantime, to provide a way for you to see the progress made on the multitasking epic, I just [created a label](https://github.com/mozilla-mobile/firefox-ios/labels/multitasking). As you can see there are multiple tasks in there to enable multitasking 😄

**Comment by kubukoz** [comment] 2024-01-26 00:26
That's great, thanks!

**Comment by mattreaganmozilla** [comment] 2024-06-28 18:51
Just wanted to close the loop on this and mention that multi-window support in Firefox iOS will be available in the upcoming v128 release. (Because it's the initial release of this feature there will be additional changes & fixes forthcoming as well in subsequent updates.)
