### ISSUE TITLE
JS alerts can still cause crashes (e.g Scan QR Code App shortcut)

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#13974] opened 2023-04-17 07:48 UTC
## Steps to reproduce

• Visit a website that displays one of the JS alert types, (alert, message or prompt) and display such an alert without closing it)

e.g - https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert2

• Whilst displaying the alert, go back to the phone's home screen and long-press the Firefox icon.
• Choose "Scan QR Code"

See screen recording

### Expected behavior

Firefox should not crash

### Actual behavior

Firefox does crash

### Device & build information
* Device: Any
* Build version: v112 or main

### Notes

This is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9541 as once again the alert's completion block is not being called in all cases before JSPromptAlertController is deinited.

Annoyingly, I provided a [PR to fix this](https://github.com/mozilla-mobile/firefox-ios/pull/9590) permanently over a year ago, but it was decided not to use it. A similar fix still works with the latest code, but I feel submitting a new PR will be equally unwanted.

Attachments: 

https://user-images.githubusercontent.com/2040690/232418012-5c15a95b-3c1d-473a-8184-85a78e28bc58.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6201)

**Comment by data-sync-user** [comment] 2023-05-05 15:05
➤ Yoana Rios Diaz commented:

Andrei Bodea there were still one case missing for the JSAlert crash do you mind checking the steps for this one but also some test for the previous bugs related to this crash because there was a refactoring involved to solve this issue
Thank you

**Comment by data-sync-user** [comment] 2023-05-08 15:23
➤ Andrei Bodea commented:

Hello, Yoana Rios Diazplease note that I could not reproduce this issue, and nothing related to all the linked issues on the latest v9000 with iPhone 13 Pro (15.7.1).

**Comment by data-sync-user** [comment] 2023-05-10 10:34
➤ Andrei Bodea commented:

Do you think we can close this one? Yoana Rios Diaz

**Comment by data-sync-user** [comment] 2023-05-10 12:51
➤ Yoana Rios Diaz commented:

Yes Andrei Bodea we can close it and monitor Sentry

**Comment by data-sync-user** [comment] 2023-05-10 13:10
➤ Andrei Bodea commented:

Closing based on the comments below, thank you Yoana Rios Diaz

**Closed by data-sync-user** 2023-05-10 13:10 UTC
Labels: Crash
