### ISSUE TITLE
The top sites should have a switch to turn off and on in the settings

### ISSUE THREAD

**Issue by MoistTowellettes** [mozilla-mobile/firefox-ios#5478] opened 2019-09-21 06:18 UTC
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

**Comment by SimonBasca** [comment] 2020-01-16 15:41
Duplicate of #5173

**Closed by SimonBasca** 2020-01-16 15:41 UTC
