### ISSUE TITLE
Reporting a Bug for High Memory Usage (Mac/iOS)

### ISSUE THREAD

**Issue by chivahs** [mozilla-mobile/firefox-ios#22990] opened 2024-11-08 10:43 UTC
### Device & build information
* Device: MacBook Air M2, 2022, iOS: maxOS Sequoia Version 15.1
* Build version: 132.0.1 (aarch64)
* First seen version: 132.0.1 (aarch64), but I don't really remember. I think it was already using this much memory since some couple versions before.
### 

Notes: At first I thought it's because I pinned 3 tabs to the browser permanently and I also work with Firefox, so sometimes I do have a lot of tabs open. But even if I close all tab, Firefox still uses nearly 800 MB of memory usage (which is quite a lot, I only have 8GB RAM, it's a work device). I also deleted the browser cache and reinstalled Firefox, the issues stands.
Meanwhile Google Chrome just uses around 180 MB with 8 tabs open.

Attachments: 

[memory-report.json.gz](https://github.com/user-attachments/files/17677088/memory-report.json.gz)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10493)

**Comment by data-sync-user** [comment] 2024-11-13 18:59
➤ Matt Reagan commented:

I believe we can safely close this as a duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-10482 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10482|smart-link ) which seems very likely to be the culprit here, and which is currently being investigated. If anyone has questions LMK. (cc Andres Furlan)

**Comment by data-sync-user** [comment] 2024-11-13 19:00
➤ Matt Reagan commented:

(Note: this ticket appears to mention high memory usage for the Mac client also, but that would need to be filed separately, since this ticket is on the iOS project.)

**Closed** 2024-11-13 19:01 UTC
Labels: Bug 🐞
